import { EstatMetaDefinition } from "../types";

/**
 * e-Stat 統計データのメタ情報定義
 * 従来D1データベースで管理していたものを静的管理に移行
 */
export const ESTAT_STATS_DEFINITIONS: Record<string, EstatMetaDefinition> = {
  "0000010101": { statName: "社会・人口統計体系", title: "Ａ　人口・世帯", areaType: "prefecture", description: "" },
  "0000010102": { statName: "社会・人口統計体系", title: "Ｂ　自然環境", areaType: "prefecture", description: "" },
  "0000010103": { statName: "社会・人口統計体系", title: "Ｃ　経済基盤", areaType: "prefecture", description: "" },
  "0000010104": { statName: "社会・人口統計体系", title: "Ｄ　行政基盤", areaType: "prefecture", description: "" },
  "0000010105": { statName: "社会・人口統計体系", title: "Ｅ　教育", areaType: "prefecture", description: "" },
  "0000010106": { statName: "社会・人口統計体系", title: "Ｆ　労働", areaType: "prefecture", description: "" },
  "0000010107": { statName: "社会・人口統計体系", title: "Ｇ　文化・スポーツ", areaType: "prefecture", description: "" },
  "0000010108": { statName: "社会・人口統計体系", title: "Ｈ　居住", areaType: "prefecture", description: "" },
  "0000010109": { statName: "社会・人口統計体系", title: "Ｉ　健康・医療", areaType: "prefecture", description: "" },
  "0000010110": { statName: "社会・人口統計体系", title: "Ｊ　福祉・社会保障", areaType: "prefecture", description: "" },
  "0000010111": { statName: "社会・人口統計体系", title: "Ｋ　安全", areaType: "prefecture", description: "" },
  "0000010112": { statName: "社会・人口統計体系", title: "Ｌ　家計", areaType: "prefecture", description: "" },
  "0000010113": { statName: "社会・人口統計体系", title: "Ｍ　生活時間", areaType: "prefecture", description: "" },
  "0000010201": { statName: "社会・人口統計体系", title: "Ａ　人口・世帯", areaType: "prefecture", description: "" },
  "0000010202": { statName: "社会・人口統計体系", title: "Ｂ　自然環境", areaType: "prefecture", description: "" },
  "0000010203": { statName: "社会・人口統計体系", title: "Ｃ　経済基盤", areaType: "prefecture", description: "" },
  "0000010204": { statName: "社会・人口統計体系", title: "Ｄ　行政基盤", areaType: "prefecture", description: "" },
  "0000010205": { statName: "社会・人口統計体系", title: "Ｅ　教育", areaType: "prefecture", description: "" },
  "0000010206": { statName: "社会・人口統計体系", title: "Ｆ　労働", areaType: "prefecture", description: "" },
  "0000010207": { statName: "社会・人口統計体系", title: "Ｇ　文化・スポーツ", areaType: "prefecture", description: "" },
  "0000010208": { statName: "社会・人口統計体系", title: "Ｈ　居住", areaType: "prefecture", description: "" },
  "0000010209": { statName: "社会・人口統計体系", title: "Ｉ　健康・医療", areaType: "prefecture", description: "" },
  "0000010210": { statName: "社会・人口統計体系", title: "Ｊ　福祉・社会保障", areaType: "prefecture", description: "" },
  "0000010211": { statName: "社会・人口統計体系", title: "Ｋ　安全", areaType: "prefecture", description: "" },
  "0000010212": { statName: "社会・人口統計体系", title: "Ｌ　家計", areaType: "prefecture", description: "" },
  "0000010213": { statName: "社会・人口統計体系", title: "Ｍ　生活時間", areaType: "prefecture", description: "" },
  "0000020201": { statName: "社会・人口統計体系", title: "Ａ　人口・世帯", areaType: "city", description: "" },
  "0000020202": { statName: "社会・人口統計体系", title: "Ｂ　自然環境", areaType: "city", description: "" },
  "0000020203": { statName: "社会・人口統計体系", title: "Ｃ　経済基盤", areaType: "city", description: "" },
  "0000020204": { statName: "社会・人口統計体系", title: "Ｄ　行政基盤", areaType: "city", description: "" },
  "0000020205": { statName: "社会・人口統計体系", title: "Ｅ　教育", areaType: "city", description: "" },
  "0000020206": { statName: "社会・人口統計体系", title: "Ｆ　労働", areaType: "city", description: "" },
  "0000020207": { statName: "社会・人口統計体系", title: "Ｇ　文化・スポーツ", areaType: "city", description: "" },
  "0000020208": { statName: "社会・人口統計体系", title: "Ｈ　居住", areaType: "city", description: "" },
  "0000020209": { statName: "社会・人口統計体系", title: "Ｉ　健康・医療", areaType: "city", description: "" },
  "0000020210": { statName: "社会・人口統計体系", title: "Ｊ　福祉・社会保障", areaType: "city", description: "" },
  "0000020211": { statName: "社会・人口統計体系", title: "Ｋ　安全", areaType: "city", description: "" },
  "0000020301": { statName: "社会・人口統計体系", title: "Ａ　人口・世帯", areaType: "city", description: "" },
  "0000020302": { statName: "社会・人口統計体系", title: "Ｂ　自然環境", areaType: "city", description: "" },
  "0000020303": { statName: "社会・人口統計体系", title: "Ｃ　経済基盤", areaType: "city", description: "" },
  "0000020304": { statName: "社会・人口統計体系", title: "Ｄ　行政基盤", areaType: "city", description: "" },
  "0000020305": { statName: "社会・人口統計体系", title: "Ｅ　教育", areaType: "city", description: "" },
  "0000020306": { statName: "社会・人口統計体系", title: "Ｆ　労働", areaType: "city", description: "" },
  "0000020307": { statName: "社会・人口統計体系", title: "Ｇ　文化・スポーツ", areaType: "city", description: "" },
  "0000020308": { statName: "社会・人口統計体系", title: "Ｈ　居住", areaType: "city", description: "" },
  "0000020309": { statName: "社会・人口統計体系", title: "Ｉ　健康・医療", areaType: "city", description: "" },
  "0000020310": { statName: "社会・人口統計体系", title: "Ｊ　福祉・社会保障", areaType: "city", description: "" },
  "0000020311": { statName: "社会・人口統計体系", title: "Ｋ　安全", areaType: "city", description: "" },
  "0003456093": { statName: "社会生活基本調査", title: "男女,頻度,旅行・行楽の種類別行動者率(10歳以上)－全国，都道府県", areaType: "prefecture", description: "" },
  "0003456245": { statName: "社会生活基本調査", title: "男女,学習・自己啓発・訓練の種類別行動者率(10歳以上)－全国，都道府県", areaType: "prefecture", description: "" },
  "0003456409": { statName: "社会生活基本調査", title: "男女,スポーツの種類別行動者率(10歳以上)－全国，都道府県", areaType: "prefecture", description: "" },
  "0003456573": { statName: "社会生活基本調査", title: "男女,趣味・娯楽の種類別行動者率(10歳以上)－全国，都道府県", areaType: "prefecture", description: "" },
  "0003455937": { statName: "社会生活基本調査", title: "男女,ボランティア活動の形態,ボランティア活動の種類別行動者率(10歳以上)－全国，都道府県", areaType: "prefecture", description: "" },
  "0003457307": { statName: "社会生活基本調査", title: "曜日,男女,スマートフォン・パソコンなどの使用時間,年齢,行動の種類別総平均時間(10歳以上)－全国，都道府県", areaType: "prefecture", description: "" },
  "0003457313": { statName: "社会生活基本調査", title: "曜日,男女,ふだんの就業状態,スマートフォン・パソコンなどの使用時間,年齢,行動の種類別総平均時間(15歳以上)－全国，都道府県", areaType: "prefecture", description: "" },
  "0003457707": { statName: "社会生活基本調査", title: "曜日,起床,男女,スマートフォン・パソコンなどの使用時間,年齢,時刻区分別行動者数（構成比）(10歳以上)－全国，都道府県", areaType: "prefecture", description: "" },
  "0003457886": { statName: "社会生活基本調査", title: "曜日,朝食開始,男女,スマートフォン・パソコンなどの使用時間,年齢,時刻区分別行動者数（構成比）(10歳以上)－全国，都道府県", areaType: "prefecture", description: "" },
  "0003457791": { statName: "社会生活基本調査", title: "曜日,就寝,男女,スマートフォン・パソコンなどの使用時間,年齢,時刻区分別行動者数（構成比）(15歳以上)－全国，都道府県", areaType: "prefecture", description: "" },
  "0003457830": { statName: "社会生活基本調査", title: "曜日,出勤,男女,スマートフォン・パソコンなどの使用時間,年齢,時刻区分別行動者数（構成比）(有業者)－全国，都道府県", areaType: "prefecture", description: "" },
  "0003457854": { statName: "社会生活基本調査", title: "曜日,仕事からの帰宅時間,男女,スマートフォン・パソコンなどの使用時間,年齢,時刻区分別行動者数（構成比）(有業者)－全国，都道府県", areaType: "prefecture", description: "" },
  "0003448099": { statName: "工業統計調査", title: "品目編 【１．製造品に関する統計表】（２）品目群による都道府県別出荷額（産業中分類別、従業者４人以上の事業所）", areaType: "prefecture", description: "" },
  "0003448100": { statName: "工業統計調査", title: "品目編 【１．製造品に関する統計表】（３）品目別、都道府県別の出荷及び産出事業所数（従業者４人以上の事業所）", areaType: "prefecture", description: "" },
} as const;
