import {
  BUSINESS_PLAN_CONTENT_OPPORTUNITIES,
  BUSINESS_PLAN_NOTE_PRODUCTS,
  BUSINESS_PLAN_X_IDEAS,
} from './content-opportunities';
import type {
  BusinessPlanCatalog,
  BusinessPlanDecision,
  BusinessPlanDocument,
  BusinessPlanEvent,
  BusinessPlanInitiative,
  BusinessPlanMetric,
  BusinessPlanPilotSpec,
} from './types';

export const BUSINESS_PLAN_DOCUMENTS: readonly BusinessPlanDocument[] = [
  {
    id: 'project-definition',
    title: 'プロジェクト定義',
    path: 'docs/00_プロジェクト管理/01_プロジェクト定義.md',
    role: 'ビジョン・事業境界・成功条件',
    owner: 'strategy-advisor',
  },
  {
    id: 'monetization-strategy',
    title: '収益化戦略',
    path: 'docs/00_プロジェクト管理/02_収益化戦略.md',
    role: '収益レイヤー・NSM・需要ゲート',
    owner: 'strategy-advisor',
  },
  {
    id: 'marketing-strategy',
    title: 'マーケティング戦略',
    path: 'docs/00_プロジェクト管理/03_マーケティング戦略.md',
    role: 'チャネル・1分析多用途展開・獲得サイクル',
    owner: 'strategy-advisor',
  },
  {
    id: 'personas',
    title: 'ターゲット・ペルソナ',
    path: 'docs/00_プロジェクト管理/04_ターゲットペルソナ.md',
    role: '4顧客層とJobs-to-be-Done',
    owner: 'strategy-advisor',
  },
  {
    id: 'data-architecture',
    title: 'データアーキテクチャ',
    path: 'docs/01_技術設計/02_データアーキテクチャ.md',
    role: 'git TS / R2 / エフェメラル集計の境界',
    owner: 'data-ingester',
  },
  {
    id: 'information-architecture',
    title: '情報設計',
    path: 'docs/01_技術設計/03_情報設計.md',
    role: 'ページ責務・地域分析導線・index条件',
    owner: 'site-ux-manager',
  },
  {
    id: 'design-system',
    title: 'デザインシステム',
    path: 'docs/01_技術設計/04_デザインシステム.md',
    role: '公開サイトと管理画面のUI原則',
    owner: 'site-ux-manager',
  },
  {
    id: 'automation-inventory',
    title: '自動化インベントリ',
    path: 'docs/01_技術設計/06_自動化インベントリ.md',
    role: '検証・state生成・CIの実行台帳',
    owner: 'devops-runner',
  },
  {
    id: 'analytics-events',
    title: '分析イベント規約',
    path: '.claude/rules/analytics-event-standards.md',
    role: 'イベント名・GA4登録・計測可否の正典',
    owner: 'ga4-analyst',
  },
  {
    id: 'gis-data',
    title: 'GISデータ規約',
    path: '.claude/rules/gis-data.md',
    role: 'データセットの採用・ライセンス・R2パイプライン',
    owner: 'gis-curator',
  },
];

const d = (
  chapter: number,
  title: string,
  status: BusinessPlanDecision['status'],
  summary: string,
  rationale: string,
  canonicalPaths: readonly string[],
  owners: readonly string[],
  skills: readonly string[],
  metricIds: readonly string[] = []
): BusinessPlanDecision => ({
  chapter,
  title,
  status,
  summary,
  rationale,
  canonicalPaths,
  owners,
  skills,
  metricIds,
});

export const BUSINESS_PLAN_DECISIONS: readonly BusinessPlanDecision[] = [
  d(
    1,
    '現在資産',
    'adopted',
    '2.1k+ランキング、テーマ、地域、CSVを複合分析の入口に再利用する。',
    '新規ブランドより既存検索・データ資産の再利用が速い。',
    ['docs/00_プロジェクト管理/01_プロジェクト定義.md'],
    ['strategy-advisor'],
    ['business-plan-operate']
  ),
  d(
    2,
    'ビジョンと位置付け',
    'adopted',
    'stats47を地域データの意思決定プラットフォームへ拡張する。',
    'GIS/AIを前面に出さずユーザーの問いを主語にする。',
    ['docs/00_プロジェクト管理/01_プロジェクト定義.md'],
    ['strategy-advisor', 'site-ux-manager'],
    ['business-plan-operate']
  ),
  d(
    3,
    '顧客とJTBD',
    'adapted',
    '一般・実務者・企業・公共の4層を、既存の生活意思決定セグメント中心に接続する。',
    '現行のS2重点を維持し、企業・公共は需要が見えた後に広げる。',
    ['docs/00_プロジェクト管理/04_ターゲットペルソナ.md'],
    ['strategy-advisor'],
    ['business-plan-operate']
  ),
  d(
    4,
    '収益アーキテクチャ',
    'adapted',
    '集客・商用意図・商品・継続課金・法人の5層で評価する。',
    '現行の週次収益NSMを維持し、重い課金基盤は需要ゲート後に限定する。',
    ['docs/00_プロジェクト管理/02_収益化戦略.md'],
    ['strategy-advisor', 'affiliate-manager'],
    ['monetization-strategy', 'manage-affiliate-experiment'],
    ['weekly-revenue']
  ),
  d(
    5,
    'サイト情報設計',
    'adapted',
    'ランキング→テーマ/地域→問いベース分析→行動の導線を段階導入する。',
    '/geo等は品質を満たす実分析ができるまでindex・ナビ露出しない。',
    ['docs/01_技術設計/03_情報設計.md'],
    ['site-ux-manager'],
    ['business-plan-operate']
  ),
  d(
    6,
    'GISコンテンツ',
    'adopted',
    '人口・住まい・防災・医療生活・交通・地域経済の6テーマを優先する。',
    '単一指標の複製ではなく複数条件の説明価値に集中する。',
    [
      '.claude/rules/gis-data.md',
      'packages/data-configs/src/business-plan/content-opportunities.ts',
    ],
    ['gis-curator', 'open-data-curator'],
    ['fetch-mlit-ksj', 'business-plan-operate']
  ),
  d(
    7,
    '初期20企画',
    'adapted',
    '全100候補を保持し、人口・地価・洪水・駅の4系列から需要検証する。',
    '20件一括制作ではなくデータ健全性と反応で逐次Goする。',
    ['packages/data-configs/src/business-plan/content-opportunities.ts'],
    ['strategy-advisor', 'article-writer'],
    ['business-plan-operate', 'write-prepared-article'],
    ['regional-decision-sessions']
  ),
  d(
    8,
    'X集客',
    'adapted',
    '1分析から地図・比較・裏側投稿を作り、X直収益は計画に含めない。',
    '既存SNS規約の頻度上限と投稿台帳を優先する。',
    [
      '.claude/rules/sns-content-standards.md',
      'packages/data-configs/src/business-plan/content-opportunities.ts',
    ],
    ['x-strategist', 'sns-metrics-sync'],
    ['post-x', 'sns-weekly-report'],
    ['x-qualified-posts']
  ),
  d(
    9,
    'note販売',
    'adapted',
    '結論は無料、再現手順・加工データ・時短価値を有料にする。',
    'note本文SSOT・品質ゲート・公開承認の既存運用へ接続する。',
    [
      'packages/data-configs/src/business-plan/content-opportunities.ts',
      '.claude/rules/sns-content-standards.md',
    ],
    ['note-manager', 'note-critic'],
    ['design-note-structure', 'publish-note'],
    ['paid-purchases']
  ),
  d(
    10,
    '高意図Affiliate',
    'adapted',
    '移住・住宅・旅行・仕事を意思決定後の次行動として配置する。',
    '既存在庫SSOT・compliance・実験ゲートを通し、地図に広告を直接混在させない。',
    ['docs/00_プロジェクト管理/02_収益化戦略.md'],
    ['affiliate-manager', 'adsense-analyst'],
    ['audit-affiliate-compliance', 'manage-affiliate-experiment'],
    ['weekly-revenue']
  ),
  d(
    11,
    'データ商品・レポート',
    'adapted',
    '無料の結論と出典に対し、再現性・高解像度・更新差分を商品化する。',
    '既存product-factoryへ需要確認済みの企画だけ登録する。',
    ['docs/00_プロジェクト管理/02_収益化戦略.md'],
    ['coconala-product-manager', 'kindle-publisher'],
    ['build-coconala-product', 'build-kindle-book'],
    ['paid-purchases']
  ),
  d(
    12,
    'Pro/Membership',
    'deferred',
    '保存・高度DL・更新通知の反復需要が出た場合だけ継続課金を設計する。',
    '最初の90日はSaaSを作らず、同じ依頼の反復を開始条件にする。',
    ['docs/00_プロジェクト管理/02_収益化戦略.md'],
    ['strategy-advisor'],
    ['business-plan-operate'],
    ['paid-purchases']
  ),
  d(
    13,
    'B2B',
    'adapted',
    '公開ケースから診断・PoCへ上げる。',
    'プラットフォーム先行を避け、月3件以上の問い合わせ等の需要ゲートを守る。',
    ['docs/00_プロジェクト管理/02_収益化戦略.md'],
    ['strategy-advisor'],
    ['monetization-strategy'],
    ['business-inquiries']
  ),
  d(
    14,
    'AI地域検索',
    'deferred',
    'AIは質問理解と説明に限定し、計算・空間交差・順位は決定論的にする。',
    '自由SQLや本番更新権限を与えず、検索ログと反復需要の後にβ化する。',
    [
      'docs/00_プロジェクト管理/01_プロジェクト定義.md',
      'docs/01_技術設計/02_データアーキテクチャ.md',
    ],
    ['strategy-advisor', 'data-ingester'],
    ['business-plan-operate'],
    ['ai-queries']
  ),
  d(
    15,
    '技術アーキテクチャ',
    'adapted',
    'Next.js + git TS + R2 + エフェメラルDuckDBを継続する。',
    '原案の常設D1/PostGISは完全DBレス正典と競合するため採用しない。',
    ['docs/01_技術設計/02_データアーキテクチャ.md'],
    ['data-ingester', 'snapshot-exporter', 'r2-publisher'],
    ['page-data-batch', 'sync-snapshots', 'push-r2']
  ),
  d(
    16,
    'ETL・品質',
    'adopted',
    '出典・年度・地域コード・単位・欠損・ライセンスを機械検証する。',
    '既存provenance/unit/value分布ゲートを複合分析にも適用する。',
    [
      '.claude/rules/data-provenance-standards.md',
      '.claude/rules/unit-semantics-standards.md',
    ],
    ['data-ingester', 'gis-pipeline-runner'],
    ['audit-provenance', 'audit-units', 'verify-value-distribution']
  ),
  d(
    17,
    'SEO・内部導線',
    'adapted',
    '単一指標から複合分析、方法、次行動へ意図別に接続する。',
    '薄い市区町村ページの量産はせず、index条件とcanonical規約を優先する。',
    ['docs/01_技術設計/03_情報設計.md', 'apps/web/src/lib/url-policy.ts'],
    ['site-ux-manager', 'gsc-analyst'],
    ['seo-audit', 'gsc-improvement']
  ),
  d(
    18,
    'OGP・X画像',
    'adapted',
    '同一分析から一貫した地図カードを派生する。',
    '既存画像カタログ・OGP監査・SNS配色規約を再利用する。',
    ['.claude/rules/sns-content-standards.md'],
    ['image-prompt-curator', 'chart-author'],
    ['audit-ogp-images', 'image-prompt']
  ),
  d(
    19,
    'KPI・計測',
    'adapted',
    '週次収益NSMに地域意思決定セッション等の先行指標を接続する。',
    '未実装イベントを0として扱わず、登録・反映状態を明示する。',
    [
      '.claude/rules/analytics-event-standards.md',
      'packages/data-configs/src/business-plan/catalog.ts',
    ],
    ['ga4-analyst', 'strategy-advisor'],
    ['fetch-ga4-data', 'business-plan-operate'],
    ['weekly-revenue', 'regional-decision-sessions']
  ),
  d(
    20,
    '財務計画',
    'adapted',
    'M3/M6/M12値は予測ではなく投資・撤退判断用の仮説として扱う。',
    '既存売上を混ぜず、計測不能値を実績表示しない。',
    ['docs/00_プロジェクト管理/02_収益化戦略.md'],
    ['strategy-advisor', 'adsense-analyst'],
    ['weekly-review', 'adsense-improvement'],
    ['weekly-revenue']
  ),
  d(
    21,
    '12か月ロードマップ',
    'adapted',
    'foundation→pilot→scale→demand-gatedの順に進める。',
    '暦月で自動着手せず、前段の品質・需要ゲートを満たした時だけ進める。',
    ['packages/data-configs/src/business-plan/catalog.ts'],
    ['strategy-advisor'],
    ['business-plan-operate', 'monthly-plan']
  ),
  d(
    22,
    '90日実行計画',
    'adapted',
    '4系列・X・note・商品・法人ケースを小さく検証する。',
    '公開数ではなくデータ健全性、読了/操作、購入・問い合わせを停止条件にする。',
    ['packages/data-configs/src/business-plan/catalog.ts'],
    ['strategy-advisor'],
    ['business-plan-operate', 'weekly-plan'],
    ['regional-decision-sessions', 'paid-purchases', 'business-inquiries']
  ),
  d(
    23,
    '運用',
    'adapted',
    '週次レビューで状態を再生成し、上位企画だけを次週へ送る。',
    '日次で意味判断を繰り返さず、決定的収集と週次判断を分離する。',
    [
      '.claude/skills/management/weekly-plan/SKILL.md',
      '.claude/skills/management/weekly-review/SKILL.md',
    ],
    ['strategy-advisor'],
    ['weekly-plan', 'weekly-review', 'business-plan-operate']
  ),
  d(
    24,
    '法務・信頼',
    'adopted',
    '一次資料・ライセンス・広告表示・AI利用・防災免責を成果物単位で記録する。',
    '公開データでも利用条件と第三者権利は別に確認する。',
    [
      '.claude/rules/data-provenance-standards.md',
      '.claude/rules/affiliate-ads-standards.md',
    ],
    ['open-data-curator', 'affiliate-manager'],
    ['audit-provenance', 'audit-affiliate-compliance']
  ),
  d(
    25,
    'Go/Pivot/Stop',
    'adopted',
    '90日・6か月・12か月で需要と制作負荷を判定する。',
    '機能完成ではなくユーザー価値・売上・反復利用で投資を増減する。',
    [
      'docs/00_プロジェクト管理/02_収益化戦略.md',
      'packages/data-configs/src/business-plan/catalog.ts',
    ],
    ['strategy-advisor'],
    ['business-plan-operate', 'weekly-review'],
    ['weekly-revenue', 'regional-decision-sessions']
  ),
];

export const BUSINESS_PLAN_METRICS: readonly BusinessPlanMetric[] = [
  {
    id: 'weekly-revenue',
    label: '週次収益',
    role: 'north-star',
    cadence: 'weekly',
    source: '.claude/state/metrics/',
    measurementStatus: 'partially-measured',
    targetM3: 30000,
    targetM6: 187000,
    targetM12: 1030000,
    unit: '円/月換算',
    note: '現行の収益化NSM。目標値は増分の仮説で、予測ではない。',
  },
  {
    id: 'regional-decision-sessions',
    label: '地域意思決定セッション',
    role: 'input',
    cadence: 'monthly',
    source: 'GA4',
    measurementStatus: 'not-instrumented',
    targetM3: 5000,
    targetM6: 20000,
    unit: 'セッション/月',
    note: '地域比較・地図操作・DL等の意思決定行動を含む先行指標。',
  },
  {
    id: 'map-interaction-rate',
    label: '地図操作率',
    role: 'input',
    cadence: 'weekly',
    source: 'GA4',
    measurementStatus: 'not-instrumented',
    targetM3: 25,
    unit: '%',
    note: '地域分析ページ公開後にイベント登録・反映確認して計測する。',
  },
  {
    id: 'owned-leads',
    label: '自社リード累計',
    role: 'input',
    cadence: 'monthly',
    source: 'lead ledger',
    measurementStatus: 'not-instrumented',
    targetM3: 150,
    targetM6: 700,
    targetM12: 2500,
    unit: '件',
    note: '同意・配信停止・個人情報運用の設計後に開始。',
  },
  {
    id: 'paid-purchases',
    label: '有料購入',
    role: 'input',
    cadence: 'weekly',
    source: 'note / product ledger',
    measurementStatus: 'partially-measured',
    targetM3: 10,
    unit: '件/累計',
    note: '有料noteとデータ商品の実購入。',
  },
  {
    id: 'business-inquiries',
    label: '法人問い合わせ',
    role: 'input',
    cadence: 'monthly',
    source: 'inquiry ledger',
    measurementStatus: 'manual',
    targetM3: 1,
    targetM6: 3,
    targetM12: 6,
    unit: '件/累計',
    note: 'プラットフォーム投資判断は月3件以上等の需要ゲートを優先。',
  },
  {
    id: 'x-qualified-posts',
    label: 'X有資格投稿',
    role: 'input',
    cadence: 'weekly',
    source: '.claude/state/metrics/x/',
    measurementStatus: 'measured',
    targetM3: 3,
    unit: '1万表示以上の投稿数',
    note: 'X直収益ではなく分析テーマの需要信号。',
  },
  {
    id: 'ai-queries',
    label: 'AI地域検索クエリ',
    role: 'hypothesis',
    cadence: 'monthly',
    source: 'future query ledger',
    measurementStatus: 'not-instrumented',
    unit: '件',
    note: 'AI検索βを開始するまでは未計測。',
  },
  {
    id: 'data-quality-pass-rate',
    label: 'データ品質ゲート通過率',
    role: 'guardrail',
    cadence: 'weekly',
    source: 'CI / audit state',
    measurementStatus: 'partially-measured',
    unit: '%',
    note: 'provenance・単位・分布・GISライセンスを含む。',
  },
];

export const BUSINESS_PLAN_EVENTS: readonly BusinessPlanEvent[] = [
  {
    id: 'geo-view',
    label: '地域分析閲覧',
    canonicalEvent: null,
    status: 'not-instrumented',
    owner: 'ga4-analyst',
    implementationPath: 'apps/web/src/lib/analytics/events.ts',
    note: '/geo実装時に route+analysis_id で追加する。',
  },
  {
    id: 'map-interaction',
    label: '地図操作',
    canonicalEvent: null,
    status: 'not-instrumented',
    owner: 'ga4-analyst',
    implementationPath: 'apps/web/src/lib/analytics/events.ts',
    note: '操作種別を決定的enumに限定する。',
  },
  {
    id: 'region-search',
    label: '地域検索',
    canonicalEvent: null,
    status: 'not-instrumented',
    owner: 'ga4-analyst',
    implementationPath: 'apps/web/src/lib/analytics/events.ts',
    note: '検索語そのものは送らず地域コード等を使う。',
  },
  {
    id: 'compare-add',
    label: '比較へ追加',
    canonicalEvent: null,
    status: 'not-instrumented',
    owner: 'ga4-analyst',
    implementationPath: 'apps/web/src/lib/analytics/events.ts',
    note: '比較UI実装時に追加する。',
  },
  {
    id: 'data-download',
    label: 'データDL',
    canonicalEvent: 'file_download',
    status: 'measured',
    owner: 'ga4-analyst',
    implementationPath: 'apps/web/src/lib/analytics/events.ts',
    note: '既存GA4推奨イベントへ適合済み。',
  },
  {
    id: 'email-signup',
    label: 'メール登録',
    canonicalEvent: null,
    status: 'not-instrumented',
    owner: 'ga4-analyst',
    implementationPath: 'apps/web/src/lib/analytics/events.ts',
    note: '同意管理を実装するまで追加しない。',
  },
  {
    id: 'note-click',
    label: 'note遷移',
    canonicalEvent: 'cta_click',
    status: 'partially-measured',
    owner: 'ga4-analyst',
    implementationPath: 'apps/web/src/lib/analytics/events.ts',
    note: 'CTA種別の台帳反映を確認する。',
  },
  {
    id: 'affiliate-click',
    label: 'Affiliateクリック',
    canonicalEvent: 'affiliate_click',
    status: 'measured',
    owner: 'ga4-analyst',
    implementationPath: 'apps/web/src/lib/analytics/events.ts',
    note: '既存在庫・vertical契約を利用する。',
  },
  {
    id: 'product-view',
    label: '商品閲覧',
    canonicalEvent: null,
    status: 'not-instrumented',
    owner: 'ga4-analyst',
    implementationPath: 'apps/web/src/lib/analytics/events.ts',
    note: '自社商品ページ実装時に追加する。',
  },
  {
    id: 'purchase',
    label: '購入',
    canonicalEvent: null,
    status: 'manual',
    owner: 'adsense-analyst',
    implementationPath: '.claude/state/metrics/',
    note: '外部販売サービス実績を週次で正規化する。',
  },
  {
    id: 'business-inquiry',
    label: '法人問い合わせ',
    canonicalEvent: null,
    status: 'manual',
    owner: 'strategy-advisor',
    implementationPath: '.claude/state/metrics/',
    note: '問い合わせフォーム実装までは手動台帳。',
  },
  {
    id: 'ai-query',
    label: 'AI地域検索',
    canonicalEvent: null,
    status: 'not-instrumented',
    owner: 'ga4-analyst',
    implementationPath: 'apps/web/src/lib/analytics/events.ts',
    note: 'β開始前はイベントを追加しない。',
  },
];

export const BUSINESS_PLAN_INITIATIVES: readonly BusinessPlanInitiative[] = [
  {
    id: 'bp-foundation',
    title: '方針・企画・KPIの統合SSOT',
    wave: 'foundation',
    status: 'in-progress',
    owner: 'strategy-advisor',
    skills: ['business-plan-operate'],
    deliverables: [
      '型付き事業計画カタログ',
      '管理画面の実行ビュー',
      'CI検証と週次state',
    ],
    readinessGate: '25章・100企画・30 X案・15商品が参照整合を通る',
    metricIds: ['data-quality-pass-rate'],
  },
  {
    id: 'geo-pilot-1',
    title: '人口×将来人口シリーズ',
    wave: 'pilot',
    status: 'ready',
    owner: 'article-writer',
    skills: ['write-prepared-article', 'fetch-estat-data'],
    deliverables: ['一次資料データの確定', '問いベース分析1本', 'X/note派生案'],
    readinessGate: '地域コード・年度・単位・provenanceゲートPASS',
    metricIds: ['regional-decision-sessions', 'x-qualified-posts'],
  },
  {
    id: 'geo-pilot-2',
    title: '人口×地価シリーズ',
    wave: 'pilot',
    status: 'gated',
    owner: 'open-data-curator',
    skills: ['business-plan-operate', 'fetch-mlit-ksj'],
    deliverables: ['地価データ選定', '商用意図分析', 'Affiliate候補接続'],
    readinessGate: 'pilot-1品質PASSかつ地価データの利用条件・年度確定',
    metricIds: ['regional-decision-sessions', 'weekly-revenue'],
  },
  {
    id: 'geo-pilot-3',
    title: '人口×洪水シリーズ',
    wave: 'pilot',
    status: 'gated',
    owner: 'gis-curator',
    skills: ['fetch-mlit-ksj', 'audit-provenance'],
    deliverables: ['ハザードレイヤー', '人口空間結合', '公式情報・免責導線'],
    readinessGate: '公式データ・空間単位・免責・表示性能PASS',
    metricIds: ['map-interaction-rate', 'business-inquiries'],
  },
  {
    id: 'geo-pilot-4',
    title: '人口×駅シリーズ',
    wave: 'pilot',
    status: 'gated',
    owner: 'gis-curator',
    skills: ['fetch-mlit-ksj', 'audit-provenance'],
    deliverables: ['駅アクセス定義', '将来人口結合', '移住/住宅導線'],
    readinessGate: '駅距離の定義・年度差・欠損処理を公開可能',
    metricIds: ['regional-decision-sessions', 'weekly-revenue'],
  },
  {
    id: 'geo-route',
    title: '地域分析ハブと固定テンプレート',
    wave: 'scale',
    status: 'gated',
    owner: 'site-ux-manager',
    skills: ['business-plan-operate', 'design-review'],
    deliverables: [
      '/geoハブ',
      '問いベース分析テンプレート',
      'ランキング/テーマ/地域からの導線',
    ],
    readinessGate: '実分析3本以上・計測登録・no thin content監査PASS',
    metricIds: ['regional-decision-sessions', 'map-interaction-rate'],
  },
  {
    id: 'owned-lead',
    title: '自社リード獲得',
    wave: 'scale',
    status: 'gated',
    owner: 'strategy-advisor',
    skills: ['business-plan-operate'],
    deliverables: ['同意設計', '無料DL価値', '配信停止運用'],
    readinessGate: '継続配信価値・プライバシー運用・責任者が確定',
    metricIds: ['owned-leads'],
  },
  {
    id: 'data-products',
    title: '再現可能なデータ商品',
    wave: 'scale',
    status: 'gated',
    owner: 'coconala-product-manager',
    skills: ['build-coconala-product'],
    deliverables: ['加工済みデータ', '方法・更新条件', '商品READINESS'],
    readinessGate: '無料分析の需要と購入意図を実測しライセンス確認済み',
    metricIds: ['paid-purchases', 'weekly-revenue'],
  },
  {
    id: 'b2b-case',
    title: '法人ケースと定型診断',
    wave: 'demand-gated',
    status: 'gated',
    owner: 'strategy-advisor',
    skills: ['monetization-strategy'],
    deliverables: ['公開ケース', '診断範囲・価格', '問い合わせ導線'],
    readinessGate: '公開分析から具体相談が発生し提供範囲を固定できる',
    metricIds: ['business-inquiries', 'weekly-revenue'],
  },
  {
    id: 'pro-ai',
    title: 'Pro・AI地域検索',
    wave: 'demand-gated',
    status: 'gated',
    owner: 'strategy-advisor',
    skills: ['business-plan-operate'],
    deliverables: ['保存/反復ユースケース', '決定論的検索契約', '課金仮説'],
    readinessGate: '同種依頼の反復・支払意思・運用コストを実測',
    metricIds: ['ai-queries', 'paid-purchases'],
  },
];

export const BUSINESS_PLAN_PILOT_SPECS: readonly BusinessPlanPilotSpec[] = [
  {
    id: 'pilot-population-future',
    contentId: 'geo-001',
    question: '2050年も人口が維持されやすい場所はどこか',
    geography: '市区町村を主表示、1kmメッシュを根拠レイヤーにする',
    dataRefs: [
      {
        kind: 'metric',
        id: 'future-population-change-rate-2050',
        role: '既存の県比較・入口',
      },
      { kind: 'metric', id: 'total-population', role: '現在人口の文脈' },
      { kind: 'gis', id: 'mesh1000r6', role: '1kmメッシュ将来推計人口' },
      { kind: 'gis', id: 'N03', role: '市区町村集約境界' },
    ],
    existingAssets: [
      '/ranking/future-population-change-rate-2050',
      '/themes/population-dynamics',
      'KSJ mesh1000r6 pipeline',
    ],
    method: [
      '同一基準年の現在人口と2050年推計を地域コードで結合',
      '維持率を決定論的に算出し欠損を順位から除外',
      '県平均と市区町村内分布を分けて説明',
    ],
    outputChannels: [
      '地域分析pilot',
      'X地図カード6案',
      '無料note解説',
      '有料の再現手順候補',
    ],
    qualityGates: [
      'IPSS/国交省の一次資料と推計注記',
      '地域コード・基準年・単位・47県/市区町村coverage',
      '将来を保証する表現を使わない',
    ],
    owner: 'data-ingester',
    status: 'ready',
  },
  {
    id: 'pilot-population-land-price',
    contentId: 'geo-016',
    question: '地価が高すぎず、将来人口が相対的に残る場所はどこか',
    geography: '市区町村集約と地価地点を分離表示',
    dataRefs: [
      {
        kind: 'metric',
        id: 'future-population-change-rate-2050',
        role: '将来人口',
      },
      {
        kind: 'metric',
        id: 'residential-land-price-change-rate',
        role: '既存地価比較',
      },
      { kind: 'gis', id: 'L01', role: '地価公示地点' },
      {
        kind: 'open-data',
        id: 'reinfolib-land-price-point-tiles',
        role: '地点確認候補',
      },
    ],
    existingAssets: [
      '/ranking/future-population-change-rate-2050',
      '/ranking/residential-land-price-change-rate',
      'MLIT不動産情報ライブラリcatalog',
    ],
    method: [
      '地価地点値と市区町村推計を空間結合',
      '地価水準と変化率を混同せず別変数にする',
      '等重みを既定とし主観重みは使わない',
    ],
    outputChannels: [
      '地域分析pilot',
      'X比較カード',
      '住まいAffiliateの文脈一致候補',
      '地価×将来人口note候補',
    ],
    qualityGates: [
      '地価の価格時点・用途・地点代表性',
      '年度差と外れ値処理の開示',
      '将来価格・投資成果を保証しない',
    ],
    owner: 'open-data-curator',
    status: 'gated',
  },
  {
    id: 'pilot-population-flood',
    contentId: 'geo-031',
    question: '浸水想定区域にどれだけの居住人口が重なるか',
    geography: '1km/500mメッシュと浸水想定polygon',
    dataRefs: [
      { kind: 'gis', id: 'A31b', role: '洪水浸水想定区域' },
      { kind: 'gis', id: 'mesh1000r6', role: '人口メッシュ' },
      { kind: 'gis', id: 'N03', role: '市区町村集約' },
    ],
    existingAssets: [
      'KSJ A31b catalog',
      'KSJ mesh1000r6 pipeline',
      '防災カテゴリランキング',
    ],
    method: [
      '浸水想定polygonと人口メッシュを決定論的に交差',
      '想定深・計画規模・提供年が異なるレイヤーを混ぜない',
      '重複面積と境界セルの扱いを公開',
    ],
    outputChannels: [
      '地域分析pilot',
      'X地図カード',
      '防災方法note候補',
      '法人ケース候補',
    ],
    qualityGates: [
      '公式ハザード情報への常設導線',
      '安全・避難判断を断定しない',
      'CRS・空間単位・更新年・coverage監査',
    ],
    owner: 'gis-curator',
    status: 'gated',
  },
  {
    id: 'pilot-population-station',
    contentId: 'geo-062',
    question: '駅に近く、2050年人口が相対的に残る場所はどこか',
    geography: '駅地点/路線と1kmメッシュ、市区町村',
    dataRefs: [
      { kind: 'gis', id: 'N02', role: '鉄道・駅' },
      { kind: 'gis', id: 'S12', role: '駅別乗降客数の補助' },
      { kind: 'gis', id: 'mesh1000r6', role: '将来人口メッシュ' },
      { kind: 'metric', id: 'railway-station-count', role: '既存県比較・入口' },
    ],
    existingAssets: [
      '/ranking/railway-station-count',
      'KSJ N02/S12 catalog',
      'KSJ mesh1000r6 pipeline',
    ],
    method: [
      '駅徒歩圏の距離定義を先に固定',
      '駅数とアクセス可能人口を別指標にする',
      '将来人口メッシュとの交差結果を市区町村へ集約',
    ],
    outputChannels: [
      '地域分析pilot',
      'X地図カード',
      '駅アクセスnote候補',
      '移住・住宅導線候補',
    ],
    qualityGates: [
      '徒歩圏距離とネットワーク距離の限界',
      '廃駅・年度・駅グループ重複',
      '交通利便性を駅数だけで断定しない',
    ],
    owner: 'gis-curator',
    status: 'gated',
  },
];

export const BUSINESS_PLAN_2026: BusinessPlanCatalog = {
  id: 'stats47-business-plan-2026',
  version: '2026-08-28.1',
  source: {
    title: 'stats47 2.0 超具体的 事業計画書',
    subtitle: 'GIS × AI × 地域データによるstats47事業拡張計画',
    sourcePath:
      '/Users/minamidaisuke/Downloads/stats47_2_business_plan_2026.docx',
    sourceSha256:
      '04f678551e1395a2033d8d6e34e7b6029932792f61e9dd178aedaa690de510c8',
    sourcePages: 35,
    sourceCheckedAt: '2026-08-28',
    planPeriod: '2026-09〜2027-08',
    note: '売上・CVR・アクセス目標は予測ではなく意思決定用の仮説。原本はローカル参考資料であり、正典は本カタログと既存docs。',
  },
  vision:
    'ランキングを入口に、地図で理解し、データを資産化し、AIで探し、需要が確認できた領域を法人価値へつなぐ。',
  tagline: '日本の地域データを、探す・比べる・分析する。',
  principles: [
    '新ブランドを作らずstats47を拡張する',
    '最初の90日はSaaSを作らない',
    '市区町村ページを機械的に量産しない',
    '計算と空間処理は決定論的に行う',
    '無料で結論、有料で再現性・解像度・時短を提供する',
    '一次資料・方法・限界・AI利用を開示する',
  ],
  revenueLayers: ['集客', '商用意図', '知識・データ販売', '継続課金', '法人'],
  priorityThemes: [
    '人口・未来',
    '住まい・移住',
    '防災',
    '医療・生活利便',
    '交通・都市構造',
    '地域経済・商圏',
  ],
  decisions: BUSINESS_PLAN_DECISIONS,
  documents: BUSINESS_PLAN_DOCUMENTS,
  metrics: BUSINESS_PLAN_METRICS,
  events: BUSINESS_PLAN_EVENTS,
  initiatives: BUSINESS_PLAN_INITIATIVES,
  pilotSpecs: BUSINESS_PLAN_PILOT_SPECS,
  contentOpportunities: BUSINESS_PLAN_CONTENT_OPPORTUNITIES,
  xIdeas: BUSINESS_PLAN_X_IDEAS,
  noteProducts: BUSINESS_PLAN_NOTE_PRODUCTS,
};
