/**
 * seed-to-d1-sql: seed/<table>.json (DB ネイティブ snake_case 列) を
 * リモート D1 投入用の SQL (INSERT OR REPLACE) に変換する。
 *
 * リモート D1 ハイブリッド (docs/01_技術設計/17_DBレス・アーキテクチャ移行設計.md) の seed 投入手段。
 * 生成した .sql は wrangler で D1 に流す:
 *   wrangler d1 execute stats47 --remote --file=packages/database/seed/d1-seed.sql
 *
 * 使い方:
 *   # 既定の Authored セット + articles をまとめて 1 ファイルに
 *   npx tsx packages/database/scripts/seed-to-d1-sql.ts
 *
 *   # テーブル指定
 *   npx tsx packages/database/scripts/seed-to-d1-sql.ts --tables articles,sns_posts
 *
 * 出力: packages/database/seed/d1-seed.sql
 */

import fs from "fs";
import path from "path";

const SEED_DIR = path.resolve(__dirname, "..", "seed");
const OUT_SQL = path.join(SEED_DIR, "d1-seed.sql");

/** seed が存在すれば投入する既定テーブル (Authored + articles) */
const DEFAULT_TABLES = [
  "articles",
  "sns_posts",
  "page_components",
  "affiliate_ads",
  "theme_metrics",
  "categories",
  "themes",
];

function sqlLiteral(v: unknown): string {
  if (v === null || v === undefined) return "NULL";
  if (typeof v === "number") return Number.isFinite(v) ? String(v) : "NULL";
  if (typeof v === "boolean") return v ? "1" : "0";
  if (typeof v === "object") {
    // JSON カラム等は文字列化して格納
    return `'${JSON.stringify(v).replace(/'/g, "''")}'`;
  }
  return `'${String(v).replace(/'/g, "''")}'`;
}

function tableToSql(table: string, rows: Record<string, unknown>[]): string {
  if (rows.length === 0) return `-- ${table}: 0 rows (skip)\n`;
  // 列順は最初の行のキー (全行同一 schema 前提)
  const cols = Object.keys(rows[0]);
  const colList = cols.map((c) => `"${c}"`).join(", ");
  const lines: string[] = [
    `-- ${table}: ${rows.length} rows`,
    `DELETE FROM "${table}";`,
  ];
  // バッチ INSERT (D1 の SQL サイズ制限を考慮し 100 行ずつ)
  const BATCH = 100;
  for (let i = 0; i < rows.length; i += BATCH) {
    const chunk = rows.slice(i, i + BATCH);
    const values = chunk
      .map((r) => `(${cols.map((c) => sqlLiteral(r[c])).join(", ")})`)
      .join(",\n  ");
    lines.push(
      `INSERT OR REPLACE INTO "${table}" (${colList}) VALUES\n  ${values};`,
    );
  }
  return lines.join("\n") + "\n";
}

function main() {
  const argv = process.argv.slice(2);
  const tIdx = argv.indexOf("--tables");
  const tables =
    tIdx >= 0 && argv[tIdx + 1]
      ? argv[tIdx + 1].split(",").map((s) => s.trim()).filter(Boolean)
      : DEFAULT_TABLES;

  const out: string[] = [
    "-- Generated by seed-to-d1-sql.ts",
    "-- リモート D1 投入用 seed (docs/01_技術設計/17_DBレス・アーキテクチャ移行設計.md)",
    "PRAGMA foreign_keys=OFF;",
    "",
  ];
  let totalRows = 0;
  const summary: string[] = [];
  for (const table of tables) {
    const seedPath = path.join(SEED_DIR, `${table}.json`);
    if (!fs.existsSync(seedPath)) {
      summary.push(`  - ${table}: seed なし (skip)`);
      continue;
    }
    const rows = JSON.parse(fs.readFileSync(seedPath, "utf8")) as Record<
      string,
      unknown
    >[];
    out.push(tableToSql(table, rows));
    totalRows += rows.length;
    summary.push(`  - ${table}: ${rows.length} rows`);
  }

  fs.writeFileSync(OUT_SQL, out.join("\n"));
  console.log(`✅ ${path.relative(process.cwd(), OUT_SQL)} を生成`);
  console.log(summary.join("\n"));
  console.log(`合計 ${totalRows} 行`);
  console.log(
    `\n投入: wrangler d1 execute stats47 --remote --file=${path.relative(process.cwd(), OUT_SQL)}`,
  );
}

main();
