
 ⛅️ wrangler 4.42.2
───────────────────
🌀 Executing on remote database stats47 (e6533698-d05a-475b-9f39-5558703feef7):
🌀 To execute on your local development database, remove the --remote flag from your wrangler command.
🚣 Executed 1 command in 3.2198ms
[
  {
    "results": [
      {
        "id": 1,
        "ranking_key": "accommodations",
        "label": "宿泊施設数",
        "name": "宿泊施設数",
        "description": null,
        "unit": "施設",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 2,
        "ranking_key": "adultClassLecture",
        "label": "成人一般学級・講座数（人口100万人当たり）",
        "name": "成人一般学級・講座数（人口100万人当たり）",
        "description": null,
        "unit": "学級・講座",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 3,
        "ranking_key": "agriculturalHouseholds",
        "label": "農業世帯数",
        "name": "農業世帯数",
        "description": null,
        "unit": "世帯",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 4,
        "ranking_key": "agriculturalLand",
        "label": "農用地",
        "name": "農用地",
        "description": null,
        "unit": "ha",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:07:51",
        "updated_at": "2025-10-11 00:07:51"
      },
      {
        "id": 5,
        "ranking_key": "agriculturalLandRatio",
        "label": "農用地割合",
        "name": "農用地割合",
        "description": null,
        "unit": "%",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:07:51",
        "updated_at": "2025-10-11 00:07:51"
      },
      {
        "id": 6,
        "ranking_key": "areaRatio",
        "label": "面積割合",
        "name": "面積割合（全国面積に占める割合）",
        "description": null,
        "unit": "%",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:07:51",
        "updated_at": "2025-10-11 00:07:51"
      },
      {
        "id": 7,
        "ranking_key": "averageHouseholdSize",
        "label": "平均世帯人員",
        "name": "平均世帯人員",
        "description": null,
        "unit": "人",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 8,
        "ranking_key": "averageIncome",
        "label": "平均収入",
        "name": "平均収入",
        "description": null,
        "unit": "円",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 9,
        "ranking_key": "avgTemperature",
        "label": "年平均気温",
        "name": "年平均気温",
        "description": null,
        "unit": "℃",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 10,
        "ranking_key": "birthRate",
        "label": "出生率",
        "name": "出生率",
        "description": null,
        "unit": "‰",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 11,
        "ranking_key": "births",
        "label": "出生数",
        "name": "出生数",
        "description": null,
        "unit": "人",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 12,
        "ranking_key": "children",
        "label": "園児数",
        "name": "園児数",
        "description": null,
        "unit": "人",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 13,
        "ranking_key": "clearDays",
        "label": "快晴日数（年間）",
        "name": "快晴日数（年間）",
        "description": null,
        "unit": "日",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 14,
        "ranking_key": "collegeCount",
        "label": "短期大学数",
        "name": "短期大学数",
        "description": null,
        "unit": "校",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 15,
        "ranking_key": "collegeStudents",
        "label": "短期大学生数",
        "name": "短期大学生数",
        "description": null,
        "unit": "人",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 16,
        "ranking_key": "commercialLand",
        "label": "商業地",
        "name": "商業地",
        "description": null,
        "unit": "ha",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:07:51",
        "updated_at": "2025-10-11 00:07:51"
      },
      {
        "id": 17,
        "ranking_key": "communitySports",
        "label": "社会体育施設数（人口100万人当たり）",
        "name": "社会体育施設数（人口100万人当たり）",
        "description": null,
        "unit": "施設",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 18,
        "ranking_key": "companyHousingUnits",
        "label": "給与住宅数",
        "name": "給与住宅数",
        "description": null,
        "unit": "戸",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 19,
        "ranking_key": "dayTimePopulation",
        "label": "昼間人口",
        "name": "昼間人口",
        "description": null,
        "unit": "人",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 20,
        "ranking_key": "dayTimePopulationRatio",
        "label": "昼夜間人口比率",
        "name": "昼夜間人口比率",
        "description": null,
        "unit": "%",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 21,
        "ranking_key": "deathRate",
        "label": "死亡率",
        "name": "死亡率",
        "description": null,
        "unit": "‰",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 22,
        "ranking_key": "deaths",
        "label": "死亡数",
        "name": "死亡数",
        "description": null,
        "unit": "人",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 23,
        "ranking_key": "debt",
        "label": "債務",
        "name": "債務",
        "description": null,
        "unit": "百万円",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 24,
        "ranking_key": "detachedHouses",
        "label": "一戸建住宅数",
        "name": "一戸建住宅数",
        "description": null,
        "unit": "戸",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 25,
        "ranking_key": "detachedNonWoodenHouses",
        "label": "一戸建住宅数（非木造）",
        "name": "一戸建住宅数（非木造）",
        "description": null,
        "unit": "戸",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 26,
        "ranking_key": "detachedWoodenHouses",
        "label": "一戸建住宅数（木造）",
        "name": "一戸建住宅数（木造）",
        "description": null,
        "unit": "戸",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 27,
        "ranking_key": "didAreaRatio",
        "label": "人口集中地区面積比率",
        "name": "人口集中地区面積比率",
        "description": null,
        "unit": "%",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 28,
        "ranking_key": "disabilityCertificates",
        "label": "身体障害者手帳交付数（人口千人当たり）",
        "name": "身体障害者手帳交付数（人口千人当たり）",
        "description": null,
        "unit": "人",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 29,
        "ranking_key": "disposableIncome",
        "label": "可処分所得",
        "name": "可処分所得",
        "description": null,
        "unit": "円",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 30,
        "ranking_key": "divorceRate",
        "label": "離婚率",
        "name": "離婚率",
        "description": null,
        "unit": "‰",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 31,
        "ranking_key": "divorces",
        "label": "離婚件数",
        "name": "離婚件数",
        "description": null,
        "unit": "件",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 32,
        "ranking_key": "educationBeneficiaries",
        "label": "生活保護教育扶助人員（月平均人口千人当たり）",
        "name": "生活保護教育扶助人員（月平均人口千人当たり）",
        "description": null,
        "unit": "人",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 33,
        "ranking_key": "elderlyClassLecture",
        "label": "高齢者学級・講座数（人口100万人当たり）",
        "name": "高齢者学級・講座数（人口100万人当たり）",
        "description": null,
        "unit": "学級・講座",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 34,
        "ranking_key": "elderlyOnAssistance",
        "label": "生活保護被保護高齢者数（月平均65歳以上人口千人当たり）",
        "name": "生活保護被保護高齢者数（月平均65歳以上人口千人当たり）",
        "description": null,
        "unit": "人",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 35,
        "ranking_key": "elderlyPopulation",
        "label": "65歳以上人口割合",
        "name": "65歳以上人口割合",
        "description": null,
        "unit": "%",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 36,
        "ranking_key": "employees",
        "label": "従業者数",
        "name": "従業者数",
        "description": null,
        "unit": "人",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 37,
        "ranking_key": "establishments_1",
        "label": "事業所数",
        "name": "事業所数",
        "description": null,
        "unit": "事業所",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 38,
        "ranking_key": "establishments_2",
        "label": "製造業事業所数",
        "name": "製造業事業所数",
        "description": null,
        "unit": "事業所",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 39,
        "ranking_key": "exclusiveResidentialUnits",
        "label": "専用住宅数",
        "name": "専用住宅数",
        "description": null,
        "unit": "戸",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 40,
        "ranking_key": "expenditure",
        "label": "歳出",
        "name": "歳出",
        "description": null,
        "unit": "百万円",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 41,
        "ranking_key": "farmArea",
        "label": "農地面積",
        "name": "農地面積",
        "description": null,
        "unit": "ha",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 42,
        "ranking_key": "farmWorkers",
        "label": "農業従事者数",
        "name": "農業従事者数",
        "description": null,
        "unit": "人",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 43,
        "ranking_key": "femaleClassLecture",
        "label": "女性学級・講座数（女性人口100万人当たり）",
        "name": "女性学級・講座数（女性人口100万人当たり）",
        "description": null,
        "unit": "学級・講座",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 44,
        "ranking_key": "fireStations",
        "label": "消防署数",
        "name": "消防署数",
        "description": null,
        "unit": "署",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 45,
        "ranking_key": "fireTrucks",
        "label": "消防車両数",
        "name": "消防車両数",
        "description": null,
        "unit": "台",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 46,
        "ranking_key": "firefighters",
        "label": "消防職員数",
        "name": "消防職員数",
        "description": null,
        "unit": "人",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 47,
        "ranking_key": "forestLand",
        "label": "森林",
        "name": "森林",
        "description": null,
        "unit": "ha",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:07:51",
        "updated_at": "2025-10-11 00:07:51"
      },
      {
        "id": 48,
        "ranking_key": "forestLandRatio",
        "label": "森林割合",
        "name": "森林割合",
        "description": null,
        "unit": "%",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:07:51",
        "updated_at": "2025-10-11 00:07:51"
      },
      {
        "id": 49,
        "ranking_key": "gymInstallationRate_1",
        "label": "公立小学校屋内運動場設置率",
        "name": "公立小学校屋内運動場設置率",
        "description": null,
        "unit": "％",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 50,
        "ranking_key": "gymInstallationRate_2",
        "label": "公立中学校屋内運動場設置率",
        "name": "公立中学校屋内運動場設置率",
        "description": null,
        "unit": "％",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 51,
        "ranking_key": "gymnasium",
        "label": "体育館数（公共）（人口100万人当たり）",
        "name": "体育館数（公共）（人口100万人当たり）",
        "description": null,
        "unit": "施設",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 52,
        "ranking_key": "habitableArea",
        "label": "可住地面積",
        "name": "可住地面積",
        "description": null,
        "unit": "ha",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:07:51",
        "updated_at": "2025-10-11 00:07:51"
      },
      {
        "id": 53,
        "ranking_key": "habitableAreaRatio",
        "label": "可住地面積割合",
        "name": "可住地面積割合",
        "description": null,
        "unit": "%",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:07:51",
        "updated_at": "2025-10-11 00:07:51"
      },
      {
        "id": 54,
        "ranking_key": "healthLifeExpectancyFemale",
        "label": "健康寿命（女）",
        "name": "健康寿命（女）",
        "description": null,
        "unit": "年",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 55,
        "ranking_key": "healthLifeExpectancyMale",
        "label": "健康寿命（男）",
        "name": "健康寿命（男）",
        "description": null,
        "unit": "年",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 56,
        "ranking_key": "hotels",
        "label": "宿泊施設数",
        "name": "宿泊施設数",
        "description": null,
        "unit": "施設",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 57,
        "ranking_key": "householdsOnAssistance",
        "label": "生活保護被保護実世帯数（月平均一般世帯千世帯当たり）",
        "name": "生活保護被保護実世帯数（月平均一般世帯千世帯当たり）",
        "description": null,
        "unit": "世帯",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 58,
        "ranking_key": "housingBeneficiaries",
        "label": "生活保護住宅扶助人員（月平均人口千人当たり）",
        "name": "生活保護住宅扶助人員（月平均人口千人当たり）",
        "description": null,
        "unit": "人",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 59,
        "ranking_key": "housingStarts",
        "label": "住宅着工数",
        "name": "住宅着工数",
        "description": null,
        "unit": "戸",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 60,
        "ranking_key": "housingStock",
        "label": "住宅ストック",
        "name": "住宅ストック",
        "description": null,
        "unit": "戸",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 61,
        "ranking_key": "housingUnits",
        "label": "住宅数",
        "name": "住宅数",
        "description": null,
        "unit": "戸",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 62,
        "ranking_key": "humidity",
        "label": "年平均相対湿度",
        "name": "年平均相対湿度",
        "description": null,
        "unit": "%",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 63,
        "ranking_key": "industrialLand",
        "label": "工業地",
        "name": "工業地",
        "description": null,
        "unit": "ha",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:07:51",
        "updated_at": "2025-10-11 00:07:51"
      },
      {
        "id": 64,
        "ranking_key": "infantHealthCheckup",
        "label": "健康診断受診者数（保健所実施分・乳幼児）",
        "name": "健康診断受診者数（保健所実施分・乳幼児）",
        "description": null,
        "unit": "人",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 65,
        "ranking_key": "inflowPopulationInPref",
        "label": "流入人口（県内他市区町村）",
        "name": "流入人口（県内他市区町村）",
        "description": null,
        "unit": "人",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 66,
        "ranking_key": "inflowPopulationOtherPref",
        "label": "流入人口（他県）",
        "name": "流入人口（他県）",
        "description": null,
        "unit": "人",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 67,
        "ranking_key": "kindergartens",
        "label": "幼稚園数",
        "name": "幼稚園数",
        "description": null,
        "unit": "園",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 68,
        "ranking_key": "library",
        "label": "図書館数（人口100万人当たり）",
        "name": "図書館数（人口100万人当たり）",
        "description": null,
        "unit": "館",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 69,
        "ranking_key": "lifeExpectancyAt20Female",
        "label": "平均余命（20歳）（女）",
        "name": "平均余命（20歳）（女）",
        "description": null,
        "unit": "年",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 70,
        "ranking_key": "lifeExpectancyAt20Male",
        "label": "平均余命（20歳）（男）",
        "name": "平均余命（20歳）（男）",
        "description": null,
        "unit": "年",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 71,
        "ranking_key": "lifeExpectancyAt40Female",
        "label": "平均余命（40歳）（女）",
        "name": "平均余命（40歳）（女）",
        "description": null,
        "unit": "年",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 72,
        "ranking_key": "lifeExpectancyAt40Male",
        "label": "平均余命（40歳）（男）",
        "name": "平均余命（40歳）（男）",
        "description": null,
        "unit": "年",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 73,
        "ranking_key": "lifeExpectancyAt60Female",
        "label": "平均余命（60歳）（女）",
        "name": "平均余命（60歳）（女）",
        "description": null,
        "unit": "年",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 74,
        "ranking_key": "lifeExpectancyAt60Male",
        "label": "平均余命（60歳）（男）",
        "name": "平均余命（60歳）（男）",
        "description": null,
        "unit": "年",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 75,
        "ranking_key": "lifeExpectancyAt65Female",
        "label": "平均余命（65歳）（女）",
        "name": "平均余命（65歳）（女）",
        "description": null,
        "unit": "年",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 76,
        "ranking_key": "lifeExpectancyAt65Male",
        "label": "平均余命（65歳）（男）",
        "name": "平均余命（65歳）（男）",
        "description": null,
        "unit": "年",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 77,
        "ranking_key": "lifeExpectancyAtBirthFemale",
        "label": "平均余命（0歳）（女）",
        "name": "平均余命（0歳）（女）",
        "description": null,
        "unit": "年",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 78,
        "ranking_key": "lifeExpectancyAtBirthMale",
        "label": "平均余命（0歳）（男）",
        "name": "平均余命（0歳）（男）",
        "description": null,
        "unit": "年",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 79,
        "ranking_key": "lifestyleDiseaseCheckup",
        "label": "健康診断受診者数（保健所及び市区町村実施分）（生活習慣病）",
        "name": "健康診断受診者数（保健所及び市区町村実施分）（生活習慣病）",
        "description": null,
        "unit": "人",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 80,
        "ranking_key": "majorLakeArea",
        "label": "主要湖沼面積",
        "name": "主要湖沼面積",
        "description": null,
        "unit": "ha",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:07:51",
        "updated_at": "2025-10-11 00:07:51"
      },
      {
        "id": 81,
        "ranking_key": "manual-9999999999-Z9999",
        "label": "テストデータ",
        "name": "テスト統計",
        "description": null,
        "unit": "個",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-12 23:36:46",
        "updated_at": "2025-10-12 23:36:46"
      },
      {
        "id": 82,
        "ranking_key": "marriageRate",
        "label": "婚姻率",
        "name": "婚姻率",
        "description": null,
        "unit": "‰",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 83,
        "ranking_key": "marriages",
        "label": "婚姻件数",
        "name": "婚姻件数",
        "description": null,
        "unit": "件",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 84,
        "ranking_key": "maternalHealthCheckup",
        "label": "健康診断受診者数（保健所実施分・妊産婦）",
        "name": "健康診断受診者数（保健所実施分・妊産婦）",
        "description": null,
        "unit": "人",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 85,
        "ranking_key": "maxTemperature",
        "label": "最高気温（日最高気温の月平均の最高値）",
        "name": "最高気温（日最高気温の月平均の最高値）",
        "description": null,
        "unit": "℃",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 86,
        "ranking_key": "medianIncome",
        "label": "中央値収入",
        "name": "中央値収入",
        "description": null,
        "unit": "円",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 87,
        "ranking_key": "medicalBeneficiaries",
        "label": "生活保護医療扶助人員（月平均人口千人当たり）",
        "name": "生活保護医療扶助人員（月平均人口千人当たり）",
        "description": null,
        "unit": "人",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 88,
        "ranking_key": "mentalHealthCheckup",
        "label": "健康診断受診者数（保健所実施分・精神）",
        "name": "健康診断受診者数（保健所実施分・精神）",
        "description": null,
        "unit": "人",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 89,
        "ranking_key": "minTemperature",
        "label": "最低気温（日最低気温の月平均の最低値）",
        "name": "最低気温（日最低気温の月平均の最低値）",
        "description": null,
        "unit": "℃",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 90,
        "ranking_key": "mixedUseHousingUnits",
        "label": "店舗その他の併用住宅数",
        "name": "店舗その他の併用住宅数",
        "description": null,
        "unit": "戸",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 91,
        "ranking_key": "moversIn",
        "label": "転入者数",
        "name": "転入者数",
        "description": null,
        "unit": "人",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 92,
        "ranking_key": "moversOut",
        "label": "転出者数",
        "name": "転出者数",
        "description": null,
        "unit": "人",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 93,
        "ranking_key": "multipurposeGround",
        "label": "多目的運動広場数（公共）（人口100万人当たり）",
        "name": "多目的運動広場数（公共）（人口100万人当たり）",
        "description": null,
        "unit": "施設",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 94,
        "ranking_key": "museum",
        "label": "博物館数（人口100万人当たり）",
        "name": "博物館数（人口100万人当たり）",
        "description": null,
        "unit": "館",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 95,
        "ranking_key": "nationalParks",
        "label": "国立公園",
        "name": "国立公園",
        "description": null,
        "unit": "箇所",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 96,
        "ranking_key": "nationalParksArea",
        "label": "国立公園面積",
        "name": "国立公園面積",
        "description": null,
        "unit": "ha",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 97,
        "ranking_key": "naturalIncrease",
        "label": "自然増減数",
        "name": "自然増減数",
        "description": null,
        "unit": "人",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 98,
        "ranking_key": "naturalMonuments",
        "label": "天然記念物",
        "name": "天然記念物",
        "description": null,
        "unit": "箇所",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 99,
        "ranking_key": "nuclearFamilyHouseholds",
        "label": "核家族世帯数",
        "name": "核家族世帯数",
        "description": null,
        "unit": "世帯",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 100,
        "ranking_key": "nursingBeneficiaries",
        "label": "生活保護介護扶助人員（月平均人口千人当たり）",
        "name": "生活保護介護扶助人員（月平均人口千人当たり）",
        "description": null,
        "unit": "人",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 101,
        "ranking_key": "occupancyRate",
        "label": "稼働率",
        "name": "稼働率",
        "description": null,
        "unit": "%",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 102,
        "ranking_key": "occupiedHousingUnits",
        "label": "居住世帯あり住宅数",
        "name": "居住世帯あり住宅数",
        "description": null,
        "unit": "戸",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 103,
        "ranking_key": "outflowPopulationInPref",
        "label": "流出人口（県内他市区町村）",
        "name": "流出人口（県内他市区町村）",
        "description": null,
        "unit": "人",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 104,
        "ranking_key": "outflowPopulationOtherPref",
        "label": "流出人口（他県）",
        "name": "流出人口（他県）",
        "description": null,
        "unit": "人",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 105,
        "ranking_key": "overseasTravel",
        "label": "海外旅行の年間行動者率（15歳以上）",
        "name": "海外旅行の年間行動者率（15歳以上）",
        "description": null,
        "unit": "％",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 106,
        "ranking_key": "ownerOccupiedHousing",
        "label": "持ち家数",
        "name": "持ち家数",
        "description": null,
        "unit": "戸",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 107,
        "ranking_key": "passportIssuance",
        "label": "一般旅券発行件数（人口千人当たり）",
        "name": "一般旅券発行件数（人口千人当たり）",
        "description": null,
        "unit": "件",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 108,
        "ranking_key": "perAreaCount_1",
        "label": "小学校数（可住地面積100km2当たり）",
        "name": "小学校数（可住地面積100km2当たり）",
        "description": null,
        "unit": "校",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 109,
        "ranking_key": "perAreaCount_2",
        "label": "高等学校数（可住地面積100km2当たり）",
        "name": "高等学校数（可住地面積100km2当たり）",
        "description": null,
        "unit": "校",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 110,
        "ranking_key": "perAreaCount_3",
        "label": "中学校数（可住地面積100km2当たり）",
        "name": "中学校数（可住地面積100km2当たり）",
        "description": null,
        "unit": "校",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 111,
        "ranking_key": "perCapitaCount_1",
        "label": "小学校数（6～11歳人口10万人当たり）",
        "name": "小学校数（6～11歳人口10万人当たり）",
        "description": null,
        "unit": "校",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 112,
        "ranking_key": "perCapitaCount_2",
        "label": "高等学校数（15～17歳人口10万人当たり）",
        "name": "高等学校数（15～17歳人口10万人当たり）",
        "description": null,
        "unit": "校",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 113,
        "ranking_key": "perCapitaCount_3",
        "label": "中学校数（12～14歳人口10万人当たり）",
        "name": "中学校数（12～14歳人口10万人当たり）",
        "description": null,
        "unit": "校",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 114,
        "ranking_key": "personsOnAssistance",
        "label": "生活保護被保護実人員（月平均人口千人当たり）",
        "name": "生活保護被保護実人員（月平均人口千人当たり）",
        "description": null,
        "unit": "人",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 115,
        "ranking_key": "poolInstallationRate_1",
        "label": "公立小学校プール設置率",
        "name": "公立小学校プール設置率",
        "description": null,
        "unit": "％",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 116,
        "ranking_key": "poolInstallationRate_2",
        "label": "公立高等学校プール設置率",
        "name": "公立高等学校プール設置率",
        "description": null,
        "unit": "％",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 117,
        "ranking_key": "poolInstallationRate_3",
        "label": "公立中学校プール設置率",
        "name": "公立中学校プール設置率",
        "description": null,
        "unit": "％",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 118,
        "ranking_key": "populationDensity",
        "label": "人口密度",
        "name": "人口密度",
        "description": null,
        "unit": "人/km²",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 119,
        "ranking_key": "precipitation",
        "label": "降水量（年間）",
        "name": "降水量（年間）",
        "description": null,
        "unit": "mm",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 120,
        "ranking_key": "precipitationDays",
        "label": "降水日数（年間）",
        "name": "降水日数（年間）",
        "description": null,
        "unit": "日",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 121,
        "ranking_key": "prefecturalParks",
        "label": "都道府県立自然公園",
        "name": "都道府県立自然公園",
        "description": null,
        "unit": "箇所",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 122,
        "ranking_key": "prefecturalParksArea",
        "label": "都道府県立自然公園面積",
        "name": "都道府県立自然公園面積",
        "description": null,
        "unit": "ha",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 123,
        "ranking_key": "privateRentalHousing",
        "label": "民営借家数",
        "name": "民営借家数",
        "description": null,
        "unit": "戸",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 124,
        "ranking_key": "publicHall",
        "label": "公民館数（人口100万人当たり）",
        "name": "公民館数（人口100万人当たり）",
        "description": null,
        "unit": "館",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 125,
        "ranking_key": "publicHealthCenterCheckup",
        "label": "健康診断受診者数（保健所実施分）",
        "name": "健康診断受診者数（保健所実施分）",
        "description": null,
        "unit": "人",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 126,
        "ranking_key": "publicHealthCenterLifestyleDiseaseCheckup",
        "label": "健康診断受診者数（保健所実施分・生活習慣病）",
        "name": "健康診断受診者数（保健所実施分・生活習慣病）",
        "description": null,
        "unit": "人",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 127,
        "ranking_key": "publicHousingUnits",
        "label": "公営の借家数",
        "name": "公営の借家数",
        "description": null,
        "unit": "戸",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 128,
        "ranking_key": "publicRatio",
        "label": "公立高等学校割合",
        "name": "公立高等学校割合",
        "description": null,
        "unit": "%",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 129,
        "ranking_key": "publicRentalHousing",
        "label": "公営・都市再生機構（ＵＲ）・公社の借家数",
        "name": "公営・都市再生機構（ＵＲ）・公社の借家数",
        "description": null,
        "unit": "戸",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 130,
        "ranking_key": "quasiNationalParks",
        "label": "国定公園",
        "name": "国定公園",
        "description": null,
        "unit": "箇所",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 131,
        "ranking_key": "quasiNationalParksArea",
        "label": "国定公園面積",
        "name": "国定公園面積",
        "description": null,
        "unit": "ha",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 132,
        "ranking_key": "rentalHousingUnits",
        "label": "借家数",
        "name": "借家数",
        "description": null,
        "unit": "戸",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 133,
        "ranking_key": "residentialLand",
        "label": "宅地",
        "name": "宅地",
        "description": null,
        "unit": "ha",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:07:51",
        "updated_at": "2025-10-11 00:07:51"
      },
      {
        "id": 134,
        "ranking_key": "residentialLandRatio",
        "label": "宅地割合",
        "name": "宅地割合",
        "description": null,
        "unit": "%",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:07:51",
        "updated_at": "2025-10-11 00:07:51"
      },
      {
        "id": 135,
        "ranking_key": "restaurants",
        "label": "飲食店数",
        "name": "飲食店数",
        "description": null,
        "unit": "店舗",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 136,
        "ranking_key": "retailStores",
        "label": "小売店舗数",
        "name": "小売店舗数",
        "description": null,
        "unit": "店舗",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 137,
        "ranking_key": "revenue",
        "label": "歳入",
        "name": "歳入",
        "description": null,
        "unit": "百万円",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 138,
        "ranking_key": "rowHouses",
        "label": "長屋建住宅数",
        "name": "長屋建住宅数",
        "description": null,
        "unit": "戸",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 139,
        "ranking_key": "sales",
        "label": "売上高",
        "name": "売上高",
        "description": null,
        "unit": "百万円",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 140,
        "ranking_key": "schoolCount_1",
        "label": "小学校数",
        "name": "小学校数",
        "description": null,
        "unit": "校",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 141,
        "ranking_key": "schoolCount_2",
        "label": "高等学校数",
        "name": "高等学校数",
        "description": null,
        "unit": "校",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 142,
        "ranking_key": "schoolCount_3",
        "label": "中学校数",
        "name": "中学校数",
        "description": null,
        "unit": "校",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 143,
        "ranking_key": "sewerageRate",
        "label": "下水道普及率",
        "name": "下水道普及率",
        "description": null,
        "unit": "%",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 144,
        "ranking_key": "sexRatio",
        "label": "人口性比（総数）",
        "name": "人口性比（総数）",
        "description": null,
        "unit": "-",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 145,
        "ranking_key": "singlePersonHouseholds",
        "label": "単独世帯数",
        "name": "単独世帯数",
        "description": null,
        "unit": "世帯",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 146,
        "ranking_key": "snowDays",
        "label": "雪日数（年間）",
        "name": "雪日数（年間）",
        "description": null,
        "unit": "日",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 147,
        "ranking_key": "socialIncrease",
        "label": "社会増減数",
        "name": "社会増減数",
        "description": null,
        "unit": "人",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 148,
        "ranking_key": "sports10plus",
        "label": "スポーツの年間行動者率（10歳以上）",
        "name": "スポーツの年間行動者率（10歳以上）",
        "description": null,
        "unit": "％",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 149,
        "ranking_key": "sportsParticipation",
        "label": "スポーツの年間行動者率（10歳以上）",
        "name": "スポーツの年間行動者率（10歳以上）",
        "description": null,
        "unit": "%",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 150,
        "ranking_key": "studentCount_1",
        "label": "小学校児童数",
        "name": "小学校児童数",
        "description": null,
        "unit": "人",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 151,
        "ranking_key": "studentCount_2",
        "label": "高等学校生徒数",
        "name": "高等学校生徒数",
        "description": null,
        "unit": "人",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 152,
        "ranking_key": "studentCount_3",
        "label": "中学校生徒数",
        "name": "中学校生徒数",
        "description": null,
        "unit": "人",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 153,
        "ranking_key": "sunshineDuration",
        "label": "日照時間（年間）",
        "name": "日照時間（年間）",
        "description": null,
        "unit": "時間",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 154,
        "ranking_key": "swimmingPool",
        "label": "水泳プール数（屋内，屋外）（公共）（人口100万人当たり）",
        "name": "水泳プール数（屋内，屋外）（公共）（人口100万人当たり）",
        "description": null,
        "unit": "施設",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 155,
        "ranking_key": "teachers",
        "label": "教職員数",
        "name": "教職員数",
        "description": null,
        "unit": "人",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 156,
        "ranking_key": "temporaryResidentsOnly",
        "label": "一時現在者のみ住宅数",
        "name": "一時現在者のみ住宅数",
        "description": null,
        "unit": "戸",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 157,
        "ranking_key": "totalAreaExcluding",
        "label": "総面積（除く）",
        "name": "総面積（北方地域及び竹島を除く）",
        "description": null,
        "unit": "ha",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:07:51",
        "updated_at": "2025-10-11 00:07:51"
      },
      {
        "id": 158,
        "ranking_key": "totalAreaIncluding",
        "label": "総面積（含む）",
        "name": "総面積（北方地域及び竹島を含む）",
        "description": null,
        "unit": "ha",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:07:51",
        "updated_at": "2025-10-11 00:07:51"
      },
      {
        "id": 159,
        "ranking_key": "totalAreaIncludingRatio",
        "label": "総面積（100km²）",
        "name": "総面積（北方地域及び竹島を含む）",
        "description": null,
        "unit": "100km²",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:07:51",
        "updated_at": "2025-10-11 00:07:51"
      },
      {
        "id": 160,
        "ranking_key": "totalHouseholds",
        "label": "総世帯数",
        "name": "総世帯数",
        "description": null,
        "unit": "世帯",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 161,
        "ranking_key": "totalHousingUnits",
        "label": "総住宅数",
        "name": "総住宅数",
        "description": null,
        "unit": "戸",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 162,
        "ranking_key": "totalPopulation",
        "label": "総人口",
        "name": "総人口",
        "description": null,
        "unit": "人",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 163,
        "ranking_key": "tourists",
        "label": "観光客数",
        "name": "観光客数",
        "description": null,
        "unit": "人",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 164,
        "ranking_key": "travel10plus",
        "label": "旅行・行楽の年間行動者率（10歳以上）",
        "name": "旅行・行楽の年間行動者率（10歳以上）",
        "description": null,
        "unit": "％",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 165,
        "ranking_key": "travel15plus",
        "label": "旅行・行楽の年間行動者率（15歳以上）",
        "name": "旅行・行楽の年間行動者率（15歳以上）",
        "description": null,
        "unit": "％",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 166,
        "ranking_key": "tuberculosisCheckup",
        "label": "健康診断受診者数（保健所及び市区町村実施分）（結核）",
        "name": "健康診断受診者数（保健所及び市区町村実施分）（結核）",
        "description": null,
        "unit": "人",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 167,
        "ranking_key": "underConstructionHousing",
        "label": "建築中住宅数",
        "name": "建築中住宅数",
        "description": null,
        "unit": "戸",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 168,
        "ranking_key": "universityCount",
        "label": "大学数",
        "name": "大学数",
        "description": null,
        "unit": "校",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 169,
        "ranking_key": "universityStudents",
        "label": "大学生数",
        "name": "大学生数",
        "description": null,
        "unit": "人",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 170,
        "ranking_key": "urPublicCorporationHousing",
        "label": "都市再生機構（ＵＲ）・公社の借家数",
        "name": "都市再生機構（ＵＲ）・公社の借家数",
        "description": null,
        "unit": "戸",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 171,
        "ranking_key": "vacantHouses",
        "label": "空き家数",
        "name": "空き家数",
        "description": null,
        "unit": "戸",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 172,
        "ranking_key": "vacantHousingUnits",
        "label": "居住世帯なし住宅数",
        "name": "居住世帯なし住宅数",
        "description": null,
        "unit": "戸",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 173,
        "ranking_key": "valueAdded",
        "label": "製造業付加価値額",
        "name": "製造業付加価値額",
        "description": null,
        "unit": "百万円",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 174,
        "ranking_key": "volunteer10plus",
        "label": "ボランティア活動の年間行動者率（10歳以上）",
        "name": "ボランティア活動の年間行動者率（10歳以上）",
        "description": null,
        "unit": "％",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 175,
        "ranking_key": "volunteer15plus",
        "label": "ボランティア活動の年間行動者率（15歳以上）",
        "name": "ボランティア活動の年間行動者率（15歳以上）",
        "description": null,
        "unit": "％",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 176,
        "ranking_key": "waterSupplyRate",
        "label": "上水道普及率",
        "name": "上水道普及率",
        "description": null,
        "unit": "%",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 177,
        "ranking_key": "waterUsage",
        "label": "水使用量",
        "name": "水使用量",
        "description": null,
        "unit": "L/人・日",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 178,
        "ranking_key": "workingAgePopulation",
        "label": "15-64歳人口割合",
        "name": "15-64歳人口割合",
        "description": null,
        "unit": "%",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 179,
        "ranking_key": "youngPopulation",
        "label": "15歳未満人口割合",
        "name": "15歳未満人口割合",
        "description": null,
        "unit": "%",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 180,
        "ranking_key": "youthClassLecture",
        "label": "青少年学級・講座数（人口100万人当たり）",
        "name": "青少年学級・講座数（人口100万人当たり）",
        "description": null,
        "unit": "学級・講座",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      },
      {
        "id": 181,
        "ranking_key": "youthEducation",
        "label": "青少年教育施設数（人口100万人当たり）",
        "name": "青少年教育施設数（人口100万人当たり）",
        "description": null,
        "unit": "所",
        "data_source_id": "estat",
        "map_color_scheme": "interpolateBlues",
        "map_diverging_midpoint": "zero",
        "ranking_direction": "desc",
        "conversion_factor": 1,
        "decimal_places": 0,
        "is_active": 1,
        "created_at": "2025-10-11 00:20:14",
        "updated_at": "2025-10-11 00:20:14"
      }
    ],
    "success": true,
    "meta": {
      "served_by": "v3-prod",
      "served_by_region": "APAC",
      "served_by_primary": true,
      "timings": {
        "sql_duration_ms": 3.2198
      },
      "duration": 3.2198,
      "changes": 0,
      "last_row_id": 188,
      "changed_db": false,
      "size_after": 2953216,
      "rows_read": 181,
      "rows_written": 0,
      "total_attempts": 1
    }
  }
]
