/**
 * 形状違反を明示的に許可した metric の一覧。
 *
 * ★このファイルの `EXPECTED_SHAPE_ANOMALY` 配列は **生成物**。手で書かない。
 *   再生成: `npx tsx packages/data-configs/scripts/scan-stats-shape.ts --emit-allowlist`
 *   194 件を手書きすると必ず写し間違えるため、走査スクリプトの出力を貼る。
 *
 * ## なぜ allowlist が要るか
 *
 * 2026-07-30 に形状ゲート (`shape-gate.ts`) を導入した時点で、active 2,179 metric のうち
 * **194 件が既に壊れていた**。ゲートをそのまま有効にすると全 metric の配信更新が止まり、
 * 健全な 1,984 件まで巻き添えになる。既知分を期限つきで登録し、是正しながら減らす。
 *
 * ## allowlist を腐らせない 3 つの仕掛け
 *
 * 1. `until` (失効日) が必須。期限を過ぎたエントリは許可として扱われず違反に戻る。
 * 2. `observedSeverity` を持ち、**現在値がこれ以下のときだけ**降格する。悪化したら error に戻る。
 * 3. `MAX_KNOWN_BROKEN` のラチェット (下記)。是正のたびにこの定数を下げる。増やす変更は
 *    テストが落ちるので、新しい壊れ方を allowlist に足して誤魔化すことができない。
 *
 * 正典: `.claude/rules/metric-config-standards.md` / 追跡: `docs/todo/05_機能バックログ.md`
 * の `[RANKING-VALUES-PARTITION-INTEGRITY-01]`
 */
import type { ExpectedShapeAnomalyEntry } from "./shape-gate";

/**
 * known-broken エントリ数の上限 (縮小専用ラチェット)。
 *
 * 是正して allowlist からエントリを消したら**この定数も下げる**。
 * 上げる変更は原則しない (新しい壊れ方は allowlist ではなく config の是正で解決する)。
 */

export const MAX_KNOWN_BROKEN = 203;

export const EXPECTED_SHAPE_ANOMALY: readonly ExpectedShapeAnomalyEntry[] = [
  {
    key: "bed-utilization-rate",
    check: "percent-out-of-range",
    disposition: "known-broken",
    observedSeverity: 34335382,
    reason: "2026-07-30 実測: unit が % なのに最大値 34335382。率ではなく実数が入っている。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "childcare-employment-rate",
    check: "percent-out-of-range",
    disposition: "known-broken",
    observedSeverity: 12458900,
    reason: "2026-07-30 実測: unit が % なのに最大値 12458900。率ではなく実数が入っている。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "elderly-care-employment-rate",
    check: "percent-out-of-range",
    disposition: "known-broken",
    observedSeverity: 12458900,
    reason: "2026-07-30 実測: unit が % なのに最大値 12458900。率ではなく実数が入っている。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "non-regular-employment-rate",
    check: "percent-out-of-range",
    disposition: "known-broken",
    observedSeverity: 8297100,
    reason: "2026-07-30 実測: unit が % なのに最大値 8297100。率ではなく実数が入っている。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "telework-rate",
    check: "percent-out-of-range",
    disposition: "known-broken",
    observedSeverity: 8297100,
    reason: "2026-07-30 実測: unit が % なのに最大値 8297100。率ではなく実数が入っている。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "barrier-free-housing-rate",
    check: "percent-out-of-range",
    disposition: "known-broken",
    observedSeverity: 7235400,
    reason: "2026-07-30 実測: unit が % なのに最大値 7235400。率ではなく実数が入っている。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "solar-panel-housing-rate",
    check: "percent-out-of-range",
    disposition: "known-broken",
    observedSeverity: 7235400,
    reason: "2026-07-30 実測: unit が % なのに最大値 7235400。率ではなく実数が入っている。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "wooden-housing-ratio",
    check: "percent-out-of-range",
    disposition: "known-broken",
    observedSeverity: 7231100,
    reason: "2026-07-30 実測: unit が % なのに最大値 7231100。率ではなく実数が入っている。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "earthquake-renovation-rate",
    check: "percent-out-of-range",
    disposition: "known-broken",
    observedSeverity: 3235200,
    reason: "2026-07-30 実測: unit が % なのに最大値 3235200。率ではなく実数が入っている。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "renovation-rate",
    check: "percent-out-of-range",
    disposition: "known-broken",
    observedSeverity: 3235200,
    reason: "2026-07-30 実測: unit が % なのに最大値 3235200。率ではなく実数が入っている。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "autolock-apartment-rate",
    check: "percent-out-of-range",
    disposition: "known-broken",
    observedSeverity: 2510400,
    reason: "2026-07-30 実測: unit が % なのに最大値 2510400。率ではなく実数が入っている。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "vacant-housing-rate",
    check: "percent-out-of-range",
    disposition: "known-broken",
    observedSeverity: 896500,
    reason: "2026-07-30 実測: unit が % なのに最大値 896500。率ではなく実数が入っている。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "side-job-rate",
    check: "percent-out-of-range",
    disposition: "known-broken",
    observedSeverity: 550800,
    reason: "2026-07-30 実測: unit が % なのに最大値 550800。率ではなく実数が入っている。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "husband-childcare-rate",
    check: "percent-out-of-range",
    disposition: "known-broken",
    observedSeverity: 359500,
    reason: "2026-07-30 実測: unit が % なのに最大値 359500。率ではなく実数が入っている。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "smartphone-usage-rate-by-sex",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 2084,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 2084 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "smartphone-usage-students",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 2084,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 2084 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "employment-insurance-daily-receipt-rate",
    check: "percent-out-of-range",
    disposition: "known-broken",
    observedSeverity: 1545.5,
    reason: "2026-07-30 実測: unit が % なのに最大値 1545.5。率ではなく実数が入っている。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "female-scheduled-earnings",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 1064,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 1064 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "gender-wage-gap",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 1064,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 1064 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "male-scheduled-earnings",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 1064,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 1064 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "side-job-rate",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 747,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 747 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "household-types-by-area",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 640,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 640 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "smartphone-usage-time-by-age",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 352,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 352 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "future-burden-ratio",
    check: "percent-out-of-range",
    disposition: "known-broken",
    observedSeverity: 330.8,
    reason: "2026-07-30 実測: unit が % なのに最大値 330.8。率ではなく実数が入っている。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "local-debt-current-ratio",
    check: "percent-out-of-range",
    disposition: "known-broken",
    observedSeverity: 256.5,
    reason: "2026-07-30 実測: unit が % なのに最大値 256.5。率ではなく実数が入っている。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "food-self-sufficiency-rate-calorie",
    check: "percent-out-of-range",
    disposition: "known-broken",
    observedSeverity: 223,
    reason: "2026-07-30 実測: unit が % なのに最大値 223。率ではなく実数が入っている。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "solar-panel-housing-rate",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 160,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 160 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "kidney-failure-death-count",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 145,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 145 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "liver-disease-death-count",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 145,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 145 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "pneumonia-death-count",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 145,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 145 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "senility-death-count",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 145,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 145 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "husband-childcare-rate",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 126,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 126 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "day-time-population-ratio",
    check: "percent-out-of-range",
    disposition: "known-broken",
    observedSeverity: 122,
    reason: "2026-07-30 実測: unit が % なのに最大値 122。率ではなく実数が入っている。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "hobby-activity-singleperson",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 120,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 120 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "current-balance-ratio",
    check: "percent-out-of-range",
    disposition: "known-broken",
    observedSeverity: 117.4,
    reason: "2026-07-30 実測: unit が % なのに最大値 117.4。率ではなく実数が入っている。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "daytime-population-ratio",
    check: "percent-out-of-range",
    disposition: "known-broken",
    observedSeverity: 116.14287,
    reason: "2026-07-30 実測: unit が % なのに最大値 116.14287。率ではなく実数が入っている。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "psychiatric-hospital-bed-occupancy-rate",
    check: "percent-out-of-range",
    disposition: "known-broken",
    observedSeverity: 115.2,
    reason: "2026-07-30 実測: unit が % なのに最大値 115.2。率ではなく実数が入っている。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "nursery-utilization-rate",
    check: "percent-out-of-range",
    disposition: "known-broken",
    observedSeverity: 113.2,
    reason: "2026-07-30 実測: unit が % なのに最大値 113.2。率ではなく実数が入っている。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "city-gas-supply-area-household-ratio",
    check: "percent-out-of-range",
    disposition: "known-broken",
    observedSeverity: 106.7,
    reason: "2026-07-30 実測: unit が % なのに最大値 106.7。率ではなく実数が入っている。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "water-supply-population-ratio-2012on",
    check: "percent-out-of-range",
    disposition: "known-broken",
    observedSeverity: 101.6,
    reason: "2026-07-30 実測: unit が % なのに最大値 101.6。率ではなく実数が入っている。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "flush-toilet-population-ratio",
    check: "percent-out-of-range",
    disposition: "known-broken",
    observedSeverity: 101.2,
    reason: "2026-07-30 実測: unit が % なのに最大値 101.2。率ではなく実数が入っている。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "water-supply-population-ratio-pre2011",
    check: "percent-out-of-range",
    disposition: "known-broken",
    observedSeverity: 100.9,
    reason: "2026-07-30 実測: unit が % なのに最大値 100.9。率ではなく実数が入っている。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "earthquake-renovation-rate",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 80,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 80 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "freelance-count",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 68,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 68 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "non-regular-employment-rate",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 63,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 63 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "autolock-apartment-rate",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 42,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 42 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "renovation-rate",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 39,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 39 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "hobby-participation-rate-art-appreciation",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 36,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 36 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "hobby-participation-rate-calligraphy",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 36,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 36 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "hobby-participation-rate-camping",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 36,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 36 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "hobby-participation-rate-chorus",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 36,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 36 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "hobby-participation-rate-cinema",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 36,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 36 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "hobby-participation-rate-classical-music",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 36,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 36 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "hobby-participation-rate-cooking",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 36,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 36 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "hobby-participation-rate-diy",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 36,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 36 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "hobby-participation-rate-flower-arrangement",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 36,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 36 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "hobby-participation-rate-gardening",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 36,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 36 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "hobby-participation-rate-go",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 36,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 36 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "hobby-participation-rate-home-movie",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 36,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 36 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "hobby-participation-rate-instrument",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 36,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 36 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "hobby-participation-rate-japanese-dance",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 36,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 36 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "hobby-participation-rate-japanese-music",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 36,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 36 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "hobby-participation-rate-karaoke",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 36,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 36 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "hobby-participation-rate-knitting",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 36,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 36 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "hobby-participation-rate-manga",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 36,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 36 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "hobby-participation-rate-music-listening",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 36,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 36 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "hobby-participation-rate-pachinko",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 36,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 36 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "hobby-participation-rate-painting",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 36,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 36 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "hobby-participation-rate-photography",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 36,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 36 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "hobby-participation-rate-popular-music",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 36,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 36 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "hobby-participation-rate-pottery",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 36,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 36 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "hobby-participation-rate-reading",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 36,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 36 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "hobby-participation-rate-sewing",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 36,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 36 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "hobby-participation-rate-shogi",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 36,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 36 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "hobby-participation-rate-sports-spectating",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 36,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 36 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "hobby-participation-rate-tea-ceremony",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 36,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 36 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "hobby-participation-rate-theater",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 36,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 36 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "hobby-participation-rate-theme-parks",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 36,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 36 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "hobby-participation-rate-video-games",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 36,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 36 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "hobby-participation-rate-western-dance",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 36,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 36 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "hobby-participation-rate-writing",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 36,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 36 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "convenience-store-sales-monthly",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 34,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 34 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "telework-rate",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 32,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 32 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "sole-proprietor-operating-profit",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 29,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 29 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "sole-proprietor-sales",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 29,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 29 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "sole-proprietor-sales-per-worker",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 29,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 29 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "childcare-employment-rate",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 25,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 25 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "elderly-care-employment-rate",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 25,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 25 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "accountant-annual-income",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 24,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 24 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "architect-annual-income",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 24,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 24 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "barber-beautician-annual-income",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 24,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 24 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "care-worker-annual-income",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 24,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 24 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "cleaning-worker-annual-income",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 24,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 24 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "cook-annual-income",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 24,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 24 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "dental-checkup-recipients",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 24,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 24 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "dental-hygienist-annual-income",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 24,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 24 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "designer-annual-income",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 24,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 24 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "doctor-annual-income",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 24,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 24 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "manager-annual-income",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 24,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 24 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "midwife-annual-income",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 24,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 24 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "nurse-annual-income",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 24,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 24 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "nursery-teacher-annual-income",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 24,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 24 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "pharmacist-annual-income",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 24,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 24 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "physical-therapist-annual-income",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 24,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 24 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "practical-nurse-annual-income",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 24,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 24 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "sales-clerk-annual-income",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 24,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 24 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "security-guard-annual-income",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 24,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 24 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "software-engineer-annual-income",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 24,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 24 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "sports-participation-rate-badminton",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 24,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 24 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "sports-participation-rate-baseball",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 24,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 24 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "sports-participation-rate-basketball",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 24,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 24 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "sports-participation-rate-bowling",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 24,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 24 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "sports-participation-rate-cycling",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 24,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 24 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "sports-participation-rate-fishing",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 24,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 24 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "sports-participation-rate-golf",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 24,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 24 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "sports-participation-rate-ground-golf",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 24,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 24 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "sports-participation-rate-gym-training",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 24,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 24 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "sports-participation-rate-hiking",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 24,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 24 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "sports-participation-rate-jogging",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 24,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 24 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "sports-participation-rate-judo",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 24,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 24 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "sports-participation-rate-kendo",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 24,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 24 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "sports-participation-rate-skiing",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 24,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 24 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "sports-participation-rate-soccer",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 24,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 24 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "sports-participation-rate-softball",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 24,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 24 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "sports-participation-rate-swimming",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 24,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 24 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "sports-participation-rate-table-tennis",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 24,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 24 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "sports-participation-rate-tennis",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 24,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 24 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "sports-participation-rate-volleyball",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 24,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 24 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "sports-participation-rate-walking",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 24,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 24 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "sports-participation-rate-yoga",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 24,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 24 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "system-consultant-annual-income",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 24,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 24 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "truck-driver-annual-income",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 24,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 24 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "university-professor-annual-income",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 24,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 24 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "vaccination-recipients-disease",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 21,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 21 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "barrier-free-housing-rate",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 17,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 17 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "starting-salary-highschool",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 17,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 17 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "starting-salary-university",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 17,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 17 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "study-participation-rate-academic",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 12,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 12 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "study-participation-rate-arts-culture",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 12,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 12 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "study-participation-rate-business",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 12,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 12 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "study-participation-rate-business-skills",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 12,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 12 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "study-participation-rate-computer",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 12,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 12 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "study-participation-rate-english",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 12,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 12 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "study-participation-rate-foreign-language",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 12,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 12 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "study-participation-rate-home-economics",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 12,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 12 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "study-participation-rate-nursing-care",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 12,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 12 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "study-participation-rate-other-language",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 12,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 12 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "maternal-child-health-guidance",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 10,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 10 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "retail-sales-amount-by-prefecture",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 9,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 9 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "acupuncturist-rate",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 8,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 8 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "associate-professor-annual-income",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 8,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 8 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "auto-mechanic-annual-income",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 8,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 8 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "bus-driver-annual-income",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 8,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 8 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "care-manager-annual-income",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 8,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 8 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "carpenter-annual-income",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 8,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 8 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "dentist-annual-income",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 8,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 8 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "dietitian-annual-income",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 8,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 8 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "electrician-annual-income",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 8,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 8 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "high-school-teacher-annual-income",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 8,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 8 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "home-care-worker-annual-income",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 8,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 8 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "household-income-by-type",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 8,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 8 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "judo-therapist-rate",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 8,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 8 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "kindergarten-teacher-annual-income",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 8,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 8 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "nurse-salary",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 8,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 8 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "nurses-per-100k-population",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 8,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 8 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "nursing-assistant-annual-income",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 8,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 8 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "pilot-annual-income",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 8,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 8 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "public-health-nurse-annual-income",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 8,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 8 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "researcher-annual-income",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 8,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 8 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "school-teacher-annual-income",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 8,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 8 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "taxi-driver-annual-income",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 8,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 8 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "travel-participation-rate-day-trip",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 7,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 7 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "travel-participation-rate-domestic",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 7,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 7 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "travel-participation-rate-domestic-tourism",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 7,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 7 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "travel-participation-rate-homecoming",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 7,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 7 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "travel-participation-rate-overnight",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 7,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 7 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "travel-participation-rate-overseas",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 7,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 7 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "average-length-of-stay",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 6,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 6 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "bed-utilization-rate",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 6,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 6 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "hobby-activity-by-couple",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 6,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 6 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "retail-establishments-by-prefecture",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 6,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 6 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "wooden-housing-ratio",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 6,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 6 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "dog-registration-count",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 5,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 5 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "barber-shop-count",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 4,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 4 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "beauty-salon-count",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 4,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 4 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "convenience-store-sales-yoy",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 4,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 4 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "dental-hygienist-by-prefecture",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 4,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 4 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "dental-hygienist-rate",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 4,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 4 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "dental-technician-rate",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 4,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 4 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "port-cargo-export",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 4,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 4 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "port-cargo-import",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 4,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 4 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "port-cargo-total",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 4,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 4 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "accident-death-30day",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 3,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 3 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "department-supermarket-sales",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 3,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 3 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "retail-sales-area-by-class",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 3,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 3 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "vegetable-cultivation-area",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 3,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 3 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "convenience-store-count-commercial",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 2,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 2 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "convenience-store-sales",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 2,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 2 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "food-sanitation-inspection",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 2,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 2 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "mental-health-application",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 2,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 2 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "midwife-by-prefecture",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 2,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 2 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "port-inbound-ships",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 2,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 2 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
  {
    key: "port-ships-tonnage",
    check: "duplicate-area-year",
    disposition: "known-broken",
    observedSeverity: 2,
    reason: "2026-07-30 実測: 同一 (県, 年) に最大 2 行。分類軸の絞り忘れ。是正待ち",
    issue: "RANKING-VALUES-PARTITION-INTEGRITY-01",
    until: "2026-12-31",
  },
];
