/**
 * コロプレス地図表示用のカテゴリ・サブカテゴリ定義
 */

import { CategoryData, SubcategoryData } from '@/types/choropleth';

export const CHOROPLETH_CATEGORIES: CategoryData[] = [
  {
    id: 'landweather',
    name: '国土・気象',
    description: '土地面積、土地利用、自然環境、気象・気候に関する統計',
    icon: 'MapPin',
    displayOrder: 1,
    subcategories: [
      {
        id: 'land-area',
        categoryId: 'landweather',
        name: '土地面積',
        description: '都道府県別の総面積',
        unit: 'km²',
        dataType: 'numerical',
        statsDataId: '0000010201',
        tableName: '国勢調査',
        displayOrder: 1,
        colorScheme: 'interpolateGreens',
        categoryCode: 'A01201',
      },
      {
        id: 'weather-climate',
        categoryId: 'landweather',
        name: '気象・気候',
        description: '年間降水量、平均気温等',
        unit: 'mm',
        dataType: 'numerical',
        statsDataId: '0000080101',
        tableName: '気象統計',
        displayOrder: 2,
        colorScheme: 'interpolateBlues',
      },
    ],
  },
  {
    id: 'population',
    name: '人口・世帯',
    description: '総人口、人口移動、人口構成、婚姻・家族、世帯、出生・死亡に関する統計',
    icon: 'Users',
    displayOrder: 2,
    subcategories: [
      {
        id: 'basic-population',
        categoryId: 'population',
        name: '総人口',
        description: '都道府県別の総人口',
        unit: '人',
        dataType: 'numerical',
        statsDataId: '0003448738',
        tableName: '人口推計',
        displayOrder: 1,
        colorScheme: 'interpolateBlues',
      },
      {
        id: 'population-composition',
        categoryId: 'population',
        name: '人口構成',
        description: '年齢別・性別人口構成',
        unit: '%',
        dataType: 'percentage',
        statsDataId: '0000010101',
        tableName: '国勢調査',
        displayOrder: 2,
        colorScheme: 'interpolateOranges',
      },
      {
        id: 'households',
        categoryId: 'population',
        name: '世帯',
        description: '世帯数、世帯人員、世帯構成',
        unit: '世帯',
        dataType: 'numerical',
        statsDataId: '0000010108',
        tableName: '住宅・土地統計調査',
        displayOrder: 3,
        colorScheme: 'interpolateViridis',
        categoryCode: 'H3100',
      },
      {
        id: 'marriage',
        categoryId: 'population',
        name: '婚姻・家族',
        description: '婚姻件数、離婚件数、未婚人口、配偶関係',
        unit: '組',
        dataType: 'numerical',
        statsDataId: '0000010101',
        tableName: '国勢調査',
        displayOrder: 4,
        colorScheme: 'interpolatePurples',
        categoryCode: 'A9101',
      },
      {
        id: 'population-movement',
        categoryId: 'population',
        name: '人口移動',
        description: '転入・転出、社会増減、昼間人口',
        unit: '人',
        dataType: 'numerical',
        statsDataId: '0000010101',
        tableName: '国勢調査',
        displayOrder: 5,
        colorScheme: 'interpolateRdYlBu',
        categoryCode: 'A5302',
      },
      {
        id: 'birth-death',
        categoryId: 'population',
        name: '出生・死亡',
        description: '出生数、死亡数、自然増減、合計特殊出生率',
        unit: '人',
        dataType: 'numerical',
        statsDataId: '0000010101',
        tableName: '国勢調査',
        displayOrder: 6,
        colorScheme: 'interpolateRdYlGn',
        categoryCode: 'A4301',
      },
    ],
  },
  {
    id: 'laborwage',
    name: '労働・賃金',
    description: '賃金・労働条件、労働力構造、労働争議、求職・求人、産業・職業別、雇用形態に関する統計',
    icon: 'Briefcase',
    displayOrder: 3,
    subcategories: [
      {
        id: 'wages-working-conditions',
        categoryId: 'laborwage',
        name: '賃金・労働条件',
        description: '平均賃金、労働時間等',
        unit: '円',
        dataType: 'numerical',
        statsDataId: '0000200001',
        tableName: '毎月勤労統計調査',
        displayOrder: 1,
        colorScheme: 'interpolateGreens',
      },
      {
        id: 'labor-force-structure',
        categoryId: 'laborwage',
        name: '労働力構造',
        description: '労働力人口、就業率等',
        unit: '%',
        dataType: 'percentage',
        statsDataId: '0000010101',
        tableName: '国勢調査',
        displayOrder: 2,
        colorScheme: 'interpolateBlues',
      },
    ],
  },
  {
    id: 'agriculture',
    name: '農林水産業',
    description: '農業世帯、農林水産業の生産・経営に関する統計',
    icon: 'Wheat',
    displayOrder: 4,
    subcategories: [
      {
        id: 'agricultural-household',
        categoryId: 'agriculture',
        name: '農業世帯',
        description: '農業経営体数、農業従事者数',
        unit: '戸',
        dataType: 'numerical',
        statsDataId: '0000030101',
        tableName: '農林業センサス',
        displayOrder: 1,
        colorScheme: 'interpolateYlGn',
      },
    ],
  },
  {
    id: 'miningindustry',
    name: '鉱工業',
    description: '製造業、鉱業、工業生産に関する統計',
    icon: 'Factory',
    displayOrder: 5,
    subcategories: [
      {
        id: 'manufacturing',
        categoryId: 'miningindustry',
        name: '製造業',
        description: '製造業事業所数、従業者数、出荷額',
        unit: '億円',
        dataType: 'numerical',
        statsDataId: '0000020101',
        tableName: '工業統計調査',
        displayOrder: 1,
        colorScheme: 'interpolatePlasma',
      },
    ],
  },
  {
    id: 'commercial',
    name: '商業・サービス業',
    description: '商業・サービス産業、商業施設に関する統計',
    icon: 'Store',
    displayOrder: 6,
    subcategories: [
      {
        id: 'commerce-service-industry',
        categoryId: 'commercial',
        name: '商業・サービス産業',
        description: '卸売業・小売業の事業所数、従業者数',
        unit: '事業所',
        dataType: 'numerical',
        statsDataId: '0000140001',
        tableName: '経済センサス',
        displayOrder: 1,
        colorScheme: 'interpolateMagma',
      },
    ],
  },
  {
    id: 'economy',
    name: '企業・家計・経済',
    description: '労働者世帯収入、総生産・経済指標、消費者物価地域差指数に関する統計',
    icon: 'TrendingUp',
    displayOrder: 7,
    subcategories: [
      {
        id: 'gross-product-economic-indicators',
        categoryId: 'economy',
        name: '総生産・経済指標',
        description: '県内総生産、一人当たり県民所得',
        unit: '千円',
        dataType: 'numerical',
        statsDataId: '0000040001',
        tableName: '県民経済計算',
        displayOrder: 1,
        colorScheme: 'interpolateBlues',
      },
      {
        id: 'worker-household-income',
        categoryId: 'economy',
        name: '労働者世帯収入',
        description: '勤労者世帯の実収入',
        unit: '円',
        dataType: 'numerical',
        statsDataId: '0000200001',
        tableName: '家計調査',
        displayOrder: 2,
        colorScheme: 'interpolateGreens',
      },
    ],
  },
  {
    id: 'construction',
    name: '住宅・土地・建設',
    description: '生活環境、住宅所有、住宅構造、住宅設備、建設・製造に関する統計',
    icon: 'Home',
    displayOrder: 8,
    subcategories: [
      {
        id: 'housing-ownership',
        categoryId: 'construction',
        name: '住宅所有',
        description: '持ち家率、借家率',
        unit: '%',
        dataType: 'percentage',
        statsDataId: '0000010101',
        tableName: '国勢調査',
        displayOrder: 1,
        colorScheme: 'interpolateYlOrBr',
      },
    ],
  },
  {
    id: 'energy',
    name: 'エネルギー・水',
    description: '上水道・下水道、廃棄物処理、工業用水、インフラ・エネルギーに関する統計',
    icon: 'Zap',
    displayOrder: 9,
    subcategories: [
      {
        id: 'water-supply-sewerage',
        categoryId: 'energy',
        name: '上水道・下水道',
        description: '上水道普及率、下水道普及率',
        unit: '%',
        dataType: 'percentage',
        statsDataId: '0000110101',
        tableName: '上下水道統計',
        displayOrder: 1,
        colorScheme: 'interpolateBlues',
      },
    ],
  },
  {
    id: 'tourism',
    name: '運輸・観光',
    description: '観光・宿泊、交通・運輸に関する統計',
    icon: 'Plane',
    displayOrder: 10,
    subcategories: [
      {
        id: 'tourism-accommodation',
        categoryId: 'tourism',
        name: '観光・宿泊',
        description: '観光入込客数、宿泊施設数',
        unit: '千人',
        dataType: 'numerical',
        statsDataId: '0000150101',
        tableName: '観光統計',
        displayOrder: 1,
        colorScheme: 'interpolatePurples',
      },
    ],
  },
  {
    id: 'educationsports',
    name: '教育・文化・スポーツ',
    description: '教育・スポーツ指標、文化活動に関する統計',
    icon: 'GraduationCap',
    displayOrder: 11,
    subcategories: [
      {
        id: 'education-sports-indicators',
        categoryId: 'educationsports',
        name: '教育・スポーツ指標',
        description: '大学進学率、体育施設数等',
        unit: '%',
        dataType: 'percentage',
        statsDataId: '0000060101',
        tableName: '学校基本調査',
        displayOrder: 1,
        colorScheme: 'interpolateWarm',
      },
    ],
  },
  {
    id: 'administrativefinancial',
    name: '行財政',
    description: '財政指標、職員・議会・選挙、税収、投資、歳入、歳出に関する統計',
    icon: 'Building2',
    displayOrder: 12,
    subcategories: [
      {
        id: 'fiscal-indicators',
        categoryId: 'administrativefinancial',
        name: '財政指標',
        description: '財政力指数、実質公債費比率',
        unit: '',
        dataType: 'rate',
        statsDataId: '0000170101',
        tableName: '地方財政統計',
        displayOrder: 1,
        colorScheme: 'interpolateRdYlBu',
      },
    ],
  },
  {
    id: 'safetyenvironment',
    name: '司法・安全・環境',
    description: '消防・緊急事態、火災保険、警察・犯罪、公害・環境に関する統計',
    icon: 'Shield',
    displayOrder: 13,
    subcategories: [
      {
        id: 'police-crime',
        categoryId: 'safetyenvironment',
        name: '警察・犯罪',
        description: '刑法犯認知件数、検挙率',
        unit: '件',
        dataType: 'numerical',
        statsDataId: '0000180101',
        tableName: '犯罪統計',
        displayOrder: 1,
        colorScheme: 'interpolateYlOrRd',
      },
    ],
  },
  {
    id: 'socialsecurity',
    name: '社会保障・衛生',
    description: '社会保障指標、死亡統計、医療・福祉に関する統計',
    icon: 'Heart',
    displayOrder: 14,
    subcategories: [
      {
        id: 'social-security-indicators',
        categoryId: 'socialsecurity',
        name: '社会保障指標',
        description: '医師数、病院数、福祉施設数',
        unit: '人/10万人',
        dataType: 'rate',
        statsDataId: '0000050102',
        tableName: '医師・歯科医師・薬剤師統計',
        displayOrder: 1,
        colorScheme: 'interpolateTeal',
      },
    ],
  },
  {
    id: 'international',
    name: '国際',
    description: '国際関係、貿易、在留外国人に関する統計',
    icon: 'Globe',
    displayOrder: 15,
    subcategories: [
      {
        id: 'foreign-residents',
        categoryId: 'international',
        name: '在留外国人',
        description: '在留外国人数、国籍別統計',
        unit: '人',
        dataType: 'numerical',
        statsDataId: '0000190101',
        tableName: '在留外国人統計',
        displayOrder: 1,
        colorScheme: 'interpolateSpectral',
      },
    ],
  },
  {
    id: 'infrastructure',
    name: '社会基盤施設',
    description: '道路、橋梁、公共施設等の社会基盤に関する統計',
    icon: 'Construction',
    displayOrder: 16,
    subcategories: [
      {
        id: 'road-infrastructure',
        categoryId: 'infrastructure',
        name: '道路インフラ',
        description: '道路密度、橋梁数等',
        unit: 'km/km²',
        dataType: 'rate',
        statsDataId: '0000200101',
        tableName: '道路統計',
        displayOrder: 1,
        colorScheme: 'interpolateGreys',
      },
    ],
  },
];

/**
 * カテゴリIDからカテゴリデータを取得
 */
export function getCategoryById(categoryId: string): CategoryData | undefined {
  return CHOROPLETH_CATEGORIES.find(cat => cat.id === categoryId);
}

/**
 * サブカテゴリIDからサブカテゴリデータを取得
 */
export function getSubcategoryById(subcategoryId: string): { category: CategoryData; subcategory: SubcategoryData } | undefined {
  for (const category of CHOROPLETH_CATEGORIES) {
    const subcategory = category.subcategories.find(sub => sub.id === subcategoryId);
    if (subcategory) {
      return { category, subcategory };
    }
  }
  return undefined;
}

/**
 * カテゴリの表示順でソートされたカテゴリ一覧を取得
 */
export function getSortedCategories(): CategoryData[] {
  return [...CHOROPLETH_CATEGORIES].sort((a, b) => a.displayOrder - b.displayOrder);
}