import type { ThemeCatalog, CatalogMetric } from './types';
import type { ChartColorRole } from './chart-color-role';

/**
 * 128候補のうち「新規テーマ」として採択した残り31テーマ。
 * 指標はすべて既存のMETRICS_REGISTRYに存在する実値を参照する。候補専用の
 * 観測値が未整備なものは、カタログの説明にその制約を明記し、別指標へ名前を
 * 置き換えない。追加取得後に同じキーへ差し替えられるよう章構造を固定する。
 */
type Spec = {
  key: string;
  title: string;
  description: string;
  category: ThemeCatalog['category'];
  metrics: Array<[string, string, CatalogMetric['role']?]>;
  keywords: string[];
  embeddedSectionKeys?: string[];
  charts?: ThemeCatalog['charts'];
};

function makeCatalog(spec: Spec): ThemeCatalog {
  const metrics = spec.metrics.map(([rankingKey, shortLabel, role = 'secondary']) => ({
    rankingKey,
    shortLabel,
    role,
    selection: {
      proposedBy: '128テーマ実現性調査・全体展開',
      surveyedAt: '2026-09-09',
      rationale: `${shortLabel}を都道府県別の実値として比較する。`,
    },
  }));
  // 1カード=1系列にして単位の違う指標を同じY軸へ重ねない。
  const groups = metrics.filter(metric => metric.role !== 'context').map((metric, index) => ({
    key: `${spec.key}-indicator-${index + 1}`,
    title: metric.shortLabel,
    rankingKeys: [metric.rankingKey],
    defaultCheckedKeys: [metric.rankingKey],
  }));
  return {
    key: spec.key,
    title: spec.title,
    description: spec.description,
    category: spec.category,
    usage: 'theme',
    metrics,
    charts: spec.charts ?? [],
    metricGroups: groups,
    sections: [{ key: `${spec.key}-overview`, title: `${spec.title}を都道府県別に見る`, description: spec.description, metricGroupKeys: groups.map((group) => group.key), ...(spec.charts ? { chartKeys: spec.charts.map(chart => chart.componentKey) } : {}), ...(spec.embeddedSectionKeys ? { embeddedSectionKeys: spec.embeddedSectionKeys } : {}) }],
    keywords: spec.keywords,
  };
}

const SINGLE_MOTHER_INCOME_CLASSES = [
  ['single-mother-households-income-under100', '100万円未満'],
  ['single-mother-households-income-100to199', '100〜199万円'],
  ['single-mother-households-income-200to299', '200〜299万円'],
  ['single-mother-households-income-300to399', '300〜399万円'],
  ['single-mother-households-income-400to499', '400〜499万円'],
  ['single-mother-households-income-500plus', '500万円以上'],
] as const;

const SPECS: Spec[] = [
  { key: 'land-property-market', title: '不動産取引と地価', description: '2025年の住宅地について、100㎡以上300㎡未満の土地の取引単価と公示価格の分布・標本数を示します。住宅地の区分と基準時点が異なるため、両系列は分けて読みます。住宅地・工業地の地価変動率も確認できます。', category: 'economy', metrics: [['residential-land-transaction-median-price', '住宅地の取引単価中央値（100〜300㎡未満）', 'primary'], ['residential-land-transaction-sample-count', '住宅地の取引価格標本数'], ['residential-official-land-median-price', '住宅地の公示価格中央値（100〜300㎡未満）'], ['residential-official-land-point-count', '住宅地の公示標準地数'], ['residential-land-price-change-rate', '住宅地地価変動率', 'primary'], ['industrial-land-price-change-rate', '標準価格変動率（工業地）']], embeddedSectionKeys: ['property-prices'], keywords: ['地価', '不動産', '住宅地', '工業地'] },
  { key: 'agriculture-production', title: '農業の生産力', description: '農業産出額、農家数、基幹的農業従事者を別々の指標として比較します。総額は人口規模の影響を受けるため、1人当たり指標と混同しません。', category: 'industry', metrics: [['agricultural-output', '農業産出額', 'primary'], ['agricultural-output-per-employed-person', '農業就業者1人当たり農業産出額'], ['agricultural-farm-count', '農家数'], ['core-agricultural-workers', '基幹的農業従事者数（販売農家）'], ['cultivated-area', '耕地面積']], keywords: ['農業', '農業産出額', '農家'] },
  { key: 'forestry-timber', title: '森林・林業・木材産業', description: "森林資源と木材の生産・出荷に加え、2025年農林業センサスの経営体・労働力と2024年の林業産出額を比較します。労働力は経営体ごとの過去1年間の人数で、雇用と経営内部を分けます。県別産出額は全国表と集計対象が異なり、木材・きのこ以外に薪炭・林野副産物を含みます。", category: 'industry', metrics: [['woodland-area', '森林面積', 'primary'], ['forest-area-ratio', '林野面積割合'], ['artificial-forest-area', '人工造林面積'], ['forest-road-length', '林道延長'], ["roundwood-production-volume", "素材生産量（2024年確報）", "secondary"], ["roundwood-sugi-production-volume", "すぎの素材生産量", "secondary"], ["roundwood-hinoki-production-volume", "ひのきの素材生産量", "secondary"], ["sawmill-count", "製材工場数（7.5kW以上）", "secondary"], ["sawnwood-shipment-volume", "製材品出荷量", "secondary"], ["forestry-management-entities", "林業経営体数（2025年調査）", "secondary"], ["forestry-hired-workers", "林業経営体の雇用者数（2025年調査）", "secondary"], ["forestry-internal-workers", "林業経営体の内部労働者数（2025年調査）", "secondary"], ["forestry-output-value", "林業産出額（2024年確報）", "primary"], ["forestry-timber-output-value", "木材生産産出額（2024年確報）", "secondary"], ["forestry-mushroom-output-value", "栽培きのこ類産出額（2024年確報）", "secondary"]], keywords: ['森林', '林業', '人工林', '林道'] },
  { key: 'retail-commerce', title: '商業と小売', description: '小売業の事業所数、売場面積、年間商品販売額、従業者数を比較します。従業者数は社会・人口統計体系の2021年度行に掲載された調査日現在の人数です。販売額の年間フローと調査日のストックを分けて読みます。', category: 'economy', metrics: [['retail-establishments-by-prefecture', '小売業事業所数', 'primary'], ['retail-sales-area-by-class', '小売業売場面積'], ['retail-sales-amount-by-prefecture', '小売業年間商品販売額'], ['retail-employees', '小売業従業者数']], keywords: ['小売', '商業', '販売額', '売場面積'] },
  { key: 'local-services', title: '飲食・生活関連サービス', description: "飲食店数と、洗濯・理容・美容・浴場業の事業活動を比較します。事業所・従業者は2021年6月1日の事業所所在地別、売上・純付加価値は2020年の企業本所所在地別です。対象年と県への帰属が異なるため、両者を割って生産性とはしません。産業中分類78で、その他の生活関連サービス79と娯楽80を含みません。", category: 'economy', metrics: [['restaurant-count-per-1000', '飲食店数（人口千人当たり）', 'primary'], ['number-of-hotel-facilities', 'ホテル営業施設数'], ['number-of-hotel-rooms', 'ホテル営業施設客室数'], ['personal-items-service-consumption-expenditure', '身の回り用品関連サービスへの家計支出（県庁所在市・二人以上世帯・年額）', 'context'], ["laundry-beauty-bath-industry-establishments", "洗濯・理容・美容・浴場業の事業所数", "secondary"], ["laundry-beauty-bath-industry-employees", "洗濯・理容・美容・浴場業の従業者数", "secondary"], ["laundry-beauty-bath-industry-revenue", "洗濯・理容・美容・浴場業の企業売上高", "secondary"], ["laundry-beauty-bath-industry-net-value-added", "洗濯・理容・美容・浴場業の企業純付加価値額", "secondary"]], keywords: ['飲食店', '宿泊', '生活関連サービス'] },
  { key: 'business-demography', title: '起業と開廃業', description: '雇用保険適用事業所の新規成立・消滅と、前年度末の適用事業所数を分母にした開業率・廃業率を比較します。雇用者のいない事業を含まず、企業単位の設立・倒産件数とは異なります。', category: 'economy', metrics: [['business-opening-rate', '開業率（雇用保険適用事業所）', 'primary'], ['business-closure-rate', '廃業率（雇用保険適用事業所）'], ['business-opening-establishments', '年度内の新規成立事業所数'], ['business-closure-establishments', '年度内の消滅事業所数'], ['business-opening-base-establishments', '分母となる前年度末の適用事業所数']], keywords: ['起業', '開業', '廃業', '事業所'] },
  { key: 'innovation-patents', title: '研究開発と特許', description: '特許・意匠・商標の出願と登録、延べ発明者数を比較します。件数は筆頭出願人の住所、発明者数は出願に記載された全発明者の延べ人数です。発明者数はPCT国内移行を含む2016年以降を表示します。研究の質や事業化収益を表すものではありません。', category: 'industry', metrics: [['patent-application-count', '特許出願件数（筆頭出願人住所）', 'primary'], ['patent-registration-count', '特許登録件数（筆頭出願人住所）'], ['patent-inventor-count', '出願に記載された延べ発明者数'], ['design-application-count', '意匠出願件数'], ['design-registration-count', '意匠登録件数'], ['trademark-application-count', '商標出願件数'], ['trademark-registration-count', '商標登録件数']], keywords: ['研究開発', '特許', '意匠', '商標', '発明者'] },
  { key: 'childcare-services', title: '保育の需給', description: '保育所等の数・在所児・利用率と認定こども園数に加え、2025年4月1日の保育所等利用申込者数を比較します。申込者には利用中の児童も含まれます。指標によって対象年や集計範囲が異なるため、申込者と別の指標の定員を差し引いて待機児童数とはしません。', category: 'education', metrics: [['nursery-count-per-100k-0-5', '保育所等数（0～5歳人口10万人当たり）', 'primary'], ['nursery-children-per-nursery-teacher', '保育所等在所児数（保育士1人当たり）'], ['nursery-utilization-rate', '保育所等利用率（在所児数／定員数）'], ['certified-childcare-center-count-per-100k-0-5', '認定こども園数（0～5歳人口10万人当たり）'], ['childcare-applicants', '保育所等利用申込者数（4月1日時点）', 'secondary']], keywords: ['保育', '保育所', '待機児童', 'こども園'] },
  { key: 'single-parent-households', title: 'ひとり親家庭の生活', description: '母子・父子世帯の就業、母子世帯の所得構成、公的支援の利用を別々に比較します。就業は子20歳未満、所得は子18歳未満の世帯が対象です。生活保護は年度平均世帯数、児童扶養手当は年度末受給者数で、同じ母数の率ではありません。', category: 'demographics',
    metrics: [['single-mother-employment-rate', '母子世帯の母の就業割合（労働状態不詳を除く）', 'primary'], ['single-father-employment-rate', '父子世帯の父の就業割合（労働状態不詳を除く）'], ['single-mother-households', '母子世帯数'], ['single-father-households', '父子世帯数'], ['single-mother-public-assistance-households', '生活保護を受ける母子世帯数（年度平均）'], ['child-rearing-allowance-recipients', '児童扶養手当受給者数（年度末）'], ...SINGLE_MOTHER_INCOME_CLASSES.map(([key, label]): [string, string, CatalogMetric['role']] => [key, `母子世帯の所得${label}`, 'context'])],
    charts: [{ componentKey: 'single-parent-income-composition', componentType: 'composition-chart', title: '母子世帯の年間所得階級別構成',
      annotation: '2022年就業構造基本調査。配偶者のいない母と18歳未満の子から成る世帯で、父子世帯や他の同居者がいる世帯は含みません。所得は2021年10月〜2022年9月の税込み年間収入です。構成比は表示した6階級の合計を分母とし、不詳込みの母子世帯総数との差は丸めを含むため不詳人数とは扱いません。平均所得や貧困率ではありません。',
      componentProps: { seriesRefs: SINGLE_MOTHER_INCOME_CLASSES.map(([metricKey, label], index) => ({ metricKey, label: `母子世帯の所得${label}`, colorRole: `series-${index + 1}` as ChartColorRole })) },
      relatedRankingKeys: SINGLE_MOTHER_INCOME_CLASSES.map(([key]) => key), sourceName: '就業構造基本調査', sourceLink: 'https://www.e-stat.go.jp/dbview?sid=0004008606', dataSource: 'ranking', gridColumnSpan: 12, section: 'single-parent-households-overview', sortOrder: 10 }],
    keywords: ['ひとり親', '母子世帯', '父子世帯', '所得', '就業'] },
  { key: 'long-term-care', title: '介護認定とサービスの需給', description: '2024年度末の要支援・要介護認定者総数と、介護保険給付・老人ホームの供給を比較します。認定者数は保険者報告の県別集計で、サービス利用人数や人口当たり認定率ではありません。異なる年の給付や施設数との単純な割り算は行いません。', category: 'welfare', metrics: [['long-term-care-certified-persons', '要支援・要介護認定者数（2024年度末）', 'primary'], ['nursing-care-insurance-benefit', '介護保険給付費用額', 'primary'], ['nursing-home-count-per-100k-65plus', '老人ホーム数（65歳以上人口10万人当たり）'], ['nursing-home-capacity-per-1000-65plus', '老人ホーム定員数（65歳以上人口千人当たり）'], ['nursing-home-residents-per-1000-65plus', '老人ホーム在所者数（65歳以上人口千人当たり）']], keywords: ['介護', '介護保険', '老人ホーム'] },
  { key: 'disability-support', title: '障害福祉と社会参加', description: '知的障害者援護施設の数・定員・在所者と身体障害者手帳交付数を比較します。制度区分の異なる人数を合算しません。障害者就職率は公共職業安定所における就職件数を新規求職申込件数で割った割合で、企業の実雇用率や障害者全体の就業率とは異なります。', category: 'welfare', metrics: [['intellectual-disability-support-facility-count-per-1m', '知的障害者援護施設数（人口100万人当たり）', 'primary'], ['intellectual-disability-support-facility-capacity-per-100k', '知的障害者援護施設定員数（人口10万人当たり）'], ['intellectual-disability-support-facility-residents-per-100k', '知的障害者援護施設在所者数（人口10万人当たり）'], ['physical-disability-certificates-issued-per-1000', '身体障害者手帳交付数（人口千人当たり）'], ['disabled-employment-rate', '障害者就職率（ハローワーク）']], keywords: ['障害福祉', '障害者手帳', '社会参加'] },
  { key: 'public-assistance', title: '生活保護と生活困窮', description: '生活保護の受給状況・保護費と、生活困窮者自立支援の新規相談受付件数を分けて比較します。2024年4月〜2025年3月の新規受付。管内市区町村を含む都道府県枠に、同じ県の指定都市・中核市の別掲分を一度ずつ加算する。継続相談の延べ回数や困窮者・生活保護受給者の人数ではない。実施機関の管轄を県に集約し、相談者の居住県別人数とはしない。人口10万人当たりの月平均値は使用しない。', category: 'welfare', metrics: [["poverty-support-new-consultation-cases", "生活困窮者支援の新規相談受付件数", "secondary"], ['persons-on-public-assistance-per-1000', '生活保護被保護実人員（月平均・人口千人当たり）', 'primary'], ['households-on-public-assistance-per-1000', '生活保護被保護実世帯数（月平均・一般世帯千世帯当たり）'], ['public-assistance-expenses-prefecture', '生活保護費（都道府県財政）'], ['public-assistance-facility-capacity-per-1000', '保護施設定員数（被保護実人員千人当たり）']], keywords: ['生活保護', '生活困窮', '社会保障'] },
  { key: 'health-checkups', title: '生活習慣と健診', description: '40〜74歳の特定健診受診率、保健指導の実施率、受診者のメタボ該当割合を比較します。受診率の分母は県人口に基づく対象者の推計で、県民全体の健康状態を示す値ではありません。歯科健診は別の対象・分母で表示します。', category: 'welfare', metrics: [['specific-health-checkup-participation-rate', '特定健診受診率（県別推計対象者が分母）', 'primary'], ['specific-health-guidance-completion-rate', '特定保健指導実施率'], ['metabolic-syndrome-prevalence-among-checkup-recipients', '特定健診受診者のメタボ該当割合'], ['health-checkup-recipients', '生活習慣病健康診断受診延人員'], ['dental-checkup-persons-per-1000', '歯科健診受診延人員（人口千人当たり）']], keywords: ['健診', '生活習慣病', '保健指導', '歯科健診'] },
  { key: 'daily-time-use', title: '睡眠と生活時間', description: '睡眠・家事の平均時間と、有業者に限った仕事・趣味娯楽の平均時間を男女別に比較します。対象が異なるため合計しません。平均時間は一日の行動配分であり、生活の良否を示す指標ではありません。', category: 'demographics', metrics: [['sleep-avg-time-female', '女性の睡眠時間', 'primary'], ['sleep-avg-time-male', '男性の睡眠時間'], ['housework-avg-time-female', '女性の家事時間'], ['housework-avg-time-male', '男性の家事時間'], ['hobby-leisure-avg-time-employed-female', '女性有業者の趣味・娯楽時間'], ['hobby-leisure-avg-time-employed-male', '男性有業者の趣味・娯楽時間'], ['work-avg-time-employed-female', '女性有業者の仕事時間'], ['work-avg-time-employed-male', '男性有業者の仕事時間']], keywords: ['生活時間', '睡眠', '家事', '余暇'] },
  { key: 'household-assets-debt', title: '貯蓄と負債', description: '二人以上世帯の貯蓄現在高と金融負債残高、貯蓄率を別々に比較します。世帯属性や調査年の違いを補正した推計は行いません。', category: 'economy', metrics: [['financial-assets-balance-multi-person-households', '金融資産残高（貯蓄現在高・二人以上世帯1世帯当たり）', 'primary'], ['financial-debt-balance', '金融負債残高（二人以上世帯）'], ['avg-savings-rate-worker-households', '平均貯蓄率（勤労者世帯）']], keywords: ['貯蓄', '負債', '家計'] },
  { key: 'freight-logistics', title: '物流と貨物輸送', description: '発送県と到着県の組合せを鉄道・自動車・海運・航空別に確認します。2024年度の貨物流動が基本ですが、海運は2024暦年のフレートトンです。単位と期間を分け、輸送機関横断の合計は作りません。', embeddedSectionKeys: ['freight-od'], category: 'tourism', metrics: [['jr-freight-shipment', 'JR貨物発送量', 'primary'], ['air-cargo-transport', '航空貨物輸送量'], ['number-of-freight-cars', '貨物車数'], ['truck-operators', 'トラック事業者']], keywords: ['物流', '貨物', '輸送', 'トラック'] },
  { key: 'regional-transport', title: '自動車依存と移動手段', description: '自動車保有、通勤・通学の交通手段、バス事業者を別々に比較します。自動車保有台数から交通空白を直接判定しません。', category: 'tourism', metrics: [['car-ownership-multi-person-households-per-1000', '自動車所有数量（二人以上世帯千世帯当たり）', 'primary'], ['commute-by-car', '自家用車通勤・通学者数'], ['commute-by-bus', '乗合バス通勤・通学者数'], ['commute-by-train', '鉄道・電車通勤・通学者数'], ['bus-operators', 'バス事業者']], keywords: ['自動車', '交通', '通勤', 'バス'] },
  { key: 'geographic-access', title: '交通空白と生活アクセス', description: '駅から直線800m以内に中心点がある1km人口メッシュの人口割合を、2020年と2050年推計で比較します。徒歩経路・運行頻度を考慮した交通空白認定ではありません。駅数・バス事業者数は供給の基礎情報として別に掲載します。', embeddedSectionKeys: ['geo-station-access', 'geo-public-facility-access'], category: 'safety', metrics: [['railway-station-count', '鉄道駅数', 'primary'], ['bus-operators', 'バス事業者数'], ['commute-by-car', '自家用車通勤・通学者数']], keywords: ['交通空白', '生活アクセス', '駅', 'バス'] },
  { key: 'water-services', title: '水道の持続性', description: '2024年度の法適用水道について、経年管・更新管を同じ総延長で比較します。末端給水・用水供給・法適用簡易水道を含み、同一会計内簡易水道の内数は二重計上しません。法非適用・民営等は除外し、事業団体の所属県別で集計しています。管路の物理所在地別や破損確率ではありません。上水道給水量・能力と下水道普及率は対象を分けて読みます。', category: 'industry', metrics: [["public-water-pipe-aging-rate","水道管路の経年化率","primary"], ["public-water-pipe-renewal-rate","水道管路の更新率","primary"], ["public-water-pipe-length","水道管路の総延長","secondary"], ["public-water-aged-pipe-length","法定耐用年数を経過した水道管路延長","secondary"], ["public-water-renewed-pipe-length","年度内に更新した水道管路延長","secondary"], ['water-supply-population-ratio-2012on', '上水道給水人口比率', 'primary'], ['sewerage-coverage-rate', '下水道処理人口普及率'], ['water-supply-annual-volume', '上水道年間給水量'], ['water-supply-capacity', '上水道施設能力']], keywords: ['水道', '上水道', '下水道', '持続性'] },
  { key: 'communication-access', title: '通信環境とデジタル基盤', description: 'ブロードバンド契約数と携帯電話の契約・保有を比較します。ブロードバンドはBWAを含み、携帯電話アクセスを含む旧系列と除く系列を別々に表示します。契約数は世帯普及率や通信速度とは異なります。', category: 'industry', metrics: [['broadband-contract-count-excluding-39-4g', 'ブロードバンド契約数（3.9〜4世代携帯電話アクセスを除く）', 'primary'], ['broadband-service-contract-count', 'ブロードバンド契約数（携帯電話アクセスを含む旧系列）'], ['mobile-phone-contract-count-per-1000', '携帯電話契約数（人口千人当たり）'], ['mobile-phone-ownership-multi-person-households-per-1000', '携帯電話所有数量（二人以上世帯千世帯当たり）']], keywords: ['通信', 'ブロードバンド', '携帯電話', 'インターネット'] },
  { key: 'regional-energy', title: 'エネルギー消費', description: '最終エネルギー消費量と1人当たり消費、電力需要、住宅の太陽光設備率を規模と普及に分けて比較します。電源構成は別統計として扱います。2023年度・暫定値の直接利用分（TJ）。非エネルギー利用を含みます。産業は農林水産鉱建設業と製造業の合計です。運輸は家庭乗用車に限り、営業用輸送等を含みません。電力・熱の寄与損失配分後総量やCO₂排出量、別年度の設備容量とは分けて比較します。', category: 'industry', metrics: [['final-energy-consumption', '最終エネルギー消費量', 'primary'], ['final-energy-consumption-per-capita', '1人当たり最終エネルギー消費量'], ['electricity-demand', '電力需要量'], ['solar-panel-housing-rate', '太陽光発電機のある住宅率'], ['regional-industry-final-energy-consumption', '産業部門の最終エネルギー消費量', 'secondary'], ['regional-business-final-energy-consumption', '業務他部門の最終エネルギー消費量', 'secondary'], ['regional-household-final-energy-consumption', '家庭部門の最終エネルギー消費量', 'secondary'], ['regional-household-car-final-energy-consumption', '家庭乗用車の最終エネルギー消費量', 'secondary']], keywords: ['エネルギー', '電力', '太陽光', '消費'] },
  { key: 'environmental-quality', title: '大気と水環境', description: 'PM2.5の一般環境大気測定局について、有効測定局を分母とした環境基準達成率と局数を比較します。自動車排出ガス測定局や住民の平均曝露濃度は含みません。河川・湖沼・海域の水質は2023年度の県別原表掲載行と達成判定を確認できます。汚濁負荷量は濃度・環境基準達成割合と分けて表示します。', category: 'safety', metrics: [['pm25-general-station-compliance-rate', 'PM2.5環境基準達成率（一般局）', 'primary'], ['pm25-compliant-general-station-count', 'PM2.5環境基準達成局数（一般局）'], ['pm25-valid-general-station-count', 'PM2.5有効測定局数（一般局）'], ['pm25-general-station-count', 'PM2.5総測定局数（一般局）'], ['bod-pollution-load', 'BOD汚濁負荷量'], ['cod-pollution-load', 'COD汚濁負荷量']], keywords: ['大気', '水環境', 'PM2.5', '環境基準'], embeddedSectionKeys: ['water-quality'] },
  { key: 'natural-environment', title: '森林と自然環境', description: '森林面積・林野面積割合、人工造林面積、自然環境保全地域、自然公園を別々に比較します。人工造林面積は植林した面積で、人工林全体の面積ではありません。保全地域と森林面積を足して自然面積とは扱いません。2024年の国立・国定公園の年間延べ利用者数も比較できます。利用者数は県立公園を含まないため、自然公園全体の面積との比率は計算しません。', category: 'lifestyle', metrics: [['woodland-area', '森林面積', 'primary'], ['forest-area-ratio', '林野面積割合'], ['artificial-forest-area', '人工造林面積'], ['natural-environment-conservation-area', '自然環境保全地域面積'], ['nature-park-area', '自然公園面積'], ['national-quasi-national-park-visits', '国立・国定公園の年間延べ利用者数', 'secondary']], keywords: ['自然環境', '森林', '自然公園', '保全地域'] },
  { key: 'earthquake-exposure', title: '地震への備え', description: '30年間の超過確率3%に対応する地震動の震度帯別人口を、2020年人口と2050年推計人口で比較します。住宅の耐震改修指標も別に確認できます。', category: 'safety', metrics: [['earthquake-renovation-rate', '耐震改修工事実施率', 'primary'], ['earthquake-retrofit-housing', '耐震工事をした住宅数（持ち家）'], ['fire-earthquake-insurance-consumption-expenditure', '火災・地震保険料支出（県庁所在市・二人以上世帯・年額）']], embeddedSectionKeys: ['earthquake-population'], keywords: ['地震', '耐震', '防災', '住宅'] },
  { key: 'landslide-exposure', title: '土砂災害', description: '土砂災害警戒区域と、その内数である特別警戒区域の指定数を現象別に比較します。2026年6月30日時点の行政指定状況です。別の空間分析では2025年度版の指定区域面、2020年人口、2022年の公共施設を重ねます。区域の更新日は県により異なり、京都府は利用制限により対象外です。指定数と面の集計は年・対象が異なります。', category: 'safety', metrics: [["landslide-warning-zone-count","土砂災害警戒区域数","primary"],["landslide-special-warning-zone-count","土砂災害特別警戒区域数"],["debris-flow-warning-zone-count","土石流の警戒区域数"],["debris-flow-special-warning-zone-count","土石流の特別警戒区域数"],["steep-slope-warning-zone-count","急傾斜地崩壊の警戒区域数"],["steep-slope-special-warning-zone-count","急傾斜地崩壊の特別警戒区域数"],["landslip-warning-zone-count","地滑りの警戒区域数"],["landslip-special-warning-zone-count","地滑りの特別警戒区域数"]], embeddedSectionKeys: ['landslide-population-facilities'], keywords: ['土砂災害', '警戒区域', '土石流', '地滑り'] },
  { key: 'tsunami-exposure', title: '津波と沿岸防災', description: '内閣府調査の津波避難ビル・津波避難タワー等の整備数を比較します。40県が調査対象で、対象外7県は0件と扱いません。2023年には洪水対応用施設を除外した自治体があるため、2021年からの減少を撤去や防災後退と解釈しません。施設数は浸水人口や危険度とは異なります。別表では29都道府県の公表資料に250m人口と2022年の市町村役場等・公的集会施設を重ね、県ごとの原表の浸水深区分で確認します。想定年と沿岸範囲は県ごとに異なり、歴史的な固定版を含みます。東京都は島しょ11島の想定で、本土等の未対象と9町村内の非該当・未判定を保持します。許諾・提供範囲等により未集計の県を0とせず、安全順位や全国合計は示しません。', category: 'safety', metrics: [['tsunami-evacuation-building-count', '津波避難ビル整備数', 'primary'], ['tsunami-evacuation-tower-count', '津波避難タワー等整備数']], embeddedSectionKeys: ['tsunami-scenario-exposure'], keywords: ['津波', '避難ビル', '避難タワー', '沿岸防災'] },
  { key: 'cultural-participation', title: '文化芸術への参加', description: '美術・演劇などの鑑賞行動者率、図書館利用、博物館数を参加・施設の軸に分けて比較します。行動者率と施設数を合算しません。', category: 'education', metrics: [['hobby-participation-rate-art-appreciation', '美術鑑賞の行動者率', 'primary'], ['hobby-participation-rate-theater', '演芸・演劇・舞踊鑑賞の行動者率'], ['hobby-participation-rate-classical-music', 'クラシック音楽鑑賞の行動者率'], ['hobby-participation-rate-painting', '絵画・彫刻の制作の行動者率'], ['library-lending-books', '図書館館外貸出冊数'], ['total-museum-count', '博物館総数']], keywords: ['文化', '芸術', '図書館', '博物館'] },
  { key: 'sports-participation', title: 'スポーツ施設と利用', description: 'スポーツの年間行動者率・観覧率と社会体育施設数を参加と供給に分けて比較します。施設数から利用者数は推計しません。', category: 'education', metrics: [['sports-annual-participation-rate-10plus', 'スポーツ年間行動者率（10歳以上）', 'primary'], ['hobby-participation-rate-sports-spectating', 'スポーツ観覧の行動者率'], ['community-sports-facility-count-per-million', '社会体育施設数（人口100万人当たり）'], ['sports-park-count', '運動公園数']], keywords: ['スポーツ', '施設', '運動', '観覧'] },
  { key: 'local-government-digital', title: '自治体DX', description: '都道府県行政のオンライン化と申請利用を分けて比較します。eLTAX・採用申請は2022年度、環境性能割は2023年度の実績、手続のオンライン化状況は2023年4月1日調査時点です。利用率をオンライン化率と混同せず、市町村分を合算しません。', category: 'finance', metrics: [['prefectural-dx-online-procedure-rate', '手続オンライン化率（2023年調査）', 'primary'], ['prefectural-dx-online-procedure-count', 'オンライン化済手続数'], ['prefectural-dx-applicable-procedure-count', '実施している対象手続数'], ['prefectural-eltax-online-application-rate', 'eLTAX申請利用率（2022年度）'], ['prefectural-recruitment-online-application-rate', '採用試験申請利用率（2022年度）'], ['prefectural-auto-environment-tax-online-application-rate', '環境性能割申告のオンライン利用率（2023年度）'], ['prefectural-auto-environment-tax-online-application-count', '環境性能割のオンライン申請件数'], ['prefectural-auto-environment-tax-application-count', '環境性能割の申請総件数']], keywords: ['自治体DX', 'オンライン申請', '行政', 'デジタル'] },
  { key: 'gender-participation', title: '地域の男女共同参画', description: '男女の賃金・労働力人口比率に加え、15歳以上の男女の家事時間を比較します。家事時間は行わなかった人を含む1日当たりの総平均で、夫婦に限定した値ではありません。管理職は原則2025年4月1日、県議会議員は2024年12月31日現在。管理職は都道府県職員の部局長・次長・課長相当職で、教職員を除きます。議員の分母は定数ではなく現員数です。政令市・市区町村は両系列から除き、各対象の公表割合を比較します。', category: 'economy', metrics: [['gender-wage-gap', '男女間賃金比（女性／男性）', 'primary'], ['labor-force-population-ratio-woman', '女性労働力人口比率'], ['labor-force-population-ratio-man', '男性労働力人口比率'], ['housework-avg-time-female', '女性の家事時間（15歳以上・1日平均）'], ['housework-avg-time-male', '男性の家事時間（15歳以上・1日平均）'], ['female-part-time-hourly-wage', '女性パートタイム時給'], ['prefectural-manager-female-share', '都道府県の管理職に占める女性の割合', 'secondary'], ['prefectural-assembly-female-share', '都道府県議会議員に占める女性の割合', 'secondary']], keywords: ['男女共同参画', '女性就業', '賃金格差', '家事時間'] },
  { key: 'community-participation', title: '市民参加と地域活動', description: 'ボランティア活動の年間行動者率・まちづくり活動の参加率と、選挙投票率・図書館登録者数を比較します。まちづくり活動は2021年社会生活基本調査の10歳以上が対象で、過去1年間の清掃や地域おこしなどの活動を捉えます。活動種類は重複し、自治会加入率や孤独感とは異なります。', category: 'demographics', metrics: [['volunteer-activity-annual-participation-rate-10plus', 'ボランティア年間行動者率（10歳以上）', 'primary'], ['voter-turnout-governor', '都道府県知事選挙投票率'], ['library-registered-users', '図書館登録者数'], ['community-building-volunteer-participation-rate-10plus', 'まちづくり活動の年間行動者率（10歳以上）', 'secondary']], keywords: ['市民参加', 'ボランティア', '投票率', '地域活動'] },
];

export const EXPANDED_THEME_CATALOGS: Record<string, ThemeCatalog> = Object.fromEntries(SPECS.map((spec) => [spec.key, makeCatalog(spec)]));

/** 既存テーマへ追加する67章。候補の問いごとに、既存の実値を独立カードで配置する。 */
export const EXISTING_THEME_SECTION_EXTENSIONS: Record<string, Array<{ candidateId: number; title: string; description?: string; existingSectionKey?: string; chartKeys?: string[]; embeddedSectionKeys?: string[]; metrics: Array<[string, string, CatalogMetric['role']?]> }>> = {
  'cultural-participation': [
    { candidateId: 119, title: '休養・くつろぎの時間', description: '2021年社会生活基本調査の、休養・くつろぎに使う1日当たり時間です。週全体の総平均を男女別に比較します。上の趣味・娯楽時間は有業者に限る系列なので、これらを足して総余暇時間にはしません。', metrics: [['relaxation-avg-time-male', '男性の休養・くつろぎ時間（週全体総平均・分/日）'], ['relaxation-avg-time-female', '女性の休養・くつろぎ時間（週全体総平均・分/日）']] },
    { candidateId: 115, title: '文化・趣味への参加と使う時間', description: '2021年社会生活基本調査の有業者について、趣味・娯楽に使う1日当たり時間を男女別に比較します。週全体の総平均なので、調査日にその活動をしなかった人も含みます。文化芸術以外のゲームや観光なども含む時間です。', metrics: [['hobby-leisure-avg-time-employed-male', '有業男性の趣味・娯楽時間（週全体総平均・分/日）'], ['hobby-leisure-avg-time-employed-female', '有業女性の趣味・娯楽時間（週全体総平均・分/日）']] },
  ],
  'regional-transport': [
    { candidateId: 79, title: '車・交通手段と交通通信支出', description: '交通・通信支出は県全域の二人以上世帯について、2019・2024年の10〜11月を平均した月額です。通信費を含むため純粋な移動費ではありません。自動車保有台数・通勤手段と支出は別の調査です。', metrics: [['household-survey-transport-communication-expenditure', '交通・通信支出（二人以上世帯・10〜11月の月平均）']] },
  ],
  'household-assets-debt': [
    { candidateId: 78, title: '金融資産と負債の構成', description: '2019年10月末の二人以上世帯の構成割合です。預貯金・生命保険など・有価証券は金融資産を、住宅・土地負債は金融負債を分母にしています。資産にはその他の貯蓄もあるため、掲載3区分を合計100%に直しません。', metrics: [['current-deposit-balance-ratio-multi-person-households', '預貯金が金融資産に占める割合'], ['current-life-insurance-balance-ratio-multi-person-households', '生命保険などが金融資産に占める割合'], ['current-securities-balance-ratio-multi-person-households', '有価証券が金融資産に占める割合'], ['housing-land-liabilities-ratio-multi-person-households', '住宅・土地負債が金融負債に占める割合']] },
  ],
  'health-checkups': [
    { candidateId: 69, title: '対象を分けて見る食習慣と栄養', description: '夕食・朝食の割合は2023年度の40〜74歳の健診受診者で、有効回答者が分母です。栄養摂取量は2024年の20歳以上の標本調査を59歳に年齢調整した値で、下の表に95%信頼区間と集計人数を示します。対象の違う両調査の値から因果関係や県民全体の食習慣を判断しません。', metrics: [['health-checkup-late-dinner-rate', '就寝前2時間以内の夕食が週3回以上'], ['health-checkup-breakfast-skipping-rate', '朝食を抜くことが週3回以上'], ['vegetable-intake-male-age-adjusted', '男性の野菜摂取量（年齢調整）'], ['vegetable-intake-female-age-adjusted', '女性の野菜摂取量（年齢調整）'], ['salt-intake-male-age-adjusted', '男性の食塩摂取量（年齢調整）'], ['salt-intake-female-age-adjusted', '女性の食塩摂取量（年齢調整）']], embeddedSectionKeys: ['nutrition'] },
  ],
  'regional-energy': [
    { candidateId: 98, title: 'FIT・FIPの再エネ導入設備容量', description: '2026年3月31日時点に買取が始まっている設備の累積容量です。新規認定分は制度開始後の認定設備で、当年の増設分ではありません。旧制度移行分は制度開始前の設備等を指し、FITからFIPへの移行とは異なります。容量は発電量やCO₂削減量ではありません。', metrics: [['fit-fip-installed-capacity', 'FIT・FIP導入設備容量の合計'], ['fit-fip-new-approved-installed-capacity', '制度開始後の新規認定分の導入容量'], ['fit-transition-installed-capacity', '旧制度から移行した設備の導入容量']] },
    { candidateId: 99, title: '地域のCO₂排出量推計', description: '2023年度の1,741市区町村の推計を県別に集計しています。エネルギー起源と一般廃棄物焼却のCO₂が対象で、森林吸収・航空・その他の温室効果ガスを含みません。活動量による按分推計で、直接測定した排出量や国の排出インベントリとは異なります。原推計で製造品出荷額の秘匿をゼロ扱いする影響も含みます。', metrics: [['regional-co2-emissions-estimate', '地域のCO₂排出量推計・合計'], ['regional-industry-co2-emissions-estimate', '産業部門のCO₂推計'], ['regional-business-co2-emissions-estimate', '業務その他部門のCO₂推計'], ['regional-household-co2-emissions-estimate', '家庭部門のCO₂推計'], ['regional-transport-co2-emissions-estimate', '運輸部門のCO₂推計（航空を除く）'], ['regional-waste-co2-emissions-estimate', '一般廃棄物焼却のCO₂推計']] },
  ],
  'local-services': [
    { candidateId: 120, title: '映像制作・娯楽関連産業の事業活動', description: '産業中分類41「映像・音声・文字情報制作業」と80「娯楽業」を別々に比較します。事業所・従業者は2021年6月1日の事業所所在地別、売上・純付加価値は2020年実績の企業本所所在地別です。対象と年が異なるため両者を割って生産性とはしません。金額は必要な回答が得られた企業等の集計で、文化産業全体や地域GDPではありません。', metrics: [['media-production-establishments', '映像・音声・文字情報制作業の事業所数'], ['media-production-employees', '映像・音声・文字情報制作業の従業者数'], ['media-production-revenue', '映像・音声・文字情報制作業の企業売上高'], ['media-production-net-value-added', '映像・音声・文字情報制作業の企業純付加価値額'], ['amusement-industry-establishments', '娯楽業の事業所数'], ['amusement-industry-employees', '娯楽業の従業者数'], ['amusement-industry-revenue', '娯楽業の企業売上高'], ['amusement-industry-net-value-added', '娯楽業の企業純付加価値額']] },
  ],
  'business-demography': [
    { candidateId: 19, title: '企業規模別の事業基盤', description: '2021年経済センサスの非農林漁業（公務を除く）、会社企業と個人経営の合計です。本所所在地に企業全体を集計しています。常用雇用者0〜4人は統計上の区分で、法定の中小・小規模企業とは異なります。従業者は役員・個人業主等を含み、常用雇用者だけの人数ではありません。', metrics: [['nonprimary-enterprises-count', '会社・個人経営の企業総数'], ['nonprimary-enterprises-under5-count', '常用雇用者0〜4人の企業数'], ['nonprimary-enterprises-employees', '会社・個人経営の従業者総数'], ['nonprimary-enterprises-under5-employees', '常用雇用者0〜4人企業の従業者数']] },
  ],
  'sports-participation': [
    { candidateId: 70, title: '成人の身体活動と歩数', description: '2024年国民健康・栄養調査の20〜64歳の1日歩数を、男女とも46歳に年齢調整して比較します。95%信頼区間と集計人数を併記し、順位差を有意差とみなしません。石川県は能登半島地震の影響で8地区です。10歳以上の年間運動参加率や公立小学5年生の体力とは母集団を分けて読みます。', metrics: [['daily-steps-male-20to64-age-adjusted', '男性の歩数（20〜64歳・年齢調整）'], ['daily-steps-female-20to64-age-adjusted', '女性の歩数（20〜64歳・年齢調整）']], embeddedSectionKeys: ['physical-activity'] },
    { candidateId: 118, title: "子どもの体力・運動習慣と学校体育館", description: "公立小学5年生の体力・運動習慣に加え、2024年10月1日現在の小中学校の体育館設置箇所数を比較します。施設は公私立の学校が対象で国立大学附属学校を除き、公立小5の体力調査とは対象・時点が異なります。保有学校数や整備率ではなく、回答施設の設置箇所数です。市町村教育委員会の回答率は97.5%で、未回答は補完していません。", metrics: [["elementary-school-gymnasium-count","小学校体育館設置箇所数"], ["junior-high-school-gymnasium-count","中学校体育館設置箇所数"], ['elementary5-fitness-score-male', '小学5年男子の体力合計点'], ['elementary5-fitness-score-female', '小学5年女子の体力合計点'], ['elementary5-weekly-exercise-420min-rate-male', '小学5年男子の週420分以上運動割合'], ['elementary5-weekly-exercise-420min-rate-female', '小学5年女子の週420分以上運動割合']] },
  ],
  'agriculture-production': [
    {
  candidateId: 10,
  title: '畜産・酪農の飼養規模と生産量',
  description:
    '乳用牛・肉用牛は2025年、豚・採卵鶏は2024年の2月1日時点です。生乳生産量は2025年1〜12月の確報で、出荷分に自家飲用・子牛ほ乳用など未出荷分を含みます。飼養規模と年間の生産量を別々に読み、異なる時点・単位の値を構成比にしません。',
  metrics: [
    ['raw-milk-production', '年間生乳生産量（t）'],
    ['dairy-cattle-count', '乳用牛飼養頭数'],
    ['dairy-cattle-holdings', '乳用牛の飼養戸数'],
    ['beef-cattle-count', '肉用牛飼養頭数'],
    ['pig-count', '豚飼養頭数'],
    ['layer-hen-count', '採卵鶏の成鶏めす（千羽）'],
  ],
},
  ],
  'construction-industry': [
    { candidateId: 2, title: '建設業の担い手構成と職種別待遇', description: '2020年国勢調査の常住地別の15歳以上就業者です。30歳未満・30〜54歳・55歳以上は重ならない年齢区分で、女性は各区分に含まれます。事業所所在地別の従業者数とは別集計で、年齢だけから技能継承の成否を判断しません。建築技術者の推計年収は2022年の一般労働者・男女計で、6月の月例給与を12倍し前年の賞与等を加えた額です。就業者数と給与の母集団・年を分けて読みます。', metrics: [['construction-employed-residents', '建設業就業者総数（常住地別）'], ['construction-employed-under30', '30歳未満の建設業就業者'], ['construction-employed-age30to54', '30〜54歳の建設業就業者'], ['construction-employed-age55plus', '55歳以上の建設業就業者'], ['construction-employed-female', '女性の建設業就業者'], ['architect-annual-income', '建築技術者の推計年収（2022年）']] },
    { candidateId: 4, title: '施工地別の公共工事受注', description: '公共機関から受注した1件500万円以上の工事の年度計です。施工地別に集計しており、上の業者所在地別の完成工事高とは合算しません。', metrics: [['public-construction-contract-count', '公共工事の請負契約件数（施工地別）'], ['public-construction-contract-amount', '公共工事の請負契約額（施工地別）']] },
  ],
  'living-housing': [
    { candidateId: 5, title: '住宅着工の利用関係別比較', description: '2023・2024年度の新設住宅を持家・貸家・分譲住宅に分けて比較します。給与住宅はこの3分類に含まれないため、3つの合計を新設住宅全体とは扱いません。', metrics: [['new-housing-starts', '着工新設住宅戸数'], ['new-owner-occupied-starts', '持家の新設着工戸数'], ['new-rental-starts', '貸家の新設着工戸数'], ['new-condo-starts', '分譲住宅の新設着工戸数']] },
    { candidateId: 6, title: '改修・リフォーム需要', metrics: [['renovation-rate', 'リフォーム工事実施率'], ['earthquake-renovation-rate', '耐震改修工事実施率']] },
    { candidateId: 8, title: '空き家の用途と住宅ストック', description: '2023年10月1日の空き家を賃貸用・売却用・二次的住宅・それ以外に分けて比較します。標本調査の推計値は100戸単位に丸められ、内訳の合計と総数が一致しない場合があります。二次的住宅には別荘等を含み、それ以外の空き家を管理不全空家の認定件数とはみなしません。', metrics: [['vacant-housing-rate', '空き家率'], ['households', '一般世帯数'], ['vacant-housing-excluding-rental-sale-secondary', '賃貸・売却用及び二次的住宅を除く空き家'], ['vacant-housing-for-rent', '賃貸用の空き家'], ['vacant-housing-for-sale', '売却用の空き家'], ['vacant-housing-secondary-residences', '二次的住宅']] },
    { candidateId: 44, title: '単身化と一人暮らし', description: "2020年国勢調査の単独世帯を男女・年齢別に比較します。65歳以上の人数と単独世帯全体の割合は分母が異なります。年齢不詳を独立した区分として残し、施設等の世帯は含めません。", metrics: [["single-households-age65plus-male", "65歳以上の男性単独世帯数"], ["single-households-age65plus-female", "65歳以上の女性単独世帯数"], ['single-person-household-ratio', '単独世帯割合']], embeddedSectionKeys: ['single-households-demographics'] },
    { candidateId: 45, title: '世帯構成の変化', metrics: [['households', '一般世帯数'], ['average-persons-per-general-household', '一般世帯の平均人員']] },
    { candidateId: 74, title: '住居費と住宅取得の負債', description: '2019年の総世帯における住宅・土地のための負債残高を、家賃支出や二人以上世帯の金融負債と区別して確認します。住宅・土地負債はローンのない世帯も含む平均で、年間返済額ではありません。対象年・世帯区分が異なる指標から返済負担率は計算しません。', metrics: [['housing-land-debt-per-household', '住宅・土地のための負債（総世帯平均）'], ['private-rent-consumption-expenditure', '家賃支出'], ['current-liabilities-balance-multi-person-households-per-household', '負債現在高']] },
    { candidateId: 93, title: '都市の人口集積と計画上の区域', description: '人口集中地区は実際の人口集積、都市計画区域や市街化調整区域は計画上の指定です。区域面積は3月31日時点で、調整区域の割合は都市計画区域を分母とします。非線引区域もあるため、残りを市街化区域の割合とは扱いません。', metrics: [['densely-inhabited-district-population-density', '人口集中地区人口密度'], ['urban-planning-area', '都市計画区域の指定面積'], ['urbanization-control-area-ratio', '都市計画区域に占める市街化調整区域の割合']] },
    { candidateId: 94, title: '公園と都市緑地', metrics: [['urban-parks', '都市公園数'], ['urban-parks-area', '都市公園面積']] },
  ],
  manufacturing: [
    { candidateId: 12, title: '食料品製造の生産と雇用', description: '産業中分類09の食料品製造業を対象に、個人経営を除く全規模の事業所を比較します。2024年調査の再集計参考値で、事業所・従業者は2024年6月、出荷額等は2023年の実績です。農業・外食・飲料製造とは合算しません。', metrics: [['food-manufacturing-establishments', '食料品製造業の事業所数'], ['food-manufacturing-employees', '食料品製造業の従業者数'], ['food-manufacturing-shipment-amount', '食料品製造業の出荷額等']] },
    { candidateId: 22, title: '企業立地と工場投資', description: '2024年の工場立地に伴う設備投資額を、公式全国値と47県の公表状態を保った表で確認します。秘匿の3県は非公表と表示し、県内全企業の投資実績や別年の立地敷地面積とは分けて読みます。', metrics: [['factory-location-area-annual', '工場立地敷地面積（年次）']], embeddedSectionKeys: ['factory-investment'] },
  ],
  'local-economy': [
    { candidateId: 16, title: "産業別の雇用構成と特化係数", description: "2021年6月1日の同一統計を使い、県の産業別従業者割合を全国と比べます。特化係数1は全国と同じ構成比です。公務、農林漁業の個人経営、外国会社・法人でない団体等を除き、事業所所在地別に集計しています。公式全産業の分母には大分類へ分かれない上位集計の差分を含めます。", metrics: [["employment-location-quotient-manufacturing", "製造業の従業者特化係数"], ["employment-location-quotient-information-communication", "情報通信業の従業者特化係数"], ["employment-location-quotient-health-welfare", "医療・福祉の従業者特化係数"]], embeddedSectionKeys: ['industry-specialization'] },
    { candidateId: 18, title: "企業の付加価値と地域への配分", description: "2020年の全産業純付加価値を、企業本所所在地別と傘下事業所への従事者按分で比べます。全国額は同じでも県別への帰属が異なります。GDPとは含まれる項目が異なり、異なる県帰属の売上・雇用と割って生産性を作りません。", metrics: [["enterprise-net-value-added-all-industries", "全産業の企業純付加価値（本所県）"], ["private-establishment-net-value-added", "民営事業所の純付加価値（所在地へ按分）"]] },
  ],
  tourism: [
    { candidateId: 25, title: '宿泊市場と稼働率', metrics: [['room-utilization-rate', '客室稼働率']] },
    { candidateId: 26, title: '外国人旅行者の訪問・宿泊・消費', description: '訪問者数は2025年の全目的・一般客の推計で、日帰りと空港・港の所在地も含みます。同じ旅行で複数県を訪れるため県別値を全国実人数へ合算しません。訪問回答数は重み付け前の標本で、回答数から推計訪問率を作り直しません。宿泊・消費の系列とは単位と対象を分けます。', metrics: [['inbound-visitors-by-destination', '訪日外国人の訪問者数（推計）'], ['inbound-visit-sample-by-destination', '訪問者数推計の県別回答数'], ['total-overnight-guests-foreign', '外国人延べ宿泊者数']] },
    { candidateId: 27, title: '訪問先の旅行消費額', description: '日本人の国内旅行と訪日外国人一般客が訪問先の県で消費した金額を別々に比較します。全目的・宿泊と日帰りを含み、県間交通費等を除きます。異なる標本調査の推計で、県内所得や地域への還元率ではありません。', metrics: [['domestic-travel-consumption-by-destination', '日本人旅行者の県内消費額'], ['inbound-travel-consumption-by-destination', '訪日外国人旅行者の県内消費額']] },
    { candidateId: 28, title: '宿泊の規模と季節性', description: '年間の宿泊規模と2024年の月別の増減を確認します。月別値は全施設の確定値で、観光・出張等の全目的を含みます。月の日数の違いや能登半島地震による調査対象の除外に注意して読みます。', metrics: [['total-overnight-guests', '年間の延べ宿泊者数']], embeddedSectionKeys: ['tourism-seasonality'] },
    { candidateId: 85, title: '空港と航空交通', description: '2025年の空港別旅客・貨物取扱いを国内線・国際線に分けて確認します。所在地で空港を選び、国際線通過客や複数県にまたがる空港を区別します。県民の実利用人数ではありません。', embeddedSectionKeys: ['airport-traffic'], metrics: [['airport-count', '空港数'], ['air-passenger-transport', '航空輸送人員']] },
  ],
  'labor-mobility': [
    { candidateId: 33, title: '人手不足と求人', metrics: [['active-job-opening-ratio', '有効求人倍率']] },
    { candidateId: 37, title: '非正規雇用と雇用の安定性', description: '非正規雇用率に加え、2022年就業構造基本調査の非正規の職員・従業員数と、継続・転職希望の割合を比較します。希望割合の分母は希望不詳を含む非正規の職員・従業員総数です。継続希望は追加就業希望を含まず、転職希望は実際の転職とは異なります。', metrics: [['non-regular-employment-rate', '非正規雇用率'], ['nonregular-employees-count', '非正規の職員・従業員数（15歳以上）'], ['nonregular-continuation-wish-rate', '非正規の継続就業希望割合'], ['nonregular-job-change-wish-rate', '非正規の転職希望割合']] },
    { candidateId: 38, title: '労働時間と長時間就業', description: '月間平均実労働時間と、2022年就業構造基本調査の週60時間以上就業する雇用者数・割合を比較します。週60時間以上の指標は役員を除く雇用者のうち年間200日以上就業する人が対象で、割合の分母には週間時間不詳を含みます。主な仕事のふだんの時間を表し、平均実労働時間の系列とは調査と対象が異なります。', metrics: [['monthly-average-actual-working-hours-male', '男性月間平均実労働時間'], ['monthly-average-actual-working-hours-female', '女性月間平均実労働時間'], ['employees-weekly-hours-60plus-count', '週60時間以上の雇用者数（年間200日以上）'], ['employees-weekly-hours-60plus-rate', '週60時間以上の雇用者割合（年間200日以上）']] },
    { candidateId: 39, title: 'テレワークと通勤', metrics: [['telework-rate', 'テレワーク実施率']] },
    { candidateId: 84, title: '通勤通学と昼間人口', metrics: [['day-time-population-ratio', '昼夜間人口比率'], ['commuter-ratio-to-other-municipalities', '他市区町村への通勤者比率']] },
  ],
  'labor-wages': [
    { candidateId: 35, title: '女性の就業と賃金', metrics: [['labor-force-population-ratio-woman', '女性労働力人口比率'], ['female-scheduled-earnings', '女性所定内給与額']] },
  ],
  'population-dynamics': [
    { candidateId: 34, title: "若年層の県間移動と卒業後の進路", description: "2025年の15〜24歳・25〜34歳の県間転入超過数は外国人を含む移動者です。年齢・男女別の詳細は「年齢・男女別にみる県間の人口移動」で確認できます。県外就職割合は高校卒業後に就職した人、進学率は卒業者全体が分母で、就職先と住所の移動は別に読みます。", metrics: [["interprefecture-net-migration-age15to24", "15〜24歳の県間転入超過数"], ["interprefecture-net-migration-age25to34", "25〜34歳の県間転入超過数"], ['high-school-graduates-out-of-prefecture-job-ratio', '高校卒業就職者のうち県外就職者の割合'], ['high-school-advancement-rate', '高等学校卒業者の進学率']], embeddedSectionKeys: ['young-migration-link'] },
    { candidateId: 41, title: '出生と母の年齢・出生順位', description: '2024年の日本における日本人の出生を、母の年齢5区分と出生順位3区分で比較します。地域は子の住所です。年齢不詳は5区分に含めず、全国12人を原典に保持しています。全国は住所が外国の18人を含み、47県合計と異なります。出生順位は同じ母親がこれまでに生んだ出生子を数えた順序です。', metrics: [['births', '出生数'], ['total-fertility-rate', '合計特殊出生率'], ['births-mother-under25', '母が25歳未満の出生数'], ['births-mother-age25to29', '母が25〜29歳の出生数'], ['births-mother-age30to34', '母が30〜34歳の出生数'], ['births-mother-age35to39', '母が35〜39歳の出生数'], ['births-mother-age40plus', '母が40歳以上の出生数'], ['births-first-child', '第1子の出生数'], ['births-second-child', '第2子の出生数'], ['births-third-child-plus', '第3子以降の出生数']] },
    { candidateId: 43, title: "県間の人口移動と5年前の居住地", description: "県間移動の詳細表は2025年の外国人を含む移動者を年齢・男女・相手県別に比較します。5年前の居住地は2020年の5歳以上住民を2015年と比較したもので、5年間の転居回数ではありません。外国人の転入・転出カードは外国人だけを対象とする別系列です。", metrics: [["five-year-residence-same-address", "5年前と同じ住所に住む5歳以上人口"], ["five-year-residence-other-prefecture", "5年前は他県に住んでいた5歳以上人口"], ['movers-in', '外国人の転入者数'], ['movers-out', '外国人の転出者数']], embeddedSectionKeys: ['migration-demographics', 'five-year-residence'] },
    { candidateId: 47, title: '人口の将来推計', description: '社人研の令和5年推計です。2020年の国勢調査人口と将来推計を区別し、2050年の値は実績ではなく出生・死亡・移動の仮定に基づく推計として読みます。', metrics: [['future-population', '将来推計人口'], ['future-population-change-rate-2050', '2020～2050年の人口増減率（推計）']] },
  ],
  'aging-society': [
    { candidateId: 36, title: '高齢者の就業', description: '高齢就業者割合を掲載します。65～69歳など年齢階級別の有業率は含みません。', metrics: [['elderly-workers-ratio', '高齢就業者割合']] },
    { candidateId: 42, title: '婚姻と家族形成', metrics: [['marriages-per-total-population', '婚姻率'], ['divorces-per-total-population', '離婚率']] },
    { candidateId: 48, title: '過疎地域等の集落と高齢化', description: '2024年4月1日時点の調査対象78,485集落について、住民に占める65歳以上割合の7区分を全国・10地方ブロックで示します。県を選択した場合も、その県に対応する地方ブロック全体の集計です。北海道・沖縄県を除く県別内訳は本表に公表されていません。無回答と内数を保持します。県全体の高齢化率とは対象を分けて読みます。', metrics: [['ratio-65-plus', '県全体の65歳以上人口割合', 'context']], embeddedSectionKeys: ['depopulated-settlements'] },
  ],
  'local-finance': [
    { candidateId: 50, title: '児童福祉への支出と公的給付', description: '都道府県の会計における児童福祉費と歳出に占める割合です。財政値は市町村支出や各家庭の費用を含みません。児童扶養手当受給者数はひとり親等を対象とする2023年度末の実績で、すべての児童を対象とする児童手当とは別の制度です。支出額・割合・受給者数を別々に読みます。', metrics: [['child-welfare-expenses-prefecture', '児童福祉費（都道府県財政）'], ['child-welfare-expenditure-ratio-pref-finance', '児童福祉費割合'], ['child-rearing-allowance-recipients', '児童扶養手当受給者数（ひとり親等）']] },
    { candidateId: 92, title: '公共施設の量と維持・建設への支出', description: '都道府県が報告する行政財産・普通財産の建物延面積と、都道府県財政の維持補修費・普通建設事業費を掲載します。建物面積は2024年度末の所有資産で、市町村分や道路等を含みません。支出は建物以外や新規建設を含むため、面積当たりの建物更新費には換算しません。', metrics: [['maintenance-repair-expenses-prefecture', '維持補修費（都道府県財政）'], ['ordinary-construction-expenses-prefecture', '普通建設事業費（都道府県財政）'], ['prefectural-public-building-floor-area', '都道府県有建物の延面積（年度末）']] },
    { candidateId: 121, title: '財政の持続性', existingSectionKey: 'fiscal-capacity', metrics: [['current-balance-ratio', '経常収支比率'], ['future-burden-ratio', '将来負担比率']] },
    { candidateId: 122, title: '目的別と性質別の歳出を分けて見る', description: '各指標に表示した年度の都道府県普通会計の歳出に対する人件費・扶助費・投資的経費の割合を比較します。性質別の分類で、目的別歳出のフローとは別です。ほかの性質の支出もあるため、3項目を合計100%に直しません。都道府県・市町村合算の1人当たり歳出とも会計範囲が異なります。', metrics: [['per-capita-total-expenditure-pref-municipal', '1人当たり歳出（都道府県・市町村合計）'], ['personnel-expenditure-ratio-pref-finance', '人件費割合（都道府県普通会計）'], ['assistance-expenditure-ratio-pref-finance', '扶助費割合（都道府県普通会計）'], ['investment-expenditure-ratio-pref-finance', '投資的経費割合（都道府県普通会計）']] },
    { candidateId: 123, title: '行政部門の職員数と職種別給与', description: '都道府県職員の一般行政部門・警察部門の人数と、一般行政職・教育公務員・警察職の平均給与月額を分けて比較します。部門人数は4月1日時点で、県内市町村職員を含みません。平均年齢は年齢階級別の構成割合ではなく、職種の平均給与の差だけで同じ仕事の待遇差とは判断できません。', metrics: [['prefectural-general-administration-staff', '一般行政部門職員数（都道府県）'], ['avg-salary-admin-prefecture', '一般行政職の平均給与月額（都道府県）'], ['avg-age-admin-prefecture', '一般行政職の平均年齢（都道府県）'], ['avg-salary-education-prefecture', '教育公務員の平均給与月額（都道府県）'], ['avg-salary-police-prefecture', '警察職の平均給与月額（都道府県）'], ['police-department-staff', '警察部門職員数（都道府県）']] },
    // 寄附の受入・募集費・税控除は別の原典を要する。地方税割合では代用しない。
    { candidateId: 125, title: 'ふるさと納税の受入・募集費・税控除', description: '都道府県自身の2025年度決算見込で、県内市町村分は含みません。東京都は当年度の指定申出がなく特例控除対象外ですが、原表の受入実績に含めています。募集費は返礼品調達費・送付費を含むため合算しません。税控除は県内市区町村の課税分で、2026年度課税（2025暦年寄附分）の推計値を含みます。受入額と対象・期間が異なるため差額を損益とは扱いません。', metrics: [['furusato-donation-amount-prefecture', '受入額（県自身）'], ['furusato-donation-count-prefecture', '受入件数（県自身）'], ['furusato-fundraising-cost-prefecture', '募集経費（県自身）'], ['furusato-return-gift-procurement-cost-prefecture', '返礼品調達費（募集費の内数）'], ['furusato-return-gift-shipping-cost-prefecture', '返礼品送付費（募集費の内数）'], ['furusato-tax-deduction-municipal-prefecture', '市町村民税控除額（県内課税分・推計値含む）'], ['furusato-tax-deduction-prefectural-prefecture', '道府県民税控除額（県内課税分・推計値含む）']] },
  ],
  'education-culture': [
    { candidateId: 52, title: "学校の規模と廃校の実績", description: "学校数の推移と、2004〜2023年度の公立学校廃校発生延べ数を別々に確認します。廃校の累計は2024年5月1日現在に把握した実績で、単年度件数や現存施設数ではありません。県別の廃校活用率はこの原表から算出できません。", metrics: [["public-school-closures-cumulative","公立学校廃校発生数（2004〜2023年度累計）"], ['elementary-school-count', '小学校数'], ['junior-high-school-count', '中学校数']] },
    { candidateId: 53, title: '高校卒業後の進路', description: '2025年3月に国公私立高校の全日制・定時制を卒業した人を、卒業校の所在地別に8つの進路へ分けます。進学しながら就職している人は進学区分の内数で、不詳・死亡は独立した区分です。通信制高校などを含まず、進学率カードとは対象年と定義を分けて読みます。', metrics: [['high-school-advancement-rate', '高等学校卒業者の進学率']], embeddedSectionKeys: ['graduation-paths'] },
    { candidateId: 54, title: '大学と地域人材', metrics: [['university-count', '大学数'], ['university-count-per-100k', '大学数（人口10万人当たり）']] },
    { candidateId: 55, title: '教育費と学習環境', metrics: [['elementary-school-education-cost-per-student', '小学校教育費']] },
    { candidateId: 56, title: '生涯学習と学び直し', metrics: [['study-participation-rate-business', '商業実務・ビジネス関係の学習行動者率']] },
    { candidateId: 113, title: '図書館と読書環境', metrics: [['library-books', '図書館蔵書数'], ['library-lending-books', '図書館貸出冊数']] },
    { candidateId: 114, title: "博物館・美術館の供給と利用", description: "2023年度の入館者数を登録博物館・指定施設・博物館類似施設に分けます。美術博物館のほか科学・歴史博物館や動植物園等を含むため、美術館だけの利用者数ではありません。特別展は内数で、実人数や住民利用率とも異なります。施設数とは年と法的区分を揃えるまで1施設当たり値を作りません。", metrics: [["registered-museum-visitors","登録博物館の入館者数"], ["designated-museum-visitors","指定施設の入館者数"], ["museum-like-facility-visitors","博物館類似施設の入館者数"], ['total-museum-count', '博物館総数'], ['art-museum-count', '美術博物館数']] },
    { candidateId: 116, title: '文化財の指定・保護と所在地', description: '県指定等文化財件数、県政府の保護経費、県・市町村・調査組織の埋蔵文化財専門職員を別々に比較します。指定件数・職員は2025年5月、保護経費は2024年度です。対象範囲が異なるため、1件当たり経費・職員には換算しません。別表では2026年9月11日に国指定文化財等DBへ収録された特別史跡・特別名勝・特別天然記念物167件の種類・名称・所在地を確認できます。県指定文化財とは別の範囲で、地域を定めない14件は県へ配分しません。', metrics: [['prefecture-designated-cultural-property-count', '県指定等文化財件数'], ['prefectural-cultural-property-protection-expenditure', '県政府の文化財保護経費'], ['buried-cultural-property-specialist-count', '埋蔵文化財専門職員数']], embeddedSectionKeys: ['cultural-heritage-locations'] },
  ],
  healthcare: [
    { candidateId: 57, title: "診療科と年齢から見る医療人材", description: "2024年12月31日の医療施設従事医師を、主たる従業地別に診療科と年齢で比較します。40歳未満・40〜59歳・60歳以上は同じ総数の内訳です。小児科・産婦人科系・救急科は主たる診療科の人数で、全診療科の内訳は専用図表から確認できます。人口当たり指標と人数は区別して読みます。", metrics: [['physicians-in-medical-facilities-per-100k', '医師数（人口10万人当たり）'], ['nurses-in-medical-facilities-per-100k', '看護師・准看護師数（人口10万人当たり）'], ["medical-physicians-under-40", "40歳未満の医療施設従事医師数（2024年末）"], ["medical-physicians-age-40-59", "40〜59歳の医療施設従事医師数（2024年末）"], ["medical-physicians-age-60-plus", "60歳以上の医療施設従事医師数（2024年末）"], ["medical-physicians-pediatrics", "小児科の医師数（2024年末）"], ["medical-physicians-obstetrics-gynecology", "産婦人科系の医師数（2024年末）"], ["medical-physicians-emergency-medicine", "救急科の医師数（2024年末）"]], embeddedSectionKeys: ['medical-workforce'] },
    { candidateId: 58, title: "救急搬送の所要時間と初診時の傷病程度", description: "2024年中の救急自動車による搬送人員を、初診時の医師の診断による死亡・重症・中等症・軽症・その他に分けます。5区分は同じ搬送総数の内訳で、出動件数を分母にしません。軽症は入院加療が不要という分類で、早期治療が必要な人も含みます。搬送時間だけから傷病程度や治療の成否を判断しません。", metrics: [["ambulance-transported-persons", "救急自動車による搬送人員"], ["ambulance-transported-deaths", "救急搬送人員（初診時死亡）"], ["ambulance-transported-severe", "救急搬送人員（重症）"], ["ambulance-transported-moderate", "救急搬送人員（中等症）"], ["ambulance-transported-mild", "救急搬送人員（軽症）"], ["ambulance-transported-other", "救急搬送人員（その他）"], ['ambulance-hospital-arrival-time', '救急搬送病院収容所要時間'], ['annual-emergency-dispatches-per-1000', '救急出動件数（人口千人当たり）']] },
    { candidateId: 59, title: '出産と周産期医療の施設供給', description: '分娩取扱病院・診療所は2023年10月、総合・地域周産期母子医療センターは2026年4月の施設数です。9月の分娩実績がない取扱施設も含み、病院とセンターは重複するため合算しません。施設数はNICU病床数や患者の受入能力とは異なります。', metrics: [['delivery-hospital-count', '分娩取扱病院数（2023年）'], ['delivery-clinic-count', '分娩取扱診療所数（2023年）'], ['general-perinatal-center-count', '総合周産期母子医療センター（2026年）'], ['regional-perinatal-center-count', '地域周産期母子医療センター（2026年）']] },
    { candidateId: 61, title: '訪問診療と訪問看護の実施', description: '2023年9月の1か月間、病院・一般診療所による医療保険等の訪問診療と訪問看護・指導の実施件数を比較します。県は医療施設所在地で、患者の居住地ではありません。実人数や年間件数ではなく、訪問看護ステーション、精神科の別項目、介護保険による訪問看護は含みません。訪問介護の利用者数・給与は別の指標です。', metrics: [['home-medical-visit-cases', '訪問診療実施件数（2023年9月）'], ['home-nursing-visit-cases', '訪問看護・指導実施件数（2023年9月）'], ['home-helper-users-per-office', '訪問介護利用者数（1事業所当たり）'], ['home-care-worker-annual-income', '訪問介護従事者平均年収']] },
    { candidateId: 65, title: '健康寿命と平均寿命', description: '健康寿命は2022年、0歳平均余命である平均寿命は2020年の値です。健康寿命は日常生活に制限のない期間を表します。年と算定方法が異なるため、2系列を差し引いて不健康な期間を求めません。', metrics: [['healthy-life-expectancy-male', '男性健康寿命'], ['healthy-life-expectancy-female', '女性健康寿命'], ['life-expectancy-0-male', '男性平均寿命（2020年）'], ['life-expectancy-0-female', '女性平均寿命（2020年）']] },
    { candidateId: 67, title: 'がんの新規罹患と疾病の死亡', description: '2023年の悪性新生物（全部位C00-C96）の罹患数を診断時住所の県別で確認します。多重原発がんは別腫瘍となるため単位は例です。上皮内新生物は含まず、性別不詳4例は総数に含みます。人口や年齢構成を調整したリスクではなく、既存の生活習慣病死亡率とも別の指標です。', metrics: [['new-cancer-incidence-count', 'がんの新規罹患数（2023年）'], ['deaths-lifestyle-diseases-per-100k', '生活習慣病死亡率']] },
    { candidateId: 68, title: "こころの状態と相談・受療", description: "K6は2025年6月5日調査の12歳以上・入院者除外。不詳を除く公表級別推計人数を分母に使用し、年齢調整はしていません。人数は千人単位の丸めた推計値で実回答者数ではありません。相談は2024年度の市区町村での延人員です。受療率とも対象・時点が異なり、同じ人の流れを表しません。", metrics: [["k6-score10plus-rate-12plus", "K6が10点以上の割合（12歳以上・不詳除外）", "secondary"], ["municipal-mental-health-consultation-extended-persons", "市区町村の精神保健福祉相談延人員", "secondary"], ["treatment-rate-mood-disorder-outpatient", "気分障害外来受療率", "secondary"], ["k6-score10plus-estimated-persons-12plus", "K6が10点以上の推計人数（分子）", "context"], ["k6-known-score-estimated-persons-12plus", "K6の点数が判明している推計人数（分母）", "context"]] },
  ],
  'foreign-residents': [
    { candidateId: 40, title: '外国人の雇用と事業所', description: '2025年10月末の事業主による外国人雇用届出を集計しています。特別永住者と在留資格「外交」「公用」は対象外です。外国人住民の総数や年間の新規採用人数とは異なり、事業所数は企業数ではありません。', metrics: [['foreign-worker-count', '外国人労働者数（雇用届出）'], ['foreign-employing-establishment-count', '外国人を雇用する事業所数']] },
  ],
  'real-income': [
    { candidateId: 73, title: '可処分所得と生活費', metrics: [['disposable-income-worker-households', '可処分所得'], ['actual-income-worker-households-per-month', '実収入']] },
    { candidateId: 77, title: '家計の消費配分', description: '全国家計構造調査の都道府県全域・二人以上世帯が対象です。10〜11月の1世帯当たり月平均で、県庁所在市の通年家計調査とは異なります。総額と10費目の構成を分けて確認します。', metrics: [['household-survey-consumption-expenditure', '消費支出（全費目）']], chartKeys: ['real-income-household-composition'] },
    { candidateId: 80, title: '所得と金融資産の分布', description: '2019年全国家計構造調査の総世帯について、県内の分布の不均等度を示すジニ係数を比較します。所得と金融資産では有効回答世帯が異なるため、同一標本の差ではありません。金融資産は負債控除前の貯蓄現在高です。', metrics: [['gini-coefficient-disposable-income', '等価可処分所得ジニ係数（総世帯）'], ['gini-coefficient-financial-assets', '等価金融資産残高ジニ係数（総世帯）']] },
  ],
  'consumer-prices': [
    { candidateId: 75, title: '光熱価格・家計支出と気温', description: '家計支出は県全域の二人以上世帯について、2019・2024年の10〜11月を平均した月額です。気温は代表観測地点の年間平均であり、県全域の気温や通年の光熱費ではありません。物価指数・支出額・気温はそれぞれ別の指標です。', metrics: [['consumer-price-difference-index-utilities', '光熱・水道物価地域差指数'], ['household-survey-utilities-expenditure', '光熱・水道支出（二人以上世帯・10〜11月の月平均）'], ['average-temperature', '年平均気温（代表観測地点）']] },
    { candidateId: 76, title: '食料価格と家計の食料支出', description: '食料支出は県全域の二人以上世帯について、2019・2024年の10〜11月を平均した月額です。食料の物価指数とは単位と対象が異なり、支出額の差だけで同じ商品の価格差とは判断できません。', metrics: [['consumer-price-difference-index-food', '食料物価地域差指数'], ['household-survey-food-expenditure', '食料支出（二人以上世帯・10〜11月の月平均）']] },
  ],
  ports: [{ candidateId: 86, title: '港湾と国際物流', metrics: [['maritime-import-export-cargo', '海上出入貨物']] }],
  safety: [
    { candidateId: 88, title: '交通安全と高齢者の死傷', description: '交通事故件数・死亡率に加え、65歳以上の死傷者数を比較します。高齢者の被害を捉える年齢区分であり、高齢運転者が起こした事故件数や事故原因を表すものではありません。', metrics: [['traffic-accident-count', '交通事故発生件数'], ['traffic-accident-deaths-per-100k', '交通事故死者数（人口10万人当たり）'], ['traffic-accident-casualties-elderly-65plus', '交通事故死傷者数（65歳以上）']] },
    { candidateId: 106, title: '洪水と浸水', metrics: [['flood-damage-general-assets', '水害一般資産等被害額'], ['flood-affected-municipalities', '水害被災市区町村数']] },
    { candidateId: 109, title: "自然災害の人的・住家被害と復旧支出", description: "2024年中に発生した自然災害等の被害を、2025年4月1日現在の集計で掲載します。死者には災害関連死を含み、負傷者は重傷と軽傷の合計です。住家の全壊・半壊・一部破損は棟数で、浸水のみの被害を含む総数ではありません。既存の被害額や復旧支出は対象年・年度・単位を別に確認し、支出の多さを復旧速度とみなしません。", metrics: [["natural-disaster-deaths", "自然災害による死者数"], ["natural-disaster-missing-persons", "自然災害による行方不明者数"], ["natural-disaster-injured-persons", "自然災害による負傷者数"], ["natural-disaster-destroyed-houses", "自然災害による全壊住家棟数"], ["natural-disaster-half-destroyed-houses", "自然災害による半壊住家棟数"], ["natural-disaster-partially-damaged-houses", "自然災害による一部破損住家棟数"], ["disaster-recovery-expenses-prefecture", "災害復旧費（都道府県財政）"], ['disaster-damage-amount-per-person', '1人当たり災害被害額']] },
    { candidateId: 110, title: '消防・救急の人員と車両', description: '消防吏員・消防ポンプ自動車等は2022年、救急自動車は2024年の人口10万人当たりの値です。車両や人員の実数ではなく、各県の人口規模をそろえた供給量として読みます。異なる年の値を同年の構成比にはしません。', metrics: [['fire-department-water-count-per-100-thousand-people', '消防水利数'], ['annual-emergency-dispatches-per-1000', '救急出動件数（人口千人当たり）'], ['fire-department-member-count-per-100-thousand-people', '消防吏員数（人口10万人当たり）'], ['fire-department-pump-car-count-per-100-thousand-people', '消防ポンプ自動車等現有数（人口10万人当たり）'], ['fire-department-emergency-car-count-per-100k', '救急自動車数（人口10万人当たり）']] },
    { candidateId: 111, title: "避難施設と個別避難計画の整備", description: "個別避難計画は2026年4月1日現在、名簿に載る要支援者のうち計画が作成された人数と割合です。自治体ごとに名簿の対象基準が異なり、過去の累計や優先作成対象者数は分母にしません。施設数と計画作成率は実際の避難成功率ではありません。津波避難施設の対象外7県は0へ置き換えず、他災害の施設総数にも読み替えません。", embeddedSectionKeys: ['shelter-applicability'], metrics: [["individual-evacuation-plan-coverage-rate", "個別避難計画の作成率"], ["individual-evacuation-plan-listed-persons", "避難行動要支援者名簿の掲載人数"], ["individual-evacuation-plan-covered-persons", "個別避難計画が作成された人数"], ['tsunami-evacuation-building-count', '津波避難ビル数'], ['tsunami-evacuation-tower-count', '津波避難タワー等数'], ['disaster-relief-expenses-prefecture', '災害救助費']] },
    { candidateId: 112, title: '犯罪と消費者被害', description: "2025年度調査で把握した2024年度中の受付件数。都道府県・政令市・市区町村・広域連合・一部事務組合を含む県別の公表合計を使用する。「うちあっせん件数」は内数であり加算しない。相談者の実人数や認定された消費者被害の件数、犯罪認知件数とは異なる。窓口の県別集計であり、相談者の居住県別とはしない。", metrics: [["consumer-consultation-accepted-cases", "消費生活相談受付件数（年度）", "secondary"], ['criminal-recognition-count', '刑法犯認知件数'], ['police-officer-count-per-population', '警察官数（人口千人当たり）']] },
  ],
  roads: [{ candidateId: 89, title: '道路橋の架設年度と橋梁・トンネルの健全性', description: '2025年度末時点の全道路管理者の施設を所在地の県別に比較します。2014〜2025年度の最新診断による総数と、その内数である早期措置段階（Ⅲ）・緊急措置段階（Ⅳ）を掲載します。3巡目だけの点検実施数、修繕未着手数、倒壊確率とは異なります。架設年度分布は2025年度に点検・掲載された橋だけを別の分母にし、年度末に診断中の橋を除きます。全管理橋の年齢構成へ一般化しません。', metrics: [['road-bridge-diagnosed-count', '道路橋の診断済総数'], ['road-bridge-condition-iii-count', '道路橋の早期措置段階（Ⅲ）'], ['road-bridge-condition-iv-count', '道路橋の緊急措置段階（Ⅳ）'], ['road-tunnel-diagnosed-count', 'トンネルの診断済総数'], ['road-tunnel-condition-iii-count', 'トンネルの早期措置段階（Ⅲ）'], ['road-tunnel-condition-iv-count', 'トンネルの緊急措置段階（Ⅳ）']], embeddedSectionKeys: ['bridge-inspection-age'] }],
  climate: [
    { candidateId: 96, title: '雪国の暮らしと除雪', metrics: [['annual-snow-days', '年間雪日数'], ['maximum-snow-depth', '最深積雪']] },
    { candidateId: 104, title: "暑さと熱中症の救急搬送", description: "熱中症救急搬送は2025年5〜9月の確定値です。搬送人員は発症者の全数ではありません。気温・日照は代表観測地点の年間値なので、期間と地理の違いを保って読み、同期間の比較や対策の効果を示すものとは扱いません。", metrics: [["heatstroke-emergency-transports", "熱中症救急搬送人員"], ['maximum-temperature', '最高気温'], ['annual-sunshine-duration', '年間日照時間']] },
  ],
};

export function extensionMetric(metric: [string, string, CatalogMetric['role']?]): CatalogMetric {
  return {
    rankingKey: metric[0],
    shortLabel: metric[1],
    role: metric[2] ?? 'secondary',
    selection: { proposedBy: '128テーマ実現性調査・既存テーマ拡充', surveyedAt: '2026-09-09', rationale: `${metric[1]}を既存テーマの独立章へ追加する。` },
  };
}
