// 全サブカテゴリのフォールバック設定
// 生成日時: 2025-10-11T00:20:25.112Z
// 総サブカテゴリ数: 65
// 総ランキング項目数: 273

import { RankingConfigResponse } from "./get-ranking-items";

export const FALLBACK_CONFIGS: Record<string, RankingConfigResponse> = {
  expenditure: {
    subcategory: {
      id: "expenditure",
      categoryId: "administrativefinancial",
      name: "Expenditure",
      description: undefined,
      defaultRankingKey: "generalExpenditure",
    },
    rankingItems: [
      {
        rankingKey: "generalExpenditure",
        label: "一般会計支出",
        statsDataId: "0000010156",
        cdCat01: "CCC1101",
        unit: "百万円",
        name: "一般会計支出",
        displayOrder: 1,
        isActive: true,
      },
      {
        rankingKey: "specialExpenditure",
        label: "特別会計支出",
        statsDataId: "0000010156",
        cdCat01: "CCC1102",
        unit: "百万円",
        name: "特別会計支出",
        displayOrder: 2,
        isActive: true,
      },
      {
        rankingKey: "debtService",
        label: "公債費",
        statsDataId: "0000010156",
        cdCat01: "CCC1103",
        unit: "百万円",
        name: "公債費",
        displayOrder: 3,
        isActive: true,
      },
    ],
  },
  "fiscal-indicators": {
    subcategory: {
      id: "fiscal-indicators",
      categoryId: "administrativefinancial",
      name: "Fiscal Indicators",
      description: undefined,
      defaultRankingKey: "revenue",
    },
    rankingItems: [
      {
        rankingKey: "revenue",
        label: "歳入",
        statsDataId: "0000010112",
        cdCat01: "K1101",
        unit: "百万円",
        name: "歳入",
        displayOrder: 1,
        isActive: true,
      },
      {
        rankingKey: "expenditure",
        label: "歳出",
        statsDataId: "0000010112",
        cdCat01: "K1102",
        unit: "百万円",
        name: "歳出",
        displayOrder: 2,
        isActive: true,
      },
      {
        rankingKey: "debt",
        label: "債務",
        statsDataId: "0000010112",
        cdCat01: "K1103",
        unit: "百万円",
        name: "債務",
        displayOrder: 3,
        isActive: true,
      },
    ],
  },
  investment: {
    subcategory: {
      id: "investment",
      categoryId: "administrativefinancial",
      name: "Investment",
      description: undefined,
      defaultRankingKey: "publicInvestment",
    },
    rankingItems: [
      {
        rankingKey: "publicInvestment",
        label: "公共投資",
        statsDataId: "0000010154",
        cdCat01: "AAA1101",
        unit: "百万円",
        name: "公共投資",
        displayOrder: 1,
        isActive: true,
      },
      {
        rankingKey: "privateInvestment",
        label: "民間投資",
        statsDataId: "0000010154",
        cdCat01: "AAA1102",
        unit: "百万円",
        name: "民間投資",
        displayOrder: 2,
        isActive: true,
      },
      {
        rankingKey: "foreignInvestment",
        label: "対外投資",
        statsDataId: "0000010154",
        cdCat01: "AAA1103",
        unit: "百万円",
        name: "対外投資",
        displayOrder: 3,
        isActive: true,
      },
    ],
  },
  revenue: {
    subcategory: {
      id: "revenue",
      categoryId: "administrativefinancial",
      name: "Revenue",
      description: undefined,
      defaultRankingKey: "taxRevenue",
    },
    rankingItems: [
      {
        rankingKey: "taxRevenue",
        label: "税収",
        statsDataId: "0000010155",
        cdCat01: "BBB1101",
        unit: "百万円",
        name: "税収",
        displayOrder: 1,
        isActive: true,
      },
      {
        rankingKey: "nonTaxRevenue",
        label: "税外収入",
        statsDataId: "0000010155",
        cdCat01: "BBB1102",
        unit: "百万円",
        name: "税外収入",
        displayOrder: 2,
        isActive: true,
      },
      {
        rankingKey: "grants",
        label: "交付金",
        statsDataId: "0000010155",
        cdCat01: "BBB1103",
        unit: "百万円",
        name: "交付金",
        displayOrder: 3,
        isActive: true,
      },
    ],
  },
  "staff-assembly-election": {
    subcategory: {
      id: "staff-assembly-election",
      categoryId: "administrativefinancial",
      name: "Staff Assembly Election",
      description: undefined,
      defaultRankingKey: "staff",
    },
    rankingItems: [
      {
        rankingKey: "staff",
        label: "職員数",
        statsDataId: "0000010123",
        cdCat01: "V1101",
        unit: "人",
        name: "職員数",
        displayOrder: 1,
        isActive: true,
      },
      {
        rankingKey: "assemblyMembers",
        label: "議会議員数",
        statsDataId: "0000010123",
        cdCat01: "V1102",
        unit: "人",
        name: "議会議員数",
        displayOrder: 2,
        isActive: true,
      },
      {
        rankingKey: "electionTurnout",
        label: "投票率",
        statsDataId: "0000010123",
        cdCat01: "V1103",
        unit: "%",
        name: "投票率",
        displayOrder: 3,
        isActive: true,
      },
    ],
  },
  "tax-revenue": {
    subcategory: {
      id: "tax-revenue",
      categoryId: "administrativefinancial",
      name: "Tax Revenue",
      description: undefined,
      defaultRankingKey: "taxRevenue",
    },
    rankingItems: [
      {
        rankingKey: "taxRevenue",
        label: "税収",
        statsDataId: "0000010124",
        cdCat01: "W1101",
        unit: "百万円",
        name: "税収",
        displayOrder: 1,
        isActive: true,
      },
      {
        rankingKey: "incomeTax",
        label: "所得税",
        statsDataId: "0000010124",
        cdCat01: "W1102",
        unit: "百万円",
        name: "所得税",
        displayOrder: 2,
        isActive: true,
      },
      {
        rankingKey: "corporateTax",
        label: "法人税",
        statsDataId: "0000010124",
        cdCat01: "W1103",
        unit: "百万円",
        name: "法人税",
        displayOrder: 3,
        isActive: true,
      },
    ],
  },
  "agricultural-household": {
    subcategory: {
      id: "agricultural-household",
      categoryId: "agriculture",
      name: "Agricultural Household",
      description: undefined,
      defaultRankingKey: "agriculturalHouseholds",
    },
    rankingItems: [
      {
        rankingKey: "agriculturalHouseholds",
        label: "農業世帯数",
        statsDataId: "0000010104",
        cdCat01: "D1101",
        unit: "世帯",
        name: "農業世帯数",
        displayOrder: 1,
        isActive: true,
      },
      {
        rankingKey: "farmWorkers",
        label: "農業従事者数",
        statsDataId: "0000010104",
        cdCat01: "D1102",
        unit: "人",
        name: "農業従事者数",
        displayOrder: 2,
        isActive: true,
      },
      {
        rankingKey: "farmArea",
        label: "農地面積",
        statsDataId: "0000010104",
        cdCat01: "D1103",
        unit: "ha",
        name: "農地面積",
        displayOrder: 3,
        isActive: true,
      },
    ],
  },
  "commerce-service-industry": {
    subcategory: {
      id: "commerce-service-industry",
      categoryId: "commercial",
      name: "Commerce Service Industry",
      description: undefined,
      defaultRankingKey: "sales",
    },
    rankingItems: [
      {
        rankingKey: "sales",
        label: "売上高",
        statsDataId: "0000010105",
        cdCat01: "E1101",
        unit: "百万円",
        name: "売上高",
        displayOrder: 1,
        isActive: true,
      },
      {
        rankingKey: "establishments",
        label: "事業所数",
        statsDataId: "0000010105",
        cdCat01: "E1102",
        unit: "事業所",
        name: "事業所数",
        displayOrder: 2,
        isActive: true,
      },
      {
        rankingKey: "employees",
        label: "従業者数",
        statsDataId: "0000010105",
        cdCat01: "E1103",
        unit: "人",
        name: "従業者数",
        displayOrder: 3,
        isActive: true,
      },
    ],
  },
  "commercial-facilities": {
    subcategory: {
      id: "commercial-facilities",
      categoryId: "commercial",
      name: "Commercial Facilities",
      description: undefined,
      defaultRankingKey: "retailStores",
    },
    rankingItems: [
      {
        rankingKey: "retailStores",
        label: "小売店舗数",
        statsDataId: "0000010106",
        cdCat01: "E2101",
        unit: "店舗",
        name: "小売店舗数",
        displayOrder: 1,
        isActive: true,
      },
      {
        rankingKey: "restaurants",
        label: "飲食店数",
        statsDataId: "0000010106",
        cdCat01: "E2102",
        unit: "店舗",
        name: "飲食店数",
        displayOrder: 2,
        isActive: true,
      },
      {
        rankingKey: "hotels",
        label: "宿泊施設数",
        statsDataId: "0000010106",
        cdCat01: "E2103",
        unit: "施設",
        name: "宿泊施設数",
        displayOrder: 3,
        isActive: true,
      },
    ],
  },
  "construction-manufacturing": {
    subcategory: {
      id: "construction-manufacturing",
      categoryId: "construction",
      name: "Construction Manufacturing",
      description: undefined,
      defaultRankingKey: "constructionValue",
    },
    rankingItems: [
      {
        rankingKey: "constructionValue",
        label: "建設投資額",
        statsDataId: "0000010140",
        cdCat01: "MM1101",
        unit: "百万円",
        name: "建設投資額",
        displayOrder: 1,
        isActive: true,
      },
      {
        rankingKey: "manufacturingValue",
        label: "製造業生産額",
        statsDataId: "0000010140",
        cdCat01: "MM1102",
        unit: "百万円",
        name: "製造業生産額",
        displayOrder: 2,
        isActive: true,
      },
      {
        rankingKey: "employment",
        label: "従業者数",
        statsDataId: "0000010140",
        cdCat01: "MM1103",
        unit: "人",
        name: "従業者数",
        displayOrder: 3,
        isActive: true,
      },
    ],
  },
  "housing-facilities": {
    subcategory: {
      id: "housing-facilities",
      categoryId: "construction",
      name: "Housing Facilities",
      description: undefined,
      defaultRankingKey: "airConditioning",
    },
    rankingItems: [
      {
        rankingKey: "airConditioning",
        label: "エアコン設置率",
        statsDataId: "0000010139",
        cdCat01: "LL1101",
        unit: "%",
        name: "エアコン設置率",
        displayOrder: 1,
        isActive: true,
      },
      {
        rankingKey: "internet",
        label: "インターネット普及率",
        statsDataId: "0000010139",
        cdCat01: "LL1102",
        unit: "%",
        name: "インターネット普及率",
        displayOrder: 2,
        isActive: true,
      },
      {
        rankingKey: "solarPanel",
        label: "太陽光パネル設置率",
        statsDataId: "0000010139",
        cdCat01: "LL1103",
        unit: "%",
        name: "太陽光パネル設置率",
        displayOrder: 3,
        isActive: true,
      },
    ],
  },
  "housing-ownership": {
    subcategory: {
      id: "housing-ownership",
      categoryId: "construction",
      name: "Housing Ownership",
      description: undefined,
      defaultRankingKey: "ownedHouses",
    },
    rankingItems: [
      {
        rankingKey: "ownedHouses",
        label: "持ち家数",
        statsDataId: "0000010137",
        cdCat01: "JJ1101",
        unit: "戸",
        name: "持ち家数",
        displayOrder: 1,
        isActive: true,
      },
      {
        rankingKey: "rentalHouses",
        label: "借家数",
        statsDataId: "0000010137",
        cdCat01: "JJ1102",
        unit: "戸",
        name: "借家数",
        displayOrder: 2,
        isActive: true,
      },
      {
        rankingKey: "ownershipRate",
        label: "持ち家率",
        statsDataId: "0000010137",
        cdCat01: "JJ1103",
        unit: "%",
        name: "持ち家率",
        displayOrder: 3,
        isActive: true,
      },
    ],
  },
  "housing-statistics": {
    subcategory: {
      id: "housing-statistics",
      categoryId: "construction",
      name: "Housing Statistics",
      description: undefined,
      defaultRankingKey: "totalHousingUnits",
    },
    rankingItems: [
      {
        rankingKey: "totalHousingUnits",
        label: "総住宅数",
        statsDataId: "0000010108",
        cdCat01: "H1100",
        unit: "戸",
        name: "総住宅数",
        displayOrder: 1,
        isActive: true,
      },
      {
        rankingKey: "occupiedHousingUnits",
        label: "居住世帯あり住宅数",
        statsDataId: "0000010108",
        cdCat01: "H1101",
        unit: "戸",
        name: "居住世帯あり住宅数",
        displayOrder: 2,
        isActive: true,
      },
      {
        rankingKey: "vacantHousingUnits",
        label: "居住世帯なし住宅数",
        statsDataId: "0000010108",
        cdCat01: "H1102",
        unit: "戸",
        name: "居住世帯なし住宅数",
        displayOrder: 3,
        isActive: true,
      },
      {
        rankingKey: "temporaryResidentsOnly",
        label: "一時現在者のみ住宅数",
        statsDataId: "0000010108",
        cdCat01: "H110201",
        unit: "戸",
        name: "一時現在者のみ住宅数",
        displayOrder: 4,
        isActive: true,
      },
      {
        rankingKey: "vacantHouses",
        label: "空き家数",
        statsDataId: "0000010108",
        cdCat01: "H110202",
        unit: "戸",
        name: "空き家数",
        displayOrder: 5,
        isActive: true,
      },
      {
        rankingKey: "underConstructionHousing",
        label: "建築中住宅数",
        statsDataId: "0000010108",
        cdCat01: "H110203",
        unit: "戸",
        name: "建築中住宅数",
        displayOrder: 6,
        isActive: true,
      },
      {
        rankingKey: "exclusiveResidentialUnits",
        label: "専用住宅数",
        statsDataId: "0000010108",
        cdCat01: "H1201",
        unit: "戸",
        name: "専用住宅数",
        displayOrder: 7,
        isActive: true,
      },
      {
        rankingKey: "mixedUseHousingUnits",
        label: "店舗その他の併用住宅数",
        statsDataId: "0000010108",
        cdCat01: "H1203",
        unit: "戸",
        name: "店舗その他の併用住宅数",
        displayOrder: 8,
        isActive: true,
      },
      {
        rankingKey: "ownerOccupiedHousing",
        label: "持ち家数",
        statsDataId: "0000010108",
        cdCat01: "H1310",
        unit: "戸",
        name: "持ち家数",
        displayOrder: 9,
        isActive: true,
      },
      {
        rankingKey: "rentalHousingUnits",
        label: "借家数",
        statsDataId: "0000010108",
        cdCat01: "H1320",
        unit: "戸",
        name: "借家数",
        displayOrder: 10,
        isActive: true,
      },
      {
        rankingKey: "publicRentalHousing",
        label: "公営・都市再生機構（ＵＲ）・公社の借家数",
        statsDataId: "0000010108",
        cdCat01: "H1321",
        unit: "戸",
        name: "公営・都市再生機構（ＵＲ）・公社の借家数",
        displayOrder: 11,
        isActive: true,
      },
      {
        rankingKey: "publicHousingUnits",
        label: "公営の借家数",
        statsDataId: "0000010108",
        cdCat01: "H132101",
        unit: "戸",
        name: "公営の借家数",
        displayOrder: 12,
        isActive: true,
      },
      {
        rankingKey: "urPublicCorporationHousing",
        label: "都市再生機構（ＵＲ）・公社の借家数",
        statsDataId: "0000010108",
        cdCat01: "H132102",
        unit: "戸",
        name: "都市再生機構（ＵＲ）・公社の借家数",
        displayOrder: 13,
        isActive: true,
      },
      {
        rankingKey: "privateRentalHousing",
        label: "民営借家数",
        statsDataId: "0000010108",
        cdCat01: "H1322",
        unit: "戸",
        name: "民営借家数",
        displayOrder: 14,
        isActive: true,
      },
      {
        rankingKey: "companyHousingUnits",
        label: "給与住宅数",
        statsDataId: "0000010108",
        cdCat01: "H1323",
        unit: "戸",
        name: "給与住宅数",
        displayOrder: 15,
        isActive: true,
      },
      {
        rankingKey: "detachedHouses",
        label: "一戸建住宅数",
        statsDataId: "0000010108",
        cdCat01: "H1401",
        unit: "戸",
        name: "一戸建住宅数",
        displayOrder: 16,
        isActive: true,
      },
      {
        rankingKey: "detachedWoodenHouses",
        label: "一戸建住宅数（木造）",
        statsDataId: "0000010108",
        cdCat01: "H140101",
        unit: "戸",
        name: "一戸建住宅数（木造）",
        displayOrder: 17,
        isActive: true,
      },
      {
        rankingKey: "detachedNonWoodenHouses",
        label: "一戸建住宅数（非木造）",
        statsDataId: "0000010108",
        cdCat01: "H140102",
        unit: "戸",
        name: "一戸建住宅数（非木造）",
        displayOrder: 18,
        isActive: true,
      },
      {
        rankingKey: "rowHouses",
        label: "長屋建住宅数",
        statsDataId: "0000010108",
        cdCat01: "H1402",
        unit: "戸",
        name: "長屋建住宅数",
        displayOrder: 19,
        isActive: true,
      },
    ],
  },
  "housing-structure": {
    subcategory: {
      id: "housing-structure",
      categoryId: "construction",
      name: "Housing Structure",
      description: undefined,
      defaultRankingKey: "woodenHouses",
    },
    rankingItems: [
      {
        rankingKey: "woodenHouses",
        label: "木造住宅",
        statsDataId: "0000010138",
        cdCat01: "KK1101",
        unit: "戸",
        name: "木造住宅",
        displayOrder: 1,
        isActive: true,
      },
      {
        rankingKey: "concreteHouses",
        label: "コンクリート住宅",
        statsDataId: "0000010138",
        cdCat01: "KK1102",
        unit: "戸",
        name: "コンクリート住宅",
        displayOrder: 2,
        isActive: true,
      },
      {
        rankingKey: "steelHouses",
        label: "鉄骨住宅",
        statsDataId: "0000010138",
        cdCat01: "KK1103",
        unit: "戸",
        name: "鉄骨住宅",
        displayOrder: 3,
        isActive: true,
      },
    ],
  },
  "living-environment": {
    subcategory: {
      id: "living-environment",
      categoryId: "construction",
      name: "Living Environment",
      description: undefined,
      defaultRankingKey: "housingUnits",
    },
    rankingItems: [
      {
        rankingKey: "housingUnits",
        label: "住宅数",
        statsDataId: "0000010108",
        cdCat01: "G1101",
        unit: "戸",
        name: "住宅数",
        displayOrder: 1,
        isActive: true,
      },
      {
        rankingKey: "housingStock",
        label: "住宅ストック",
        statsDataId: "0000010108",
        cdCat01: "G1102",
        unit: "戸",
        name: "住宅ストック",
        displayOrder: 2,
        isActive: true,
      },
      {
        rankingKey: "housingStarts",
        label: "住宅着工数",
        statsDataId: "0000010108",
        cdCat01: "G1103",
        unit: "戸",
        name: "住宅着工数",
        displayOrder: 3,
        isActive: true,
      },
    ],
  },
  "welfare-facilities": {
    subcategory: {
      id: "welfare-facilities",
      categoryId: "construction",
      name: "Welfare Facilities",
      description: undefined,
      defaultRankingKey: "facilities",
    },
    rankingItems: [
      {
        rankingKey: "facilities",
        label: "福祉施設数",
        statsDataId: "0000010127",
        cdCat01: "Z1101",
        unit: "箇所",
        name: "福祉施設数",
        displayOrder: 1,
        isActive: true,
      },
      {
        rankingKey: "capacity",
        label: "収容定員",
        statsDataId: "0000010127",
        cdCat01: "Z1102",
        unit: "人",
        name: "収容定員",
        displayOrder: 2,
        isActive: true,
      },
      {
        rankingKey: "utilizationRate",
        label: "利用率",
        statsDataId: "0000010127",
        cdCat01: "Z1103",
        unit: "%",
        name: "利用率",
        displayOrder: 3,
        isActive: true,
      },
    ],
  },
  "business-activity": {
    subcategory: {
      id: "business-activity",
      categoryId: "economy",
      name: "Business Activity",
      description: undefined,
      defaultRankingKey: "businessEstablishments",
    },
    rankingItems: [
      {
        rankingKey: "businessEstablishments",
        label: "事業所数",
        statsDataId: "0000010119",
        cdCat01: "R1101",
        unit: "事業所",
        name: "事業所数",
        displayOrder: 1,
        isActive: true,
      },
      {
        rankingKey: "employees",
        label: "従業者数",
        statsDataId: "0000010119",
        cdCat01: "R1102",
        unit: "人",
        name: "従業者数",
        displayOrder: 2,
        isActive: true,
      },
      {
        rankingKey: "sales",
        label: "売上高",
        statsDataId: "0000010119",
        cdCat01: "R1103",
        unit: "百万円",
        name: "売上高",
        displayOrder: 3,
        isActive: true,
      },
    ],
  },
  "business-scale": {
    subcategory: {
      id: "business-scale",
      categoryId: "economy",
      name: "Business Scale",
      description: undefined,
      defaultRankingKey: "largeEnterprises",
    },
    rankingItems: [
      {
        rankingKey: "largeEnterprises",
        label: "大企業数",
        statsDataId: "0000010120",
        cdCat01: "S1101",
        unit: "社",
        name: "大企業数",
        displayOrder: 1,
        isActive: true,
      },
      {
        rankingKey: "mediumEnterprises",
        label: "中企業数",
        statsDataId: "0000010120",
        cdCat01: "S1102",
        unit: "社",
        name: "中企業数",
        displayOrder: 2,
        isActive: true,
      },
      {
        rankingKey: "smallEnterprises",
        label: "小企業数",
        statsDataId: "0000010120",
        cdCat01: "S1103",
        unit: "社",
        name: "小企業数",
        displayOrder: 3,
        isActive: true,
      },
    ],
  },
  "consumer-price-difference-index": {
    subcategory: {
      id: "consumer-price-difference-index",
      categoryId: "economy",
      name: "Consumer Price Difference Index",
      description: undefined,
      defaultRankingKey: "priceIndex",
    },
    rankingItems: [
      {
        rankingKey: "priceIndex",
        label: "物価指数",
        statsDataId: "0000010122",
        cdCat01: "U1101",
        unit: "指数",
        name: "物価指数",
        displayOrder: 1,
        isActive: true,
      },
      {
        rankingKey: "regionalDifference",
        label: "地域差",
        statsDataId: "0000010122",
        cdCat01: "U1102",
        unit: "指数",
        name: "地域差",
        displayOrder: 2,
        isActive: true,
      },
      {
        rankingKey: "priceLevel",
        label: "価格水準",
        statsDataId: "0000010122",
        cdCat01: "U1103",
        unit: "指数",
        name: "価格水準",
        displayOrder: 3,
        isActive: true,
      },
    ],
  },
  "gross-product-economic-indicators": {
    subcategory: {
      id: "gross-product-economic-indicators",
      categoryId: "economy",
      name: "Gross Product Economic Indicators",
      description: undefined,
      defaultRankingKey: "grossProduct",
    },
    rankingItems: [
      {
        rankingKey: "grossProduct",
        label: "総生産",
        statsDataId: "0000010121",
        cdCat01: "T1101",
        unit: "百万円",
        name: "総生産",
        displayOrder: 1,
        isActive: true,
      },
      {
        rankingKey: "economicIndicators",
        label: "経済指標",
        statsDataId: "0000010121",
        cdCat01: "T1102",
        unit: "指数",
        name: "経済指標",
        displayOrder: 2,
        isActive: true,
      },
      {
        rankingKey: "growthRate",
        label: "成長率",
        statsDataId: "0000010121",
        cdCat01: "T1103",
        unit: "%",
        name: "成長率",
        displayOrder: 3,
        isActive: true,
      },
    ],
  },
  "household-economy": {
    subcategory: {
      id: "household-economy",
      categoryId: "economy",
      name: "Household Economy",
      description: undefined,
      defaultRankingKey: "householdIncome",
    },
    rankingItems: [
      {
        rankingKey: "householdIncome",
        label: "世帯収入",
        statsDataId: "0000010118",
        cdCat01: "Q1101",
        unit: "円",
        name: "世帯収入",
        displayOrder: 1,
        isActive: true,
      },
      {
        rankingKey: "householdExpenditure",
        label: "世帯支出",
        statsDataId: "0000010118",
        cdCat01: "Q1102",
        unit: "円",
        name: "世帯支出",
        displayOrder: 2,
        isActive: true,
      },
      {
        rankingKey: "savings",
        label: "貯蓄",
        statsDataId: "0000010118",
        cdCat01: "Q1103",
        unit: "円",
        name: "貯蓄",
        displayOrder: 3,
        isActive: true,
      },
    ],
  },
  "worker-household-income": {
    subcategory: {
      id: "worker-household-income",
      categoryId: "economy",
      name: "Worker Household Income",
      description: undefined,
      defaultRankingKey: "averageIncome",
    },
    rankingItems: [
      {
        rankingKey: "averageIncome",
        label: "平均収入",
        statsDataId: "0000010107",
        cdCat01: "F1101",
        unit: "円",
        name: "平均収入",
        displayOrder: 1,
        isActive: true,
      },
      {
        rankingKey: "medianIncome",
        label: "中央値収入",
        statsDataId: "0000010107",
        cdCat01: "F1102",
        unit: "円",
        name: "中央値収入",
        displayOrder: 2,
        isActive: true,
      },
      {
        rankingKey: "disposableIncome",
        label: "可処分所得",
        statsDataId: "0000010107",
        cdCat01: "F1103",
        unit: "円",
        name: "可処分所得",
        displayOrder: 3,
        isActive: true,
      },
    ],
  },
  "childcare-early-education": {
    subcategory: {
      id: "childcare-early-education",
      categoryId: "educationsports",
      name: "Childcare Early Education",
      description: undefined,
      defaultRankingKey: "childcareFacilities",
    },
    rankingItems: [
      {
        rankingKey: "childcareFacilities",
        label: "保育施設数",
        statsDataId: "0000010128",
        cdCat01: "AA1101",
        unit: "箇所",
        name: "保育施設数",
        displayOrder: 1,
        isActive: true,
      },
      {
        rankingKey: "childcareCapacity",
        label: "保育定員",
        statsDataId: "0000010128",
        cdCat01: "AA1102",
        unit: "人",
        name: "保育定員",
        displayOrder: 2,
        isActive: true,
      },
      {
        rankingKey: "enrollmentRate",
        label: "入園率",
        statsDataId: "0000010128",
        cdCat01: "AA1103",
        unit: "%",
        name: "入園率",
        displayOrder: 3,
        isActive: true,
      },
    ],
  },
  "college-university": {
    subcategory: {
      id: "college-university",
      categoryId: "educationsports",
      name: "College University",
      description: undefined,
      defaultRankingKey: "collegeCount",
    },
    rankingItems: [
      {
        rankingKey: "collegeCount",
        label: "短期大学数",
        statsDataId: "0000010105",
        cdCat01: "E5101",
        unit: "校",
        name: "短期大学数",
        displayOrder: 1,
        isActive: true,
      },
      {
        rankingKey: "universityCount",
        label: "大学数",
        statsDataId: "0000010105",
        cdCat01: "E5201",
        unit: "校",
        name: "大学数",
        displayOrder: 2,
        isActive: true,
      },
      {
        rankingKey: "collegeStudents",
        label: "短期大学生数",
        statsDataId: "0000010105",
        cdCat01: "E5301",
        unit: "人",
        name: "短期大学生数",
        displayOrder: 3,
        isActive: true,
      },
      {
        rankingKey: "universityStudents",
        label: "大学生数",
        statsDataId: "0000010105",
        cdCat01: "E5401",
        unit: "人",
        name: "大学生数",
        displayOrder: 4,
        isActive: true,
      },
    ],
  },
  "compulsory-education": {
    subcategory: {
      id: "compulsory-education",
      categoryId: "educationsports",
      name: "Compulsory Education",
      description: undefined,
      defaultRankingKey: "elementarySchools",
    },
    rankingItems: [
      {
        rankingKey: "elementarySchools",
        label: "小学校数",
        statsDataId: "0000010129",
        cdCat01: "BB1101",
        unit: "校",
        name: "小学校数",
        displayOrder: 1,
        isActive: true,
      },
      {
        rankingKey: "juniorHighSchools",
        label: "中学校数",
        statsDataId: "0000010129",
        cdCat01: "BB1102",
        unit: "校",
        name: "中学校数",
        displayOrder: 2,
        isActive: true,
      },
      {
        rankingKey: "students",
        label: "生徒数",
        statsDataId: "0000010129",
        cdCat01: "BB1103",
        unit: "人",
        name: "生徒数",
        displayOrder: 3,
        isActive: true,
      },
    ],
  },
  "cultural-facilities": {
    subcategory: {
      id: "cultural-facilities",
      categoryId: "educationsports",
      name: "Cultural Facilities",
      description: undefined,
      defaultRankingKey: "publicHall",
    },
    rankingItems: [
      {
        rankingKey: "publicHall",
        label: "公民館数（人口100万人当たり）",
        statsDataId: "0000010207",
        cdCat01: "#G01101",
        unit: "館",
        name: "公民館数（人口100万人当たり）",
        displayOrder: 1,
        isActive: true,
      },
      {
        rankingKey: "library",
        label: "図書館数（人口100万人当たり）",
        statsDataId: "0000010207",
        cdCat01: "#G01104",
        unit: "館",
        name: "図書館数（人口100万人当たり）",
        displayOrder: 2,
        isActive: true,
      },
      {
        rankingKey: "museum",
        label: "博物館数（人口100万人当たり）",
        statsDataId: "0000010207",
        cdCat01: "#G01107",
        unit: "館",
        name: "博物館数（人口100万人当たり）",
        displayOrder: 3,
        isActive: true,
      },
      {
        rankingKey: "youthEducation",
        label: "青少年教育施設数（人口100万人当たり）",
        statsDataId: "0000010207",
        cdCat01: "#G01109",
        unit: "所",
        name: "青少年教育施設数（人口100万人当たり）",
        displayOrder: 4,
        isActive: true,
      },
      {
        rankingKey: "youthClassLecture",
        label: "青少年学級・講座数（人口100万人当たり）",
        statsDataId: "0000010207",
        cdCat01: "#G03201",
        unit: "学級・講座",
        name: "青少年学級・講座数（人口100万人当たり）",
        displayOrder: 5,
        isActive: true,
      },
      {
        rankingKey: "adultClassLecture",
        label: "成人一般学級・講座数（人口100万人当たり）",
        statsDataId: "0000010207",
        cdCat01: "#G03203",
        unit: "学級・講座",
        name: "成人一般学級・講座数（人口100万人当たり）",
        displayOrder: 6,
        isActive: true,
      },
      {
        rankingKey: "femaleClassLecture",
        label: "女性学級・講座数（女性人口100万人当たり）",
        statsDataId: "0000010207",
        cdCat01: "#G0320501",
        unit: "学級・講座",
        name: "女性学級・講座数（女性人口100万人当たり）",
        displayOrder: 7,
        isActive: true,
      },
      {
        rankingKey: "elderlyClassLecture",
        label: "高齢者学級・講座数（人口100万人当たり）",
        statsDataId: "0000010207",
        cdCat01: "#G03207",
        unit: "学級・講座",
        name: "高齢者学級・講座数（人口100万人当たり）",
        displayOrder: 8,
        isActive: true,
      },
    ],
  },
  "elementary-school": {
    subcategory: {
      id: "elementary-school",
      categoryId: "educationsports",
      name: "Elementary School",
      description: undefined,
      defaultRankingKey: "schoolCount",
    },
    rankingItems: [
      {
        rankingKey: "schoolCount",
        label: "小学校数",
        statsDataId: "0000010105",
        cdCat01: "E2101",
        unit: "校",
        name: "小学校数",
        displayOrder: 1,
        isActive: true,
      },
      {
        rankingKey: "studentCount",
        label: "小学校児童数",
        statsDataId: "0000010105",
        cdCat01: "E2201",
        unit: "人",
        name: "小学校児童数",
        displayOrder: 2,
        isActive: true,
      },
      {
        rankingKey: "perCapitaCount",
        label: "小学校数（6～11歳人口10万人当たり）",
        statsDataId: "0000010205",
        cdCat01: "#E0110101",
        unit: "校",
        name: "小学校数（6～11歳人口10万人当たり）",
        displayOrder: 3,
        isActive: true,
      },
      {
        rankingKey: "perAreaCount",
        label: "小学校数（可住地面積100km2当たり）",
        statsDataId: "0000010205",
        cdCat01: "#E0110201",
        unit: "校",
        name: "小学校数（可住地面積100km2当たり）",
        displayOrder: 4,
        isActive: true,
      },
      {
        rankingKey: "gymInstallationRate",
        label: "公立小学校屋内運動場設置率",
        statsDataId: "0000010205",
        cdCat01: "#E02601",
        unit: "％",
        name: "公立小学校屋内運動場設置率",
        displayOrder: 5,
        isActive: true,
      },
      {
        rankingKey: "poolInstallationRate",
        label: "公立小学校プール設置率",
        statsDataId: "0000010205",
        cdCat01: "#E02701",
        unit: "％",
        name: "公立小学校プール設置率",
        displayOrder: 6,
        isActive: true,
      },
    ],
  },
  "high-school": {
    subcategory: {
      id: "high-school",
      categoryId: "educationsports",
      name: "High School",
      description: undefined,
      defaultRankingKey: "schoolCount",
    },
    rankingItems: [
      {
        rankingKey: "schoolCount",
        label: "高等学校数",
        statsDataId: "0000010105",
        cdCat01: "E4101",
        unit: "校",
        name: "高等学校数",
        displayOrder: 1,
        isActive: true,
      },
      {
        rankingKey: "studentCount",
        label: "高等学校生徒数",
        statsDataId: "0000010105",
        cdCat01: "E4201",
        unit: "人",
        name: "高等学校生徒数",
        displayOrder: 2,
        isActive: true,
      },
      {
        rankingKey: "perCapitaCount",
        label: "高等学校数（15～17歳人口10万人当たり）",
        statsDataId: "0000010205",
        cdCat01: "#E0110103",
        unit: "校",
        name: "高等学校数（15～17歳人口10万人当たり）",
        displayOrder: 3,
        isActive: true,
      },
      {
        rankingKey: "perAreaCount",
        label: "高等学校数（可住地面積100km2当たり）",
        statsDataId: "0000010205",
        cdCat01: "#E0110203",
        unit: "校",
        name: "高等学校数（可住地面積100km2当たり）",
        displayOrder: 4,
        isActive: true,
      },
      {
        rankingKey: "publicRatio",
        label: "公立高等学校割合",
        statsDataId: "0000010205",
        cdCat01: "#E01303",
        unit: "%",
        name: "公立高等学校割合",
        displayOrder: 5,
        isActive: true,
      },
      {
        rankingKey: "poolInstallationRate",
        label: "公立高等学校プール設置率",
        statsDataId: "0000010205",
        cdCat01: "#E02703",
        unit: "％",
        name: "公立高等学校プール設置率",
        displayOrder: 6,
        isActive: true,
      },
    ],
  },
  "junior-high-school": {
    subcategory: {
      id: "junior-high-school",
      categoryId: "educationsports",
      name: "Junior High School",
      description: undefined,
      defaultRankingKey: "schoolCount",
    },
    rankingItems: [
      {
        rankingKey: "schoolCount",
        label: "中学校数",
        statsDataId: "0000010105",
        cdCat01: "E3101",
        unit: "校",
        name: "中学校数",
        displayOrder: 1,
        isActive: true,
      },
      {
        rankingKey: "studentCount",
        label: "中学校生徒数",
        statsDataId: "0000010105",
        cdCat01: "E3201",
        unit: "人",
        name: "中学校生徒数",
        displayOrder: 2,
        isActive: true,
      },
      {
        rankingKey: "perCapitaCount",
        label: "中学校数（12～14歳人口10万人当たり）",
        statsDataId: "0000010205",
        cdCat01: "#E0110102",
        unit: "校",
        name: "中学校数（12～14歳人口10万人当たり）",
        displayOrder: 3,
        isActive: true,
      },
      {
        rankingKey: "perAreaCount",
        label: "中学校数（可住地面積100km2当たり）",
        statsDataId: "0000010205",
        cdCat01: "#E0110202",
        unit: "校",
        name: "中学校数（可住地面積100km2当たり）",
        displayOrder: 4,
        isActive: true,
      },
      {
        rankingKey: "gymInstallationRate",
        label: "公立中学校屋内運動場設置率",
        statsDataId: "0000010205",
        cdCat01: "#E02602",
        unit: "％",
        name: "公立中学校屋内運動場設置率",
        displayOrder: 5,
        isActive: true,
      },
      {
        rankingKey: "poolInstallationRate",
        label: "公立中学校プール設置率",
        statsDataId: "0000010205",
        cdCat01: "#E02702",
        unit: "％",
        name: "公立中学校プール設置率",
        displayOrder: 6,
        isActive: true,
      },
    ],
  },
  kindergarten: {
    subcategory: {
      id: "kindergarten",
      categoryId: "educationsports",
      name: "Kindergarten",
      description: undefined,
      defaultRankingKey: "kindergartens",
    },
    rankingItems: [
      {
        rankingKey: "kindergartens",
        label: "幼稚園数",
        statsDataId: "0000010111",
        cdCat01: "J1101",
        unit: "園",
        name: "幼稚園数",
        displayOrder: 1,
        isActive: true,
      },
      {
        rankingKey: "children",
        label: "園児数",
        statsDataId: "0000010111",
        cdCat01: "J1102",
        unit: "人",
        name: "園児数",
        displayOrder: 2,
        isActive: true,
      },
      {
        rankingKey: "teachers",
        label: "教職員数",
        statsDataId: "0000010111",
        cdCat01: "J1103",
        unit: "人",
        name: "教職員数",
        displayOrder: 3,
        isActive: true,
      },
    ],
  },
  "social-activities": {
    subcategory: {
      id: "social-activities",
      categoryId: "educationsports",
      name: "Social Activities",
      description: undefined,
      defaultRankingKey: "volunteer15plus",
    },
    rankingItems: [
      {
        rankingKey: "volunteer15plus",
        label: "ボランティア活動の年間行動者率（15歳以上）",
        statsDataId: "0000010207",
        cdCat01: "#G04101",
        unit: "％",
        name: "ボランティア活動の年間行動者率（15歳以上）",
        displayOrder: 1,
        isActive: true,
      },
      {
        rankingKey: "volunteer10plus",
        label: "ボランティア活動の年間行動者率（10歳以上）",
        statsDataId: "0000010207",
        cdCat01: "#G041011",
        unit: "％",
        name: "ボランティア活動の年間行動者率（10歳以上）",
        displayOrder: 2,
        isActive: true,
      },
      {
        rankingKey: "sports10plus",
        label: "スポーツの年間行動者率（10歳以上）",
        statsDataId: "0000010207",
        cdCat01: "#G042111",
        unit: "％",
        name: "スポーツの年間行動者率（10歳以上）",
        displayOrder: 3,
        isActive: true,
      },
      {
        rankingKey: "travel15plus",
        label: "旅行・行楽の年間行動者率（15歳以上）",
        statsDataId: "0000010207",
        cdCat01: "#G04306",
        unit: "％",
        name: "旅行・行楽の年間行動者率（15歳以上）",
        displayOrder: 4,
        isActive: true,
      },
      {
        rankingKey: "travel10plus",
        label: "旅行・行楽の年間行動者率（10歳以上）",
        statsDataId: "0000010207",
        cdCat01: "#G043061",
        unit: "％",
        name: "旅行・行楽の年間行動者率（10歳以上）",
        displayOrder: 5,
        isActive: true,
      },
      {
        rankingKey: "overseasTravel",
        label: "海外旅行の年間行動者率（15歳以上）",
        statsDataId: "0000010207",
        cdCat01: "#G04307",
        unit: "％",
        name: "海外旅行の年間行動者率（15歳以上）",
        displayOrder: 6,
        isActive: true,
      },
      {
        rankingKey: "passportIssuance",
        label: "一般旅券発行件数（人口千人当たり）",
        statsDataId: "0000010207",
        cdCat01: "#G0430501",
        unit: "件",
        name: "一般旅券発行件数（人口千人当たり）",
        displayOrder: 7,
        isActive: true,
      },
    ],
  },
  "sports-facilities": {
    subcategory: {
      id: "sports-facilities",
      categoryId: "educationsports",
      name: "Sports Facilities",
      description: undefined,
      defaultRankingKey: "communitySports",
    },
    rankingItems: [
      {
        rankingKey: "communitySports",
        label: "社会体育施設数（人口100万人当たり）",
        statsDataId: "0000010207",
        cdCat01: "#G01321",
        unit: "施設",
        name: "社会体育施設数（人口100万人当たり）",
        displayOrder: 1,
        isActive: true,
      },
      {
        rankingKey: "multipurposeGround",
        label: "多目的運動広場数（公共）（人口100万人当たり）",
        statsDataId: "0000010207",
        cdCat01: "#G01323",
        unit: "施設",
        name: "多目的運動広場数（公共）（人口100万人当たり）",
        displayOrder: 2,
        isActive: true,
      },
      {
        rankingKey: "gymnasium",
        label: "体育館数（公共）（人口100万人当たり）",
        statsDataId: "0000010207",
        cdCat01: "#G01325",
        unit: "施設",
        name: "体育館数（公共）（人口100万人当たり）",
        displayOrder: 3,
        isActive: true,
      },
      {
        rankingKey: "swimmingPool",
        label: "水泳プール数（屋内，屋外）（公共）（人口100万人当たり）",
        statsDataId: "0000010207",
        cdCat01: "#G01326",
        unit: "施設",
        name: "水泳プール数（屋内，屋外）（公共）（人口100万人当たり）",
        displayOrder: 4,
        isActive: true,
      },
      {
        rankingKey: "sportsParticipation",
        label: "スポーツの年間行動者率（10歳以上）",
        statsDataId: "0000010207",
        cdCat01: "#G042111",
        unit: "%",
        name: "スポーツの年間行動者率（10歳以上）",
        displayOrder: 5,
        isActive: true,
      },
    ],
  },
  "industrial-water": {
    subcategory: {
      id: "industrial-water",
      categoryId: "energy",
      name: "Industrial Water",
      description: undefined,
      defaultRankingKey: "waterUsage",
    },
    rankingItems: [
      {
        rankingKey: "waterUsage",
        label: "工業用水使用量",
        statsDataId: "0000010142",
        cdCat01: "OO1101",
        unit: "千m³",
        name: "工業用水使用量",
        displayOrder: 1,
        isActive: true,
      },
      {
        rankingKey: "waterSupply",
        label: "工業用水供給量",
        statsDataId: "0000010142",
        cdCat01: "OO1102",
        unit: "千m³",
        name: "工業用水供給量",
        displayOrder: 2,
        isActive: true,
      },
      {
        rankingKey: "recyclingRate",
        label: "水リサイクル率",
        statsDataId: "0000010142",
        cdCat01: "OO1103",
        unit: "%",
        name: "水リサイクル率",
        displayOrder: 3,
        isActive: true,
      },
    ],
  },
  "infrastructure-energy": {
    subcategory: {
      id: "infrastructure-energy",
      categoryId: "energy",
      name: "Infrastructure Energy",
      description: undefined,
      defaultRankingKey: "electricity",
    },
    rankingItems: [
      {
        rankingKey: "electricity",
        label: "電力供給量",
        statsDataId: "0000010143",
        cdCat01: "PP1101",
        unit: "GWh",
        name: "電力供給量",
        displayOrder: 1,
        isActive: true,
      },
      {
        rankingKey: "gas",
        label: "ガス供給量",
        statsDataId: "0000010143",
        cdCat01: "PP1102",
        unit: "千m³",
        name: "ガス供給量",
        displayOrder: 2,
        isActive: true,
      },
      {
        rankingKey: "renewable",
        label: "再生可能エネルギー",
        statsDataId: "0000010143",
        cdCat01: "PP1103",
        unit: "GWh",
        name: "再生可能エネルギー",
        displayOrder: 3,
        isActive: true,
      },
    ],
  },
  "waste-management": {
    subcategory: {
      id: "waste-management",
      categoryId: "energy",
      name: "Waste Management",
      description: undefined,
      defaultRankingKey: "wasteAmount",
    },
    rankingItems: [
      {
        rankingKey: "wasteAmount",
        label: "廃棄物量",
        statsDataId: "0000010126",
        cdCat01: "Y1101",
        unit: "トン",
        name: "廃棄物量",
        displayOrder: 1,
        isActive: true,
      },
      {
        rankingKey: "recyclingRate",
        label: "リサイクル率",
        statsDataId: "0000010126",
        cdCat01: "Y1102",
        unit: "%",
        name: "リサイクル率",
        displayOrder: 2,
        isActive: true,
      },
      {
        rankingKey: "incinerationRate",
        label: "焼却率",
        statsDataId: "0000010126",
        cdCat01: "Y1103",
        unit: "%",
        name: "焼却率",
        displayOrder: 3,
        isActive: true,
      },
    ],
  },
  "water-supply-sewerage": {
    subcategory: {
      id: "water-supply-sewerage",
      categoryId: "energy",
      name: "Water Supply Sewerage",
      description: undefined,
      defaultRankingKey: "waterSupplyRate",
    },
    rankingItems: [
      {
        rankingKey: "waterSupplyRate",
        label: "上水道普及率",
        statsDataId: "0000010109",
        cdCat01: "H1101",
        unit: "%",
        name: "上水道普及率",
        displayOrder: 1,
        isActive: true,
      },
      {
        rankingKey: "sewerageRate",
        label: "下水道普及率",
        statsDataId: "0000010109",
        cdCat01: "H1102",
        unit: "%",
        name: "下水道普及率",
        displayOrder: 2,
        isActive: true,
      },
      {
        rankingKey: "waterUsage",
        label: "水使用量",
        statsDataId: "0000010109",
        cdCat01: "H1103",
        unit: "L/人・日",
        name: "水使用量",
        displayOrder: 3,
        isActive: true,
      },
    ],
  },
  roads: {
    subcategory: {
      id: "roads",
      categoryId: "infrastructure",
      name: "Roads",
      description: undefined,
      defaultRankingKey: "roadLength",
    },
    rankingItems: [
      {
        rankingKey: "roadLength",
        label: "道路延長",
        statsDataId: "0000010116",
        cdCat01: "O1101",
        unit: "km",
        name: "道路延長",
        displayOrder: 1,
        isActive: true,
      },
      {
        rankingKey: "bridges",
        label: "橋梁数",
        statsDataId: "0000010116",
        cdCat01: "O1102",
        unit: "橋",
        name: "橋梁数",
        displayOrder: 2,
        isActive: true,
      },
      {
        rankingKey: "tunnels",
        label: "トンネル数",
        statsDataId: "0000010116",
        cdCat01: "O1103",
        unit: "本",
        name: "トンネル数",
        displayOrder: 3,
        isActive: true,
      },
    ],
  },
  "foreign-population": {
    subcategory: {
      id: "foreign-population",
      categoryId: "international",
      name: "Foreign Population",
      description: undefined,
      defaultRankingKey: "foreignResidents",
    },
    rankingItems: [
      {
        rankingKey: "foreignResidents",
        label: "外国人住民数",
        statsDataId: "0000010115",
        cdCat01: "N1101",
        unit: "人",
        name: "外国人住民数",
        displayOrder: 1,
        isActive: true,
      },
      {
        rankingKey: "naturalizations",
        label: "帰化者数",
        statsDataId: "0000010115",
        cdCat01: "N1102",
        unit: "人",
        name: "帰化者数",
        displayOrder: 2,
        isActive: true,
      },
      {
        rankingKey: "internationalStudents",
        label: "留学生数",
        statsDataId: "0000010115",
        cdCat01: "N1103",
        unit: "人",
        name: "留学生数",
        displayOrder: 3,
        isActive: true,
      },
    ],
  },
  "commuting-employment": {
    subcategory: {
      id: "commuting-employment",
      categoryId: "laborwage",
      name: "Commuting Employment",
      description: undefined,
      defaultRankingKey: "commuters",
    },
    rankingItems: [
      {
        rankingKey: "commuters",
        label: "通勤者数",
        statsDataId: "0000010132",
        cdCat01: "EE1101",
        unit: "人",
        name: "通勤者数",
        displayOrder: 1,
        isActive: true,
      },
      {
        rankingKey: "commutingTime",
        label: "通勤時間",
        statsDataId: "0000010132",
        cdCat01: "EE1102",
        unit: "分",
        name: "通勤時間",
        displayOrder: 2,
        isActive: true,
      },
      {
        rankingKey: "employmentRate",
        label: "就職率",
        statsDataId: "0000010132",
        cdCat01: "EE1103",
        unit: "%",
        name: "就職率",
        displayOrder: 3,
        isActive: true,
      },
    ],
  },
  "employment-type": {
    subcategory: {
      id: "employment-type",
      categoryId: "laborwage",
      name: "Employment Type",
      description: undefined,
      defaultRankingKey: "regular",
    },
    rankingItems: [
      {
        rankingKey: "regular",
        label: "正規雇用",
        statsDataId: "0000010136",
        cdCat01: "II1101",
        unit: "人",
        name: "正規雇用",
        displayOrder: 1,
        isActive: true,
      },
      {
        rankingKey: "nonRegular",
        label: "非正規雇用",
        statsDataId: "0000010136",
        cdCat01: "II1102",
        unit: "人",
        name: "非正規雇用",
        displayOrder: 2,
        isActive: true,
      },
      {
        rankingKey: "selfEmployed",
        label: "自営業",
        statsDataId: "0000010136",
        cdCat01: "II1103",
        unit: "人",
        name: "自営業",
        displayOrder: 3,
        isActive: true,
      },
    ],
  },
  "industrial-structure": {
    subcategory: {
      id: "industrial-structure",
      categoryId: "laborwage",
      name: "Industrial Structure",
      description: undefined,
      defaultRankingKey: "primaryIndustry",
    },
    rankingItems: [
      {
        rankingKey: "primaryIndustry",
        label: "第1次産業",
        statsDataId: "0000010131",
        cdCat01: "DD1101",
        unit: "人",
        name: "第1次産業",
        displayOrder: 1,
        isActive: true,
      },
      {
        rankingKey: "secondaryIndustry",
        label: "第2次産業",
        statsDataId: "0000010131",
        cdCat01: "DD1102",
        unit: "人",
        name: "第2次産業",
        displayOrder: 2,
        isActive: true,
      },
      {
        rankingKey: "tertiaryIndustry",
        label: "第3次産業",
        statsDataId: "0000010131",
        cdCat01: "DD1103",
        unit: "人",
        name: "第3次産業",
        displayOrder: 3,
        isActive: true,
      },
    ],
  },
  "industry-occupation": {
    subcategory: {
      id: "industry-occupation",
      categoryId: "laborwage",
      name: "Industry Occupation",
      description: undefined,
      defaultRankingKey: "manufacturing",
    },
    rankingItems: [
      {
        rankingKey: "manufacturing",
        label: "製造業",
        statsDataId: "0000010135",
        cdCat01: "HH1101",
        unit: "人",
        name: "製造業",
        displayOrder: 1,
        isActive: true,
      },
      {
        rankingKey: "services",
        label: "サービス業",
        statsDataId: "0000010135",
        cdCat01: "HH1102",
        unit: "人",
        name: "サービス業",
        displayOrder: 2,
        isActive: true,
      },
      {
        rankingKey: "agriculture",
        label: "農業",
        statsDataId: "0000010135",
        cdCat01: "HH1103",
        unit: "人",
        name: "農業",
        displayOrder: 3,
        isActive: true,
      },
    ],
  },
  "job-seeking-placement": {
    subcategory: {
      id: "job-seeking-placement",
      categoryId: "laborwage",
      name: "Job Seeking Placement",
      description: undefined,
      defaultRankingKey: "jobSeekers",
    },
    rankingItems: [
      {
        rankingKey: "jobSeekers",
        label: "求職者数",
        statsDataId: "0000010134",
        cdCat01: "GG1101",
        unit: "人",
        name: "求職者数",
        displayOrder: 1,
        isActive: true,
      },
      {
        rankingKey: "jobOpenings",
        label: "求人数",
        statsDataId: "0000010134",
        cdCat01: "GG1102",
        unit: "件",
        name: "求人数",
        displayOrder: 2,
        isActive: true,
      },
      {
        rankingKey: "placementRate",
        label: "就職率",
        statsDataId: "0000010134",
        cdCat01: "GG1103",
        unit: "%",
        name: "就職率",
        displayOrder: 3,
        isActive: true,
      },
    ],
  },
  "labor-disputes": {
    subcategory: {
      id: "labor-disputes",
      categoryId: "laborwage",
      name: "Labor Disputes",
      description: undefined,
      defaultRankingKey: "disputes",
    },
    rankingItems: [
      {
        rankingKey: "disputes",
        label: "労働争議件数",
        statsDataId: "0000010133",
        cdCat01: "FF1101",
        unit: "件",
        name: "労働争議件数",
        displayOrder: 1,
        isActive: true,
      },
      {
        rankingKey: "participants",
        label: "参加者数",
        statsDataId: "0000010133",
        cdCat01: "FF1102",
        unit: "人",
        name: "参加者数",
        displayOrder: 2,
        isActive: true,
      },
      {
        rankingKey: "lostDays",
        label: "労働損失日数",
        statsDataId: "0000010133",
        cdCat01: "FF1103",
        unit: "日",
        name: "労働損失日数",
        displayOrder: 3,
        isActive: true,
      },
    ],
  },
  "labor-force-structure": {
    subcategory: {
      id: "labor-force-structure",
      categoryId: "laborwage",
      name: "Labor Force Structure",
      description: undefined,
      defaultRankingKey: "laborForce",
    },
    rankingItems: [
      {
        rankingKey: "laborForce",
        label: "労働力人口",
        statsDataId: "0000010130",
        cdCat01: "CC1101",
        unit: "人",
        name: "労働力人口",
        displayOrder: 1,
        isActive: true,
      },
      {
        rankingKey: "employmentRate",
        label: "就業率",
        statsDataId: "0000010130",
        cdCat01: "CC1102",
        unit: "%",
        name: "就業率",
        displayOrder: 2,
        isActive: true,
      },
      {
        rankingKey: "unemploymentRate",
        label: "失業率",
        statsDataId: "0000010130",
        cdCat01: "CC1103",
        unit: "%",
        name: "失業率",
        displayOrder: 3,
        isActive: true,
      },
    ],
  },
  "wages-working-conditions": {
    subcategory: {
      id: "wages-working-conditions",
      categoryId: "laborwage",
      name: "Wages Working Conditions",
      description: undefined,
      defaultRankingKey: "averageWage",
    },
    rankingItems: [
      {
        rankingKey: "averageWage",
        label: "平均賃金",
        statsDataId: "0000010117",
        cdCat01: "P1101",
        unit: "円",
        name: "平均賃金",
        displayOrder: 1,
        isActive: true,
      },
      {
        rankingKey: "minimumWage",
        label: "最低賃金",
        statsDataId: "0000010117",
        cdCat01: "P1102",
        unit: "円",
        name: "最低賃金",
        displayOrder: 2,
        isActive: true,
      },
      {
        rankingKey: "workingHours",
        label: "労働時間",
        statsDataId: "0000010117",
        cdCat01: "P1103",
        unit: "時間",
        name: "労働時間",
        displayOrder: 3,
        isActive: true,
      },
    ],
  },
  "natural-environment": {
    subcategory: {
      id: "natural-environment",
      categoryId: "landweather",
      name: "Natural Environment",
      description: undefined,
      defaultRankingKey: "nationalParks",
    },
    rankingItems: [
      {
        rankingKey: "nationalParks",
        label: "国立公園",
        statsDataId: "0000010201",
        cdCat01: "#A01301",
        unit: "箇所",
        name: "国立公園",
        displayOrder: 1,
        isActive: true,
      },
      {
        rankingKey: "quasiNationalParks",
        label: "国定公園",
        statsDataId: "0000010201",
        cdCat01: "#A01302",
        unit: "箇所",
        name: "国定公園",
        displayOrder: 2,
        isActive: true,
      },
      {
        rankingKey: "prefecturalParks",
        label: "都道府県立自然公園",
        statsDataId: "0000010201",
        cdCat01: "#A01303",
        unit: "箇所",
        name: "都道府県立自然公園",
        displayOrder: 3,
        isActive: true,
      },
      {
        rankingKey: "naturalMonuments",
        label: "天然記念物",
        statsDataId: "0000010201",
        cdCat01: "#A01304",
        unit: "箇所",
        name: "天然記念物",
        displayOrder: 4,
        isActive: true,
      },
      {
        rankingKey: "nationalParksArea",
        label: "国立公園面積",
        statsDataId: "0000010201",
        cdCat01: "#A01305",
        unit: "ha",
        name: "国立公園面積",
        displayOrder: 5,
        isActive: true,
      },
      {
        rankingKey: "quasiNationalParksArea",
        label: "国定公園面積",
        statsDataId: "0000010201",
        cdCat01: "#A01306",
        unit: "ha",
        name: "国定公園面積",
        displayOrder: 6,
        isActive: true,
      },
      {
        rankingKey: "prefecturalParksArea",
        label: "都道府県立自然公園面積",
        statsDataId: "0000010201",
        cdCat01: "#A01307",
        unit: "ha",
        name: "都道府県立自然公園面積",
        displayOrder: 7,
        isActive: true,
      },
    ],
  },
  "weather-climate": {
    subcategory: {
      id: "weather-climate",
      categoryId: "landweather",
      name: "Weather Climate",
      description: undefined,
      defaultRankingKey: "avgTemperature",
    },
    rankingItems: [
      {
        rankingKey: "avgTemperature",
        label: "年平均気温",
        statsDataId: "0000010202",
        cdCat01: "#B02101",
        unit: "℃",
        name: "年平均気温",
        displayOrder: 1,
        isActive: true,
      },
      {
        rankingKey: "maxTemperature",
        label: "最高気温（日最高気温の月平均の最高値）",
        statsDataId: "0000010202",
        cdCat01: "#B02102",
        unit: "℃",
        name: "最高気温（日最高気温の月平均の最高値）",
        displayOrder: 2,
        isActive: true,
      },
      {
        rankingKey: "minTemperature",
        label: "最低気温（日最低気温の月平均の最低値）",
        statsDataId: "0000010202",
        cdCat01: "#B02103",
        unit: "℃",
        name: "最低気温（日最低気温の月平均の最低値）",
        displayOrder: 3,
        isActive: true,
      },
      {
        rankingKey: "humidity",
        label: "年平均相対湿度",
        statsDataId: "0000010202",
        cdCat01: "#B02201",
        unit: "%",
        name: "年平均相対湿度",
        displayOrder: 4,
        isActive: true,
      },
      {
        rankingKey: "clearDays",
        label: "快晴日数（年間）",
        statsDataId: "0000010202",
        cdCat01: "#B02301",
        unit: "日",
        name: "快晴日数（年間）",
        displayOrder: 5,
        isActive: true,
      },
      {
        rankingKey: "precipitationDays",
        label: "降水日数（年間）",
        statsDataId: "0000010202",
        cdCat01: "#B02303",
        unit: "日",
        name: "降水日数（年間）",
        displayOrder: 6,
        isActive: true,
      },
      {
        rankingKey: "snowDays",
        label: "雪日数（年間）",
        statsDataId: "0000010202",
        cdCat01: "#B02304",
        unit: "日",
        name: "雪日数（年間）",
        displayOrder: 7,
        isActive: true,
      },
      {
        rankingKey: "sunshineDuration",
        label: "日照時間（年間）",
        statsDataId: "0000010202",
        cdCat01: "#B02401",
        unit: "時間",
        name: "日照時間（年間）",
        displayOrder: 8,
        isActive: true,
      },
      {
        rankingKey: "precipitation",
        label: "降水量（年間）",
        statsDataId: "0000010202",
        cdCat01: "#B02402",
        unit: "mm",
        name: "降水量（年間）",
        displayOrder: 9,
        isActive: true,
      },
    ],
  },
  manufacturing: {
    subcategory: {
      id: "manufacturing",
      categoryId: "miningindustry",
      name: "Manufacturing",
      description: undefined,
      defaultRankingKey: "valueAdded",
    },
    rankingItems: [
      {
        rankingKey: "valueAdded",
        label: "製造業付加価値額",
        statsDataId: "0000010103",
        cdCat01: "C3402",
        unit: "百万円",
        name: "製造業付加価値額",
        displayOrder: 1,
        isActive: true,
      },
      {
        rankingKey: "establishments",
        label: "製造業事業所数",
        statsDataId: "0000010103",
        cdCat01: "C3403",
        unit: "事業所",
        name: "製造業事業所数",
        displayOrder: 2,
        isActive: true,
      },
    ],
  },
  "basic-population": {
    subcategory: {
      id: "basic-population",
      categoryId: "population",
      name: "Basic Population",
      description: undefined,
      defaultRankingKey: "totalPopulation",
    },
    rankingItems: [
      {
        rankingKey: "totalPopulation",
        label: "総人口",
        statsDataId: "0000010101",
        cdCat01: "A1101",
        unit: "人",
        name: "総人口",
        displayOrder: 1,
        isActive: true,
      },
      {
        rankingKey: "populationDensity",
        label: "人口密度",
        statsDataId: "0000010201",
        cdCat01: "#A01201",
        unit: "人/km²",
        name: "人口密度",
        displayOrder: 2,
        isActive: true,
      },
      {
        rankingKey: "didAreaRatio",
        label: "人口集中地区面積比率",
        statsDataId: "0000010201",
        cdCat01: "#A01402",
        unit: "%",
        name: "人口集中地区面積比率",
        displayOrder: 3,
        isActive: true,
      },
    ],
  },
  "birth-death": {
    subcategory: {
      id: "birth-death",
      categoryId: "population",
      name: "Birth Death",
      description: undefined,
      defaultRankingKey: "births",
    },
    rankingItems: [
      {
        rankingKey: "births",
        label: "出生数",
        statsDataId: "0000010101",
        cdCat01: "A4101",
        unit: "人",
        name: "出生数",
        displayOrder: 1,
        isActive: true,
      },
      {
        rankingKey: "deaths",
        label: "死亡数",
        statsDataId: "0000010101",
        cdCat01: "A4102",
        unit: "人",
        name: "死亡数",
        displayOrder: 2,
        isActive: true,
      },
      {
        rankingKey: "naturalIncrease",
        label: "自然増減数",
        statsDataId: "0000010101",
        cdCat01: "A4103",
        unit: "人",
        name: "自然増減数",
        displayOrder: 3,
        isActive: true,
      },
      {
        rankingKey: "birthRate",
        label: "出生率",
        statsDataId: "0000010101",
        cdCat01: "A4104",
        unit: "‰",
        name: "出生率",
        displayOrder: 4,
        isActive: true,
      },
      {
        rankingKey: "deathRate",
        label: "死亡率",
        statsDataId: "0000010101",
        cdCat01: "A4105",
        unit: "‰",
        name: "死亡率",
        displayOrder: 5,
        isActive: true,
      },
    ],
  },
  households: {
    subcategory: {
      id: "households",
      categoryId: "population",
      name: "Households",
      description: undefined,
      defaultRankingKey: "totalHouseholds",
    },
    rankingItems: [
      {
        rankingKey: "totalHouseholds",
        label: "総世帯数",
        statsDataId: "0000010101",
        cdCat01: "A3101",
        unit: "世帯",
        name: "総世帯数",
        displayOrder: 1,
        isActive: true,
      },
      {
        rankingKey: "averageHouseholdSize",
        label: "平均世帯人員",
        statsDataId: "0000010101",
        cdCat01: "A3102",
        unit: "人",
        name: "平均世帯人員",
        displayOrder: 2,
        isActive: true,
      },
      {
        rankingKey: "nuclearFamilyHouseholds",
        label: "核家族世帯数",
        statsDataId: "0000010101",
        cdCat01: "A3103",
        unit: "世帯",
        name: "核家族世帯数",
        displayOrder: 3,
        isActive: true,
      },
      {
        rankingKey: "singlePersonHouseholds",
        label: "単独世帯数",
        statsDataId: "0000010101",
        cdCat01: "A3104",
        unit: "世帯",
        name: "単独世帯数",
        displayOrder: 4,
        isActive: true,
      },
    ],
  },
  marriage: {
    subcategory: {
      id: "marriage",
      categoryId: "population",
      name: "Marriage",
      description: undefined,
      defaultRankingKey: "marriages",
    },
    rankingItems: [
      {
        rankingKey: "marriages",
        label: "婚姻件数",
        statsDataId: "0000010101",
        cdCat01: "A2101",
        unit: "件",
        name: "婚姻件数",
        displayOrder: 1,
        isActive: true,
      },
      {
        rankingKey: "divorces",
        label: "離婚件数",
        statsDataId: "0000010101",
        cdCat01: "A2102",
        unit: "件",
        name: "離婚件数",
        displayOrder: 2,
        isActive: true,
      },
      {
        rankingKey: "marriageRate",
        label: "婚姻率",
        statsDataId: "0000010101",
        cdCat01: "A2103",
        unit: "‰",
        name: "婚姻率",
        displayOrder: 3,
        isActive: true,
      },
      {
        rankingKey: "divorceRate",
        label: "離婚率",
        statsDataId: "0000010101",
        cdCat01: "A2104",
        unit: "‰",
        name: "離婚率",
        displayOrder: 4,
        isActive: true,
      },
    ],
  },
  "population-composition": {
    subcategory: {
      id: "population-composition",
      categoryId: "population",
      name: "Population Composition",
      description: undefined,
      defaultRankingKey: "youngPopulation",
    },
    rankingItems: [
      {
        rankingKey: "youngPopulation",
        label: "15歳未満人口割合",
        statsDataId: "0000010101",
        cdCat01: "A1301",
        unit: "%",
        name: "15歳未満人口割合",
        displayOrder: 1,
        isActive: true,
      },
      {
        rankingKey: "workingAgePopulation",
        label: "15-64歳人口割合",
        statsDataId: "0000010101",
        cdCat01: "A1302",
        unit: "%",
        name: "15-64歳人口割合",
        displayOrder: 2,
        isActive: true,
      },
      {
        rankingKey: "elderlyPopulation",
        label: "65歳以上人口割合",
        statsDataId: "0000010101",
        cdCat01: "A1303",
        unit: "%",
        name: "65歳以上人口割合",
        displayOrder: 3,
        isActive: true,
      },
      {
        rankingKey: "sexRatio",
        label: "人口性比（総数）",
        statsDataId: "0000010201",
        cdCat01: "#A02101",
        unit: "-",
        name: "人口性比（総数）",
        displayOrder: 4,
        isActive: true,
      },
    ],
  },
  "population-movement": {
    subcategory: {
      id: "population-movement",
      categoryId: "population",
      name: "Population Movement",
      description: undefined,
      defaultRankingKey: "moversIn",
    },
    rankingItems: [
      {
        rankingKey: "moversIn",
        label: "転入者数",
        statsDataId: "0000010101",
        cdCat01: "A5103",
        unit: "人",
        name: "転入者数",
        displayOrder: 1,
        isActive: true,
      },
      {
        rankingKey: "moversOut",
        label: "転出者数",
        statsDataId: "0000010101",
        cdCat01: "A5104",
        unit: "人",
        name: "転出者数",
        displayOrder: 2,
        isActive: true,
      },
      {
        rankingKey: "socialIncrease",
        label: "社会増減数",
        statsDataId: "0000010101",
        cdCat01: "A5302",
        unit: "人",
        name: "社会増減数",
        displayOrder: 3,
        isActive: true,
      },
      {
        rankingKey: "dayTimePopulationRatio",
        label: "昼夜間人口比率",
        statsDataId: "0000010101",
        cdCat01: "A6108",
        unit: "%",
        name: "昼夜間人口比率",
        displayOrder: 4,
        isActive: true,
      },
      {
        rankingKey: "dayTimePopulation",
        label: "昼間人口",
        statsDataId: "0000010101",
        cdCat01: "A6107",
        unit: "人",
        name: "昼間人口",
        displayOrder: 5,
        isActive: true,
      },
      {
        rankingKey: "inflowPopulationInPref",
        label: "流入人口（県内他市区町村）",
        statsDataId: "0000010101",
        cdCat01: "A6105",
        unit: "人",
        name: "流入人口（県内他市区町村）",
        displayOrder: 6,
        isActive: true,
      },
      {
        rankingKey: "inflowPopulationOtherPref",
        label: "流入人口（他県）",
        statsDataId: "0000010101",
        cdCat01: "A6106",
        unit: "人",
        name: "流入人口（他県）",
        displayOrder: 7,
        isActive: true,
      },
      {
        rankingKey: "outflowPopulationInPref",
        label: "流出人口（県内他市区町村）",
        statsDataId: "0000010101",
        cdCat01: "A6103",
        unit: "人",
        name: "流出人口（県内他市区町村）",
        displayOrder: 8,
        isActive: true,
      },
      {
        rankingKey: "outflowPopulationOtherPref",
        label: "流出人口（他県）",
        statsDataId: "0000010101",
        cdCat01: "A6104",
        unit: "人",
        name: "流出人口（他県）",
        displayOrder: 9,
        isActive: true,
      },
    ],
  },
  "fire-emergency": {
    subcategory: {
      id: "fire-emergency",
      categoryId: "safetyenvironment",
      name: "Fire Emergency",
      description: undefined,
      defaultRankingKey: "fireStations",
    },
    rankingItems: [
      {
        rankingKey: "fireStations",
        label: "消防署数",
        statsDataId: "0000010113",
        cdCat01: "L1101",
        unit: "署",
        name: "消防署数",
        displayOrder: 1,
        isActive: true,
      },
      {
        rankingKey: "firefighters",
        label: "消防職員数",
        statsDataId: "0000010113",
        cdCat01: "L1102",
        unit: "人",
        name: "消防職員数",
        displayOrder: 2,
        isActive: true,
      },
      {
        rankingKey: "fireTrucks",
        label: "消防車両数",
        statsDataId: "0000010113",
        cdCat01: "L1103",
        unit: "台",
        name: "消防車両数",
        displayOrder: 3,
        isActive: true,
      },
    ],
  },
  "fire-insurance": {
    subcategory: {
      id: "fire-insurance",
      categoryId: "safetyenvironment",
      name: "Fire Insurance",
      description: undefined,
      defaultRankingKey: "fireIncidents",
    },
    rankingItems: [
      {
        rankingKey: "fireIncidents",
        label: "火災件数",
        statsDataId: "0000010157",
        cdCat01: "DDD1101",
        unit: "件",
        name: "火災件数",
        displayOrder: 1,
        isActive: true,
      },
      {
        rankingKey: "fireDamage",
        label: "火災損害額",
        statsDataId: "0000010157",
        cdCat01: "DDD1102",
        unit: "千円",
        name: "火災損害額",
        displayOrder: 2,
        isActive: true,
      },
      {
        rankingKey: "insuranceClaims",
        label: "保険金支払額",
        statsDataId: "0000010157",
        cdCat01: "DDD1103",
        unit: "千円",
        name: "保険金支払額",
        displayOrder: 3,
        isActive: true,
      },
    ],
  },
  "police-crime": {
    subcategory: {
      id: "police-crime",
      categoryId: "safetyenvironment",
      name: "Police Crime",
      description: undefined,
      defaultRankingKey: "crimes",
    },
    rankingItems: [
      {
        rankingKey: "crimes",
        label: "犯罪件数",
        statsDataId: "0000010158",
        cdCat01: "EEE1101",
        unit: "件",
        name: "犯罪件数",
        displayOrder: 1,
        isActive: true,
      },
      {
        rankingKey: "arrests",
        label: "検挙件数",
        statsDataId: "0000010158",
        cdCat01: "EEE1102",
        unit: "件",
        name: "検挙件数",
        displayOrder: 2,
        isActive: true,
      },
      {
        rankingKey: "policeOfficers",
        label: "警察官数",
        statsDataId: "0000010158",
        cdCat01: "EEE1103",
        unit: "人",
        name: "警察官数",
        displayOrder: 3,
        isActive: true,
      },
    ],
  },
  "pollution-environment": {
    subcategory: {
      id: "pollution-environment",
      categoryId: "safetyenvironment",
      name: "Pollution Environment",
      description: undefined,
      defaultRankingKey: "airPollution",
    },
    rankingItems: [
      {
        rankingKey: "airPollution",
        label: "大気汚染",
        statsDataId: "0000010159",
        cdCat01: "FFF1101",
        unit: "μg/m³",
        name: "大気汚染",
        displayOrder: 1,
        isActive: true,
      },
      {
        rankingKey: "waterPollution",
        label: "水質汚濁",
        statsDataId: "0000010159",
        cdCat01: "FFF1102",
        unit: "mg/L",
        name: "水質汚濁",
        displayOrder: 2,
        isActive: true,
      },
      {
        rankingKey: "wasteDisposal",
        label: "廃棄物処理",
        statsDataId: "0000010159",
        cdCat01: "FFF1103",
        unit: "t",
        name: "廃棄物処理",
        displayOrder: 3,
        isActive: true,
      },
    ],
  },
  "traffic-accidents": {
    subcategory: {
      id: "traffic-accidents",
      categoryId: "safetyenvironment",
      name: "Traffic Accidents",
      description: undefined,
      defaultRankingKey: "accidents",
    },
    rankingItems: [
      {
        rankingKey: "accidents",
        label: "交通事故件数",
        statsDataId: "0000010125",
        cdCat01: "X1101",
        unit: "件",
        name: "交通事故件数",
        displayOrder: 1,
        isActive: true,
      },
      {
        rankingKey: "fatalities",
        label: "死者数",
        statsDataId: "0000010125",
        cdCat01: "X1102",
        unit: "人",
        name: "死者数",
        displayOrder: 2,
        isActive: true,
      },
      {
        rankingKey: "injuries",
        label: "負傷者数",
        statsDataId: "0000010125",
        cdCat01: "X1103",
        unit: "人",
        name: "負傷者数",
        displayOrder: 3,
        isActive: true,
      },
    ],
  },
  card: {
    subcategory: {
      id: "card",
      categoryId: "socialsecurity",
      name: "Card",
      description: undefined,
      defaultRankingKey: "medicalFacilities",
    },
    rankingItems: [
      {
        rankingKey: "medicalFacilities",
        label: "医療施設数",
        statsDataId: "0000010114",
        cdCat01: "M1101",
        unit: "施設",
        name: "医療施設数",
        displayOrder: 1,
        isActive: true,
      },
      {
        rankingKey: "doctors",
        label: "医師数",
        statsDataId: "0000010114",
        cdCat01: "M1102",
        unit: "人",
        name: "医師数",
        displayOrder: 2,
        isActive: true,
      },
      {
        rankingKey: "nurses",
        label: "看護師数",
        statsDataId: "0000010114",
        cdCat01: "M1103",
        unit: "人",
        name: "看護師数",
        displayOrder: 3,
        isActive: true,
      },
    ],
  },
  "death-statistics": {
    subcategory: {
      id: "death-statistics",
      categoryId: "socialsecurity",
      name: "Death Statistics",
      description: undefined,
      defaultRankingKey: "deaths",
    },
    rankingItems: [
      {
        rankingKey: "deaths",
        label: "死亡数",
        statsDataId: "0000010151",
        cdCat01: "XX1101",
        unit: "人",
        name: "死亡数",
        displayOrder: 1,
        isActive: true,
      },
      {
        rankingKey: "deathRate",
        label: "死亡率",
        statsDataId: "0000010151",
        cdCat01: "XX1102",
        unit: "‰",
        name: "死亡率",
        displayOrder: 2,
        isActive: true,
      },
      {
        rankingKey: "lifeExpectancy",
        label: "平均寿命",
        statsDataId: "0000010151",
        cdCat01: "XX1103",
        unit: "歳",
        name: "平均寿命",
        displayOrder: 3,
        isActive: true,
      },
    ],
  },
  "health-care": {
    subcategory: {
      id: "health-care",
      categoryId: "socialsecurity",
      name: "Health Care",
      description: undefined,
      defaultRankingKey: "tuberculosisCheckup",
    },
    rankingItems: [
      {
        rankingKey: "tuberculosisCheckup",
        label: "健康診断受診者数（保健所及び市区町村実施分）（結核）",
        statsDataId: "0000010109",
        cdCat01: "I210101",
        unit: "人",
        name: "健康診断受診者数（保健所及び市区町村実施分）（結核）",
        displayOrder: 1,
        isActive: true,
      },
      {
        rankingKey: "lifestyleDiseaseCheckup",
        label: "健康診断受診者数（保健所及び市区町村実施分）（生活習慣病）",
        statsDataId: "0000010109",
        cdCat01: "I210104",
        unit: "人",
        name: "健康診断受診者数（保健所及び市区町村実施分）（生活習慣病）",
        displayOrder: 2,
        isActive: true,
      },
      {
        rankingKey: "publicHealthCenterCheckup",
        label: "健康診断受診者数（保健所実施分）",
        statsDataId: "0000010109",
        cdCat01: "I210110",
        unit: "人",
        name: "健康診断受診者数（保健所実施分）",
        displayOrder: 3,
        isActive: true,
      },
      {
        rankingKey: "mentalHealthCheckup",
        label: "健康診断受診者数（保健所実施分・精神）",
        statsDataId: "0000010109",
        cdCat01: "I210112",
        unit: "人",
        name: "健康診断受診者数（保健所実施分・精神）",
        displayOrder: 4,
        isActive: true,
      },
      {
        rankingKey: "publicHealthCenterLifestyleDiseaseCheckup",
        label: "健康診断受診者数（保健所実施分・生活習慣病）",
        statsDataId: "0000010109",
        cdCat01: "I210114",
        unit: "人",
        name: "健康診断受診者数（保健所実施分・生活習慣病）",
        displayOrder: 5,
        isActive: true,
      },
      {
        rankingKey: "maternalHealthCheckup",
        label: "健康診断受診者数（保健所実施分・妊産婦）",
        statsDataId: "0000010109",
        cdCat01: "I210115",
        unit: "人",
        name: "健康診断受診者数（保健所実施分・妊産婦）",
        displayOrder: 6,
        isActive: true,
      },
      {
        rankingKey: "infantHealthCheckup",
        label: "健康診断受診者数（保健所実施分・乳幼児）",
        statsDataId: "0000010109",
        cdCat01: "I210116",
        unit: "人",
        name: "健康診断受診者数（保健所実施分・乳幼児）",
        displayOrder: 7,
        isActive: true,
      },
      {
        rankingKey: "lifeExpectancyAtBirthMale",
        label: "平均余命（0歳）（男）",
        statsDataId: "0000010109",
        cdCat01: "I1101",
        unit: "年",
        name: "平均余命（0歳）（男）",
        displayOrder: 8,
        isActive: true,
      },
      {
        rankingKey: "lifeExpectancyAtBirthFemale",
        label: "平均余命（0歳）（女）",
        statsDataId: "0000010109",
        cdCat01: "I1102",
        unit: "年",
        name: "平均余命（0歳）（女）",
        displayOrder: 9,
        isActive: true,
      },
      {
        rankingKey: "lifeExpectancyAt20Male",
        label: "平均余命（20歳）（男）",
        statsDataId: "0000010109",
        cdCat01: "I1201",
        unit: "年",
        name: "平均余命（20歳）（男）",
        displayOrder: 10,
        isActive: true,
      },
      {
        rankingKey: "lifeExpectancyAt20Female",
        label: "平均余命（20歳）（女）",
        statsDataId: "0000010109",
        cdCat01: "I1202",
        unit: "年",
        name: "平均余命（20歳）（女）",
        displayOrder: 11,
        isActive: true,
      },
      {
        rankingKey: "lifeExpectancyAt40Male",
        label: "平均余命（40歳）（男）",
        statsDataId: "0000010109",
        cdCat01: "I1301",
        unit: "年",
        name: "平均余命（40歳）（男）",
        displayOrder: 12,
        isActive: true,
      },
      {
        rankingKey: "lifeExpectancyAt40Female",
        label: "平均余命（40歳）（女）",
        statsDataId: "0000010109",
        cdCat01: "I1302",
        unit: "年",
        name: "平均余命（40歳）（女）",
        displayOrder: 13,
        isActive: true,
      },
      {
        rankingKey: "lifeExpectancyAt60Male",
        label: "平均余命（60歳）（男）",
        statsDataId: "0000010109",
        cdCat01: "I1401",
        unit: "年",
        name: "平均余命（60歳）（男）",
        displayOrder: 14,
        isActive: true,
      },
      {
        rankingKey: "lifeExpectancyAt60Female",
        label: "平均余命（60歳）（女）",
        statsDataId: "0000010109",
        cdCat01: "I1402",
        unit: "年",
        name: "平均余命（60歳）（女）",
        displayOrder: 15,
        isActive: true,
      },
      {
        rankingKey: "lifeExpectancyAt65Male",
        label: "平均余命（65歳）（男）",
        statsDataId: "0000010109",
        cdCat01: "I1501",
        unit: "年",
        name: "平均余命（65歳）（男）",
        displayOrder: 16,
        isActive: true,
      },
      {
        rankingKey: "lifeExpectancyAt65Female",
        label: "平均余命（65歳）（女）",
        statsDataId: "0000010109",
        cdCat01: "I1502",
        unit: "年",
        name: "平均余命（65歳）（女）",
        displayOrder: 17,
        isActive: true,
      },
      {
        rankingKey: "healthLifeExpectancyMale",
        label: "健康寿命（男）",
        statsDataId: "0000010109",
        cdCat01: "I1601",
        unit: "年",
        name: "健康寿命（男）",
        displayOrder: 18,
        isActive: true,
      },
      {
        rankingKey: "healthLifeExpectancyFemale",
        label: "健康寿命（女）",
        statsDataId: "0000010109",
        cdCat01: "I1602",
        unit: "年",
        name: "健康寿命（女）",
        displayOrder: 19,
        isActive: true,
      },
    ],
  },
  "public-assistance-welfare": {
    subcategory: {
      id: "public-assistance-welfare",
      categoryId: "socialsecurity",
      name: "Public Assistance Welfare",
      description: undefined,
      defaultRankingKey: "householdsOnAssistance",
    },
    rankingItems: [
      {
        rankingKey: "householdsOnAssistance",
        label: "生活保護被保護実世帯数（月平均一般世帯千世帯当たり）",
        statsDataId: "0000010210",
        cdCat01: "#J01101",
        unit: "世帯",
        name: "生活保護被保護実世帯数（月平均一般世帯千世帯当たり）",
        displayOrder: 1,
        isActive: true,
      },
      {
        rankingKey: "personsOnAssistance",
        label: "生活保護被保護実人員（月平均人口千人当たり）",
        statsDataId: "0000010210",
        cdCat01: "#J01107",
        unit: "人",
        name: "生活保護被保護実人員（月平均人口千人当たり）",
        displayOrder: 2,
        isActive: true,
      },
      {
        rankingKey: "educationBeneficiaries",
        label: "生活保護教育扶助人員（月平均人口千人当たり）",
        statsDataId: "0000010210",
        cdCat01: "#J0110803",
        unit: "人",
        name: "生活保護教育扶助人員（月平均人口千人当たり）",
        displayOrder: 3,
        isActive: true,
      },
      {
        rankingKey: "medicalBeneficiaries",
        label: "生活保護医療扶助人員（月平均人口千人当たり）",
        statsDataId: "0000010210",
        cdCat01: "#J0110804",
        unit: "人",
        name: "生活保護医療扶助人員（月平均人口千人当たり）",
        displayOrder: 4,
        isActive: true,
      },
      {
        rankingKey: "housingBeneficiaries",
        label: "生活保護住宅扶助人員（月平均人口千人当たり）",
        statsDataId: "0000010210",
        cdCat01: "#J0110805",
        unit: "人",
        name: "生活保護住宅扶助人員（月平均人口千人当たり）",
        displayOrder: 5,
        isActive: true,
      },
      {
        rankingKey: "nursingBeneficiaries",
        label: "生活保護介護扶助人員（月平均人口千人当たり）",
        statsDataId: "0000010210",
        cdCat01: "#J0110806",
        unit: "人",
        name: "生活保護介護扶助人員（月平均人口千人当たり）",
        displayOrder: 6,
        isActive: true,
      },
      {
        rankingKey: "elderlyOnAssistance",
        label: "生活保護被保護高齢者数（月平均65歳以上人口千人当たり）",
        statsDataId: "0000010210",
        cdCat01: "#J0110902",
        unit: "人",
        name: "生活保護被保護高齢者数（月平均65歳以上人口千人当たり）",
        displayOrder: 7,
        isActive: true,
      },
      {
        rankingKey: "disabilityCertificates",
        label: "身体障害者手帳交付数（人口千人当たり）",
        statsDataId: "0000010210",
        cdCat01: "#J01200",
        unit: "人",
        name: "身体障害者手帳交付数（人口千人当たり）",
        displayOrder: 8,
        isActive: true,
      },
    ],
  },
  "tourism-accommodation": {
    subcategory: {
      id: "tourism-accommodation",
      categoryId: "tourism",
      name: "Tourism Accommodation",
      description: undefined,
      defaultRankingKey: "tourists",
    },
    rankingItems: [
      {
        rankingKey: "tourists",
        label: "観光客数",
        statsDataId: "0000010110",
        cdCat01: "I1101",
        unit: "人",
        name: "観光客数",
        displayOrder: 1,
        isActive: true,
      },
      {
        rankingKey: "accommodations",
        label: "宿泊施設数",
        statsDataId: "0000010110",
        cdCat01: "I1102",
        unit: "施設",
        name: "宿泊施設数",
        displayOrder: 2,
        isActive: true,
      },
      {
        rankingKey: "occupancyRate",
        label: "稼働率",
        statsDataId: "0000010110",
        cdCat01: "I1103",
        unit: "%",
        name: "稼働率",
        displayOrder: 3,
        isActive: true,
      },
    ],
  },
};
