/*
 * AUTOGENERATED by packages/data-configs/scripts/evidence/japan-zue.ts
 * candidatesSha256: 74d1ae472384d7ad8f83c6c9a8691ec2b504b039fe8136d7a4439e6879a8bb92
 * DO NOT EDIT. Change policy.ts and rerun evidence:resolve.
 */
import type { JapanZueEvidenceItem } from "../types";
import { JAPAN_ZUE_EVIDENCE_ITEMS_0 } from "./items.generated.0";
import { JAPAN_ZUE_EVIDENCE_ITEMS_1 } from "./items.generated.1";
import { JAPAN_ZUE_EVIDENCE_ITEMS_2 } from "./items.generated.2";

export const JAPAN_ZUE_EVIDENCE_ITEMS: readonly JapanZueEvidenceItem[] = [
  ...JAPAN_ZUE_EVIDENCE_ITEMS_0,
  ...JAPAN_ZUE_EVIDENCE_ITEMS_1,
  ...JAPAN_ZUE_EVIDENCE_ITEMS_2,
];
