export {
  CITY_TOP_BAND,
  HIGHLIGHT_EXCLUDED_KEY_PATTERN,
  MIN_HIGHLIGHT_YEAR,
  buildQualifiedLabel,
  buildSubtitleQualifier,
  collectHighlightCandidateKeys,
  computeMargin,
  detectRankDirection,
  familyKeyOf,
  highlightTone,
  listAreaHighlightCandidates,
  parseHighlightYear,
  selectAreaHighlights,
  selectCityHighlights,
  type AreaHighlight,
  type AreaHighlights,
  type CityHighlightSource,
  type DatabookTemplateLike,
  type HighlightDirection,
  type HighlightTone,
  type RankedValue,
  type SelectAreaHighlightsOptions,
} from "./select-area-highlights";
export {
  AREA_HIGHLIGHT_REQUIRED_PER_GROUP,
  checkAreaHighlights,
  validateAreaHighlights,
  type AreaHighlightCheckResult,
  type AreaHighlightViolation,
  type AreaHighlightViolationKind,
} from "./check-area-highlights";
