import type { ProductDefinition } from "../types";

export const ASSET_PRODUCTS: readonly ProductDefinition[] = [
  {
    id: "A-01",
    family: "asset",
    name: "47都道府県コロプレス地図（連続値）",
    audience: ["企画・営業", "コンサル"],
    jobToBeDone: "連続値を色分け地図で説明する",
    formats: ["pptx", "svg"],
    price: { minYen: 1500, maxYen: 3980, initialYen: 1500 },
    dataMode: "empty",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: [
      "PowerPoint 365 (Windows / Mac)",
      "SVG / PNG 対応ビューア",
    ],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "A-02",
    family: "asset",
    name: "47都道府県カテゴリ色分け地図",
    audience: ["企画・営業", "コンサル"],
    jobToBeDone: "カテゴリ区分を地図で説明する",
    formats: ["pptx", "svg"],
    price: { minYen: 1500, maxYen: 3980, initialYen: 1500 },
    dataMode: "empty",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: [
      "PowerPoint 365 (Windows / Mac)",
      "SVG / PNG 対応ビューア",
    ],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "A-03",
    family: "asset",
    name: "特定県だけを強調する日本地図47パターン",
    audience: ["企画・営業", "コンサル"],
    jobToBeDone: "特定県を強調して資料に使う",
    formats: ["pptx", "png", "svg"],
    price: { minYen: 2000, maxYen: 5000, initialYen: 2000 },
    dataMode: "empty",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: [
      "PowerPoint 365 (Windows / Mac)",
      "SVG / PNG 対応ビューア",
    ],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "A-04",
    family: "asset",
    name: "地方ブロック別の日本地図",
    audience: ["企画・営業", "コンサル"],
    jobToBeDone: "地方ブロック単位で説明する",
    formats: ["pptx", "svg"],
    price: { minYen: 1500, maxYen: 3000, initialYen: 1500 },
    dataMode: "empty",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: [
      "PowerPoint 365 (Windows / Mac)",
      "SVG / PNG 対応ビューア",
    ],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "A-05",
    family: "asset",
    name: "都道府県ラベル・県庁所在地付き地図",
    audience: ["企画・営業", "教育"],
    jobToBeDone: "地名・県庁所在地を明示した地図を使う",
    formats: ["pptx", "svg"],
    price: { minYen: 1500, maxYen: 3000, initialYen: 1500 },
    dataMode: "empty",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: [
      "PowerPoint 365 (Windows / Mac)",
      "SVG / PNG 対応ビューア",
    ],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "A-06",
    family: "asset",
    name: "色覚多様性対応の地図パレット集",
    audience: ["企画・営業", "公務員"],
    jobToBeDone: "誰にでも読める配色で地図を作る",
    formats: ["pptx", "svg"],
    price: { minYen: 1000, maxYen: 2500, initialYen: 1000 },
    dataMode: "empty",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: [
      "PowerPoint 365 (Windows / Mac)",
      "SVG / PNG 対応ビューア",
    ],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "A-07",
    family: "asset",
    name: "上位10・下位10ランキングテンプレート",
    audience: ["企画・営業", "研究者"],
    jobToBeDone: "上位・下位を並べて比較する",
    formats: ["pptx", "xlsx"],
    price: { minYen: 1500, maxYen: 3000, initialYen: 1500 },
    dataMode: "empty",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: ["PowerPoint 365 (Windows / Mac)", "Excel 365 (Windows / Mac)"],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "A-08",
    family: "asset",
    name: "47都道府県全順位テンプレート",
    audience: ["企画・営業", "研究者"],
    jobToBeDone: "47都道府県を全件順位表示する",
    formats: ["pptx", "xlsx"],
    price: { minYen: 1500, maxYen: 3000, initialYen: 1500 },
    dataMode: "empty",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: ["PowerPoint 365 (Windows / Mac)", "Excel 365 (Windows / Mac)"],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "A-09",
    family: "asset",
    name: "全国平均・自県・類似県比較テンプレート",
    audience: ["企画・営業", "自治体"],
    jobToBeDone: "自県を全国平均・類似県と比較する",
    formats: ["pptx", "xlsx"],
    price: { minYen: 2000, maxYen: 4000, initialYen: 2000 },
    dataMode: "empty",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: ["PowerPoint 365 (Windows / Mac)", "Excel 365 (Windows / Mac)"],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "A-10",
    family: "asset",
    name: "都道府県散布図・四象限分析テンプレート",
    audience: ["企画・営業", "研究者"],
    jobToBeDone: "2指標の関係を四象限で分析する",
    formats: ["pptx", "xlsx"],
    price: { minYen: 2000, maxYen: 4000, initialYen: 2000 },
    dataMode: "empty",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: ["PowerPoint 365 (Windows / Mac)", "Excel 365 (Windows / Mac)"],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "A-11",
    family: "asset",
    name: "時系列・前年差・指数化チャート集",
    audience: ["企画・営業", "研究者"],
    jobToBeDone: "時系列変化を前年差・指数で示す",
    formats: ["pptx", "xlsx"],
    price: { minYen: 2000, maxYen: 4000, initialYen: 2000 },
    dataMode: "empty",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: ["PowerPoint 365 (Windows / Mac)", "Excel 365 (Windows / Mac)"],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "A-12",
    family: "asset",
    name: "人口ピラミッドテンプレート",
    audience: ["企画・営業", "自治体"],
    jobToBeDone: "年齢構成を人口ピラミッドで示す",
    formats: ["pptx", "xlsx"],
    price: { minYen: 2000, maxYen: 5000, initialYen: 2000 },
    dataMode: "empty",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: ["PowerPoint 365 (Windows / Mac)", "Excel 365 (Windows / Mac)"],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "A-13",
    family: "asset",
    name: "転入・転出フロー／サンキー図テンプレート",
    audience: ["企画・営業", "自治体"],
    jobToBeDone: "人口移動の流れをサンキー図で示す",
    formats: ["pptx", "svg"],
    price: { minYen: 3000, maxYen: 8000, initialYen: 3000 },
    dataMode: "empty",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: [
      "PowerPoint 365 (Windows / Mac)",
      "SVG / PNG 対応ビューア",
    ],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "A-14",
    family: "asset",
    name: "構成比・積み上げ・レーダーチャート集",
    audience: ["企画・営業", "研究者"],
    jobToBeDone: "構成比を積み上げ・レーダーで示す",
    formats: ["pptx", "xlsx"],
    price: { minYen: 2000, maxYen: 4000, initialYen: 2000 },
    dataMode: "empty",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: ["PowerPoint 365 (Windows / Mac)", "Excel 365 (Windows / Mac)"],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "A-15",
    family: "asset",
    name: "KPIカード・注記・出典フッター素材集",
    audience: ["企画・営業", "公務員"],
    jobToBeDone: "資料にKPI・注記・出典を素早く付与する",
    formats: ["pptx"],
    price: { minYen: 1000, maxYen: 2500, initialYen: 1000 },
    dataMode: "empty",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: ["PowerPoint 365 (Windows / Mac)"],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "A-16",
    family: "asset",
    name: "地図＋ランキング＋要点の1枚資料",
    audience: ["企画・営業", "コンサル"],
    jobToBeDone: "地図・ランキング・要点を1枚に集約する",
    formats: ["pptx", "xlsx"],
    price: { minYen: 2000, maxYen: 4000, initialYen: 2000 },
    dataMode: "empty",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: ["PowerPoint 365 (Windows / Mac)", "Excel 365 (Windows / Mac)"],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "A-17",
    family: "asset",
    name: "SNS縦長・正方形向けランキング図版",
    audience: ["メディア", "SNS運用"],
    jobToBeDone: "SNS投稿用のランキング図版を作る",
    formats: ["pptx", "png"],
    price: { minYen: 2000, maxYen: 5000, initialYen: 2000 },
    dataMode: "empty",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: [
      "PowerPoint 365 (Windows / Mac)",
      "SVG / PNG 対応ビューア",
    ],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "A-18",
    family: "asset",
    name: "動画用16:9都道府県ランキング画面",
    audience: ["メディア", "動画クリエイター"],
    jobToBeDone: "動画に使うランキング画面を作る",
    formats: ["pptx", "png"],
    price: { minYen: 2000, maxYen: 5000, initialYen: 2000 },
    dataMode: "empty",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: [
      "PowerPoint 365 (Windows / Mac)",
      "SVG / PNG 対応ビューア",
    ],
    risk: "normal",
    status: "cataloged",
  },
];
