import type { ProductDefinition } from "../types";

export const CONSUMER_PRODUCTS: readonly ProductDefinition[] = [
  {
    id: "I-01",
    family: "consumer",
    name: "移住候補県比較シート",
    audience: ["移住検討者"],
    jobToBeDone: "移住候補県を条件別に比較して絞り込む",
    formats: ["xlsx", "pdf"],
    price: { minYen: 1980, maxYen: 4980, initialYen: 1980 },
    dataMode: "sample",
    metrics: [],
    templateIds: [],
    licenseId: "personal",
    supportLevel: "manual",
    compatibility: [
      "Excel 365 (Windows / Mac)",
      "PDF 閲覧環境",
    ],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "I-02",
    family: "consumer",
    name: "引越し先の生活コスト比較",
    audience: ["引越し検討者"],
    jobToBeDone: "引越し先候補の生活コストを比較する",
    formats: ["xlsx", "pdf"],
    price: { minYen: 1980, maxYen: 4980, initialYen: 1980 },
    dataMode: "sample",
    metrics: [],
    templateIds: [],
    licenseId: "personal",
    supportLevel: "manual",
    compatibility: [
      "Excel 365 (Windows / Mac)",
      "PDF 閲覧環境",
    ],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "I-03",
    family: "consumer",
    name: "子育て環境比較シート",
    audience: ["子育て世帯"],
    jobToBeDone: "子育て環境を条件別に比較する",
    formats: ["xlsx", "pdf"],
    price: { minYen: 1980, maxYen: 4980, initialYen: 1980 },
    dataMode: "sample",
    metrics: [],
    templateIds: [],
    licenseId: "personal",
    supportLevel: "manual",
    compatibility: [
      "Excel 365 (Windows / Mac)",
      "PDF 閲覧環境",
    ],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "I-04",
    family: "consumer",
    name: "転職先・勤務地比較シート",
    audience: ["転職検討者"],
    jobToBeDone: "転職先・勤務地の条件を比較する",
    formats: ["xlsx", "pdf"],
    price: { minYen: 1980, maxYen: 4980, initialYen: 1980 },
    dataMode: "sample",
    metrics: [],
    templateIds: [],
    licenseId: "personal",
    supportLevel: "manual",
    compatibility: [
      "Excel 365 (Windows / Mac)",
      "PDF 閲覧環境",
    ],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "I-05",
    family: "consumer",
    name: "退職後の居住地比較",
    audience: ["老後・移住検討者"],
    jobToBeDone: "退職後の居住地候補を条件別に比較する",
    formats: ["xlsx", "pdf"],
    price: { minYen: 1980, maxYen: 4980, initialYen: 1980 },
    dataMode: "sample",
    metrics: [],
    templateIds: [],
    licenseId: "personal",
    supportLevel: "manual",
    compatibility: [
      "Excel 365 (Windows / Mac)",
      "PDF 閲覧環境",
    ],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "I-06",
    family: "consumer",
    name: "二拠点生活候補地比較",
    audience: ["二拠点生活検討者"],
    jobToBeDone: "二拠点生活の候補地を比較する",
    formats: ["xlsx", "pdf"],
    price: { minYen: 1980, maxYen: 4980, initialYen: 1980 },
    dataMode: "sample",
    metrics: [],
    templateIds: [],
    licenseId: "personal",
    supportLevel: "manual",
    compatibility: [
      "Excel 365 (Windows / Mac)",
      "PDF 閲覧環境",
    ],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "I-07",
    family: "consumer",
    name: "大学進学先の地域比較",
    audience: ["進学検討者"],
    jobToBeDone: "大学進学先の地域を条件別に比較する",
    formats: ["xlsx", "pdf"],
    price: { minYen: 1980, maxYen: 4980, initialYen: 1980 },
    dataMode: "sample",
    metrics: [],
    templateIds: [],
    licenseId: "personal",
    supportLevel: "manual",
    compatibility: [
      "Excel 365 (Windows / Mac)",
      "PDF 閲覧環境",
    ],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "I-08",
    family: "consumer",
    name: "Uターン・Iターン比較",
    audience: ["帰郷・移住検討者"],
    jobToBeDone: "Uターン・Iターン先の条件を比較する",
    formats: ["xlsx", "pdf"],
    price: { minYen: 1980, maxYen: 4980, initialYen: 1980 },
    dataMode: "sample",
    metrics: [],
    templateIds: [],
    licenseId: "personal",
    supportLevel: "manual",
    compatibility: [
      "Excel 365 (Windows / Mac)",
      "PDF 閲覧環境",
    ],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "I-09",
    family: "consumer",
    name: "自分用の都道府県重み付け診断表",
    audience: ["多条件比較検討者"],
    jobToBeDone: "重み付け入力で都道府県を総合診断する",
    formats: ["xlsx", "pdf"],
    price: { minYen: 2980, maxYen: 5980, initialYen: 2980 },
    dataMode: "sample",
    metrics: [],
    templateIds: [],
    licenseId: "personal",
    supportLevel: "manual",
    compatibility: [
      "Excel 365 (Windows / Mac)",
      "PDF 閲覧環境",
    ],
    risk: "normal",
    status: "cataloged",
  },
];
