import type { ProductDefinition } from "../types";

export const DATA_PRODUCTS: readonly ProductDefinition[] = [
  {
    id: "D-01",
    family: "data",
    name: "47都道府県基礎統計データブック",
    audience: ["企画・営業", "自治体・公務員"],
    jobToBeDone: "人口・面積・世帯・所得を一冊で把握する",
    formats: ["xlsx", "csv", "pdf"],
    price: { minYen: 2980, maxYen: 5980, initialYen: 2980 },
    dataMode: "fixed-year",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: [
      "Excel 365 (Windows / Mac)",
      "UTF-8 (BOM) 対応表計算ソフト",
      "PDF 閲覧環境",
    ],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "D-02",
    family: "data",
    name: "人口・将来推計パック",
    audience: ["自治体・公務員", "研究者"],
    jobToBeDone: "年齢構成・増減・将来人口をまとめて把握する",
    formats: ["xlsx", "csv", "pdf"],
    price: { minYen: 3980, maxYen: 9800, initialYen: 3980 },
    dataMode: "fixed-year",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: [
      "Excel 365 (Windows / Mac)",
      "UTF-8 (BOM) 対応表計算ソフト",
      "PDF 閲覧環境",
    ],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "D-03",
    family: "data",
    name: "所得・賃金・雇用パック",
    audience: ["人事・採用支援", "事業企画"],
    jobToBeDone: "県民所得・賃金・求人をまとめて把握する",
    formats: ["xlsx", "csv", "pdf"],
    price: { minYen: 3980, maxYen: 9800, initialYen: 3980 },
    dataMode: "fixed-year",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: [
      "Excel 365 (Windows / Mac)",
      "UTF-8 (BOM) 対応表計算ソフト",
      "PDF 閲覧環境",
    ],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "D-04",
    family: "data",
    name: "物価・家計・消費パック",
    audience: ["事業企画", "調査担当"],
    jobToBeDone: "物価水準・家計調査をまとめて把握する",
    formats: ["xlsx", "csv", "pdf"],
    price: { minYen: 3980, maxYen: 9800, initialYen: 3980 },
    dataMode: "fixed-year",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: [
      "Excel 365 (Windows / Mac)",
      "UTF-8 (BOM) 対応表計算ソフト",
      "PDF 閲覧環境",
    ],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "D-05",
    family: "data",
    name: "住宅・地価・空き家パック",
    audience: ["不動産事業者", "移住支援"],
    jobToBeDone: "地価・家賃・持家・空き家をまとめて把握する",
    formats: ["xlsx", "csv", "pdf"],
    price: { minYen: 3980, maxYen: 9800, initialYen: 3980 },
    dataMode: "fixed-year",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: [
      "Excel 365 (Windows / Mac)",
      "UTF-8 (BOM) 対応表計算ソフト",
      "PDF 閲覧環境",
    ],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "D-06",
    family: "data",
    name: "医療・介護パック",
    audience: ["医療・介護事業者", "自治体・公務員"],
    jobToBeDone: "病床・医師・介護・高齢化をまとめて把握する",
    formats: ["xlsx", "csv", "pdf"],
    price: { minYen: 3980, maxYen: 9800, initialYen: 3980 },
    dataMode: "fixed-year",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: [
      "Excel 365 (Windows / Mac)",
      "UTF-8 (BOM) 対応表計算ソフト",
      "PDF 閲覧環境",
    ],
    risk: "high-stakes",
    status: "cataloged",
  },
  {
    id: "D-07",
    family: "data",
    name: "教育・子育てパック",
    audience: ["教育・移住支援"],
    jobToBeDone: "学校・保育・進学・出生をまとめて把握する",
    formats: ["xlsx", "csv", "pdf"],
    price: { minYen: 3980, maxYen: 9800, initialYen: 3980 },
    dataMode: "fixed-year",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: [
      "Excel 365 (Windows / Mac)",
      "UTF-8 (BOM) 対応表計算ソフト",
      "PDF 閲覧環境",
    ],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "D-08",
    family: "data",
    name: "観光・宿泊パック",
    audience: ["観光事業者"],
    jobToBeDone: "宿泊・訪日・観光消費をまとめて把握する",
    formats: ["xlsx", "csv", "pdf"],
    price: { minYen: 3980, maxYen: 9800, initialYen: 3980 },
    dataMode: "fixed-year",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: [
      "Excel 365 (Windows / Mac)",
      "UTF-8 (BOM) 対応表計算ソフト",
      "PDF 閲覧環境",
    ],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "D-09",
    family: "data",
    name: "産業・事業所パック",
    audience: ["事業企画", "コンサル"],
    jobToBeDone: "産業構成・事業所・就業者をまとめて把握する",
    formats: ["xlsx", "csv", "pdf"],
    price: { minYen: 3980, maxYen: 9800, initialYen: 3980 },
    dataMode: "fixed-year",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: [
      "Excel 365 (Windows / Mac)",
      "UTF-8 (BOM) 対応表計算ソフト",
      "PDF 閲覧環境",
    ],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "D-10",
    family: "data",
    name: "自治体財政パック",
    audience: ["自治体・公務員"],
    jobToBeDone: "歳入歳出・財政指標をまとめて把握する",
    formats: ["xlsx", "csv", "pdf"],
    price: { minYen: 3980, maxYen: 9800, initialYen: 3980 },
    dataMode: "fixed-year",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: [
      "Excel 365 (Windows / Mac)",
      "UTF-8 (BOM) 対応表計算ソフト",
      "PDF 閲覧環境",
    ],
    risk: "high-stakes",
    status: "cataloged",
  },
  {
    id: "D-11",
    family: "data",
    name: "交通・アクセスパック",
    audience: ["事業企画", "自治体・公務員"],
    jobToBeDone: "自動車・鉄道・空港等をまとめて把握する",
    formats: ["xlsx", "csv", "pdf"],
    price: { minYen: 3980, maxYen: 9800, initialYen: 3980 },
    dataMode: "fixed-year",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: [
      "Excel 365 (Windows / Mac)",
      "UTF-8 (BOM) 対応表計算ソフト",
      "PDF 閲覧環境",
    ],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "D-12",
    family: "data",
    name: "環境・エネルギーパック",
    audience: ["自治体・公務員", "事業企画"],
    jobToBeDone: "ごみ・排出・再エネ等をまとめて把握する",
    formats: ["xlsx", "csv", "pdf"],
    price: { minYen: 3980, maxYen: 9800, initialYen: 3980 },
    dataMode: "fixed-year",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: [
      "Excel 365 (Windows / Mac)",
      "UTF-8 (BOM) 対応表計算ソフト",
      "PDF 閲覧環境",
    ],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "D-13",
    family: "data",
    name: "安全・防災パック",
    audience: ["自治体・公務員"],
    jobToBeDone: "災害・犯罪・事故・消防をまとめて把握する",
    formats: ["xlsx", "csv", "pdf"],
    price: { minYen: 3980, maxYen: 9800, initialYen: 3980 },
    dataMode: "fixed-year",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: [
      "Excel 365 (Windows / Mac)",
      "UTF-8 (BOM) 対応表計算ソフト",
      "PDF 閲覧環境",
    ],
    risk: "high-stakes",
    status: "cataloged",
  },
  {
    id: "D-14",
    family: "data",
    name: "農林水産業パック",
    audience: ["農林水産事業者", "自治体・公務員"],
    jobToBeDone: "生産・就業・農地等をまとめて把握する",
    formats: ["xlsx", "csv", "pdf"],
    price: { minYen: 3980, maxYen: 9800, initialYen: 3980 },
    dataMode: "fixed-year",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: [
      "Excel 365 (Windows / Mac)",
      "UTF-8 (BOM) 対応表計算ソフト",
      "PDF 閲覧環境",
    ],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "D-15",
    family: "data",
    name: "文化・図書館・博物館パック",
    audience: ["自治体・公務員", "教育関係者"],
    jobToBeDone: "施設・利用・文化活動をまとめて把握する",
    formats: ["xlsx", "csv", "pdf"],
    price: { minYen: 2980, maxYen: 7980, initialYen: 2980 },
    dataMode: "fixed-year",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: [
      "Excel 365 (Windows / Mac)",
      "UTF-8 (BOM) 対応表計算ソフト",
      "PDF 閲覧環境",
    ],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "D-16",
    family: "data",
    name: "スポーツ・余暇・旅行パック",
    audience: ["観光事業者", "教育関係者"],
    jobToBeDone: "行動者率・施設・旅行をまとめて把握する",
    formats: ["xlsx", "csv", "pdf"],
    price: { minYen: 2980, maxYen: 7980, initialYen: 2980 },
    dataMode: "fixed-year",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: [
      "Excel 365 (Windows / Mac)",
      "UTF-8 (BOM) 対応表計算ソフト",
      "PDF 閲覧環境",
    ],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "D-17",
    family: "data",
    name: "女性・若者・高齢者の地域比較",
    audience: ["自治体・公務員", "研究者"],
    jobToBeDone: "属性別人口・就業・生活を地域比較する",
    formats: ["xlsx", "csv", "pdf"],
    price: { minYen: 3980, maxYen: 9800, initialYen: 3980 },
    dataMode: "fixed-year",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: [
      "Excel 365 (Windows / Mac)",
      "UTF-8 (BOM) 対応表計算ソフト",
      "PDF 閲覧環境",
    ],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "D-18",
    family: "data",
    name: "市区町村内格差パック",
    audience: ["自治体・公務員", "研究者"],
    jobToBeDone: "県内順位・分布・格差をまとめて把握する",
    formats: ["xlsx", "csv", "pdf"],
    price: { minYen: 5980, maxYen: 14800, initialYen: 5980 },
    dataMode: "fixed-year",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: [
      "Excel 365 (Windows / Mac)",
      "UTF-8 (BOM) 対応表計算ソフト",
      "PDF 閲覧環境",
    ],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "D-19",
    family: "data",
    name: "都道府県間人口移動パック",
    audience: ["自治体・公務員", "移住支援"],
    jobToBeDone: "転入元・転出先・純移動をまとめて把握する",
    formats: ["xlsx", "csv", "pdf"],
    price: { minYen: 5980, maxYen: 14800, initialYen: 5980 },
    dataMode: "fixed-year",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: [
      "Excel 365 (Windows / Mac)",
      "UTF-8 (BOM) 対応表計算ソフト",
      "PDF 閲覧環境",
    ],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "D-20",
    family: "data",
    name: "テーマ別100図表パック",
    audience: ["企画・営業", "編集者・ライター"],
    jobToBeDone: "複数テーマの図表を一括で入手する",
    formats: ["xlsx", "csv", "pdf"],
    price: { minYen: 9800, maxYen: 29800, initialYen: 9800 },
    dataMode: "fixed-year",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: [
      "Excel 365 (Windows / Mac)",
      "UTF-8 (BOM) 対応表計算ソフト",
      "PDF 閲覧環境",
    ],
    risk: "normal",
    status: "cataloged",
  },
];
