import type { ProductDefinition } from "../types";

export const EDUCATION_PRODUCTS: readonly ProductDefinition[] = [
  {
    id: "H-01",
    family: "education",
    name: "中高生向け47都道府県統計教材",
    audience: ["学校・塾"],
    jobToBeDone: "47都道府県統計を授業教材として使う",
    formats: ["pptx", "pdf"],
    price: { minYen: 2980, maxYen: 7980, initialYen: 2980 },
    dataMode: "sample",
    metrics: [],
    templateIds: [],
    licenseId: "education",
    supportLevel: "manual",
    compatibility: [
      "PowerPoint 365 (Windows / Mac)",
      "PDF 閲覧環境",
    ],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "H-02",
    family: "education",
    name: "探究学習用の地域比較ワークシート",
    audience: ["学校・家庭"],
    jobToBeDone: "地域比較を通じて探究学習を進行する",
    formats: ["pptx", "pdf"],
    price: { minYen: 1980, maxYen: 4980, initialYen: 1980 },
    dataMode: "sample",
    metrics: [],
    templateIds: [],
    licenseId: "education",
    supportLevel: "manual",
    compatibility: [
      "PowerPoint 365 (Windows / Mac)",
      "PDF 閲覧環境",
    ],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "H-03",
    family: "education",
    name: "Excelグラフ作成演習データ",
    audience: ["学校・研修"],
    jobToBeDone: "Excelでグラフ作成を演習する",
    formats: ["xlsx"],
    price: { minYen: 1980, maxYen: 4980, initialYen: 1980 },
    dataMode: "sample",
    metrics: [],
    templateIds: [],
    licenseId: "education",
    supportLevel: "manual",
    compatibility: ["Excel 365 (Windows / Mac)"],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "H-04",
    family: "education",
    name: "PowerPointデータ発表演習",
    audience: ["学校・研修"],
    jobToBeDone: "PowerPointでデータ発表を演習する",
    formats: ["pptx"],
    price: { minYen: 1980, maxYen: 4980, initialYen: 1980 },
    dataMode: "sample",
    metrics: [],
    templateIds: [],
    licenseId: "education",
    supportLevel: "manual",
    compatibility: ["PowerPoint 365 (Windows / Mac)"],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "H-05",
    family: "education",
    name: "統計の読み方・相関と因果教材",
    audience: ["学校・企業研修"],
    jobToBeDone: "相関と因果の違いを統計データで学ぶ",
    formats: ["pptx", "pdf"],
    price: { minYen: 2980, maxYen: 7980, initialYen: 2980 },
    dataMode: "sample",
    metrics: [],
    templateIds: [],
    licenseId: "education",
    supportLevel: "manual",
    compatibility: [
      "PowerPoint 365 (Windows / Mac)",
      "PDF 閲覧環境",
    ],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "H-06",
    family: "education",
    name: "オープンデータ調査演習",
    audience: ["大学・研修"],
    jobToBeDone: "オープンデータの探索・調査手順を演習する",
    formats: ["pptx", "pdf"],
    price: { minYen: 2980, maxYen: 7980, initialYen: 2980 },
    dataMode: "sample",
    metrics: [],
    templateIds: [],
    licenseId: "education",
    supportLevel: "manual",
    compatibility: [
      "PowerPoint 365 (Windows / Mac)",
      "PDF 閲覧環境",
    ],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "H-07",
    family: "education",
    name: "自県研究テンプレート",
    audience: ["小中高"],
    jobToBeDone: "自分の県を統計で調べてまとめる",
    formats: ["pptx", "pdf"],
    price: { minYen: 1980, maxYen: 4980, initialYen: 1980 },
    dataMode: "sample",
    metrics: [],
    templateIds: [],
    licenseId: "education",
    supportLevel: "manual",
    compatibility: [
      "PowerPoint 365 (Windows / Mac)",
      "PDF 閲覧環境",
    ],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "H-08",
    family: "education",
    name: "都道府県クイズ・ランキング教材",
    audience: ["家庭・講師"],
    jobToBeDone: "クイズ形式で都道府県ランキングを学ぶ",
    formats: ["pptx", "pdf"],
    price: { minYen: 1500, maxYen: 3980, initialYen: 1500 },
    dataMode: "sample",
    metrics: [],
    templateIds: [],
    licenseId: "education",
    supportLevel: "manual",
    compatibility: [
      "PowerPoint 365 (Windows / Mac)",
      "PDF 閲覧環境",
    ],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "H-09",
    family: "education",
    name: "卒論・レポート用データ管理表",
    audience: ["大学生"],
    jobToBeDone: "卒論・レポート用に統計データを管理する",
    formats: ["xlsx"],
    price: { minYen: 1980, maxYen: 4980, initialYen: 1980 },
    dataMode: "sample",
    metrics: [],
    templateIds: [],
    licenseId: "education",
    supportLevel: "manual",
    compatibility: ["Excel 365 (Windows / Mac)"],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "H-10",
    family: "education",
    name: "教員向け授業スライド＋解説",
    audience: ["教員"],
    jobToBeDone: "授業スライドと解説を揃えて即使用する",
    formats: ["pptx", "pdf"],
    price: { minYen: 3980, maxYen: 9800, initialYen: 3980 },
    dataMode: "sample",
    metrics: [],
    templateIds: [],
    licenseId: "education",
    supportLevel: "manual",
    compatibility: [
      "PowerPoint 365 (Windows / Mac)",
      "PDF 閲覧環境",
    ],
    risk: "normal",
    status: "cataloged",
  },
];
