import type { ProductDefinition } from "../types";

export const ENTRY_PRODUCTS: readonly ProductDefinition[] = [
  {
    id: "L-01",
    family: "entry",
    name: "都道府県地図1枚の無料サンプル",
    audience: ["導線対象"],
    jobToBeDone: "無料サンプルで地図の操作性・品質を確認する",
    formats: ["pptx", "svg", "png"],
    price: { minYen: 0, maxYen: 0, initialYen: 0 },
    dataMode: "empty",
    metrics: [],
    templateIds: [],
    licenseId: "free-sample",
    supportLevel: "none",
    compatibility: [
      "PowerPoint 365 (Windows / Mac)",
      "SVG / PNG 対応ビューア",
    ],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "L-02",
    family: "entry",
    name: "ランキングスライド3枚版",
    audience: ["導線対象"],
    jobToBeDone: "PowerPoint商品の入口として3枚を試す",
    formats: ["pptx"],
    price: { minYen: 0, maxYen: 0, initialYen: 0 },
    dataMode: "empty",
    metrics: [],
    templateIds: [],
    licenseId: "free-sample",
    supportLevel: "none",
    compatibility: ["PowerPoint 365 (Windows / Mac)"],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "L-03",
    family: "entry",
    name: "Excel都道府県コード変換表",
    audience: ["導線対象"],
    jobToBeDone: "Excel商品の入口としてコード変換表を試す",
    formats: ["xlsx", "csv"],
    price: { minYen: 0, maxYen: 0, initialYen: 0 },
    dataMode: "empty",
    metrics: [],
    templateIds: [],
    licenseId: "free-sample",
    supportLevel: "none",
    compatibility: [
      "Excel 365 (Windows / Mac)",
      "UTF-8 (BOM) 対応表計算ソフト",
    ],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "L-04",
    family: "entry",
    name: "出典表記テンプレート",
    audience: ["導線対象"],
    jobToBeDone: "出典表記を統一して信頼性を訴求する",
    formats: ["docx", "pdf"],
    price: { minYen: 0, maxYen: 0, initialYen: 0 },
    dataMode: "empty",
    metrics: [],
    templateIds: [],
    licenseId: "free-sample",
    supportLevel: "none",
    compatibility: [
      "Word 365 (Windows / Mac)",
      "PDF 閲覧環境",
    ],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "L-05",
    family: "entry",
    name: "色覚対応カラーパレット",
    audience: ["導線対象"],
    jobToBeDone: "色覚対応パレットでデザイン品質を訴求する",
    formats: ["pptx", "svg"],
    price: { minYen: 0, maxYen: 0, initialYen: 0 },
    dataMode: "empty",
    metrics: [],
    templateIds: [],
    licenseId: "free-sample",
    supportLevel: "none",
    compatibility: [
      "PowerPoint 365 (Windows / Mac)",
      "SVG / PNG 対応ビューア",
    ],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "L-06",
    family: "entry",
    name: "サンプルデータ入り地図",
    audience: ["導線対象"],
    jobToBeDone: "サンプルデータ入り地図で購入後体験を確認する",
    formats: ["pptx", "png"],
    price: { minYen: 0, maxYen: 0, initialYen: 0 },
    dataMode: "sample",
    metrics: [],
    templateIds: [],
    licenseId: "free-sample",
    supportLevel: "none",
    compatibility: [
      "PowerPoint 365 (Windows / Mac)",
      "SVG / PNG 対応ビューア",
    ],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "L-07",
    family: "entry",
    name: "地域比較チェックリスト",
    audience: ["導線対象"],
    jobToBeDone: "チェックリストから受注サービスへ導線を作る",
    formats: ["pdf", "xlsx"],
    price: { minYen: 0, maxYen: 0, initialYen: 0 },
    dataMode: "empty",
    metrics: [],
    templateIds: [],
    licenseId: "free-sample",
    supportLevel: "none",
    compatibility: [
      "PDF 閲覧環境",
      "Excel 365 (Windows / Mac)",
    ],
    risk: "normal",
    status: "cataloged",
  },
];
