import type { ProductDefinition } from "../types";

export const EXCEL_PRODUCTS: readonly ProductDefinition[] = [
  {
    id: "C-01",
    family: "excel",
    name: "数値を貼るだけの47都道府県コロプレス地図",
    audience: ["企画・営業", "自治体・公務員"],
    jobToBeDone: "数値貼付だけで都道府県地図を自動着色する",
    formats: ["xlsx"],
    price: { minYen: 3980, maxYen: 7980, initialYen: 3980 },
    dataMode: "empty",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: [
      "Excel 365 (Windows / Mac)",
      "地図の新規作成・データ追加にオンライン接続が必要",
    ],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "C-02",
    family: "excel",
    name: "47都道府県ランキング自動作成",
    audience: ["企画・営業", "調査担当"],
    jobToBeDone: "数値入力だけで順位・上位下位を自動集計する",
    formats: ["xlsx"],
    price: { minYen: 2980, maxYen: 5980, initialYen: 2980 },
    dataMode: "empty",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: ["Excel 365 (Windows / Mac)"],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "C-03",
    family: "excel",
    name: "地図・ランキング・グラフ統合ダッシュボード",
    audience: ["企画・経営層", "自治体・公務員"],
    jobToBeDone: "1枚サマリーで地図・順位・推移を同時把握する",
    formats: ["xlsx"],
    price: { minYen: 5980, maxYen: 12000, initialYen: 5980 },
    dataMode: "empty",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: [
      "Excel 365 (Windows / Mac)",
      "地図の新規作成・データ追加にオンライン接続が必要",
    ],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "C-04",
    family: "excel",
    name: "複数指標の都道府県スコアリング",
    audience: ["事業企画", "コンサル"],
    jobToBeDone: "重み付けで複数指標を総合点化し比較する",
    formats: ["xlsx"],
    price: { minYen: 5980, maxYen: 12000, initialYen: 5980 },
    dataMode: "empty",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: ["Excel 365 (Windows / Mac)"],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "C-05",
    family: "excel",
    name: "候補地域の比較表",
    audience: ["事業企画", "出店担当"],
    jobToBeDone: "3〜10地域を選択して横並び比較する",
    formats: ["xlsx"],
    price: { minYen: 3980, maxYen: 7980, initialYen: 3980 },
    dataMode: "empty",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: ["Excel 365 (Windows / Mac)"],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "C-06",
    family: "excel",
    name: "自県と全国平均との差分析",
    audience: ["自治体・公務員", "調査担当"],
    jobToBeDone: "偏差・順位・平均差から自県の位置を把握する",
    formats: ["xlsx"],
    price: { minYen: 3980, maxYen: 7980, initialYen: 3980 },
    dataMode: "empty",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: ["Excel 365 (Windows / Mac)"],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "C-07",
    family: "excel",
    name: "時系列・前年差・成長率分析",
    audience: ["事業企画", "調査担当"],
    jobToBeDone: "CAGR・指数・前年差で推移を分析する",
    formats: ["xlsx"],
    price: { minYen: 3980, maxYen: 7980, initialYen: 3980 },
    dataMode: "empty",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: ["Excel 365 (Windows / Mac)"],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "C-08",
    family: "excel",
    name: "2指標相関・四象限分析",
    audience: ["調査担当", "研究者"],
    jobToBeDone: "散布図と相関から地域を四象限分類する",
    formats: ["xlsx"],
    price: { minYen: 3980, maxYen: 7980, initialYen: 3980 },
    dataMode: "empty",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: ["Excel 365 (Windows / Mac)"],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "C-09",
    family: "excel",
    name: "人口構成・人口ピラミッド",
    audience: ["自治体・公務員", "調査担当"],
    jobToBeDone: "年齢別・男女別の人口構成を可視化する",
    formats: ["xlsx"],
    price: { minYen: 3980, maxYen: 7980, initialYen: 3980 },
    dataMode: "empty",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: ["Excel 365 (Windows / Mac)"],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "C-10",
    family: "excel",
    name: "転入転出・人口移動分析",
    audience: ["自治体・公務員", "移住支援"],
    jobToBeDone: "純移動・流入元・流出先を集計分析する",
    formats: ["xlsx"],
    price: { minYen: 5980, maxYen: 12000, initialYen: 5980 },
    dataMode: "empty",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: ["Excel 365 (Windows / Mac)"],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "C-11",
    family: "excel",
    name: "商圏・出店候補スコアリング",
    audience: ["小売・飲食", "事業企画"],
    jobToBeDone: "人口・所得・競合等から出店候補を採点する",
    formats: ["xlsx"],
    price: { minYen: 7980, maxYen: 19800, initialYen: 7980 },
    dataMode: "empty",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: ["Excel 365 (Windows / Mac)"],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "C-12",
    family: "excel",
    name: "採用市場比較",
    audience: ["人事・採用支援"],
    jobToBeDone: "賃金・求人・人口から採用市場を比較する",
    formats: ["xlsx"],
    price: { minYen: 5980, maxYen: 12000, initialYen: 5980 },
    dataMode: "empty",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: ["Excel 365 (Windows / Mac)"],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "C-13",
    family: "excel",
    name: "移住候補地比較",
    audience: ["個人", "移住支援"],
    jobToBeDone: "住宅・所得・医療・教育で移住候補を比較する",
    formats: ["xlsx"],
    price: { minYen: 5980, maxYen: 12000, initialYen: 5980 },
    dataMode: "empty",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: ["Excel 365 (Windows / Mac)"],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "C-14",
    family: "excel",
    name: "観光需要ダッシュボード",
    audience: ["観光事業者"],
    jobToBeDone: "宿泊・外国人・季節性から観光需要を把握する",
    formats: ["xlsx"],
    price: { minYen: 5980, maxYen: 12000, initialYen: 5980 },
    dataMode: "empty",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: ["Excel 365 (Windows / Mac)"],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "C-15",
    family: "excel",
    name: "地域経済ダッシュボード",
    audience: ["事業企画", "コンサル"],
    jobToBeDone: "所得・事業所・産業から地域経済を俯瞰する",
    formats: ["xlsx"],
    price: { minYen: 5980, maxYen: 12000, initialYen: 5980 },
    dataMode: "empty",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: ["Excel 365 (Windows / Mac)"],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "C-16",
    family: "excel",
    name: "自治体財政比較",
    audience: ["自治体・公務員"],
    jobToBeDone: "財政力・経常収支等で自治体財政を比較する",
    formats: ["xlsx"],
    price: { minYen: 5980, maxYen: 12000, initialYen: 5980 },
    dataMode: "empty",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: ["Excel 365 (Windows / Mac)"],
    risk: "high-stakes",
    status: "cataloged",
  },
  {
    id: "C-17",
    family: "excel",
    name: "医療・介護需給比較",
    audience: ["医療・介護事業者", "自治体・公務員"],
    jobToBeDone: "高齢人口・施設・従事者で医療介護需給を比較する",
    formats: ["xlsx"],
    price: { minYen: 5980, maxYen: 12000, initialYen: 5980 },
    dataMode: "empty",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: ["Excel 365 (Windows / Mac)"],
    risk: "high-stakes",
    status: "cataloged",
  },
  {
    id: "C-18",
    family: "excel",
    name: "教育環境比較",
    audience: ["教育・移住支援"],
    jobToBeDone: "学校・進学・子育てで教育環境を比較する",
    formats: ["xlsx"],
    price: { minYen: 5980, maxYen: 12000, initialYen: 5980 },
    dataMode: "empty",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: ["Excel 365 (Windows / Mac)"],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "C-19",
    family: "excel",
    name: "防災・安全指標比較",
    audience: ["自治体・公務員"],
    jobToBeDone: "災害・事故・消防等で防災安全指標を比較する",
    formats: ["xlsx"],
    price: { minYen: 5980, maxYen: 12000, initialYen: 5980 },
    dataMode: "empty",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: ["Excel 365 (Windows / Mac)"],
    risk: "high-stakes",
    status: "cataloged",
  },
  {
    id: "C-20",
    family: "excel",
    name: "e-Stat CSV整形テンプレート",
    audience: ["調査担当", "データ担当"],
    jobToBeDone: "コード変換・縦横変換でe-Stat CSVを整形する",
    formats: ["xlsx", "csv"],
    price: { minYen: 3980, maxYen: 9800, initialYen: 3980 },
    dataMode: "empty",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: ["Excel 365 (Windows / Mac)", "UTF-8 (BOM) 対応表計算ソフト"],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "C-21",
    family: "excel",
    name: "都道府県コード・名称変換ツール",
    audience: ["調査担当", "データ担当"],
    jobToBeDone: "コード・表記ゆれを正規化変換する",
    formats: ["xlsx", "csv"],
    price: { minYen: 1500, maxYen: 3980, initialYen: 1500 },
    dataMode: "empty",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: ["Excel 365 (Windows / Mac)", "UTF-8 (BOM) 対応表計算ソフト"],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "C-22",
    family: "excel",
    name: "複数年度ファイル統合テンプレート",
    audience: ["調査担当", "データ担当"],
    jobToBeDone: "年次結合・差分算出でファイルを統合する",
    formats: ["xlsx"],
    price: { minYen: 3980, maxYen: 9800, initialYen: 3980 },
    dataMode: "empty",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: ["Excel 365 (Windows / Mac)"],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "C-23",
    family: "excel",
    name: "統計表の出典・メタデータ管理表",
    audience: ["調査担当", "研究者"],
    jobToBeDone: "調査名・年・表番号を一元管理する",
    formats: ["xlsx"],
    price: { minYen: 2980, maxYen: 5980, initialYen: 2980 },
    dataMode: "empty",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: ["Excel 365 (Windows / Mac)"],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "C-24",
    family: "excel",
    name: "レポート用グラフ書き出し管理表",
    audience: ["編集者・ライター", "調査担当"],
    jobToBeDone: "サイズ・色・注記を揃えたグラフ出力を管理する",
    formats: ["xlsx"],
    price: { minYen: 3980, maxYen: 7980, initialYen: 3980 },
    dataMode: "empty",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: ["Excel 365 (Windows / Mac)"],
    risk: "normal",
    status: "cataloged",
  },
];
