import type { ProductDefinition } from "../types";

export const GOVERNMENT_PRODUCTS: readonly ProductDefinition[] = [
  {
    id: "F-01",
    family: "government",
    name: "e-Stat検索・加工を短縮するExcel一式",
    audience: ["自治体職員", "公務員"],
    jobToBeDone: "統計を探し加工する手間を短縮する",
    formats: ["xlsx"],
    price: { minYen: 5980, maxYen: 14800, initialYen: 5980 },
    dataMode: "empty",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: ["Excel 365 (Windows / Mac)"],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "F-02",
    family: "government",
    name: "自県と類似団体の比較テンプレート",
    audience: ["自治体職員", "公務員"],
    jobToBeDone: "比較対象を選定する",
    formats: ["xlsx"],
    price: { minYen: 5980, maxYen: 14800, initialYen: 5980 },
    dataMode: "empty",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: ["Excel 365 (Windows / Mac)"],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "F-03",
    family: "government",
    name: "総合計画KPI管理ダッシュボード",
    audience: ["自治体職員", "企画担当"],
    jobToBeDone: "計画の進捗を管理する",
    formats: ["xlsx"],
    price: { minYen: 9800, maxYen: 29800, initialYen: 9800 },
    dataMode: "empty",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: ["Excel 365 (Windows / Mac)"],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "F-04",
    family: "government",
    name: "EBPMロジックモデル＋指標管理表",
    audience: ["自治体職員", "政策担当"],
    jobToBeDone: "政策を設計する",
    formats: ["xlsx"],
    price: { minYen: 7980, maxYen: 19800, initialYen: 7980 },
    dataMode: "empty",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: ["Excel 365 (Windows / Mac)"],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "F-05",
    family: "government",
    name: "予算要求・査定説明用データスライド",
    audience: ["自治体職員", "財政担当"],
    jobToBeDone: "庁内説明資料を作る",
    formats: ["pptx"],
    price: { minYen: 5980, maxYen: 14800, initialYen: 5980 },
    dataMode: "empty",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: ["PowerPoint 365 (Windows / Mac)"],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "F-06",
    family: "government",
    name: "議会答弁・委員会説明用図表セット",
    audience: ["自治体職員", "議会対応担当"],
    jobToBeDone: "説明資料を作成する",
    formats: ["pptx"],
    price: { minYen: 5980, maxYen: 14800, initialYen: 5980 },
    dataMode: "empty",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: ["PowerPoint 365 (Windows / Mac)"],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "F-07",
    family: "government",
    name: "人口ビジョン更新テンプレート",
    audience: ["自治体職員", "企画担当"],
    jobToBeDone: "人口を分析する",
    formats: ["xlsx"],
    price: { minYen: 7980, maxYen: 19800, initialYen: 7980 },
    dataMode: "empty",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: ["Excel 365 (Windows / Mac)"],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "F-08",
    family: "government",
    name: "地方版総合戦略の指標整理表",
    audience: ["自治体職員", "企画担当"],
    jobToBeDone: "KPIを整理する",
    formats: ["xlsx"],
    price: { minYen: 7980, maxYen: 19800, initialYen: 7980 },
    dataMode: "empty",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: ["Excel 365 (Windows / Mac)"],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "F-09",
    family: "government",
    name: "県勢・市勢要覧の図表テンプレート",
    audience: ["自治体職員", "広報担当"],
    jobToBeDone: "定例資料を作る",
    formats: ["pptx"],
    price: { minYen: 5980, maxYen: 14800, initialYen: 5980 },
    dataMode: "empty",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: ["PowerPoint 365 (Windows / Mac)"],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "F-10",
    family: "government",
    name: "自治体広報向け統計図版セット",
    audience: ["自治体職員", "広報担当"],
    jobToBeDone: "広報を制作する",
    formats: ["svg", "png"],
    price: { minYen: 3980, maxYen: 9800, initialYen: 3980 },
    dataMode: "empty",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: ["SVG / PNG 対応ビューア"],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "F-11",
    family: "government",
    name: "統計出典・調査年の管理台帳",
    audience: ["自治体職員", "統計担当"],
    jobToBeDone: "引用を管理する",
    formats: ["xlsx"],
    price: { minYen: 2980, maxYen: 7980, initialYen: 2980 },
    dataMode: "empty",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: ["Excel 365 (Windows / Mac)"],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "F-12",
    family: "government",
    name: "オープンデータ公開チェックリスト",
    audience: ["自治体職員", "情報公開担当"],
    jobToBeDone: "公開品質を確認する",
    formats: ["pdf", "xlsx"],
    price: { minYen: 2980, maxYen: 7980, initialYen: 2980 },
    dataMode: "empty",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: ["PDF 閲覧環境", "Excel 365 (Windows / Mac)"],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "F-13",
    family: "government",
    name: "公務員向け統計グラフ作成研修教材",
    audience: ["自治体職員", "研修担当"],
    jobToBeDone: "人材を育成する",
    formats: ["pptx", "pdf"],
    price: { minYen: 5980, maxYen: 19800, initialYen: 5980 },
    dataMode: "empty",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: ["PowerPoint 365 (Windows / Mac)", "PDF 閲覧環境"],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "F-14",
    family: "government",
    name: "公務員向けPowerPoint図表改善教材",
    audience: ["自治体職員", "資料作成担当"],
    jobToBeDone: "資料品質を改善する",
    formats: ["pptx", "pdf"],
    price: { minYen: 5980, maxYen: 19800, initialYen: 5980 },
    dataMode: "empty",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: ["PowerPoint 365 (Windows / Mac)", "PDF 閲覧環境"],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "F-15",
    family: "government",
    name: "Claude Code / AIで統計加工する演習教材",
    audience: ["自治体職員", "業務効率化担当"],
    jobToBeDone: "業務を効率化する",
    formats: ["pptx", "pdf"],
    price: { minYen: 7980, maxYen: 24800, initialYen: 7980 },
    dataMode: "empty",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: ["PowerPoint 365 (Windows / Mac)", "PDF 閲覧環境"],
    risk: "normal",
    status: "cataloged",
  },
];
