import type { ProductDefinition } from "../types";

export const INDUSTRY_PRODUCTS: readonly ProductDefinition[] = [
  {
    id: "E-01",
    family: "industry",
    name: "飲食店出店候補地パック",
    audience: ["飲食店経営者", "商圏選定担当"],
    jobToBeDone: "商圏を選定する",
    formats: ["pptx", "xlsx", "pdf"],
    price: { minYen: 7980, maxYen: 19800, initialYen: 7980 },
    dataMode: "fixed-year",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: [
      "PowerPoint 365 (Windows / Mac)",
      "Excel 365 (Windows / Mac)",
      "PDF 閲覧環境",
    ],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "E-02",
    family: "industry",
    name: "小売店出店候補地パック",
    audience: ["小売店経営者", "出店担当"],
    jobToBeDone: "人口・所得・消費を比較する",
    formats: ["pptx", "xlsx", "pdf"],
    price: { minYen: 7980, maxYen: 19800, initialYen: 7980 },
    dataMode: "fixed-year",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: [
      "PowerPoint 365 (Windows / Mac)",
      "Excel 365 (Windows / Mac)",
      "PDF 閲覧環境",
    ],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "E-03",
    family: "industry",
    name: "学習塾・教育サービス出店パック",
    audience: ["学習塾経営者", "教育サービス事業者"],
    jobToBeDone: "子ども人口・所得・学校数を把握する",
    formats: ["pptx", "xlsx", "pdf"],
    price: { minYen: 7980, maxYen: 19800, initialYen: 7980 },
    dataMode: "fixed-year",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: [
      "PowerPoint 365 (Windows / Mac)",
      "Excel 365 (Windows / Mac)",
      "PDF 閲覧環境",
    ],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "E-04",
    family: "industry",
    name: "介護事業所出店パック",
    audience: ["介護事業者", "出店担当"],
    jobToBeDone: "高齢人口・供給状況を把握する",
    formats: ["pptx", "xlsx", "pdf"],
    price: { minYen: 7980, maxYen: 19800, initialYen: 7980 },
    dataMode: "fixed-year",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: [
      "PowerPoint 365 (Windows / Mac)",
      "Excel 365 (Windows / Mac)",
      "PDF 閲覧環境",
    ],
    risk: "high-stakes",
    status: "cataloged",
  },
  {
    id: "E-05",
    family: "industry",
    name: "クリニック開業地域比較パック",
    audience: ["医師", "クリニック開業希望者"],
    jobToBeDone: "人口・医療需給の概況を比較する",
    formats: ["pptx", "xlsx", "pdf"],
    price: { minYen: 9800, maxYen: 24800, initialYen: 9800 },
    dataMode: "fixed-year",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: [
      "PowerPoint 365 (Windows / Mac)",
      "Excel 365 (Windows / Mac)",
      "PDF 閲覧環境",
    ],
    risk: "high-stakes",
    status: "cataloged",
  },
  {
    id: "E-06",
    family: "industry",
    name: "宿泊施設・観光事業パック",
    audience: ["宿泊事業者", "観光事業者"],
    jobToBeDone: "観光需要・季節性を把握する",
    formats: ["pptx", "xlsx", "pdf"],
    price: { minYen: 7980, maxYen: 19800, initialYen: 7980 },
    dataMode: "fixed-year",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: [
      "PowerPoint 365 (Windows / Mac)",
      "Excel 365 (Windows / Mac)",
      "PDF 閲覧環境",
    ],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "E-07",
    family: "industry",
    name: "不動産営業地域比較パック",
    audience: ["不動産営業担当", "不動産事業者"],
    jobToBeDone: "人口移動・住宅・地価を比較する",
    formats: ["pptx", "xlsx", "pdf"],
    price: { minYen: 7980, maxYen: 19800, initialYen: 7980 },
    dataMode: "fixed-year",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: [
      "PowerPoint 365 (Windows / Mac)",
      "Excel 365 (Windows / Mac)",
      "PDF 閲覧環境",
    ],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "E-08",
    family: "industry",
    name: "採用拠点・支店候補パック",
    audience: ["人事採用担当", "拠点開発担当"],
    jobToBeDone: "労働人口・賃金・アクセスを比較する",
    formats: ["pptx", "xlsx", "pdf"],
    price: { minYen: 7980, maxYen: 19800, initialYen: 7980 },
    dataMode: "fixed-year",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: [
      "PowerPoint 365 (Windows / Mac)",
      "Excel 365 (Windows / Mac)",
      "PDF 閲覧環境",
    ],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "E-09",
    family: "industry",
    name: "EC地域マーケティングパック",
    audience: ["EC事業者", "マーケティング担当"],
    jobToBeDone: "消費・世帯・所得を把握する",
    formats: ["pptx", "xlsx", "pdf"],
    price: { minYen: 5980, maxYen: 14800, initialYen: 5980 },
    dataMode: "fixed-year",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: [
      "PowerPoint 365 (Windows / Mac)",
      "Excel 365 (Windows / Mac)",
      "PDF 閲覧環境",
    ],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "E-10",
    family: "industry",
    name: "ふるさと納税企画パック",
    audience: ["自治体担当者", "ふるさと納税事業者"],
    jobToBeDone: "寄付・産品・地域訴求を企画する",
    formats: ["pptx", "xlsx", "pdf"],
    price: { minYen: 5980, maxYen: 14800, initialYen: 5980 },
    dataMode: "fixed-year",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: [
      "PowerPoint 365 (Windows / Mac)",
      "Excel 365 (Windows / Mac)",
      "PDF 閲覧環境",
    ],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "E-11",
    family: "industry",
    name: "地域金融・営業企画パック",
    audience: ["地域金融機関担当者", "営業企画担当"],
    jobToBeDone: "産業・人口・事業所を把握する",
    formats: ["pptx", "xlsx", "pdf"],
    price: { minYen: 7980, maxYen: 19800, initialYen: 7980 },
    dataMode: "fixed-year",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: [
      "PowerPoint 365 (Windows / Mac)",
      "Excel 365 (Windows / Mac)",
      "PDF 閲覧環境",
    ],
    risk: "high-stakes",
    status: "cataloged",
  },
  {
    id: "E-12",
    family: "industry",
    name: "自治体シティプロモーションパック",
    audience: ["自治体広報担当", "シティプロモーション担当"],
    jobToBeDone: "県勢・比較・強みを抽出する",
    formats: ["pptx", "xlsx", "pdf"],
    price: { minYen: 7980, maxYen: 19800, initialYen: 7980 },
    dataMode: "fixed-year",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: [
      "PowerPoint 365 (Windows / Mac)",
      "Excel 365 (Windows / Mac)",
      "PDF 閲覧環境",
    ],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "E-13",
    family: "industry",
    name: "地方創生プロジェクト企画パック",
    audience: ["自治体担当者", "地方創生コンサル"],
    jobToBeDone: "課題構造・KPIを整理する",
    formats: ["pptx", "xlsx", "pdf"],
    price: { minYen: 9800, maxYen: 24800, initialYen: 9800 },
    dataMode: "fixed-year",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: [
      "PowerPoint 365 (Windows / Mac)",
      "Excel 365 (Windows / Mac)",
      "PDF 閲覧環境",
    ],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "E-14",
    family: "industry",
    name: "地域メディア記事企画パック",
    audience: ["地域メディア編集者", "記者"],
    jobToBeDone: "ネタ・図表・出典を揃える",
    formats: ["pptx", "xlsx", "pdf"],
    price: { minYen: 5980, maxYen: 14800, initialYen: 5980 },
    dataMode: "fixed-year",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: [
      "PowerPoint 365 (Windows / Mac)",
      "Excel 365 (Windows / Mac)",
      "PDF 閲覧環境",
    ],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "E-15",
    family: "industry",
    name: "YouTube都道府県ネタ制作パック",
    audience: ["YouTuber", "動画制作者"],
    jobToBeDone: "ランキング・地図・台本骨子を揃える",
    formats: ["pptx", "xlsx", "pdf"],
    price: { minYen: 5980, maxYen: 14800, initialYen: 5980 },
    dataMode: "fixed-year",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: [
      "PowerPoint 365 (Windows / Mac)",
      "Excel 365 (Windows / Mac)",
      "PDF 閲覧環境",
    ],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "E-16",
    family: "industry",
    name: "SNS運用向け地域統計投稿パック",
    audience: ["SNS運用担当", "コンテンツ制作者"],
    jobToBeDone: "正方形・縦長図版を揃える",
    formats: ["pptx", "xlsx", "pdf"],
    price: { minYen: 3980, maxYen: 9800, initialYen: 3980 },
    dataMode: "fixed-year",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: [
      "PowerPoint 365 (Windows / Mac)",
      "Excel 365 (Windows / Mac)",
      "PDF 閲覧環境",
    ],
    risk: "normal",
    status: "cataloged",
  },
];
