import type { ProductDefinition } from "../types";

export const LICENSE_PRODUCTS: readonly ProductDefinition[] = [
  {
    id: "K-01",
    family: "license",
    name: "空テンプレート版",
    audience: ["全商品共通"],
    jobToBeDone: "データなしのテンプレートを更新責任なしで使う",
    formats: [],
    price: { minYen: 0, maxYen: 0, initialYen: 0 },
    dataMode: "empty",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: ["各ベース商品の対応環境に準ずる"],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "K-02",
    family: "license",
    name: "サンプルデータ版",
    audience: ["全商品共通"],
    jobToBeDone: "架空または公的サンプル付きで商品を試す",
    formats: [],
    price: { minYen: 0, maxYen: 0, initialYen: 0 },
    dataMode: "sample",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: ["各ベース商品の対応環境に準ずる"],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "K-03",
    family: "license",
    name: "基準年固定データ版",
    audience: ["全商品共通"],
    jobToBeDone: "調査年を明記した買い切りデータで使う",
    formats: [],
    price: { minYen: 0, maxYen: 0, initialYen: 0 },
    dataMode: "fixed-year",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: ["各ベース商品の対応環境に準ずる"],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "K-04",
    family: "license",
    name: "最新年更新版",
    audience: ["全商品共通"],
    jobToBeDone: "更新時期と対象統計を限定して最新年データを使う",
    formats: [],
    price: { minYen: 0, maxYen: 0, initialYen: 0 },
    dataMode: "updated",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: ["各ベース商品の対応環境に準ずる"],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "K-05",
    family: "license",
    name: "個人ライセンス",
    audience: ["全商品共通"],
    jobToBeDone: "購入者本人のみが利用するライセンスで使う",
    formats: [],
    price: { minYen: 0, maxYen: 0, initialYen: 0 },
    dataMode: "empty",
    metrics: [],
    templateIds: [],
    licenseId: "personal",
    supportLevel: "manual",
    compatibility: ["各ベース商品の対応環境に準ずる"],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "K-06",
    family: "license",
    name: "1法人ライセンス",
    audience: ["全商品共通"],
    jobToBeDone: "1法人内での利用を許可するライセンスで使う",
    formats: [],
    price: { minYen: 0, maxYen: 0, initialYen: 0 },
    dataMode: "empty",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: ["各ベース商品の対応環境に準ずる"],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "K-07",
    family: "license",
    name: "クライアントワーク可",
    audience: ["全商品共通"],
    jobToBeDone: "成果物への組み込みを許可するライセンスで使う",
    formats: [],
    price: { minYen: 0, maxYen: 0, initialYen: 0 },
    dataMode: "empty",
    metrics: [],
    templateIds: [],
    licenseId: "client-work",
    supportLevel: "manual",
    compatibility: ["各ベース商品の対応環境に準ずる"],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "K-08",
    family: "license",
    name: "教育機関ライセンス",
    audience: ["全商品共通"],
    jobToBeDone: "授業・配布範囲を限定した教育機関向けに使う",
    formats: [],
    price: { minYen: 0, maxYen: 0, initialYen: 0 },
    dataMode: "empty",
    metrics: [],
    templateIds: [],
    licenseId: "education",
    supportLevel: "manual",
    compatibility: ["各ベース商品の対応環境に準ずる"],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "K-09",
    family: "license",
    name: "カスタマイズ付き",
    audience: ["全商品共通"],
    jobToBeDone: "色・ロゴ・項目を変更したカスタマイズ版で使う",
    formats: [],
    price: { minYen: 0, maxYen: 0, initialYen: 0 },
    dataMode: "empty",
    metrics: [],
    templateIds: [],
    licenseId: "customization",
    supportLevel: "manual",
    compatibility: ["各ベース商品の対応環境に準ずる"],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "K-10",
    family: "license",
    name: "サポート付き",
    audience: ["全商品共通"],
    jobToBeDone: "導入説明と一定期間の質問対応を受けて使う",
    formats: [],
    price: { minYen: 0, maxYen: 0, initialYen: 0 },
    dataMode: "empty",
    metrics: [],
    templateIds: [],
    licenseId: "support-included",
    supportLevel: "limited",
    compatibility: ["各ベース商品の対応環境に準ずる"],
    risk: "normal",
    status: "cataloged",
  },
];
