import type { ProductDefinition } from "../types";

export const MEDIA_PRODUCTS: readonly ProductDefinition[] = [
  {
    id: "G-01",
    family: "media",
    name: "都道府県ランキング記事用図版セット",
    audience: ["メディア編集者", "ライター"],
    jobToBeDone: "ランキング記事に図版を使う",
    formats: ["svg", "png", "pptx"],
    price: { minYen: 2980, maxYen: 7980, initialYen: 2980 },
    dataMode: "sample",
    metrics: [],
    templateIds: [],
    licenseId: "client-work",
    supportLevel: "manual",
    compatibility: [
      "SVG / PNG 対応ビューア",
      "PowerPoint 365 (Windows / Mac)",
    ],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "G-02",
    family: "media",
    name: "地域ニュース用コロプレス地図",
    audience: ["メディア編集者", "記者"],
    jobToBeDone: "地域ニュースに地図を使う",
    formats: ["svg", "pptx"],
    price: { minYen: 2980, maxYen: 7980, initialYen: 2980 },
    dataMode: "sample",
    metrics: [],
    templateIds: [],
    licenseId: "client-work",
    supportLevel: "manual",
    compatibility: [
      "SVG / PNG 対応ビューア",
      "PowerPoint 365 (Windows / Mac)",
    ],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "G-03",
    family: "media",
    name: "YouTubeランキング動画用スライド",
    audience: ["YouTuber", "動画制作者"],
    jobToBeDone: "ランキング動画のスライドを作る",
    formats: ["pptx", "png"],
    price: { minYen: 3980, maxYen: 9800, initialYen: 3980 },
    dataMode: "sample",
    metrics: [],
    templateIds: [],
    licenseId: "client-work",
    supportLevel: "manual",
    compatibility: [
      "PowerPoint 365 (Windows / Mac)",
      "SVG / PNG 対応ビューア",
    ],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "G-04",
    family: "media",
    name: "ショート動画用縦型統計カード",
    audience: ["動画制作者", "SNS運用担当"],
    jobToBeDone: "ショート動画用の統計カードを作る",
    formats: ["pptx", "png"],
    price: { minYen: 2980, maxYen: 7980, initialYen: 2980 },
    dataMode: "sample",
    metrics: [],
    templateIds: [],
    licenseId: "client-work",
    supportLevel: "manual",
    compatibility: [
      "PowerPoint 365 (Windows / Mac)",
      "SVG / PNG 対応ビューア",
    ],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "G-05",
    family: "media",
    name: "Instagramカルーセル図表テンプレート",
    audience: ["SNS運用担当", "コンテンツ制作者"],
    jobToBeDone: "カルーセル図表を作る",
    formats: ["pptx", "png"],
    price: { minYen: 2980, maxYen: 7980, initialYen: 2980 },
    dataMode: "sample",
    metrics: [],
    templateIds: [],
    licenseId: "client-work",
    supportLevel: "manual",
    compatibility: [
      "PowerPoint 365 (Windows / Mac)",
      "SVG / PNG 対応ビューア",
    ],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "G-06",
    family: "media",
    name: "X投稿向け1枚統計図解",
    audience: ["SNS運用担当", "コンテンツ制作者"],
    jobToBeDone: "1枚の統計図解を作る",
    formats: ["pptx", "png"],
    price: { minYen: 1980, maxYen: 4980, initialYen: 1980 },
    dataMode: "sample",
    metrics: [],
    templateIds: [],
    licenseId: "client-work",
    supportLevel: "manual",
    compatibility: [
      "PowerPoint 365 (Windows / Mac)",
      "SVG / PNG 対応ビューア",
    ],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "G-07",
    family: "media",
    name: "note記事用地図・チャートセット",
    audience: ["noteクリエイター", "ライター"],
    jobToBeDone: "note記事に地図・チャートを使う",
    formats: ["svg", "png"],
    price: { minYen: 2980, maxYen: 7980, initialYen: 2980 },
    dataMode: "sample",
    metrics: [],
    templateIds: [],
    licenseId: "client-work",
    supportLevel: "manual",
    compatibility: ["SVG / PNG 対応ビューア"],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "G-08",
    family: "media",
    name: "編集部向け年間都道府県ネタカレンダー",
    audience: ["メディア編集部", "編集者"],
    jobToBeDone: "年間の企画ネタを揃える",
    formats: ["xlsx", "pdf"],
    price: { minYen: 3980, maxYen: 9800, initialYen: 3980 },
    dataMode: "sample",
    metrics: [],
    templateIds: [],
    licenseId: "client-work",
    supportLevel: "manual",
    compatibility: ["Excel 365 (Windows / Mac)", "PDF 閲覧環境"],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "G-09",
    family: "media",
    name: "地域データ記事の構成テンプレート",
    audience: ["ライター", "メディア編集者"],
    jobToBeDone: "記事構成をテンプレ化する",
    formats: ["docx", "pptx"],
    price: { minYen: 2980, maxYen: 7980, initialYen: 2980 },
    dataMode: "sample",
    metrics: [],
    templateIds: [],
    licenseId: "client-work",
    supportLevel: "manual",
    compatibility: [
      "Word 365 (Windows / Mac)",
      "PowerPoint 365 (Windows / Mac)",
    ],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "G-10",
    family: "media",
    name: "出典・注記・ファクトチェック台帳",
    audience: ["メディア編集者", "校正担当"],
    jobToBeDone: "出典と注記を管理する",
    formats: ["xlsx"],
    price: { minYen: 2980, maxYen: 7980, initialYen: 2980 },
    dataMode: "sample",
    metrics: [],
    templateIds: [],
    licenseId: "client-work",
    supportLevel: "manual",
    compatibility: ["Excel 365 (Windows / Mac)"],
    risk: "normal",
    status: "cataloged",
  },
];
