/**
 * テーマパック・カタログ (SSOT) — P-01〜P-14。
 *
 * 2026-07-23: 旧 174 件 (A-01〜L-07・family 別 12 ファイル) を破壊的に縮約した。同一テーマが
 * family 横断で重複していた (観光 = B-06/C-14/D-08/E-06 等) ため、出品・実データ接続・管理の単位を
 * テーマパックへ集約する。sourceIds に吸収元の旧 ID をトレースする (非網羅・参照用)。
 *
 * 出品規律: 実データを接続済みのパックだけ status を approved/listed にできる (validator が datasets の
 * 実在を検査)。当面 P-01 のみ実データ接続済 (旧 D-01 の 4 データセットを継承)。他は cataloged 固定。
 */
import type { ProductDefinition } from "../types";
import { PACK_RANKING_KEYS } from "../pack-rankingkeys.generated";

/** データ系パック (pptx+xlsx+csv+pdf+png) の共通対応環境。 */
const OFFICE_COMPAT: readonly string[] = [
  "PowerPoint 365 (Windows / Mac)",
  "Excel 365 (Windows / Mac)",
  "UTF-8 (BOM) 対応表計算ソフト",
  "PDF 閲覧環境",
];

/** データ系パックの標準形式。 */
const DATA_FORMATS = ["pptx", "xlsx", "csv", "pdf", "png"] as const;

/**
 * パック定義 (rankingKeys を除く)。rankingKeys は pack-rankingkeys.generated.ts から
 * id 単位で注入する (2,000+ キーを literal に転記しないため)。
 */
const RAW_PACKS: readonly Omit<ProductDefinition, "rankingKeys">[] = [
  {
    id: "P-01",
    theme: "population-household",
    name: "人口・世帯データパック（47都道府県）",
    audience: ["企画・営業", "自治体・公務員", "研究者"],
    jobToBeDone: "人口・面積・世帯・所得を一冊で把握する",
    formats: [...DATA_FORMATS],
    price: { minYen: 4000, maxYen: 8000, initialYen: 4000 },
    dataMode: "fixed-year",
    metrics: [],
    datasets: [
      "total-population",
      "total-area-including-northern-territories-and-takeshima",
      "general-households",
      "per-capita-prefectural-income-h27",
    ],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: OFFICE_COMPAT,
    risk: "normal",
    status: "listed",
    sourceIds: ["D-01"],
  },
  {
    id: "P-02",
    theme: "income-wage-hiring",
    name: "所得・賃金・採用データパック（47都道府県）",
    audience: ["人事・採用支援", "事業企画"],
    jobToBeDone: "県民所得・賃金・求人・採用市場をまとめて把握・比較する",
    formats: [...DATA_FORMATS],
    price: { minYen: 5000, maxYen: 12000, initialYen: 5000 },
    dataMode: "sample",
    metrics: [],
    datasets: [
      "per-capita-prefectural-income-h27",
      "avg-salary-all-prefecture",
      "active-job-opening-ratio",
      "annual-income-per-household",
      "disposable-income-worker-households",
      "dual-income-household-ratio",
    ],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: OFFICE_COMPAT,
    risk: "normal",
    status: "approved",
    sourceIds: ["B-05", "C-12", "D-03", "E-08", "J-08"],
  },
  {
    id: "P-03",
    theme: "tourism-lodging",
    name: "観光・宿泊データパック（47都道府県）",
    audience: ["観光事業者", "自治体・公務員"],
    jobToBeDone: "宿泊・訪日・観光消費の地域差をまとめて把握・比較する",
    formats: [...DATA_FORMATS],
    price: { minYen: 5000, maxYen: 12000, initialYen: 5000 },
    dataMode: "sample",
    metrics: [],
    datasets: [
      "total-overnight-guests",
      "total-overnight-guests-foreign",
      "number-of-hotel-facilities",
      "number-of-hotel-rooms",
      "travel-participation-rate-overnight",
    ],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: OFFICE_COMPAT,
    risk: "normal",
    status: "approved",
    sourceIds: ["B-06", "C-14", "D-08", "E-06"],
  },
  {
    id: "P-04",
    theme: "municipal-finance",
    name: "自治体財政データパック（47都道府県）",
    audience: ["自治体・公務員", "研究者"],
    jobToBeDone: "歳入歳出・財政指標・類似団体比較をまとめて把握する",
    formats: [...DATA_FORMATS],
    price: { minYen: 6000, maxYen: 14000, initialYen: 6000 },
    dataMode: "sample",
    metrics: [],
    datasets: [
      "fiscal-strength-index-prefecture",
      "real-public-debt-service-ratio",
      "local-tax-prefecture",
      "laspeyres-index-prefecture",
      "total-revenue-prefecture",
      "independent-revenue-prefecture",
    ],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: OFFICE_COMPAT,
    risk: "high-stakes",
    status: "approved",
    sourceIds: ["C-16", "D-10", "F-01", "F-02"],
  },
  {
    id: "P-05",
    theme: "healthcare-nursing",
    name: "医療・介護データパック（47都道府県）",
    audience: ["医療・介護事業者", "自治体・公務員"],
    jobToBeDone: "病床・医師・介護・高齢化をまとめて把握・比較する",
    formats: [...DATA_FORMATS],
    price: { minYen: 5000, maxYen: 12000, initialYen: 5000 },
    dataMode: "sample",
    metrics: [],
    datasets: [
      "physicians-in-medical-facilities-per-100k",
      "general-hospital-bed-count-per-100k",
      "nurses-per-100k-population",
      "nursing-welfare-facility-count-per-100k-65plus",
      "aging-index",
      "average-life-expectancy-male",
    ],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: OFFICE_COMPAT,
    risk: "high-stakes",
    status: "approved",
    sourceIds: ["D-06", "C-17", "E-04"],
  },
  {
    id: "P-06",
    theme: "education-childcare",
    name: "教育・子育てデータパック（47都道府県）",
    audience: ["教育関係者", "移住支援", "自治体・公務員"],
    jobToBeDone: "学校・保育・進学・出生・子育て環境をまとめて把握する",
    formats: [...DATA_FORMATS],
    price: { minYen: 5000, maxYen: 12000, initialYen: 5000 },
    dataMode: "sample",
    metrics: [],
    datasets: [
      "high-school-advancement-rate",
      "total-fertility-rate",
      "certified-childcare-center-count-per-100k-0-5",
      "elementary-school-students-per-teacher",
      "childcare-employment-rate",
      "crude-birth-rate",
    ],
    templateIds: [],
    licenseId: "education",
    supportLevel: "manual",
    compatibility: OFFICE_COMPAT,
    risk: "normal",
    status: "approved",
    sourceIds: ["D-07", "H-01"],
  },
  {
    id: "P-07",
    theme: "migration-living",
    name: "移住・生活データパック（47都道府県）",
    audience: ["移住支援", "個人", "自治体・公務員"],
    jobToBeDone: "住宅・物価・人口移動など移住候補地の生活データを比較する",
    formats: [...DATA_FORMATS],
    price: { minYen: 4500, maxYen: 9000, initialYen: 4500 },
    dataMode: "sample",
    metrics: [],
    datasets: [
      "social-increase-rate",
      "consumer-price-difference-index-overall",
      "consumer-price-difference-index-housing",
      "residential-land-price-change-rate",
      "home-ownership-rate-kakei",
      "private-rental-housing-rent-per-3-3m2",
    ],
    templateIds: [],
    licenseId: "personal",
    supportLevel: "manual",
    compatibility: OFFICE_COMPAT,
    risk: "normal",
    status: "approved",
    sourceIds: ["I-01", "D-05", "D-19"],
  },
  {
    id: "P-08",
    theme: "retail-trade-area",
    name: "出店・商圏データパック（47都道府県）",
    audience: ["小売・飲食事業者", "事業企画"],
    jobToBeDone: "出店候補地の商圏・人口・購買力を点数化して比較する",
    formats: [...DATA_FORMATS],
    price: { minYen: 6000, maxYen: 14000, initialYen: 6000 },
    dataMode: "sample",
    metrics: [],
    datasets: [
      "annual-sales-amount",
      "annual-sales-amount-per-establishment",
      "convenience-store-count-per-100k",
      "department-store-count-per-100k",
      "total-population",
      "per-capita-prefectural-income-h27",
    ],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: OFFICE_COMPAT,
    risk: "normal",
    status: "approved",
    sourceIds: ["E-01", "E-02", "C-11"],
  },
  {
    id: "P-09",
    theme: "industry-economy",
    name: "産業・経済データパック（47都道府県）",
    audience: ["事業企画", "コンサル", "研究者"],
    jobToBeDone: "産業構成・事業所・就業者・経済規模をまとめて把握する",
    formats: [...DATA_FORMATS],
    price: { minYen: 5000, maxYen: 12000, initialYen: 5000 },
    dataMode: "sample",
    metrics: [],
    datasets: [
      "manufacturing-shipment-amount",
      "manufacturing-establishments",
      "manufacturing-employees",
      "factory-establishment-count",
      "gross-prefectural-product-expenditure-nominal-h27",
      "annual-sales-amount",
    ],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: OFFICE_COMPAT,
    risk: "normal",
    status: "approved",
    sourceIds: ["D-09"],
  },
  {
    id: "P-10",
    theme: "disaster-infrastructure",
    name: "防災・インフラデータパック（47都道府県）",
    audience: ["自治体・公務員", "事業企画"],
    jobToBeDone: "災害・交通・エネルギー・インフラをまとめて把握する",
    formats: [...DATA_FORMATS],
    price: { minYen: 5000, maxYen: 12000, initialYen: 5000 },
    dataMode: "sample",
    metrics: [],
    datasets: [
      "road-length-per-km2",
      "main-road-length-per-km2",
      "sewerage-penetration-rate-2012on",
      "water-supply-annual-volume",
      "disaster-damage-amount-per-person",
      "nature-park-area-ratio",
    ],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: OFFICE_COMPAT,
    risk: "high-stakes",
    status: "approved",
    sourceIds: ["D-13", "D-11", "D-12"],
  },
  {
    id: "P-11",
    theme: "map-chart-assets",
    name: "都道府県 地図・チャート素材集",
    audience: ["編集者・ライター", "企画・営業", "クリエイター"],
    jobToBeDone: "資料・記事・SNS にそのまま貼れる地図・ランキング図版を入手する",
    formats: ["pptx", "svg", "png", "pdf"],
    price: { minYen: 4000, maxYen: 8000, initialYen: 4000 },
    dataMode: "sample",
    metrics: [],
    datasets: [
      "total-population",
      "total-area-including-northern-territories-and-takeshima",
      "general-households",
      "per-capita-prefectural-income-h27",
    ],
    templateIds: [],
    licenseId: "client-work",
    supportLevel: "manual",
    compatibility: [
      "PowerPoint 365 (Windows / Mac)",
      "SVG 対応ベクター編集ソフト",
      "PNG 閲覧環境",
      "PDF 閲覧環境",
    ],
    risk: "normal",
    status: "approved",
    sourceIds: ["A-01", "G-01"],
  },
  {
    id: "P-12",
    theme: "all-in-one",
    name: "都道府県データ 全部入りバンドル",
    audience: ["企画・営業", "自治体・公務員", "編集者・ライター"],
    jobToBeDone: "テーマ横断で都道府県データと図表を一括で入手する",
    formats: ["pptx", "xlsx", "csv", "svg", "png", "pdf"],
    price: { minYen: 10000, maxYen: 30000, initialYen: 10000 },
    dataMode: "sample",
    metrics: [],
    datasets: [
      "total-population",
      "total-area-including-northern-territories-and-takeshima",
      "general-households",
      "per-capita-prefectural-income-h27",
      "avg-salary-all-prefecture",
      "active-job-opening-ratio",
      "annual-income-per-household",
      "disposable-income-worker-households",
      "dual-income-household-ratio",
      "total-overnight-guests",
      "total-overnight-guests-foreign",
      "number-of-hotel-facilities",
      "number-of-hotel-rooms",
      "travel-participation-rate-overnight",
      "fiscal-strength-index-prefecture",
      "real-public-debt-service-ratio",
      "local-tax-prefecture",
      "laspeyres-index-prefecture",
      "total-revenue-prefecture",
      "independent-revenue-prefecture",
      "physicians-in-medical-facilities-per-100k",
      "general-hospital-bed-count-per-100k",
      "nurses-per-100k-population",
      "nursing-welfare-facility-count-per-100k-65plus",
      "aging-index",
      "average-life-expectancy-male",
      "high-school-advancement-rate",
      "total-fertility-rate",
      "certified-childcare-center-count-per-100k-0-5",
      "elementary-school-students-per-teacher",
      "childcare-employment-rate",
      "crude-birth-rate",
      "social-increase-rate",
      "consumer-price-difference-index-overall",
      "consumer-price-difference-index-housing",
      "residential-land-price-change-rate",
      "home-ownership-rate-kakei",
      "private-rental-housing-rent-per-3-3m2",
      "annual-sales-amount",
      "annual-sales-amount-per-establishment",
      "convenience-store-count-per-100k",
      "department-store-count-per-100k",
      "manufacturing-shipment-amount",
      "manufacturing-establishments",
      "manufacturing-employees",
      "factory-establishment-count",
      "gross-prefectural-product-expenditure-nominal-h27",
      "road-length-per-km2",
      "main-road-length-per-km2",
      "sewerage-penetration-rate-2012on",
      "water-supply-annual-volume",
      "disaster-damage-amount-per-person",
      "nature-park-area-ratio",
    ],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: OFFICE_COMPAT,
    risk: "normal",
    status: "cataloged",
    sourceIds: ["D-20"],
  },
  {
    id: "P-13",
    theme: "free-trial",
    name: "都道府県データ 無料お試しサンプル",
    audience: ["はじめての購入者"],
    jobToBeDone: "有料版を買う前に地図・データの品質と使い勝手を無料で試す",
    formats: ["pdf", "png", "csv"],
    price: { minYen: 0, maxYen: 0, initialYen: 0 },
    dataMode: "fixed-year",
    metrics: [],
    datasets: ["total-population"],
    templateIds: [],
    licenseId: "free-sample",
    supportLevel: "none",
    compatibility: ["PDF 閲覧環境", "PNG 閲覧環境"],
    risk: "normal",
    status: "cataloged",
    sourceIds: ["L-01"],
  },
  {
    id: "P-14",
    theme: "household-consumption",
    name: "家計・消費データパック（47都道府県）",
    audience: ["企画・営業", "編集者・ライター", "研究者"],
    jobToBeDone: "家計調査の消費支出・消費数量を品目横断でまとめて把握・比較する",
    formats: [...DATA_FORMATS],
    price: { minYen: 5000, maxYen: 12000, initialYen: 5000 },
    dataMode: "fixed-year",
    metrics: [],
    // 全指標は pack snapshot、販売内容の代表値は git TS の基準年固定 dataset が供給する。
    datasets: ["beef-consumption-expenditure"],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: OFFICE_COMPAT,
    risk: "normal",
    // 家計消費品目 (source.kind=kakei-chousa) を P-09 から分離。代表 dataset は接続済み。
    // 出品可能化 (approved) は Office 実機検証後 (人間工程)。
    status: "cataloged",
    sourceIds: ["P-09"],
  },
];

/** rankingKeys を id 単位で注入した最終カタログ (SSOT)。 */
export const PACKS: readonly ProductDefinition[] = RAW_PACKS.map((p) => ({
  ...p,
  rankingKeys: PACK_RANKING_KEYS[p.id] ?? [],
}));
