import type { ProductDefinition } from "../types";

export const POWERPOINT_PRODUCTS: readonly ProductDefinition[] = [
  {
    id: "B-01",
    family: "powerpoint",
    name: "都道府県データ説明スライド20枚セット",
    audience: ["企画・営業", "公務員"],
    jobToBeDone: "都道府県データを社内外に説明する",
    formats: ["pptx"],
    price: { minYen: 3980, maxYen: 5980, initialYen: 3980 },
    dataMode: "sample",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: ["PowerPoint 365 (Windows / Mac)"],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "B-02",
    family: "powerpoint",
    name: "地域市場調査レポート雛形",
    audience: ["コンサル", "事業企画"],
    jobToBeDone: "地域市場を調査しレポートにまとめる",
    formats: ["pptx"],
    price: { minYen: 4980, maxYen: 9800, initialYen: 4980 },
    dataMode: "sample",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: ["PowerPoint 365 (Windows / Mac)"],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "B-03",
    family: "powerpoint",
    name: "出店候補地域の比較提案書",
    audience: ["小売", "飲食"],
    jobToBeDone: "出店候補地域を比較提案する",
    formats: ["pptx"],
    price: { minYen: 4980, maxYen: 9800, initialYen: 4980 },
    dataMode: "sample",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: ["PowerPoint 365 (Windows / Mac)"],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "B-04",
    family: "powerpoint",
    name: "移住候補地の比較資料",
    audience: ["個人", "移住支援"],
    jobToBeDone: "移住候補地を比較検討する",
    formats: ["pptx"],
    price: { minYen: 3980, maxYen: 7980, initialYen: 3980 },
    dataMode: "sample",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: ["PowerPoint 365 (Windows / Mac)"],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "B-05",
    family: "powerpoint",
    name: "採用・賃金地域比較資料",
    audience: ["人事", "採用支援"],
    jobToBeDone: "採用・賃金の地域差を比較する",
    formats: ["pptx"],
    price: { minYen: 4980, maxYen: 9800, initialYen: 4980 },
    dataMode: "sample",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: ["PowerPoint 365 (Windows / Mac)"],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "B-06",
    family: "powerpoint",
    name: "観光・宿泊市場分析資料",
    audience: ["観光事業者"],
    jobToBeDone: "観光・宿泊市場を分析する",
    formats: ["pptx"],
    price: { minYen: 4980, maxYen: 9800, initialYen: 4980 },
    dataMode: "sample",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: ["PowerPoint 365 (Windows / Mac)"],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "B-07",
    family: "powerpoint",
    name: "自治体政策立案・庁内説明資料",
    audience: ["自治体", "公務員"],
    jobToBeDone: "政策立案を庁内で説明する",
    formats: ["pptx"],
    price: { minYen: 5980, maxYen: 12000, initialYen: 5980 },
    dataMode: "sample",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: ["PowerPoint 365 (Windows / Mac)"],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "B-08",
    family: "powerpoint",
    name: "議会・委員会説明用の統計資料",
    audience: ["自治体", "議員補助"],
    jobToBeDone: "議会・委員会向けに統計を説明する",
    formats: ["pptx"],
    price: { minYen: 5980, maxYen: 12000, initialYen: 5980 },
    dataMode: "sample",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: ["PowerPoint 365 (Windows / Mac)"],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "B-09",
    family: "powerpoint",
    name: "地域企業向け会社紹介・商圏説明資料",
    audience: ["中小企業"],
    jobToBeDone: "会社と商圏を地域データで紹介する",
    formats: ["pptx"],
    price: { minYen: 3980, maxYen: 7980, initialYen: 3980 },
    dataMode: "sample",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: ["PowerPoint 365 (Windows / Mac)"],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "B-10",
    family: "powerpoint",
    name: "地方創生・地域課題プレゼン雛形",
    audience: ["自治体", "NPO"],
    jobToBeDone: "地方創生・地域課題をプレゼンする",
    formats: ["pptx"],
    price: { minYen: 4980, maxYen: 9800, initialYen: 4980 },
    dataMode: "sample",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: ["PowerPoint 365 (Windows / Mac)"],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "B-11",
    family: "powerpoint",
    name: "県勢・市勢紹介スライド",
    audience: ["自治体", "学校", "団体"],
    jobToBeDone: "県勢・市勢をスライドで紹介する",
    formats: ["pptx"],
    price: { minYen: 3980, maxYen: 7980, initialYen: 3980 },
    dataMode: "sample",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: ["PowerPoint 365 (Windows / Mac)"],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "B-12",
    family: "powerpoint",
    name: "地域メディアの企画会議資料",
    audience: ["編集者", "ライター"],
    jobToBeDone: "地域メディアの企画会議資料を作る",
    formats: ["pptx"],
    price: { minYen: 3980, maxYen: 7980, initialYen: 3980 },
    dataMode: "sample",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: ["PowerPoint 365 (Windows / Mac)"],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "B-13",
    family: "powerpoint",
    name: "統計調査結果の記者発表資料",
    audience: ["調査担当", "広報"],
    jobToBeDone: "統計調査結果を記者発表する",
    formats: ["pptx"],
    price: { minYen: 5980, maxYen: 12000, initialYen: 5980 },
    dataMode: "sample",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: ["PowerPoint 365 (Windows / Mac)"],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "B-14",
    family: "powerpoint",
    name: "アンケート結果報告スライド",
    audience: ["企業", "研究者"],
    jobToBeDone: "アンケート結果を報告する",
    formats: ["pptx"],
    price: { minYen: 3980, maxYen: 7980, initialYen: 3980 },
    dataMode: "sample",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: ["PowerPoint 365 (Windows / Mac)"],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "B-15",
    family: "powerpoint",
    name: "セミナー・研修用の地域統計教材",
    audience: ["講師", "学校"],
    jobToBeDone: "地域統計をセミナー・研修で教える",
    formats: ["pptx"],
    price: { minYen: 3980, maxYen: 9800, initialYen: 3980 },
    dataMode: "sample",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: ["PowerPoint 365 (Windows / Mac)"],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "B-16",
    family: "powerpoint",
    name: "卒論・研究発表向け統計図表テンプレート",
    audience: ["学生", "研究者"],
    jobToBeDone: "卒論・研究発表で統計図表を使う",
    formats: ["pptx"],
    price: { minYen: 2980, maxYen: 5980, initialYen: 2980 },
    dataMode: "sample",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: ["PowerPoint 365 (Windows / Mac)"],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "B-17",
    family: "powerpoint",
    name: "営業提案に使う地域データ図表集",
    audience: ["営業", "代理店"],
    jobToBeDone: "営業提案で地域データ図表を使う",
    formats: ["pptx"],
    price: { minYen: 4980, maxYen: 9800, initialYen: 4980 },
    dataMode: "sample",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: ["PowerPoint 365 (Windows / Mac)"],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "B-18",
    family: "powerpoint",
    name: "不動産・住宅市場の地域比較資料",
    audience: ["不動産事業者"],
    jobToBeDone: "不動産・住宅市場を地域比較する",
    formats: ["pptx"],
    price: { minYen: 5980, maxYen: 12000, initialYen: 5980 },
    dataMode: "sample",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: ["PowerPoint 365 (Windows / Mac)"],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "B-19",
    family: "powerpoint",
    name: "医療・介護需要の地域比較資料",
    audience: ["医療・介護事業者"],
    jobToBeDone: "医療・介護需要を地域比較する",
    formats: ["pptx"],
    price: { minYen: 5980, maxYen: 12000, initialYen: 5980 },
    dataMode: "sample",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: ["PowerPoint 365 (Windows / Mac)"],
    risk: "high-stakes",
    status: "cataloged",
  },
  {
    id: "B-20",
    family: "powerpoint",
    name: "教育・子育て環境の地域比較資料",
    audience: ["教育", "移住支援"],
    jobToBeDone: "教育・子育て環境を地域比較する",
    formats: ["pptx"],
    price: { minYen: 4980, maxYen: 9800, initialYen: 4980 },
    dataMode: "sample",
    metrics: [],
    templateIds: [],
    licenseId: "single-corporate",
    supportLevel: "manual",
    compatibility: ["PowerPoint 365 (Windows / Mac)"],
    risk: "normal",
    status: "cataloged",
  },
];
