import type { ProductDefinition } from "../types";

export const SERVICE_PRODUCTS: readonly ProductDefinition[] = [
  {
    id: "J-01",
    family: "service",
    name: "顧客データを都道府県地図にする",
    audience: ["企画・営業", "自治体・公務員"],
    jobToBeDone: "顧客データを都道府県地図に可視化する",
    formats: ["pptx", "png"],
    price: { minYen: 5000, maxYen: 15000, initialYen: 5000 },
    dataMode: "customer",
    metrics: [],
    templateIds: [],
    licenseId: "service-deliverable",
    supportLevel: "custom",
    compatibility: [
      "PowerPoint 365 (Windows / Mac)",
      "SVG / PNG 対応ビューア",
    ],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "J-02",
    family: "service",
    name: "顧客データからランキングを作る",
    audience: ["企画・営業", "調査担当"],
    jobToBeDone: "顧客データから都道府県ランキングを作成する",
    formats: ["xlsx", "pptx"],
    price: { minYen: 5000, maxYen: 15000, initialYen: 5000 },
    dataMode: "customer",
    metrics: [],
    templateIds: [],
    licenseId: "service-deliverable",
    supportLevel: "custom",
    compatibility: [
      "Excel 365 (Windows / Mac)",
      "PowerPoint 365 (Windows / Mac)",
    ],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "J-03",
    family: "service",
    name: "地図・チャート10枚を資料化する",
    audience: ["企画・経営層"],
    jobToBeDone: "地図・チャート10枚をまとめて資料化する",
    formats: ["pptx"],
    price: { minYen: 15000, maxYen: 30000, initialYen: 15000 },
    dataMode: "customer",
    metrics: [],
    templateIds: [],
    licenseId: "service-deliverable",
    supportLevel: "custom",
    compatibility: ["PowerPoint 365 (Windows / Mac)"],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "J-04",
    family: "service",
    name: "公的統計を探して出典付きで納品する",
    audience: ["調査担当", "編集者・ライター"],
    jobToBeDone: "公的統計を出典付きで調査・納品する",
    formats: ["xlsx", "csv"],
    price: { minYen: 10000, maxYen: 30000, initialYen: 10000 },
    dataMode: "customer",
    metrics: [],
    templateIds: [],
    licenseId: "service-deliverable",
    supportLevel: "custom",
    compatibility: [
      "Excel 365 (Windows / Mac)",
      "UTF-8 (BOM) 対応表計算ソフト",
    ],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "J-05",
    family: "service",
    name: "地域比較レポートを作る",
    audience: ["企画・経営層", "コンサル"],
    jobToBeDone: "地域比較レポートを作成する",
    formats: ["pdf", "pptx"],
    price: { minYen: 15000, maxYen: 50000, initialYen: 15000 },
    dataMode: "customer",
    metrics: [],
    templateIds: [],
    licenseId: "service-deliverable",
    supportLevel: "custom",
    compatibility: [
      "PDF 閲覧環境",
      "PowerPoint 365 (Windows / Mac)",
    ],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "J-06",
    family: "service",
    name: "出店候補地域を比較する",
    audience: ["小売・飲食", "事業企画"],
    jobToBeDone: "出店候補地域を統計で比較する",
    formats: ["pptx", "xlsx"],
    price: { minYen: 20000, maxYen: 50000, initialYen: 20000 },
    dataMode: "customer",
    metrics: [],
    templateIds: [],
    licenseId: "service-deliverable",
    supportLevel: "custom",
    compatibility: [
      "PowerPoint 365 (Windows / Mac)",
      "Excel 365 (Windows / Mac)",
    ],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "J-07",
    family: "service",
    name: "移住候補地を条件別に比較する",
    audience: ["移住検討者", "移住支援"],
    jobToBeDone: "移住候補地を条件別に比較する",
    formats: ["pptx", "xlsx"],
    price: { minYen: 15000, maxYen: 30000, initialYen: 15000 },
    dataMode: "customer",
    metrics: [],
    templateIds: [],
    licenseId: "service-deliverable",
    supportLevel: "custom",
    compatibility: [
      "PowerPoint 365 (Windows / Mac)",
      "Excel 365 (Windows / Mac)",
    ],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "J-08",
    family: "service",
    name: "採用・賃金市場を地域比較する",
    audience: ["人事・採用支援"],
    jobToBeDone: "採用・賃金市場を地域別に比較する",
    formats: ["pptx", "xlsx"],
    price: { minYen: 20000, maxYen: 50000, initialYen: 20000 },
    dataMode: "customer",
    metrics: [],
    templateIds: [],
    licenseId: "service-deliverable",
    supportLevel: "custom",
    compatibility: [
      "PowerPoint 365 (Windows / Mac)",
      "Excel 365 (Windows / Mac)",
    ],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "J-09",
    family: "service",
    name: "既存Excelを地図ダッシュボード化する",
    audience: ["企画・営業", "データ担当"],
    jobToBeDone: "既存Excelを地図ダッシュボードに改修する",
    formats: ["xlsx"],
    price: { minYen: 20000, maxYen: 80000, initialYen: 20000 },
    dataMode: "customer",
    metrics: [],
    templateIds: [],
    licenseId: "service-deliverable",
    supportLevel: "custom",
    compatibility: ["Excel 365 (Windows / Mac)"],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "J-10",
    family: "service",
    name: "既存PowerPointの図表を改善する",
    audience: ["企画・営業", "編集者・ライター"],
    jobToBeDone: "既存PowerPointの図表デザインを改善する",
    formats: ["pptx"],
    price: { minYen: 10000, maxYen: 50000, initialYen: 10000 },
    dataMode: "customer",
    metrics: [],
    templateIds: [],
    licenseId: "service-deliverable",
    supportLevel: "custom",
    compatibility: ["PowerPoint 365 (Windows / Mac)"],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "J-11",
    family: "service",
    name: "自治体・地域団体向け統計資料を作る",
    audience: ["自治体・公務員", "地域団体"],
    jobToBeDone: "自治体・地域団体向け統計資料を作成する",
    formats: ["pptx", "xlsx"],
    price: { minYen: 30000, maxYen: 100000, initialYen: 30000 },
    dataMode: "customer",
    metrics: [],
    templateIds: [],
    licenseId: "service-deliverable",
    supportLevel: "custom",
    compatibility: [
      "PowerPoint 365 (Windows / Mac)",
      "Excel 365 (Windows / Mac)",
    ],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "J-12",
    family: "service",
    name: "地域データの定期更新を代行する",
    audience: ["企画・営業", "自治体・公務員"],
    jobToBeDone: "地域データの月次・年次更新を代行する",
    formats: ["xlsx", "pptx"],
    price: { minYen: 0, maxYen: 0, initialYen: 0 },
    dataMode: "customer",
    metrics: [],
    templateIds: [],
    licenseId: "service-deliverable",
    supportLevel: "custom",
    compatibility: [
      "Excel 365 (Windows / Mac)",
      "PowerPoint 365 (Windows / Mac)",
    ],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "J-13",
    family: "service",
    name: "Web地域ダッシュボードを構築する",
    audience: ["企画・営業", "自治体・公務員"],
    jobToBeDone: "Web地域ダッシュボードを構築する",
    formats: ["web"],
    price: { minYen: 50000, maxYen: 50000, initialYen: 50000 },
    dataMode: "customer",
    metrics: [],
    templateIds: [],
    licenseId: "service-deliverable",
    supportLevel: "custom",
    compatibility: ["モダンブラウザ"],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "J-14",
    family: "service",
    name: "テンプレートの色・ロゴ・項目を変更する",
    audience: ["企画・営業", "自治体・公務員"],
    jobToBeDone: "既存テンプレートの色・ロゴ・項目をカスタマイズする",
    formats: ["pptx", "xlsx"],
    price: { minYen: 5000, maxYen: 20000, initialYen: 5000 },
    dataMode: "customer",
    metrics: [],
    templateIds: [],
    licenseId: "service-deliverable",
    supportLevel: "custom",
    compatibility: [
      "PowerPoint 365 (Windows / Mac)",
      "Excel 365 (Windows / Mac)",
    ],
    risk: "normal",
    status: "cataloged",
  },
  {
    id: "J-15",
    family: "service",
    name: "統計資料の定義・出典・年次を監査する",
    audience: ["調査担当", "編集者・ライター"],
    jobToBeDone: "統計資料の定義・出典・年次を監査し是正する",
    formats: ["xlsx"],
    price: { minYen: 15000, maxYen: 50000, initialYen: 15000 },
    dataMode: "customer",
    metrics: [],
    templateIds: [],
    licenseId: "service-deliverable",
    supportLevel: "custom",
    compatibility: ["Excel 365 (Windows / Mac)"],
    risk: "normal",
    status: "cataloged",
  },
];
