import type { MetricConfig } from "../types";

export const deathsLifestyleDiseasesPer100k: MetricConfig = {
  "key": "deaths-lifestyle-diseases-per-100k",
  "title": "生活習慣病による死亡者数",
  "subtitle": "人口10万人当たり",
  "description": "人口動態調査で原死因が悪性新生物（腫瘍）、糖尿病、高血圧性疾患、心疾患（高血圧性を除く）、脳血管疾患のいずれかだった死亡者数の合計を、日本人人口で割り10万倍した値。",
  "note": "死亡診断書に複数の死因が記載された場合も、統計表章では死亡を引き起こした一連の事象の起因となる原死因1つで分類する。",
  "unit": "人",
  "category": "population",
  "source": {
    "kind": "estat",
    "statsDataId": "0000010209",
    "cdCat01": "#I06101",
    "displayName": "社会・人口統計体系",
    "url": "https://www.stat.go.jp/data/ssds/index.htm",
  },
  "entities": [
    "prefecture",
  ],
  "years": {
    "years": [
      1980,
      1981,
      1982,
      1983,
      1984,
      1985,
      1986,
      1987,
      1988,
      1989,
      1990,
      1991,
      1992,
      1993,
      1994,
      1995,
      1996,
      1997,
      1998,
      1999,
      2000,
      2001,
      2023,
    ],
  },
  "yearFormat": "fiscal",
  "visualization": {
    "colorScheme": "interpolateBlues",
    "colorSchemeType": "sequential",
    "minValueType": "data-min",
  },
  "display": {
    "conversionFactor": 1,
    "decimalPlaces": 1,
  },
  "calculation": {
    "isCalculated": false,
    "normalizationOptions": [
      {
        "type": "per_population",
        "label": "人口10万人あたり",
        "unit": "人/10万人",
        "scaleFactor": 100000,
        "decimalPlaces": 1,
      },
      {
        "type": "per_area",
        "label": "面積100km²あたり",
        "unit": "人/100km²",
        "scaleFactor": 100,
        "decimalPlaces": 2,
      },
    ],
  },
  "groupKey": "deaths-lifestyle-diseases",
  "seoTitle": "生活習慣病による死亡者数ランキング都道府県【2023年】｜1位秋田県（881.7人）",
  "seoDescription": "2023年の生活習慣病による死亡者数の都道府県別ランキング。1位秋田県（881.7人）、最下位沖縄県（466.2人）で1.9倍の格差。地図やグラフで47都道府県を比較。",
  "isActive": true,
};
