import type { MetricConfig } from "../types";

export const deathsDiabetesPer100k: MetricConfig = {
  "key": "deaths-diabetes-per-100k",
  "title": "糖尿病による死亡者数",
  "subtitle": "人口10万人当たり",
  "description": "人口動態調査で原死因が糖尿病だった死亡者数を日本人人口で割り、10万倍した値。",
  "unit": "人",
  "category": "population",
  "source": {
    "kind": "estat",
    "statsDataId": "0000010209",
    "cdCat01": "#I06103",
    "displayName": "社会・人口統計体系",
    "url": "https://www.stat.go.jp/data/ssds/index.htm",
  },
  "entities": [
    "prefecture",
  ],
  "years": {
    "years": [
      1985,
      1986,
      1987,
      1988,
      1989,
      1990,
      1991,
      1992,
      1993,
      1994,
      1995,
      1996,
      1997,
      1998,
      1999,
      2000,
      2001,
      2002,
      2003,
      2004,
      2005,
      2006,
      2023,
    ],
  },
  "yearFormat": "fiscal",
  "visualization": {
    "colorScheme": "interpolateBlues",
    "colorSchemeType": "sequential",
    "minValueType": "data-min",
  },
  "display": {
    "conversionFactor": 1,
    "decimalPlaces": 1,
  },
  "calculation": {
    "isCalculated": false,
    "normalizationOptions": [
      {
        "type": "per_population",
        "label": "人口10万人あたり",
        "unit": "人/10万人",
        "scaleFactor": 100000,
        "decimalPlaces": 1,
      },
      {
        "type": "per_area",
        "label": "面積100km²あたり",
        "unit": "人/100km²",
        "scaleFactor": 100,
        "decimalPlaces": 2,
      },
    ],
  },
  "groupKey": "deaths-diabetes",
  "seoTitle": "糖尿病による死亡者数ランキング都道府県【2023年】｜1位青森県（20.6人）",
  "seoDescription": "2023年の糖尿病による死亡者数の都道府県別ランキング。1位青森県（20.6人）、最下位愛知県（8.1人）で2.5倍の格差。地図やグラフで47都道府県を比較。",
  "isActive": true,
};
