import type { MetricConfig } from "../types";

export const juvenileCriminalArrestPersonPerPopulation: MetricConfig = {
  "key": "juvenile-criminal-arrest-person-per-population",
  "title": "少年刑法犯検挙人員",
  "subtitle": "14～19歳人口千人当たり",
  "unit": "人",
  "category": "safetyenvironment",
  "description": "少年刑法犯検挙人員を14～19歳の人口で除し、14～19歳人口千人当たりに換算した値。",
  "source": {
    "kind": "estat",
    "statsDataId": "0000010211",
    "cdCat01": "#K06301",
    "displayName": "社会・人口統計体系",
    "url": "https://www.stat.go.jp/data/ssds/index.htm",
  },
  "entities": [
    "prefecture",
  ],
  "years": {
    "years": [
      1980,
      1985,
      1990,
      1995,
      2000,
      2002,
      2003,
      2004,
      2005,
      2006,
      2007,
      2008,
      2009,
      2010,
      2011,
      2012,
      2013,
      2014,
      2015,
      2016,
      2017,
      2018,
      2019,
      2023,
    ],
  },
  "yearFormat": "fiscal",
  "visualization": {
    "colorScheme": "interpolateBlues",
    "colorSchemeType": "sequential",
    "minValueType": "data-min",
  },
  "display": {
    "conversionFactor": 1,
    "decimalPlaces": 2,
  },
  "calculation": {
    "isCalculated": false,
  },
  "groupKey": "juvenile-criminal-arrest-person",
  "seoTitle": "少年刑法犯検挙人員（14～19歳人口千人当たり）ランキング都道府県",
  "seoDescription": "14～19歳人口千人当たりの少年刑法犯検挙人員を都道府県別に比較。総数とは区別して、同じ分母の指標で地域差と経年変化を確認できます。",
  "isActive": true,
};
