import type { MetricConfig } from "../types";

export const manufacturingShipmentAmountPerEmployee: MetricConfig = {
  "key": "manufacturing-shipment-amount-per-employee",
  "title": "製造品出荷額等",
  "subtitle": "従業員当たり",
  "description": "製造品出荷額等を製造業従業者数で割った、従業者1人当たりの出荷額等。",
  "note": "出荷額等には加工賃、くず廃物、その他収入や内国消費税等を含むため、従業者1人当たりの賃金や付加価値額を示す指標ではない。調査変更をまたぐ時系列比較には注意が必要。",
  "unit": "万円",
  "category": "miningindustry",
  "source": {
    "kind": "estat",
    "statsDataId": "0000010203",
    "cdCat01": "#C04401",
    "displayName": "社会・人口統計体系",
    "url": "https://www.stat.go.jp/data/ssds/index.htm",
  },
  "entities": [
    "prefecture",
  ],
  "years": {
    "years": [
      1992,
      1993,
      1994,
      1995,
      1996,
      1997,
      1998,
      1999,
      2000,
      2001,
      2002,
      2003,
      2004,
      2005,
      2006,
      2007,
      2008,
      2009,
      2010,
      2011,
      2012,
      2013,
      2023,
    ],
  },
  "yearFormat": "fiscal",
  "visualization": {
    "colorScheme": "interpolateBlues",
    "colorSchemeType": "sequential",
    "minValueType": "data-min",
  },
  "display": {
    "conversionFactor": 1,
    "decimalPlaces": 1,
  },
  "calculation": {
    "isCalculated": false,
    "normalizationOptions": [
      {
        "type": "per_population",
        "label": "人口10万人あたり",
        "unit": "万円/10万人",
        "scaleFactor": 100000,
        "decimalPlaces": 1,
      },
      {
        "type": "per_area",
        "label": "面積100km²あたり",
        "unit": "万円/100km²",
        "scaleFactor": 100,
        "decimalPlaces": 2,
      },
    ],
  },
  "groupKey": "manufacturing-shipment-amount",
  "seoTitle": "製造品出荷額等ランキング都道府県【2023年】｜1位大分県（8,547.4万円）",
  "seoDescription": "2023年の製造品出荷額等の都道府県別ランキング。1位大分県（8,547.4万円）、最下位沖縄県（2,166.9万円）で3.9倍の格差。地図やグラフで47都道府県を比較。",
  "isActive": true,
};
