import type { MetricConfig } from "../types";

export const perCapitaTotalExpenditurePrefMunicipal: MetricConfig = {
  "key": "per-capita-total-expenditure-pref-municipal",
  "title": "歳出決算総額",
  "subtitle": "都道府県・市町村財政合計",
  "description": "都道府県と市町村の1会計年度における歳出決算総額を合計し、総人口で割った人口1人当たりの支出額。",
  "note": "行政目的別・経費性質別の各支出を含む財政規模の指標であり、住民個人が受け取った給付額や行政サービスの質を示すものではない。",
  "unit": "千円",
  "category": "administrativefinancial",
  "source": {
    "kind": "estat",
    "statsDataId": "0000010204",
    "cdCat01": "#D0330103",
    "displayName": "社会・人口統計体系",
    "url": "https://www.stat.go.jp/data/ssds/index.htm",
  },
  "entities": [
    "prefecture",
  ],
  "years": {
    "years": [
      1994,
      1995,
      1996,
      1997,
      1998,
      1999,
      2000,
      2001,
      2002,
      2003,
      2004,
      2005,
      2006,
      2007,
      2008,
      2009,
      2010,
      2011,
      2012,
      2013,
      2014,
      2015,
      2016,
      2022,
    ],
  },
  "yearFormat": "fiscal",
  "visualization": {
    "colorScheme": "interpolateBlues",
    "colorSchemeType": "sequential",
    "minValueType": "data-min",
  },
  "display": {
    "conversionFactor": 1,
    "decimalPlaces": 1,
  },
  "calculation": {
    "isCalculated": false,
    "normalizationOptions": [
      {
        "type": "per_population",
        "label": "人口10万人あたり",
        "unit": "千円/10万人",
        "scaleFactor": 100000,
        "decimalPlaces": 1,
      },
      {
        "type": "per_area",
        "label": "面積100km²あたり",
        "unit": "千円/100km²",
        "scaleFactor": 100,
        "decimalPlaces": 2,
      },
    ],
  },
  "groupKey": "total-expenditure-prefecture",
  "seoTitle": "歳出決算総額ランキング都道府県【2022年】｜1位島根県（1,597.6千円）",
  "seoDescription": "2022年の歳出決算総額の都道府県別ランキング。1位島根県（1,597.6千円）、最下位埼玉県（718.7千円）で2.2倍の格差。地図やグラフで47都道府県を比較。",
  "isActive": true,
};
