import type { MetricConfig } from "../types";

export const pharmacistCount: MetricConfig = {
  "key": "pharmacist-count",
  "title": "薬剤師数",
  "unit": "人",
  "category": "socialsecurity",
  "source": {
    "kind": "estat",
    "statsDataId": "0000010109",
    "cdCat01": "I6300",
    "displayName": "社会・人口統計体系",
    "url": "https://www.stat.go.jp/data/ssds/index.htm",
  },
  "entities": [
    "prefecture",
    "city",
  ],
  "years": {
    "years": [
      1981,
      1982,
      1984,
      1986,
      1988,
      1990,
      1992,
      1994,
      1996,
      1998,
      2000,
      2002,
      2004,
      2006,
      2008,
      2010,
      2012,
      2014,
      2016,
      2018,
      2020,
      2022,
    ],
  },
  "yearFormat": "fiscal",
  "visualization": {
    "colorScheme": "interpolateBlues",
    "colorSchemeType": "sequential",
    "divergingMidpoint": "zero",
    "minValueType": "data-min",
    "isReversed": false,
    "isSymmetrized": false,
  },
  "display": {
    "conversionFactor": 1,
    "decimalPlaces": 0,
  },
  "calculation": {
    "isCalculated": false,
    "normalizationOptions": [
      {
        "type": "per_population",
        "label": "人口10万人あたり",
        "unit": "人/10万人",
        "scaleFactor": 100000,
        "decimalPlaces": 1,
      },
      {
        "type": "per_area",
        "label": "面積100km²あたり",
        "unit": "人/100km²",
        "scaleFactor": 100,
        "decimalPlaces": 2,
      },
    ],
  },
  "seoTitle": "薬剤師数ランキング都道府県【2022年】｜1位東京都（53,527人）",
  "seoDescription": "2022年の薬剤師数の都道府県別ランキング。1位東京都（53,527人）、最下位鳥取県（1,243人）で43.1倍の格差。地図やグラフで47都道府県を比較。",
  "isActive": true,
};
