import type { MetricConfig } from "../types";

export const physicalDisabilityRehabilitationCasesPer1000: MetricConfig = {
  "key": "physical-disability-rehabilitation-cases-per-1000",
  "title": "身体障害者更生援護取扱実人員",
  "subtitle": "人口1000人当たり",
  "unit": "人",
  "category": "socialsecurity",
  "source": {
    "kind": "estat",
    "statsDataId": "0000010210",
    "cdCat01": "#J05203",
    "displayName": "社会・人口統計体系",
    "url": "https://www.stat.go.jp/data/ssds/index.htm",
  },
  "entities": [
    "prefecture",
  ],
  "years": {
    "years": [
      1981,
      1982,
      1983,
      1984,
      1985,
      1986,
      1987,
      1988,
      1989,
      1990,
      1991,
      1992,
      1993,
      1994,
      1995,
      1996,
      1997,
      1998,
      1999,
      2000,
      2001,
      2002,
      2003,
      2007,
    ],
  },
  "yearFormat": "fiscal",
  "visualization": {
    "colorScheme": "interpolateBlues",
    "colorSchemeType": "sequential",
    "minValueType": "data-min",
  },
  "display": {
    "conversionFactor": 1,
    "decimalPlaces": 2,
  },
  "calculation": {
    "isCalculated": false,
    "normalizationOptions": [
      {
        "type": "per_population",
        "label": "人口10万人あたり",
        "unit": "人/10万人",
        "scaleFactor": 100000,
        "decimalPlaces": 1,
      },
      {
        "type": "per_area",
        "label": "面積100km²あたり",
        "unit": "人/100km²",
        "scaleFactor": 100,
        "decimalPlaces": 2,
      },
    ],
  },
  "groupKey": "physical-disability-rehabilitation-cases",
  "seoTitle": "身体障害者更生援護取扱実人員ランキング都道府県【2007年】｜1位兵庫県（39.1人）",
  "seoDescription": "2007年の身体障害者更生援護取扱実人員の都道府県別ランキング。1位兵庫県（39.1人）、最下位茨城県（5.74人）で6.8倍の格差。地図やグラフで47都道府県を比較。",
  "isActive": true,
};
