import type { MetricConfig } from "../types";

export const taxpayerRatioPerPrefResident: MetricConfig = {
  "key": "taxpayer-ratio-per-pref-resident",
  "title": "納税義務者割合",
  "description": "個人の市町村民税所得割の納税義務者数を総人口で割り、100倍した割合。",
  "note": "分母は就業者や成人人口ではなく、子どもを含む総人口。所得割の納税義務者だけを数えるため、何らかの税を納める住民全体の割合ではない。",
  "unit": "％",
  "category": "administrativefinancial",
  "source": {
    "kind": "estat",
    "statsDataId": "0000010204",
    "cdCat01": "#D02207",
    "displayName": "社会・人口統計体系",
    "url": "https://www.stat.go.jp/data/ssds/index.htm",
  },
  "entities": [
    "prefecture",
  ],
  "years": {
    "years": [
      1993,
      1994,
      1995,
      1996,
      1997,
      1998,
      1999,
      2000,
      2001,
      2002,
      2003,
      2004,
      2005,
      2006,
      2007,
      2008,
      2009,
      2010,
      2011,
      2012,
      2013,
      2014,
      2024,
    ],
  },
  "yearFormat": "fiscal",
  "visualization": {
    "colorScheme": "interpolateBlues",
    "colorSchemeType": "sequential",
    "divergingMidpoint": "zero",
    "minValueType": "data-min",
    "isReversed": false,
    "isSymmetrized": false,
  },
  "display": {
    "conversionFactor": 1,
    "decimalPlaces": 1,
  },
  "calculation": {
    "isCalculated": false,
  },
  "seoTitle": "納税義務者割合ランキング都道府県【2024年】｜1位東京都（51.5％）",
  "seoDescription": "2024年の納税義務者割合の都道府県別ランキング。1位東京都（51.5％）、最下位沖縄県（40.1％）で1.3倍の格差。地図やグラフで47都道府県を比較。",
  "isActive": true,
};
