import type { MetricConfig } from "../types";

export const youthClassLectureCountPerMillion: MetricConfig = {
  "key": "youth-class-lecture-count-per-million",
  "title": "青少年学級・講座数",
  "unit": "学級･講座",
  "category": "educationsports",
  "source": {
    "kind": "estat",
    "statsDataId": "0000010207",
    "cdCat01": "#G03201",
    "displayName": "社会・人口統計体系",
    "url": "https://www.stat.go.jp/data/ssds/index.htm",
  },
  "entities": [
    "prefecture",
  ],
  "years": {
    "years": [
      1977,
      1978,
      1979,
      1990,
      1991,
      1992,
      1993,
      1994,
      1995,
      1996,
      1997,
      1998,
      2001,
      2004,
      2007,
      2010,
      2014,
      2017,
      2020,
    ],
  },
  "yearFormat": "fiscal",
  "visualization": {
    "colorScheme": "interpolateBlues",
    "colorSchemeType": "sequential",
    "divergingMidpoint": "zero",
    "minValueType": "data-min",
    "isReversed": false,
    "isSymmetrized": false,
  },
  "display": {
    "conversionFactor": 1,
    "decimalPlaces": 1,
    "displayUnit": "学級",
  },
  "calculation": {
    "isCalculated": false,
    "normalizationOptions": [
      {
        "type": "per_population",
        "label": "人口10万人あたり",
        "unit": "学級･講座/10万人",
        "scaleFactor": 100000,
        "decimalPlaces": 1,
      },
      {
        "type": "per_area",
        "label": "面積100km²あたり",
        "unit": "学級･講座/100km²",
        "scaleFactor": 100,
        "decimalPlaces": 2,
      },
    ],
  },
  "seoTitle": "青少年学級・講座数ランキング都道府県【2020年】｜1位鳥取県（3,001.4学級･講座）",
  "seoDescription": "2020年の青少年学級・講座数の都道府県別ランキング。1位鳥取県（3,001.4学級･講座）、最下位神奈川県（41.6学級･講座）で72.1倍の格差。地図やグラフで47都道府県を比較。",
  "isActive": true,
};
