/**
 * DB から削除済み・非アクティブの旧ランキングキー一覧
 *
 * これらのキーは旧 URL 構造（/{cat}/{sub}/ranking/{key}）で存在していたか、
 * または現在 is_active=false となっている。middleware で 410 Gone を返し、
 * Google にインデックスからの即時除去を促す。
 *
 * 更新日: 2026-03-27（442 → 489 件。inactive 50 件追加、active 復帰 3 件削除）
 * 更新日: 2026-06-12（per-capita-prefectural-income-h27 を active 復帰で削除。RANK-LINK-01）
 * 更新日: 2026-06-16（COVERAGE-DEACT-01。GSC カバレッジ是正ループで「config も R2 データも無いのに
 *   stale prerender で 200 を返す空 ranking」32 件を特定し追加。Google が soft404 判定していた発生源。
 *   middleware 410 で stale ページより前段で短絡し即時除去を促す。将来データ投入時は本 Set から削除して復帰可。
 *   一覧の真実源: .claude/state/gsc/coverage-remediation-queue.json の content_verdict=deactivate）
 * 更新日: 2026-07-03（誤検知 3 件を active 復帰で削除: marine-aquaculture-harvest /
 *   marine-fishery-catch / marine-fishery-output-value。いずれも KNOWN_RANKING_KEYS 登録済・
 *   config isActive:true・R2 item.json/values.json に実データあり（COVERAGE-DEACT-01 の
 *   06-16 追加より前の生成日時）で、本番で /ranking/marine-aquaculture-harvest が 410 になる
 *   不具合をユーザー報告で検知。marine-aquaculture-output は KNOWN でも isActive でもなく
 *   正しく gone のため維持）
 * 更新日: 2026-07-03 追補（同一シグネチャの誤検知を全数調査し 53 件を一括復帰。全 53 件が
 *   KNOWN 登録済 + isActive:true + R2 values.json 200 (実データあり) + 本番 410 を実測確認。
 *   births / marriages / ratio-65-plus / population-growth-rate 等の基礎統計を含む。
 *   再発防止: ranking-key-consistency.test.ts が GONE∩KNOWN=∅ / GONE∩isActive=∅ を
 *   CI で恒久検証する。本 Set への追加は必ず「KNOWN 再生成 + config isActive:false」とセットで行うこと）
 * 更新日: 2026-08-05（VALUE-GATE-01。値分布ゲートが「順位として成立しない」と判定した 3 件を退役。
 *   いずれも最新年の全 47 県が同じ値 0 で、1 位が決まらないため ranking ページとして成立しない:
 *   gini-coefficient-disposable-income = e-Stat 0000010112 が全エリア・全年 "0" を返す (SSDS の
 *     整数丸め配信でジニ係数を取得できない。config の軸選択は正しく、cdCat 是正では直らないことを
 *     getStatsData で実測確認済み)。代替出典は .claude/todo/backlog.md に記録
 *   bowling-alley-public = 公共ボウリング場が最良年 (2015) でも値 1 の県が 2 つだけ
 *   unemployment-measures-project-expenses-prefecture = 失業対策事業は 1996 年廃止で 2007 年以降全年 0
 *   config isActive:false + KNOWN 再生成 (2176→2173) とセットで実施）
 * 更新日: 2026-08-06（COVERAGE-SOFT404-01。GSC が soft404 判定した空 ranking 39 件を退役。
 *   いずれも (a) metric config が存在しない (b) KNOWN_RANKING_KEYS 未登録 (c) R2 values.json も無い、の
 *   3 条件をすべて満たす死にキーで、本番は HTTP 200 + 「ランキングが見つかりません」の soft404 を返していた。
 *   middleware 410 で page 到達前に短絡する。
 *   ★2026-06-16 の同種作業で 56 件の誤検知 (KNOWN 登録済 + isActive + R2 実データありを GONE 化) が
 *     発生したため、今回は上記 3 条件を機械検証してから追加した (要注意 0 件)。
 *   entities:["city"] の isActive 4 件 (real-public-debt-service-ratio-city 等) は別問題として除外した）
 * 更新日: 2026-08-16（e-Stat の統計表そのものが廃止された 9 件を退役。data-refresh が 8/5 に
 *   STATUS=300「データは存在しません」で落ちていた発生源で、後継表の有無を e-Stat カタログ全件
 *   走査で確認したうえでの判断:
 *   construction-contract-* 8 件 (旧 statsDataId 0003458635 / 建設工事受注動態統計調査) =
 *     2021 年の統計不正を受けた調査再設計で「都道府県 × 工事種類」の軸が消滅した。現行カタログの
 *     統計コード 00600130 配下 4 系統 (公共工事着工 / 民間土木工事着工 / 建設工事施工 /
 *     大手 50 社) をメタまで実測したが、いずれも当該軸を持たない (大手 50 社は都道府県軸自体なし)。
 *   noise-regulation-rate (旧 0003368792 / 騒音規制法施行状況調査) = 調査自体が e-Stat カタログから
 *     消滅。searchWord「騒音規制法施行状況調査」「騒音・振動規制法」で 0 件、「騒音」386 件を
 *     走査しても該当なし。
 *   代替候補 (建設は「元請完成工事高」= 業種別 × 都道府県別の別軸) は概念が変わるため
 *   .claude/todo/backlog.md へ記録し、採否は別途判断する）
 * 更新日: 2026-08-17（RANKING-DUPLICATE-PATIENT-SURVEY-01。患者調査 0004026104/0004026105 系の
 *   patient-receiving-rate-by-age / patient-receiving-rate-by-disease を退役。どちらも総数を指すため
 *   inpatient-rate-per-100k と同一値 (2023 高知 1,785 / 神奈川 665) で重複コンテンツだった。
 *   config は既に isActive:false だが R2 item.json が残っており本番は 200 で実タイトルを返していた
 *   (isActive:false ≠ 本番非公開)。生存キーは inpatient-rate-per-100k）
 */
export const GONE_RANKING_KEYS = new Set([
  // 2026-08-16 退役 (e-Stat 側で統計表が廃止・後継なし)
  "construction-contract-total",
  "construction-contract-housing",
  "construction-contract-road",
  "construction-contract-river",
  "construction-contract-sewerage",
  "construction-contract-port-airport",
  "construction-contract-disaster-recovery",
  "construction-projects-total",
  "noise-regulation-rate",
  "patient-receiving-rate-by-age",
  "patient-receiving-rate-by-disease",
  "ssdse-c-lb072003",
  "ssdse-c-lb080011",
  "ssdse-c-lb121202",
  "child-height-regional-gap",
  "miso-consumption-quantity-prefecture-gap",
  "ssdse-c-lb092009",
  "ssdse-c-lb021105",
  "ssdse-d-md17",
  "ssdse-c-lb051208",
  "ssdse-c-lb102001",
  "ssdse-c-lb110003",
  "ssdse-c-lb072001",
  "ssdse-c-la03",
  "agricultural-production-value",
  "ssdse-d-md12",
  "instant-noodles-expenditure",
  "avg-height-middle-school-2nd-male",
  "ssdse-c-lb054005",
  "ssdse-c-lb110005",
  "ssdse-c-lb122001",
  "ssdse-c-lb103005",
  "ssdse-c-lb061008",
  "population-density",
  "ssdse-d-md18",
  "ssdse-f-snow-days",
  "ssdse-c-lb054001",
  "rice-expenditure",
  "total-overnight-guests-foreign-china",
  "consumer-price-regional-difference-index",
  "ssdse-c-lb051203",
  "ssdse-d-md13",
  "ssdse-c-lb072010",
  "ssdse-c-lb054008",
  "ssdse-c-lb051206",
  "fiscal-self-reliance-ratio",
  "total-overnight-guests-foreign-korea",
  "ssdse-c-lb061001",
  "education-cost-per-student",
  "commerce-sales-amount",
  "actual-road-length",
  "age-adjusted-death-rate-female-h27-per-1000",
  "age-adjusted-death-rate-female-s60-per-1000",
  "age-adjusted-death-rate-male-h27-per-1000",
  "age-adjusted-death-rate-male-s60-per-1000",
  "age-adjusted-mortality-rate-old",
  "agricultural-output-city",
  "agricultural-output-per-worker-individual-farm",
  "agriculture-forestry-fishery-employees",
  "agriculture-forestry-fishery-workers",
  "amount-of-public-construction-contracts",
  "annual-water-supply-volume-municipal",
  "apparel-retail-store-count-per-1000-alt",
  "average-life-expectancy-male-65",
  "average-number-of-people-in-general-households",
  "births-under-2500g",
  "blood-donor-count",
  "bowling-alley-public",
  "building-fire-count-per-100k",
  "bullying-recognition-count",
  "bullying-resolution-count",
  "capacity-utilization-rate",
  "city-gas-meter-installations",
  "city-gas-meter-readings",
  "commercial-neighborhood-zone",
  "commercial-zone",
  "community-center-count",
  "community-parks-area",
  "computer-per-student-elementary",
  "computer-per-student-junior-high",
  "consolidated-real-deficit-ratio-municipal",
  "constructed-building-floor-area",
  "corporate-income-h27",
  "cpi-change-rate-overall-excl-imputed-rent",
  "cpi-change-rate-overall-incl-imputed-rent",
  "criminal-arrest-count",
  "current-account-ratio-municipal",
  "current-local-bonds-municipality",
  "death-accident-male",
  "death-cerebrovascular",
  "death-diabetes",
  "death-heart-disease",
  "death-hypertension",
  "death-lifestyle-disease",
  "deaths-male",
  "department-stores-10-per",
  "digital-textbook-rate-high",
  "domestic-bank-personal-deposit-balance",
  "domestic-case-count-mediation",
  "dual-income-household-count",
  "dwelling-per-floor-area",
  "edu-academic-junior-math",
  "education-cost-per-student-high-fulltime",
  "electricity-consumption",
  "electronic-blackboard-per-school-high",
  "electronic-blackboard-rate-elementary",
  "elementary-school-long-absence-count",
  "elementary-school-long-absence-count-illness",
  "elementary-school-long-absence-count-nonattendance",
  "elementary-school-student-count",
  "elementary-school-teacher-count",
  "employed-people-count",
  "employee-compensation-h27",
  "factor-income-from-outside-prefecture-nominal-h27",
  "final-education-population-university-graduate",
  "final-waste-disposal-volume",
  "financial-capability-index-municipal",
  "fire-brigade-count",
  "fire-damage-amount",
  "fire-damage-casualties",
  "fire-damage-death-count",
  "fire-damage-injury-count",
  "fire-department-branch-count",
  "fire-department-count",
  "fire-department-dispatch-building-fire-count",
  "fire-department-dispatch-count",
  "fire-department-emergency-car-count",
  "fire-department-emergency-dispatch-count",
  "fire-department-employees-count",
  "fire-department-fire-hydrant-count",
  "fire-department-member-count",
  "fire-department-pump-car-count",
  "fire-division-count",
  "fire-insurance-amount-received-per-contract-alt",
  "fire-insurance-claims-received-per-1000-households",
  "fire-insurance-claims-received-per-1000-households-alt",
  "fire-insurance-new-contract-count",
  "fire-insurance-new-contracts-per-1000-households",
  "fire-insurance-new-contracts-per-1000-households-alt",
  "fire-officer-count",
  "fire-outbreak-count",
  "food-poisoning-patient-count",
  "food-retail-store-count-per-1000-alt",
  "fulltime-physicians-general-hospital-per-100beds-report",
  "future-burden-ratio-municipal",
  "gdp-growth-rate-pref-h27",
  "general-funds-municipality",
  "general-household-members",
  "gini-coefficient-disposable-income",
  "goods-services-net-exports-imports-nominal-h27",
  "green-corridor-area",
  "gross-capital-formation-nominal-h27",
  "gross-capital-formation-real-h27",
  "gross-fixed-capital-formation-nominal-h27",
  "gross-fixed-capital-formation-real-h27",
  "gross-prefectural-income-growth-rate-nominal-h27",
  "gross-prefectural-income-nominal-h27",
  "gross-prefectural-product-accommodation-food-h27",
  "gross-prefectural-product-agriculture-forestry-fisheries-h27",
  "gross-prefectural-product-agriculture-h27",
  "gross-prefectural-product-construction-h27",
  "gross-prefectural-product-education-h27",
  "gross-prefectural-product-electricity-gas-water-waste-h27",
  "gross-prefectural-product-expenditure-nominal-h27",
  "gross-prefectural-product-finance-insurance-h27",
  "gross-prefectural-product-fisheries-h27",
  "gross-prefectural-product-forestry-h27",
  "gross-prefectural-product-health-social-h27",
  "gross-prefectural-product-information-communication-h27",
  "gross-prefectural-product-manufacturing-h27",
  "gross-prefectural-product-mining-h27",
  "gross-prefectural-product-primary-industry-h27",
  "gross-prefectural-product-professional-scientific-support-h27",
  "gross-prefectural-product-public-h27",
  "gross-prefectural-product-real-estate-h27",
  "gross-prefectural-product-secondary-industry-h27",
  "gross-prefectural-product-tertiary-industry-h27",
  "gross-prefectural-product-transport-postal-h27",
  "gross-prefectural-product-wholesale-retail-h27",
  "handball-throw-grade8-female",
  "handball-throw-grade8-male",
  "health-life-expectancy-female",
  "health-life-expectancy-male",
  "height-grade11-male",
  "height-grade5-male",
  "height-grade8-female",
  "height-grade8-male",
  "high-school-student-count",
  "hospital-count",
  "house-councillors-election-turnout-constituency",
  "households-in-city-gas-supply-area",
  "households-on-public-assistance-benefit",
  "households-started-assistance",
  "industrial-only-zone",
  "industrial-quasi-zone",
  "industrial-water-usage-fresh",
  "industrial-zone",
  "intellectual-offense-recognized-count",
  "inventory-change-nominal-h27",
  "investment-expenses-municipality",
  "job-changers",
  "junior-college-student-count",
  "junior-high-school-class-count",
  "junior-high-school-graduates",
  "junior-high-school-student-count",
  "junior-high-school-teacher-count",
  "juvenile-heinous-offense-arrested-person-count",
  "juvenile-protection-event-new-admission-person",
  "kenmin-shotoku-h27",
  "kindergarten-count",
  "kindergarten-enrollment",
  "kindergarten-teacher-count",
  "labor-force-population",
  "labor-union-members",
  "labor-unions",
  "land-use-zone-area",
  "large-display-rate-elementary",
  "large-display-rate-junior-high",
  "large-retail-store-count-per-100k-alt",
  "large-scale-retail-stores-10-per",
  "late-elderly-medical-expense",
  "late-elderly-medical-expense-per-person",
  "leavers",
  "library-count",
  "life-expectancy-at-60-male",
  "local-government-final-consumption-expenditure-nominal-h27",
  "local-government-final-consumption-expenditure-real-h27",
  "marine-aquaculture-output",
  "medical-expenses-per-person",
  "mobile-phone-contracts",
  "morals-offense-arrested-count",
  "morals-offense-arrested-person-count",
  "municipal-assembly-election-turnout",
  "municipal-mayor-election-turnout",
  "museum-count",
  "national-medical-expenses-total",
  "neighborhood-commercial-zone",
  "neighborhood-parks",
  "neighborhood-parks-area",
  "non-flush-toilet-population",
  "nuclear-family-households",
  "number-of-commercial-establishments-wholesale-retail",
  "number-of-public-construction-contracts",
  "number-of-ryokan-facilities-incl-hotel",
  "number-of-ryokan-rooms-incl-hotel",
  "nursing-welfare-facilities-basic-tabulation-6510-per",
  "nursing-welfare-facilities-detailed-tabulation-6510-per",
  "occupational-accident-severity-rate",
  "old-population",
  "outflow-population-other-pref",
  "outpatients-per-fulltime-physician-per-day-report",
  "overtime-working-hours-female",
  "overtime-working-hours-male",
  "owner-occupied-housing",
  "passenger-car-ownership-per-household",
  "paved-road-length",
  "per-capita-kenmin-shotoku-h27",
  "persons-on-public-assistance-benefit",
  "planned-construction-cost",
  "pollution-complaint-accepted-seven-typical",
  "pollution-complaint-processed-count",
  "post-offices",
  "prefectural-governor-election-turnout",
  "prefectural-income-growth-rate-h27",
  "private-auto-insurance-payment-count",
  "private-final-consumption-expenditure-nominal-h27",
  "private-final-consumption-expenditure-real-h27",
  "production-age-population",
  "projected-population-2020",
  "projected-population-2025",
  "projected-population-2030",
  "projected-population-2035",
  "projected-population-2040",
  "projected-population-2045",
  "projected-population-2050",
  "property-income-h27",
  "property-offense-arrested-count",
  "property-offense-arrested-person-count",
  "public-harm-complaint-handling-count",
  "public-telephones",
  "real-debt-service-ratio-municipal",
  "real-deficit-ratio-municipal",
  "rental-housing-units",
  "residential-zone",
  "restaurant-count-per-1000-alt",
  "restaurants-per",
  "retail-store-count-per-1000-alt",
  "road-traffic-accident-count",
  "road-traffic-law-violation-arrest-count",
  "run50m-grade5-female",
  "run50m-grade5-male",
  "run50m-grade8-female",
  "run50m-grade8-male",
  "secondary-industry-employed-people-count",
  "sewerage-drainage-area-population",
  "shipment-value-manufacturing",
  "shipment-value-manufacturing-1",
  "shipment-value-manufacturing-10",
  "shipment-value-manufacturing-11",
  "shipment-value-manufacturing-12",
  "shipment-value-manufacturing-13",
  "shipment-value-manufacturing-14",
  "shipment-value-manufacturing-15",
  "shipment-value-manufacturing-16",
  "shipment-value-manufacturing-17",
  "shipment-value-manufacturing-18",
  "shipment-value-manufacturing-19",
  "shipment-value-manufacturing-2",
  "shipment-value-manufacturing-20",
  "shipment-value-manufacturing-3",
  "shipment-value-manufacturing-4",
  "shipment-value-manufacturing-5",
  "shipment-value-manufacturing-6",
  "shipment-value-manufacturing-7",
  "shipment-value-manufacturing-8",
  "shipment-value-manufacturing-9",
  "shipment-value-manufacturing-beverage",
  "shipment-value-manufacturing-food",
  "shipment-value-manufacturing-textile",
  "sleep-avg-time-male-10plus",
  "sleep-avg-time-male-15plus",
  "sports-parks",
  "sports-parks-area",
  "ssdse-c-lb013002",
  "ssdse-c-lb014002",
  "ssdse-c-lb021104",
  "ssdse-c-lb024001",
  "ssdse-c-lb051303",
  "ssdse-c-lb052003",
  "ssdse-c-lb061011",
  "ssdse-c-lb072014",
  "ssdse-c-lb080012",
  "ssdse-c-lb091005",
  "ssdse-c-lb092004",
  "ssdse-c-lb103001",
  "ssdse-c-lb121107",
  "ssdse-c-lb121201",
  "ssdse-d-md03",
  "ssdse-d-md31",
  "ssdse-d-md33",
  "ssdse-d-mf0211",
  "ssdse-d-mg07",
  "ssdse-d-mg09",
  "ssdse-f-avg-temp-under-0",
  "ssdse-f-max-temp-avg",
  "ssdse-f-snow-depth-over-10",
  "ssdse-f-snow-depth-over-5",
  "ssdse-f-wind-over-10",
  "standard-financial-scale-municipal",
  "standing-long-jump-grade5-female",
  "standing-long-jump-grade8-female",
  "standing-long-jump-grade8-male",
  "statistical-discrepancy-nominal-h27",
  "stereo-cd-md-radio-ownership-multi-person-households-per-1000",
  "taxable-income",
  "tertiary-industry-employed-people-count",
  "total-housing-units",
  "total-overnight-guests-prefecture",
  "total-population-female",
  "total-population-male",
  "total-waste-generation-volume",
  "traffic-accident-casualties",
  "traffic-accident-casualties-elementary",
  "traffic-accident-death-count",
  "traffic-accident-injury-count",
  "tv-broadcast-contracts",
  "unemployed-people-count",
  "unemployment-measures-project-expenses-prefecture",
  "unemployment-rate-man",
  "unemployment-rate-woman",
  "university-advancement",
  "university-graduates",
  "university-student-count",
  "university-teacher-count",
  "unmarried-ratio-female-20-24",
  "unmarried-ratio-male-20-24",
  "urban-green-area",
  "urbanization-control-area",
  "urbanization-promotion-area",
  "vacant-houses",
  "violence-incident-count",
  "violent-offense-arrested-count",
  "violent-offense-recognized-count",
  "voluntary-auto-insurance-contract-count",
  "wages-salaries-h27",
  "waste-generation-per-person-per-day",
  "waste-planned-collection-population",
  "waste-treatment-volume-total",
  "water-supply-population-municipal",
  "weight-grade5-male",
  "weight-grade8-female",
  "weight-grade8-male",
  "wind-power-generation-capacity",
  "wind-power-generation-number-of-units",
  "young-population",
]);
