/**
 * canonical 記事プラン (SSOT) — 174 商品を 55 本の note 記事へ束ねる。
 *
 * 旧174商品向けの記事プラン（移行対象）。恒久仕様は
 * .claude/rules/coconala-product-standards.md §9。削除条件:
 * .claude/todo/backlog.md の COCONALA-PRODUCT-FACTORY-01 完了時に14パック由来へ置換する。
 * - variant (K ライセンス / empty・sample 版) を記事本文で乱立させず canonical 記事へ集約する。
 * - memberProductIds は全体で 174 商品を「漏れなく・重複なく」覆う (coverage validator が保証)。
 * - disposition は product-note-mapping.ts が (family, 記事) から決定的に導出する。
 *
 * 価格は提案値 (仕様 §9)。公開時に人間が確定する。
 */
import type { NoteArticlePlan } from "./types";

export const CANONICAL_ARTICLES: readonly NoteArticlePlan[] = [
  // ── prefecture-map-powerpoint (A 素材 + B テンプレート) ──────────────
  {
    slug: "ppt-japan-map-assets",
    series: "prefecture-map-powerpoint",
    title: "PowerPointで使える47都道府県の白地図・色分け地図素材",
    role: "how-to",
    access: "paid",
    priceJpy: 1980,
    memberProductIds: ["A-01", "A-02", "A-03", "A-04", "A-05", "A-06"],
    stats47Targets: ["/ranking", "/themes"],
    priority: 1,
    readerJob: "資料に貼れる編集可能な都道府県地図を、県ごとに色を変えて使いたい",
    hashtags: ["都道府県", "PowerPoint", "地図素材", "資料作成", "データ可視化"],
  },
  {
    slug: "ppt-ranking-chart-assets",
    series: "prefecture-map-powerpoint",
    title: "都道府県ランキング・散布図・時系列チャートのPowerPointテンプレート集",
    role: "how-to",
    access: "paid",
    priceJpy: 1980,
    memberProductIds: ["A-07", "A-08", "A-09", "A-10", "A-11", "A-12", "A-13", "A-14"],
    stats47Targets: ["/ranking", "/themes"],
    priority: 1,
    readerJob: "47都道府県の数値をランキングや散布図で見せるチャートを、値を差し替えるだけで作りたい",
    hashtags: ["都道府県", "PowerPoint", "グラフ", "ランキング", "データ分析"],
  },
  {
    slug: "ppt-onepager-sns-assets",
    series: "prefecture-map-powerpoint",
    title: "1枚資料・SNS図版・動画画面向けの都道府県データ素材",
    role: "how-to",
    access: "paid",
    priceJpy: 1980,
    memberProductIds: ["A-15", "A-16", "A-17", "A-18"],
    stats47Targets: ["/ranking", "/blog"],
    priority: 2,
    readerJob: "地図とランキングを1枚にまとめた資料や、SNS・動画用の縦長／16:9図版がほしい",
    hashtags: ["都道府県", "SNS運用", "図版", "PowerPoint", "情報発信"],
  },
  {
    slug: "ppt-data-explainer-deck",
    series: "prefecture-map-powerpoint",
    title: "都道府県データ説明スライド20枚セット",
    role: "pillar",
    access: "paid",
    priceJpy: 3980,
    memberProductIds: ["B-01"],
    stats47Targets: ["/ranking", "/themes"],
    priority: 1,
    readerJob: "都道府県データを社内外にわかりやすく説明するスライド一式を用意したい",
    hashtags: ["都道府県", "PowerPoint", "プレゼン資料", "統計", "データ可視化"],
  },
  {
    slug: "ppt-region-intro-deck",
    series: "prefecture-map-powerpoint",
    title: "県勢・市勢紹介と地域企業向け商圏説明のスライド雛形",
    role: "use-case",
    access: "paid",
    priceJpy: 3980,
    memberProductIds: ["B-09", "B-11"],
    stats47Targets: ["/areas", "/ranking"],
    priority: 2,
    readerJob: "自分の地域や商圏を、統計の裏付けつきで紹介するスライドを作りたい",
    hashtags: ["地域", "PowerPoint", "会社紹介", "都道府県", "統計"],
  },
  {
    slug: "ppt-market-proposal-deck",
    series: "prefecture-map-powerpoint",
    title: "市場調査・出店提案・営業に使う地域比較スライド",
    role: "use-case",
    access: "paid",
    priceJpy: 4980,
    memberProductIds: ["B-02", "B-03", "B-17", "B-18"],
    stats47Targets: ["/compare", "/areas"],
    priority: 1,
    readerJob: "地域市場を調査し、出店候補や営業先を数値で比較提案する資料を作りたい",
    hashtags: ["市場調査", "PowerPoint", "出店", "営業資料", "地域分析"],
  },
  {
    slug: "ppt-relocation-hiring-deck",
    series: "prefecture-map-powerpoint",
    title: "移住候補地・採用賃金の地域比較スライド",
    role: "use-case",
    access: "paid",
    priceJpy: 4980,
    memberProductIds: ["B-04", "B-05"],
    stats47Targets: ["/areas", "/compare"],
    priority: 2,
    readerJob: "移住先や採用拠点の候補地域を、生活コストや賃金水準で比較したい",
    hashtags: ["移住", "採用", "PowerPoint", "地域比較", "賃金"],
  },
  {
    slug: "ppt-tourism-demand-deck",
    series: "prefecture-map-powerpoint",
    title: "観光・宿泊市場分析スライド雛形",
    role: "use-case",
    access: "paid",
    priceJpy: 4980,
    memberProductIds: ["B-06"],
    stats47Targets: ["/themes/tourism", "/ranking"],
    priority: 2,
    readerJob: "観光・宿泊需要の地域差を分析して事業や企画の資料にまとめたい",
    hashtags: ["観光", "宿泊", "PowerPoint", "市場分析", "地域"],
  },
  {
    slug: "ppt-healthcare-education-deck",
    series: "prefecture-map-powerpoint",
    title: "医療・介護・教育・子育て環境の地域比較スライド",
    role: "use-case",
    access: "paid",
    priceJpy: 4980,
    memberProductIds: ["B-19", "B-20"],
    stats47Targets: ["/themes/healthcare", "/compare"],
    priority: 2,
    readerJob: "医療・介護需要や教育・子育て環境の地域差を資料化したい",
    hashtags: ["医療", "子育て", "PowerPoint", "地域比較", "介護"],
  },
  {
    slug: "ppt-government-policy-deck",
    series: "prefecture-map-powerpoint",
    title: "政策立案・議会説明・地方創生のプレゼン雛形",
    role: "use-case",
    access: "paid",
    priceJpy: 5980,
    memberProductIds: ["B-07", "B-08", "B-10"],
    stats47Targets: ["/themes/local-finance", "/ranking"],
    priority: 2,
    readerJob: "政策立案や議会・委員会向けに、統計を根拠にした説明資料を作りたい",
    hashtags: ["公務員", "政策立案", "PowerPoint", "地方創生", "統計"],
  },
  {
    slug: "ppt-media-report-deck",
    series: "prefecture-map-powerpoint",
    title: "企画会議・記者発表・アンケート報告のスライド雛形",
    role: "use-case",
    access: "paid",
    priceJpy: 4980,
    memberProductIds: ["B-12", "B-13", "B-14"],
    stats47Targets: ["/ranking", "/blog"],
    priority: 3,
    readerJob: "調査結果やアンケートを、企画会議や記者発表で見せる資料にまとめたい",
    hashtags: ["メディア", "PowerPoint", "記者発表", "アンケート", "企画"],
  },
  {
    slug: "ppt-seminar-research-deck",
    series: "prefecture-map-powerpoint",
    title: "セミナー研修・卒論発表向けの統計図表テンプレート",
    role: "use-case",
    access: "paid",
    priceJpy: 3980,
    memberProductIds: ["B-15", "B-16"],
    stats47Targets: ["/ranking", "/themes"],
    priority: 3,
    readerJob: "研修や卒論・研究発表で使う、都道府県統計の図表テンプレートがほしい",
    hashtags: ["研修", "卒論", "PowerPoint", "統計", "教材"],
  },

  // ── prefecture-excel-analysis (C Excel) ─────────────────────────────
  {
    slug: "excel-choropleth-map",
    series: "prefecture-excel-analysis",
    title: "数値を貼るだけの47都道府県コロプレス地図Excel",
    role: "pillar",
    access: "paid",
    priceJpy: 3980,
    memberProductIds: ["C-01"],
    stats47Targets: ["/ranking", "/themes"],
    priority: 1,
    readerJob: "47都道府県の数値を貼るだけで、色分けされた日本地図をExcelで作りたい",
    hashtags: ["Excel", "都道府県", "地図", "データ可視化", "コロプレス"],
  },
  {
    slug: "excel-ranking-auto",
    series: "prefecture-excel-analysis",
    title: "47都道府県ランキングを自動作成するExcel",
    role: "how-to",
    access: "paid",
    priceJpy: 2980,
    memberProductIds: ["C-02"],
    stats47Targets: ["/ranking", "/compare"],
    priority: 1,
    readerJob: "数値を入れると順位とグラフが自動更新される都道府県ランキング表がほしい",
    hashtags: ["Excel", "ランキング", "都道府県", "関数", "自動化"],
  },
  {
    slug: "excel-integrated-dashboard",
    series: "prefecture-excel-analysis",
    title: "地図・ランキング・スコアリング統合Excelダッシュボード",
    role: "use-case",
    access: "paid",
    priceJpy: 5980,
    memberProductIds: ["C-03", "C-04", "C-15"],
    stats47Targets: ["/compare", "/themes"],
    priority: 1,
    readerJob: "複数指標を重み付けして地域をスコアリングし、1画面で俯瞰したい",
    hashtags: ["Excel", "ダッシュボード", "スコアリング", "地域分析", "都道府県"],
  },
  {
    slug: "excel-gap-timeseries-analysis",
    series: "prefecture-excel-analysis",
    title: "全国平均との差・時系列・相関を見るExcel分析テンプレート",
    role: "how-to",
    access: "paid",
    priceJpy: 3980,
    memberProductIds: ["C-05", "C-06", "C-07", "C-08"],
    stats47Targets: ["/ranking", "/compare"],
    priority: 2,
    readerJob: "自県と全国平均の差や、前年差・成長率・2指標の相関をExcelで分析したい",
    hashtags: ["Excel", "データ分析", "時系列", "相関", "都道府県"],
  },
  {
    slug: "excel-population-migration",
    series: "prefecture-excel-analysis",
    title: "人口構成・人口移動を分析するExcelテンプレート",
    role: "use-case",
    access: "paid",
    priceJpy: 5980,
    memberProductIds: ["C-09", "C-10"],
    stats47Targets: ["/themes/population-dynamics", "/ranking"],
    priority: 2,
    readerJob: "人口ピラミッドや転入転出の流れを都道府県別に分析したい",
    hashtags: ["Excel", "人口", "人口移動", "都道府県", "データ分析"],
  },
  {
    slug: "excel-business-location",
    series: "prefecture-excel-analysis",
    title: "商圏・採用・移住候補をスコアリングするExcel",
    role: "use-case",
    access: "paid",
    priceJpy: 7980,
    memberProductIds: ["C-11", "C-12", "C-13"],
    stats47Targets: ["/areas", "/compare"],
    priority: 2,
    readerJob: "出店候補や採用拠点、移住先を複数条件で点数化して比較したい",
    hashtags: ["Excel", "出店", "商圏分析", "採用", "移住"],
  },
  {
    slug: "excel-domain-comparison",
    series: "prefecture-excel-analysis",
    title: "観光・財政・医療・教育・防災の地域比較Excel",
    role: "use-case",
    access: "paid",
    priceJpy: 5980,
    memberProductIds: ["C-14", "C-16", "C-17", "C-18", "C-19"],
    stats47Targets: ["/themes", "/compare"],
    priority: 2,
    readerJob: "観光需要・自治体財政・医療需給・教育・防災の地域差をExcelで比較したい",
    hashtags: ["Excel", "地域比較", "自治体", "医療", "防災"],
  },
  {
    slug: "excel-data-utilities",
    series: "prefecture-excel-analysis",
    title: "e-Stat整形・都道府県コード変換・年度統合の実務Excelツール",
    role: "how-to",
    access: "paid",
    priceJpy: 3980,
    memberProductIds: ["C-20", "C-21", "C-22", "C-23", "C-24"],
    stats47Targets: ["/ranking"],
    priority: 2,
    readerJob: "e-StatのCSV整形や都道府県コード変換、複数年度の統合を効率化したい",
    hashtags: ["Excel", "eStat", "データ整形", "実務", "都道府県"],
  },

  // ── regional-data-packs (D データ) ──────────────────────────────────
  {
    slug: "data-packs-basic",
    series: "regional-data-packs",
    title: "47都道府県 基礎統計データブック",
    role: "pillar",
    access: "paid",
    priceJpy: 2980,
    memberProductIds: ["D-01"],
    stats47Targets: ["/themes", "/ranking"],
    priority: 1,
    readerJob: "都道府県の基礎統計を出典つきの一覧データとしてまとめて手に入れたい",
    hashtags: ["都道府県", "統計データ", "データパック", "オープンデータ", "eStat"],
  },
  {
    slug: "data-packs-population-economy",
    series: "regional-data-packs",
    title: "人口・所得・物価のテーマ別データパック",
    role: "use-case",
    access: "paid",
    priceJpy: 3980,
    memberProductIds: ["D-02", "D-03", "D-04"],
    stats47Targets: ["/themes/population-dynamics", "/themes/real-income"],
    priority: 2,
    readerJob: "人口推計・所得賃金・物価家計のデータを、読み方つきでまとめて使いたい",
    hashtags: ["人口", "所得", "物価", "データパック", "都道府県"],
  },
  {
    slug: "data-packs-living-infrastructure",
    series: "regional-data-packs",
    title: "住宅・医療・教育・交通のテーマ別データパック",
    role: "use-case",
    access: "paid",
    priceJpy: 3980,
    memberProductIds: ["D-05", "D-06", "D-07", "D-11"],
    stats47Targets: ["/themes/living-housing", "/themes/healthcare"],
    priority: 2,
    readerJob: "住宅・空き家・医療介護・教育子育て・交通のデータをまとめて調べたい",
    hashtags: ["住宅", "医療", "教育", "交通", "データパック"],
  },
  {
    slug: "data-packs-industry-tourism",
    series: "regional-data-packs",
    title: "観光・産業・農林水産のテーマ別データパック",
    role: "use-case",
    access: "paid",
    priceJpy: 3980,
    memberProductIds: ["D-08", "D-09", "D-14"],
    stats47Targets: ["/themes/tourism", "/ranking"],
    priority: 3,
    readerJob: "観光・宿泊、産業・事業所、農林水産業のデータをテーマ別に使いたい",
    hashtags: ["観光", "産業", "農業", "データパック", "都道府県"],
  },
  {
    slug: "data-packs-government-safety",
    series: "regional-data-packs",
    title: "財政・環境・安全防災のテーマ別データパック",
    role: "use-case",
    access: "paid",
    priceJpy: 3980,
    memberProductIds: ["D-10", "D-12", "D-13"],
    stats47Targets: ["/themes/local-finance", "/ranking"],
    priority: 3,
    readerJob: "自治体財政・環境エネルギー・安全防災のデータをまとめて把握したい",
    hashtags: ["自治体", "財政", "防災", "環境", "データパック"],
  },
  {
    slug: "data-packs-culture-demographics",
    series: "regional-data-packs",
    title: "文化・スポーツ・属性別のテーマ別データパック",
    role: "use-case",
    access: "paid",
    priceJpy: 2980,
    memberProductIds: ["D-15", "D-16", "D-17"],
    stats47Targets: ["/themes", "/ranking"],
    priority: 3,
    readerJob: "文化施設・スポーツ余暇・女性/若者/高齢者の地域差を調べたい",
    hashtags: ["文化", "スポーツ", "データパック", "都道府県", "統計"],
  },
  {
    slug: "data-packs-advanced",
    series: "regional-data-packs",
    title: "市区町村内格差・人口移動・100図表の上級データパック",
    role: "use-case",
    access: "paid",
    priceJpy: 5980,
    memberProductIds: ["D-18", "D-19", "D-20"],
    stats47Targets: ["/areas", "/themes/population-dynamics"],
    priority: 2,
    readerJob: "市区町村内の格差や都道府県間の人口移動を、まとまった図表で深掘りしたい",
    hashtags: ["市区町村", "人口移動", "データパック", "地域格差", "統計"],
  },

  // ── business-location-analysis (E 業種特化) ─────────────────────────
  {
    slug: "industry-retail-food-location",
    series: "business-location-analysis",
    title: "飲食店・小売店の出店候補地分析パック",
    role: "use-case",
    access: "paid",
    priceJpy: 7980,
    memberProductIds: ["E-01", "E-02"],
    stats47Targets: ["/areas", "/compare"],
    priority: 1,
    readerJob: "飲食・小売の出店候補地域を、人口や商圏データで比較したい",
    hashtags: ["出店", "飲食店", "小売", "商圏分析", "地域"],
  },
  {
    slug: "industry-service-location",
    series: "business-location-analysis",
    title: "学習塾・介護・クリニックの開業地域比較パック",
    role: "use-case",
    access: "paid",
    priceJpy: 7980,
    memberProductIds: ["E-03", "E-04", "E-05"],
    stats47Targets: ["/themes/healthcare", "/areas"],
    priority: 2,
    readerJob: "塾・介護事業所・クリニックの開業候補地を需要データで比較したい",
    hashtags: ["開業", "介護", "クリニック", "学習塾", "地域分析"],
  },
  {
    slug: "industry-tourism-realestate",
    series: "business-location-analysis",
    title: "宿泊施設・不動産営業の地域比較パック",
    role: "use-case",
    access: "paid",
    priceJpy: 7980,
    memberProductIds: ["E-06", "E-07"],
    stats47Targets: ["/themes/tourism", "/themes/living-housing"],
    priority: 2,
    readerJob: "宿泊・観光事業や不動産営業で、地域の需要と市場を比較したい",
    hashtags: ["宿泊", "不動産", "観光", "地域分析", "出店"],
  },
  {
    slug: "industry-hiring-branch",
    series: "business-location-analysis",
    title: "採用拠点・支店候補地の比較パック",
    role: "use-case",
    access: "paid",
    priceJpy: 7980,
    memberProductIds: ["E-08"],
    stats47Targets: ["/compare", "/areas"],
    priority: 2,
    readerJob: "採用拠点や支店の候補地を、労働市場や賃金データで比較したい",
    hashtags: ["採用", "支店", "拠点戦略", "労働市場", "地域"],
  },
  {
    slug: "industry-marketing-furusato",
    series: "business-location-analysis",
    title: "EC地域マーケティング・ふるさと納税・地域金融の企画パック",
    role: "use-case",
    access: "paid",
    priceJpy: 5980,
    memberProductIds: ["E-09", "E-10", "E-11"],
    stats47Targets: ["/ranking", "/areas"],
    priority: 3,
    readerJob: "ECや、ふるさと納税、地域金融の企画に地域統計を活用したい",
    hashtags: ["EC", "ふるさと納税", "地域金融", "マーケティング", "地域"],
  },
  {
    slug: "industry-government-promotion",
    series: "business-location-analysis",
    title: "シティプロモーション・地方創生プロジェクト企画パック",
    role: "use-case",
    access: "paid",
    priceJpy: 9800,
    memberProductIds: ["E-12", "E-13"],
    stats47Targets: ["/themes/local-finance", "/areas"],
    priority: 3,
    readerJob: "自治体のシティプロモーションや地方創生プロジェクトを統計で組み立てたい",
    hashtags: ["地方創生", "シティプロモーション", "自治体", "企画", "統計"],
  },
  {
    slug: "industry-media-sns",
    series: "business-location-analysis",
    title: "地域メディア記事・YouTube・SNS運用の制作パック",
    role: "use-case",
    access: "paid",
    priceJpy: 5980,
    memberProductIds: ["E-14", "E-15", "E-16"],
    stats47Targets: ["/ranking", "/blog"],
    priority: 3,
    readerJob: "地域データを使った記事・動画・SNS投稿のネタと図版を効率よく作りたい",
    hashtags: ["メディア", "YouTube", "SNS運用", "地域", "コンテンツ制作"],
  },

  // ── government-statistics-work (F 自治体) ────────────────────────────
  {
    slug: "gov-estat-workflow",
    series: "government-statistics-work",
    title: "e-Stat検索・出典管理・オープンデータ公開を時短する自治体Excel一式",
    role: "pillar",
    access: "paid",
    priceJpy: 5980,
    memberProductIds: ["F-01", "F-11", "F-12"],
    stats47Targets: ["/ranking", "/themes/local-finance"],
    priority: 1,
    readerJob: "e-Statの検索・加工・出典管理・オープンデータ公開の作業を減らしたい",
    hashtags: ["公務員", "eStat", "統計", "オープンデータ", "実務"],
  },
  {
    slug: "gov-similar-municipality",
    series: "government-statistics-work",
    title: "類似団体比較・人口ビジョン・総合戦略の指標整理テンプレート",
    role: "use-case",
    access: "paid",
    priceJpy: 5980,
    memberProductIds: ["F-02", "F-07", "F-08"],
    stats47Targets: ["/areas", "/themes/local-finance"],
    priority: 2,
    readerJob: "自団体と類似団体を比較し、人口ビジョンや総合戦略の指標を整理したい",
    hashtags: ["公務員", "類似団体", "総合戦略", "人口ビジョン", "自治体"],
  },
  {
    slug: "gov-kpi-ebpm",
    series: "government-statistics-work",
    title: "総合計画KPI管理・EBPMロジックモデルのダッシュボード",
    role: "use-case",
    access: "paid",
    priceJpy: 9800,
    memberProductIds: ["F-03", "F-04"],
    stats47Targets: ["/themes/local-finance", "/ranking"],
    priority: 2,
    readerJob: "総合計画のKPIやEBPMの指標を、ロジックモデルつきで管理したい",
    hashtags: ["公務員", "KPI", "EBPM", "総合計画", "自治体"],
  },
  {
    slug: "gov-presentation-decks",
    series: "government-statistics-work",
    title: "予算要求・議会答弁・県勢要覧の説明図表セット",
    role: "use-case",
    access: "paid",
    priceJpy: 5980,
    memberProductIds: ["F-05", "F-06", "F-09"],
    stats47Targets: ["/ranking", "/themes/local-finance"],
    priority: 2,
    readerJob: "予算要求や議会答弁、県勢要覧で使う統計図表を効率よく用意したい",
    hashtags: ["公務員", "議会答弁", "予算", "PowerPoint", "自治体"],
  },
  {
    slug: "gov-koho-visuals",
    series: "government-statistics-work",
    title: "自治体広報向けの統計図版セット",
    role: "how-to",
    access: "paid",
    priceJpy: 3980,
    memberProductIds: ["F-10"],
    stats47Targets: ["/ranking", "/blog"],
    priority: 3,
    readerJob: "広報紙やWebに載せる、わかりやすい統計図版を用意したい",
    hashtags: ["公務員", "広報", "図版", "統計", "自治体"],
  },
  {
    slug: "gov-training-materials",
    series: "government-statistics-work",
    title: "公務員向け統計グラフ・PowerPoint改善・AI統計加工の研修教材",
    role: "use-case",
    access: "paid",
    priceJpy: 5980,
    memberProductIds: ["F-13", "F-14", "F-15"],
    stats47Targets: ["/ranking"],
    priority: 3,
    readerJob: "統計グラフ作成やPowerPoint改善、AIでの統計加工を職員研修で教えたい",
    hashtags: ["公務員", "研修", "統計", "PowerPoint", "AI活用"],
  },

  // ── media-data-visuals (G メディア) ─────────────────────────────────
  {
    slug: "media-ranking-visuals",
    series: "media-data-visuals",
    title: "記事・ニュース・note向けの都道府県ランキング図版セット",
    role: "pillar",
    access: "paid",
    priceJpy: 2980,
    memberProductIds: ["G-01", "G-02", "G-07"],
    stats47Targets: ["/ranking", "/blog"],
    priority: 1,
    readerJob: "記事やニュースにそのまま使える都道府県ランキング図版と地図がほしい",
    hashtags: ["メディア", "図版", "ランキング", "記事作成", "都道府県"],
  },
  {
    slug: "media-video-social-visuals",
    series: "media-data-visuals",
    title: "YouTube・ショート・Instagram・X向けの統計図版テンプレート",
    role: "use-case",
    access: "paid",
    priceJpy: 3980,
    memberProductIds: ["G-03", "G-04", "G-05", "G-06"],
    stats47Targets: ["/ranking", "/blog"],
    priority: 2,
    readerJob: "動画やSNSに合わせた縦型・カルーセル・1枚図解の統計ビジュアルを作りたい",
    hashtags: ["YouTube", "SNS運用", "図版", "動画制作", "都道府県"],
  },
  {
    slug: "media-editorial-toolkit",
    series: "media-data-visuals",
    title: "編集部向けネタカレンダー・構成テンプレ・ファクトチェック台帳",
    role: "how-to",
    access: "paid",
    priceJpy: 3980,
    memberProductIds: ["G-08", "G-09", "G-10"],
    stats47Targets: ["/ranking", "/blog"],
    priority: 3,
    readerJob: "地域データ記事の年間企画・構成・出典管理を仕組み化したい",
    hashtags: ["編集", "メディア", "企画", "ファクトチェック", "コンテンツ制作"],
  },

  // ── statistics-education (H 教育) ───────────────────────────────────
  {
    slug: "edu-classroom-materials",
    series: "statistics-education",
    title: "中高生向け47都道府県の統計授業スライド・クイズ教材",
    role: "pillar",
    access: "paid",
    priceJpy: 2980,
    memberProductIds: ["H-01", "H-04", "H-08", "H-10"],
    stats47Targets: ["/ranking", "/themes"],
    priority: 1,
    readerJob: "中高生に都道府県データを教える授業スライドやクイズを用意したい",
    hashtags: ["教育", "授業", "統計", "教材", "都道府県"],
  },
  {
    slug: "edu-inquiry-worksheets",
    series: "statistics-education",
    title: "探究学習・オープンデータ調査・自県研究のワークシート",
    role: "use-case",
    access: "paid",
    priceJpy: 1980,
    memberProductIds: ["H-02", "H-06", "H-07"],
    stats47Targets: ["/ranking", "/areas"],
    priority: 2,
    readerJob: "探究学習で地域を比較したり、自県を調べたりするワークシートがほしい",
    hashtags: ["探究学習", "教育", "オープンデータ", "ワークシート", "統計"],
  },
  {
    slug: "edu-excel-stats-literacy",
    series: "statistics-education",
    title: "Excelグラフ演習・相関と因果・レポート管理の統計リテラシー教材",
    role: "use-case",
    access: "paid",
    priceJpy: 1980,
    memberProductIds: ["H-03", "H-05", "H-09"],
    stats47Targets: ["/ranking"],
    priority: 2,
    readerJob: "Excelのグラフ作成や、相関と因果の読み方、レポートの作法を学ばせたい",
    hashtags: ["Excel", "統計リテラシー", "教育", "相関と因果", "教材"],
  },

  // ── life-area-comparison (I 個人) ───────────────────────────────────
  {
    slug: "life-relocation-comparison",
    series: "life-area-comparison",
    title: "移住・引越し・二拠点・UIターンの候補地比較シート",
    role: "pillar",
    access: "paid",
    priceJpy: 1980,
    memberProductIds: ["I-01", "I-02", "I-06", "I-08"],
    stats47Targets: ["/areas", "/compare"],
    priority: 1,
    readerJob: "移住や引越し、二拠点、UIターンの候補地を生活データで比較したい",
    hashtags: ["移住", "引越し", "二拠点生活", "地域比較", "ライフプラン"],
  },
  {
    slug: "life-family-career-comparison",
    series: "life-area-comparison",
    title: "子育て・転職勤務地・大学進学先の地域比較シート",
    role: "use-case",
    access: "paid",
    priceJpy: 1980,
    memberProductIds: ["I-03", "I-04", "I-07"],
    stats47Targets: ["/themes/healthcare", "/compare"],
    priority: 2,
    readerJob: "子育て環境や転職先、進学先の地域を数値で比較して選びたい",
    hashtags: ["子育て", "転職", "大学進学", "地域比較", "ライフプラン"],
  },
  {
    slug: "life-retirement-weighting",
    series: "life-area-comparison",
    title: "退職後の居住地選びと自分用の都道府県重み付け診断シート",
    role: "use-case",
    access: "paid",
    priceJpy: 1980,
    memberProductIds: ["I-05", "I-09"],
    stats47Targets: ["/areas", "/compare"],
    priority: 3,
    readerJob: "退職後の居住地を、自分の優先度で重み付けして比較したい",
    hashtags: ["退職後", "移住", "地域比較", "ライフプラン", "診断"],
  },

  // ── custom-analysis-services (J サービス・無料 → ココナラ受注) ────────
  {
    slug: "service-map-chart-creation",
    series: "custom-analysis-services",
    title: "顧客データの地図化・ランキング化・資料化を代行します",
    role: "use-case",
    access: "free",
    priceJpy: 0,
    memberProductIds: ["J-01", "J-02", "J-03", "J-10", "J-14"],
    stats47Targets: ["/", "/ranking"],
    priority: 1,
    readerJob: "手元のデータを都道府県地図やランキング、資料に仕上げてほしい",
    hashtags: ["データ可視化", "資料作成", "ココナラ", "地図", "受託"],
  },
  {
    slug: "service-regional-report",
    series: "custom-analysis-services",
    title: "公的統計の調査・地域比較レポート・統計資料監査を承ります",
    role: "use-case",
    access: "free",
    priceJpy: 0,
    memberProductIds: ["J-04", "J-05", "J-15"],
    stats47Targets: ["/", "/ranking"],
    priority: 2,
    readerJob: "必要な公的統計を探して、出典つきのレポートや監査結果がほしい",
    hashtags: ["統計", "レポート作成", "ココナラ", "調査", "受託"],
  },
  {
    slug: "service-business-comparison",
    series: "custom-analysis-services",
    title: "出店・移住・採用の地域比較を条件別に作成します",
    role: "use-case",
    access: "free",
    priceJpy: 0,
    memberProductIds: ["J-06", "J-07", "J-08"],
    stats47Targets: ["/", "/compare"],
    priority: 2,
    readerJob: "出店候補や移住先、採用市場を自分の条件で比較してほしい",
    hashtags: ["地域比較", "出店", "移住", "ココナラ", "受託"],
  },
  {
    slug: "service-dashboard-build",
    series: "custom-analysis-services",
    title: "Excelダッシュボード化・自治体資料・定期更新・Web構築を承ります",
    role: "use-case",
    access: "free",
    priceJpy: 0,
    memberProductIds: ["J-09", "J-11", "J-12", "J-13"],
    stats47Targets: ["/", "/themes"],
    priority: 3,
    readerJob: "既存データをダッシュボード化したり、定期更新やWeb化を任せたい",
    hashtags: ["ダッシュボード", "自治体", "Web制作", "ココナラ", "受託"],
  },

  // ── license-guide (K ライセンス・比較記事に集約) ─────────────────────
  {
    slug: "license-guide",
    series: "license-guide",
    title: "都道府県データ商品のライセンス・版の違いガイド",
    role: "comparison",
    access: "free",
    priceJpy: 0,
    memberProductIds: [
      "K-01",
      "K-02",
      "K-03",
      "K-04",
      "K-05",
      "K-06",
      "K-07",
      "K-08",
      "K-09",
      "K-10",
    ],
    stats47Targets: ["/"],
    priority: 2,
    readerJob: "どのライセンス・データ版を選べばよいか、違いを一覧で理解したい",
    hashtags: ["ライセンス", "都道府県", "データ商品", "購入ガイド", "ココナラ"],
  },

  // ── free-samples (L 無料サンプル) ───────────────────────────────────
  {
    slug: "free-samples",
    series: "free-samples",
    title: "都道府県地図・テンプレート・比較チェックリストの無料サンプル",
    role: "sample",
    access: "free",
    priceJpy: 0,
    memberProductIds: ["L-01", "L-02", "L-03", "L-04", "L-05", "L-06", "L-07"],
    stats47Targets: ["/ranking", "/themes"],
    priority: 1,
    readerJob: "有料版を買う前に、地図やテンプレートの品質・使い勝手を無料で試したい",
    hashtags: ["無料", "都道府県", "地図", "テンプレート", "サンプル"],
  },
] as const;
