/**
 * `pack-rankingkeys.generated.ts` の再生成スクリプト (完全DBレス: git TS SSOT → 生成物)。
 *
 * METRICS_REGISTRY (data-configs) の active + prefecture 指標を pack-theme-map の写像で
 * P-01〜P-11 へ配分し、P-12 は P-01〜P-10 の和集合として書き出す。R2 の実在検証はしない
 * (pack-snapshot が fetch 時に検証・スキップ)。これは「どの指標をどのパックに割り当てるか」の台帳。
 *
 * 実行: npx tsx src/catalog/build-pack-rankingkeys.ts
 */
import { writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { METRICS_REGISTRY } from "@stats47/data-configs";
import {
  assignPackTheme,
  MAP_CHART_ASSET_KEYS,
  PRODUCT_EXCLUDED_RANKING_KEYS,
} from "./pack-theme-map";
import { THEME_BY_ID, EXPECTED_PACK_IDS } from "./packs";
import type { PackTheme } from "./types";

const OUT = resolve(dirname(fileURLToPath(import.meta.url)), "pack-rankingkeys.generated.ts");

/** id → theme の逆引きで、各テーマの id を得る。 */
const ID_BY_THEME = Object.fromEntries(
  Object.entries(THEME_BY_ID).map(([id, theme]) => [theme, id]),
) as Record<PackTheme, string>;

function build(): void {
  const registryKeys = new Set(Object.keys(METRICS_REGISTRY));
  const perPack: Record<string, string[]> = {};
  for (const id of EXPECTED_PACK_IDS) perPack[id] = [];

  // 1. P-01〜P-10: カテゴリ写像で配分
  let assigned = 0;
  let skippedNoCat = 0;
  for (const [key, cfg] of Object.entries(METRICS_REGISTRY)) {
    const c = cfg as {
      category?: string;
      isActive?: boolean;
      entities?: string[];
      source?: { kind?: string };
    };
    if (c.isActive !== true) continue;
    if (!Array.isArray(c.entities) || !c.entities.includes("prefecture")) continue;
    if (PRODUCT_EXCLUDED_RANKING_KEYS.has(key)) continue;
    const theme = assignPackTheme(key, c.category ?? "", c.source?.kind);
    if (!theme) {
      skippedNoCat += 1;
      continue;
    }
    const id = ID_BY_THEME[theme];
    perPack[id].push(key);
    assigned += 1;
  }

  // 2. P-11: 横断代表 (存在するもののみ)
  perPack["P-11"] = MAP_CHART_ASSET_KEYS.filter((k) => registryKeys.has(k));

  // 3. P-12: テーマ配分パック (P-01〜P-10 + P-14) の和集合。
  //    P-14 (家計・消費) は旧 P-09 から分離したため、和集合に含めないと P-12 が縮む (件数を維持する)。
  const union = new Set<string>();
  for (const id of ["P-01", "P-02", "P-03", "P-04", "P-05", "P-06", "P-07", "P-08", "P-09", "P-10", "P-14"]) {
    for (const k of perPack[id]) union.add(k);
  }
  perPack["P-12"] = [...union];

  // 決定的に並べる
  for (const id of EXPECTED_PACK_IDS) {
    // P-11 は代表順を保持 (見栄えの並び)、他はソート
    if (id !== "P-11") perPack[id] = [...perPack[id]].sort();
  }

  const body = EXPECTED_PACK_IDS.map((id) => {
    const keys = perPack[id];
    const arr = keys.map((k) => `    ${JSON.stringify(k)},`).join("\n");
    return `  ${JSON.stringify(id)}: [\n${arr}\n  ],`;
  }).join("\n");

  const header = `/**
 * AUTOGENERATED by src/catalog/build-pack-rankingkeys.ts — DO NOT EDIT MANUALLY.
 * 再生成: npx tsx src/catalog/build-pack-rankingkeys.ts
 *
 * パック → そのテーマの全ランキングキー列 (e-Stat カテゴリ 17 分類の機械配分)。
 * R2 の実在はここでは保証しない (pack-snapshot が fetch 時に検証・スキップする)。
 */
`;
  const content = `${header}export const PACK_RANKING_KEYS: Readonly<Record<string, readonly string[]>> = {\n${body}\n};\n`;
  writeFileSync(OUT, content);

  console.error(`assigned=${assigned} skipped(no-category)=${skippedNoCat}`);
  for (const id of EXPECTED_PACK_IDS) console.error(`  ${id}: ${perPack[id].length}`);
  console.error(`→ ${OUT}`);
}

build();
